// GENERATED by scratch/CRASHPARITY_0922/fxcrashvfx_vmxemu/gen_fxbundle_data.py -- do not edit.
// BrnParticle::ParticleModule::LoadFXBundle @0x8229C950 run on emu64 (the real words): per call, the
// replies injected before it and what it did (see the generator banner). Tags: handles are cell k /
// entry k (-1 = null), names index kaFxbNames.
#pragma once

static const char* const kaFxbNames[] = {
    "lowres_debris.rf3",
    "highres_debris_02.rf3",
    "Glass_debris.rf3",
    "WHITE",
    "highres_debris",
    "glass_debris",
    "particle_description_collection",
};
static const int kiFxbNameCount = 7;

struct FxbReply { int miType; int miEventId; int miCell; int miEntry; };
static const FxbReply kaFxbReplies[] = {
    { 4, 0, 20, 20 },
    { 4, 0, 0, 0 },
    { 4, 1, 1, 1 },
    { 4, 2, 2, 2 },
    { 4, 3, 3, 3 },
    { 4, 4, 4, 4 },
    { 4, 0, 10, 10 },
    { 4, 1, 11, 11 },
    { 4, 2, 12, 12 },
    { 4, 3, 13, 13 },
    { 4, 4, 14, 14 },
    { 4, 0, 20, 20 },
    { 4, 3, 3, 3 },
    { 2, 1, 9, 9 },
    { 4, 1, 1, 1 },
    { 4, 4, 4, 4 },
    { 4, 0, 0, 0 },
    { 4, 2, 7, 7 },
    { 4, 2, 2, 2 },
    { 4, 4, 14, 14 },
    { 4, 2, 12, 12 },
    { 2, 0, 19, 19 },
    { 4, 0, 10, 10 },
    { 4, 3, 13, 13 },
    { 4, 1, 11, 11 },
    { 4, 0, 20, 20 },
    { 4, 0, 0, 0 },
    { 4, 1, 1, 1 },
    { 4, 2, 2, 2 },
    { 4, 3, 3, 3 },
    { 4, 4, 4, 4 },
    { 2, 2, 9, 9 },
    { 4, 0, 10, 10 },
    { 4, 1, 11, 11 },
    { 4, 2, 12, 12 },
    { 4, 3, 13, 13 },
    { 4, 4, 14, 14 },
    { 2, 3, 19, 19 },
    { 4, 0, 20, 20 },
    { 4, 0, 0, 0 },
    { 4, 1, 1, 1 },
    { 4, 2, 2, 2 },
    { 4, 0, 0, 0 },
    { 4, 1, 1, 1 },
    { 4, 2, 2, 2 },
    { 4, 3, 3, 3 },
    { 4, 4, 4, 4 },
    { 4, 0, 10, 10 },
    { 4, 1, 11, 11 },
    { 4, 2, 12, 12 },
    { 4, 3, 13, 13 },
    { 4, 0, 10, 10 },
    { 4, 1, 11, 11 },
    { 4, 2, 12, 12 },
    { 4, 3, 13, 13 },
    { 4, 4, 14, 14 },
    { 4, 0, 0, 0 },
    { 4, 1, 1, 1 },
    { 4, 2, 2, 2 },
    { 4, 3, 3, 3 },
    { 4, 4, 4, 4 },
    { 4, 0, 10, 10 },
    { 4, 1, 11, 11 },
    { 4, 2, 12, 12 },
    { 4, 3, 13, 13 },
    { 4, 4, 14, 14 },
    { 4, 0, 20, 20 },
};

struct FxbRequest { int miType; int miSize; int miEventId; int miPool; int miName; };
static const FxbRequest kaFxbRequests[] = {
    { 4, 24, 0, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 1, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 2, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 3, 13, 1 },  // highres_debris_02.rf3
    { 4, 24, 4, 13, 2 },  // Glass_debris.rf3
    { 4, 24, 0, 13, 3 },  // WHITE
    { 4, 24, 1, 13, 3 },  // WHITE
    { 4, 24, 2, 13, 3 },  // WHITE
    { 4, 24, 3, 13, 4 },  // highres_debris
    { 4, 24, 4, 13, 5 },  // glass_debris
    { 4, 24, 0, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 1, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 2, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 3, 13, 1 },  // highres_debris_02.rf3
    { 4, 24, 4, 13, 2 },  // Glass_debris.rf3
    { 4, 24, 0, 13, 3 },  // WHITE
    { 4, 24, 1, 13, 3 },  // WHITE
    { 4, 24, 2, 13, 3 },  // WHITE
    { 4, 24, 3, 13, 4 },  // highres_debris
    { 4, 24, 4, 13, 5 },  // glass_debris
    { 4, 24, 0, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 1, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 2, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 3, 13, 1 },  // highres_debris_02.rf3
    { 4, 24, 4, 13, 2 },  // Glass_debris.rf3
    { 4, 24, 0, 13, 3 },  // WHITE
    { 4, 24, 1, 13, 3 },  // WHITE
    { 4, 24, 2, 13, 3 },  // WHITE
    { 4, 24, 3, 13, 4 },  // highres_debris
    { 4, 24, 4, 13, 5 },  // glass_debris
    { 4, 24, 0, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 1, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 2, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 3, 13, 1 },  // highres_debris_02.rf3
    { 4, 24, 4, 13, 2 },  // Glass_debris.rf3
    { 4, 24, 0, 13, 3 },  // WHITE
    { 4, 24, 1, 13, 3 },  // WHITE
    { 4, 24, 2, 13, 3 },  // WHITE
    { 4, 24, 3, 13, 4 },  // highres_debris
    { 4, 24, 4, 13, 5 },  // glass_debris
    { 4, 24, 0, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 1, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 2, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 3, 13, 1 },  // highres_debris_02.rf3
    { 4, 24, 4, 13, 2 },  // Glass_debris.rf3
    { 4, 24, 0, 13, 3 },  // WHITE
    { 4, 24, 1, 13, 3 },  // WHITE
    { 4, 24, 2, 13, 3 },  // WHITE
    { 4, 24, 3, 13, 4 },  // highres_debris
    { 4, 24, 4, 13, 5 },  // glass_debris
    { 4, 24, 0, 13, 3 },  // WHITE
    { 4, 24, 1, 13, 3 },  // WHITE
    { 4, 24, 2, 13, 3 },  // WHITE
    { 4, 24, 3, 13, 4 },  // highres_debris
    { 4, 24, 4, 13, 5 },  // glass_debris
    { 4, 24, 0, 13, 6 },  // particle_description_collection
    { 4, 24, 0, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 1, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 2, 13, 0 },  // lowres_debris.rf3
    { 4, 24, 3, 13, 1 },  // highres_debris_02.rf3
    { 4, 24, 4, 13, 2 },  // Glass_debris.rf3
};

struct FxbHandle { int miCell; int miEntry; };
struct FxbArray { int miTextureCell; int miTextureEntry; int miMeshCell; int miMeshEntry; };
struct FxbStep
{
    int miPresetStage;   // -1 = keep the state the previous call left
    int miPresetCount;
    int miPrebindMeshes; // 1 = the arrays carry mesh cells 0..4 / entries 0..4 before the call
    int miFirstReply, miReplyCount, miFirstRequest, miRequestCount, miPad;
    int miReturn;        // 0 / 1, or 0xFF when the ladder was stopped at stage 11
    int miStopped, miStage, miCount, miQueueCount, miAsserts, miLocks, miUnlocks, miPad2;
    FxbArray maArrays[5];
    FxbHandle mDescription;
};
static const FxbStep kaFxbSteps[] = {
    { 10, 1, 0, 0, 1, 0, 5, 0,  0, 0, 6, 5, 0, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { 20, 20 } },  // canonical step 0
    { -1, -1, 0, 1, 5, 5, 5, 0,  0, 0, 8, 5, 0, 0, 1, 1, 0, { { -1, -1, 0, 0 }, { -1, -1, 1, 1 }, { -1, -1, 2, 2 }, { -1, -1, 3, 3 }, { -1, -1, 4, 4 } }, { 20, 20 } },  // canonical step 1
    { -1, -1, 0, 6, 5, 10, 0, 0,  255, 1, 11, 0, 5, 0, 1, 0, 0, { { 10, 10, 0, 0 }, { 11, 11, 1, 1 }, { 12, 12, 2, 2 }, { 13, 13, 3, 3 }, { 14, 14, 4, 4 } }, { 20, 20 } },  // canonical step 2
    { 10, 1, 0, 11, 1, 10, 5, 0,  0, 0, 6, 5, 0, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { 20, 20 } },  // shuffled step 0
    { -1, -1, 0, 12, 7, 15, 5, 0,  0, 0, 8, 5, 0, 0, 1, 1, 0, { { -1, -1, 0, 0 }, { -1, -1, 1, 1 }, { -1, -1, 2, 2 }, { -1, -1, 3, 3 }, { -1, -1, 4, 4 } }, { 20, 20 } },  // shuffled step 1
    { -1, -1, 0, 19, 6, 20, 0, 0,  255, 1, 11, 0, 6, 0, 1, 0, 0, { { 10, 10, 0, 0 }, { 11, 11, 1, 1 }, { 12, 12, 2, 2 }, { 13, 13, 3, 3 }, { 14, 14, 4, 4 } }, { 20, 20 } },  // shuffled step 2
    { 10, 1, 0, 25, 1, 20, 5, 0,  0, 0, 6, 5, 0, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { 20, 20 } },  // junklast step 0
    { -1, -1, 0, 26, 6, 25, 5, 0,  0, 0, 8, 5, 0, 0, 1, 1, 0, { { -1, -1, 0, 0 }, { -1, -1, 1, 1 }, { -1, -1, 2, 2 }, { -1, -1, 3, 3 }, { -1, -1, 4, 4 } }, { 20, 20 } },  // junklast step 1
    { -1, -1, 0, 32, 6, 30, 0, 0,  255, 1, 11, 0, 6, 0, 1, 0, 0, { { 10, 10, 0, 0 }, { 11, 11, 1, 1 }, { 12, 12, 2, 2 }, { 13, 13, 3, 3 }, { 14, 14, 4, 4 } }, { 20, 20 } },  // junklast step 2
    { 10, 1, 0, 38, 1, 30, 5, 0,  0, 0, 6, 5, 0, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { 20, 20 } },  // partial step 0
    { -1, -1, 0, 39, 3, 35, 0, 0,  0, 0, 6, 5, 3, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { 20, 20 } },  // partial step 1
    { -1, -1, 0, 42, 5, 35, 5, 0,  0, 0, 8, 5, 0, 0, 1, 1, 0, { { -1, -1, 0, 0 }, { -1, -1, 1, 1 }, { -1, -1, 2, 2 }, { -1, -1, 3, 3 }, { -1, -1, 4, 4 } }, { 20, 20 } },  // partial step 2
    { -1, -1, 0, 47, 4, 40, 0, 0,  0, 0, 8, 5, 4, 0, 1, 1, 0, { { -1, -1, 0, 0 }, { -1, -1, 1, 1 }, { -1, -1, 2, 2 }, { -1, -1, 3, 3 }, { -1, -1, 4, 4 } }, { 20, 20 } },  // partial step 3
    { -1, -1, 0, 51, 5, 40, 0, 0,  255, 1, 11, 0, 5, 0, 1, 0, 0, { { 10, 10, 0, 0 }, { 11, 11, 1, 1 }, { 12, 12, 2, 2 }, { 13, 13, 3, 3 }, { 14, 14, 4, 4 } }, { 20, 20 } },  // partial step 4
    { 5, 0, 0, 56, 0, 40, 5, 0,  0, 0, 6, 5, 0, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { -1, -1 } },  // enter5 step 0
    { -1, -1, 0, 56, 5, 45, 5, 0,  0, 0, 8, 5, 0, 0, 1, 1, 0, { { -1, -1, 0, 0 }, { -1, -1, 1, 1 }, { -1, -1, 2, 2 }, { -1, -1, 3, 3 }, { -1, -1, 4, 4 } }, { -1, -1 } },  // enter5 step 1
    { 7, 0, 1, 61, 0, 50, 5, 0,  0, 0, 8, 5, 0, 0, 1, 1, 0, { { -1, -1, 0, 0 }, { -1, -1, 1, 1 }, { -1, -1, 2, 2 }, { -1, -1, 3, 3 }, { -1, -1, 4, 4 } }, { -1, -1 } },  // enter7 step 0
    { -1, -1, 0, 61, 5, 55, 0, 0,  255, 1, 11, 0, 5, 0, 1, 0, 0, { { 10, 10, 0, 0 }, { 11, 11, 1, 1 }, { 12, 12, 2, 2 }, { 13, 13, 3, 3 }, { 14, 14, 4, 4 } }, { -1, -1 } },  // enter7 step 1
    { 9, 0, 0, 66, 0, 55, 1, 0,  0, 0, 10, 1, 0, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { -1, -1 } },  // enter9 step 0
    { -1, -1, 0, 66, 1, 56, 5, 0,  0, 0, 6, 5, 0, 0, 1, 1, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { 20, 20 } },  // enter9 step 1
    { 8, 0, 0, 67, 0, 61, 0, 0,  255, 1, 11, 0, 0, 0, 1, 0, 0, { { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 }, { -1, -1, -1, -1 } }, { -1, -1 } },  // enter8empty step 0
};

struct FxbCase { const char* mpcName; int miFirstStep; int miStepCount; };
static const FxbCase kaFxbCases[] = {
    { "canonical", 0, 3 },
    { "shuffled", 3, 3 },
    { "junklast", 6, 3 },
    { "partial", 9, 5 },
    { "enter5", 14, 2 },
    { "enter7", 16, 2 },
    { "enter9", 18, 2 },
    { "enter8empty", 20, 1 },
};
static const int kiFxbCaseCount = 8;
static const int kiFxbStepCount = 21;
