// GENERATED by scratch/CRASHPARITY_0922/fxcrashvfx_vmxemu/gen_switch_data.py -- DO NOT EDIT.
// The two spark switches run on the console's own words: with the image's bytes (0x01 0x01 at
// 0x82CDB40C / 0x82CDB40D) and, as the counterfactual, with both forced to 0.
#pragma once

struct SparkSwitchRow { const char* mpcName; u32 muImagePosts; u32 muImageRngMoved; u32 muForcedPosts;
                        u32 muForcedType; u32 muForcedSize; };
static const u32 kuSparkSwitchImageBytes = 0x0101u;
static const SparkSwitchRow kaSparkSwitchRows[] = {
    { "HandleSparkContacts @0x822906A8", 0u, 0u, 1u, 3u, 0x50u },
    { "HandleRaceCarRaceCarSparks @0x82290A48", 0u, 0u, 1u, 1u, 0x50u },
};
