// FX-CRASHVFX (crash parity 2026-09-24, item 7 render half): the simple-particle quad builder -- the
// PRODUCTION BrnSimpleParticleArray::CB4ParticleBank::Render @0x8291E600,
// ShadedRotatingRenderMethod::BuildQuad @0x8291E150, NativeParticleVertex::VertexIterator::Write
// @0x8291E478 and SimpleParticleVertexBufferBuilder::BuildDispatchData @0x8291F870, compiled by
// run_fxcrashvfx_simple_render.py against the revision's own headers and the real
// EffectsVertexBuffer.cpp.
//
// THE EXPECTED VERTICES ARE THE CONSOLE'S OWN. FxCrashVfxSimpleRenderData.h was generated by executing
// the real instruction words of Render / BuildQuad / Write in a VMX emulator
// (scratch/CRASHPARITY_0922/fxcrashvfx_vmxemu/gen_render_data.py; fused vmaddfp, exact-rounded vrefp)
// on seven seeded inputs: drag on and off, 1x1 / 2x2 / 4x2 / 3x3 tile atlases, max screen sizes that do
// and do not clamp, particles unborn, expired, behind the near plane and past the far one, a lighting
// range above 1.0, and a batch with too few free vertices (the console prints its assert twice and
// draws nothing). The lowering uses unfused multiply-adds, so positions are compared to a few ulps,
// colours to one step of 255 and UVs exactly.
#include "BrnCommonTypes.h"
#include "GameSource/Effects/Particles/Native/BrnSimpleParticleArray.h"
#include "GameSource/Effects/Particles/Native/ShadedRotatingRenderMethod.h"
#include "GameSource/Effects/Particles/Native/BrnNativeParticleVertex.h"
#include "GameSource/Effects/Particles/EffectsVertexBuffer.h"
#include "FxCrashVfxSimpleRenderData.h"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <malloc.h>

static unsigned gChecks = 0, gFailures = 0, gAsserts = 0;
static char     gLastAssert[256];

static void Check(bool lbPassed, const char* lpcLabel)
{
    ++gChecks;
    if (!lbPassed)
    {
        ++gFailures;
        std::printf("FAIL  %s\n", lpcLabel);
    }
    else
    {
        std::printf("pass  %s\n", lpcLabel);
    }
}

namespace CgsDev
{
namespace Assert
{
    int   BeginAssert() { return 0; }
    int   FireAssert(const char* lpcMessage, const char*, int)
    {
        ++gAsserts;
        std::snprintf(gLastAssert, sizeof(gLastAssert), "%s", lpcMessage ? lpcMessage : "");
        return 0;
    }
    void* EndAssert() { return nullptr; }
}
}

// CgsGraphics::Camera::operator= @0x82218ED0 lives in CgsCamera.cpp with the whole frustum family; the
// builder only needs its copy, so the fixture carries the same field-for-field extent.
CgsGraphics::Camera& CgsGraphics::Camera::operator=(const Camera& rhs)
{
    mView = rhs.mView;
    mProjection = rhs.mProjection;
    mViewProjection = rhs.mViewProjection;
    for (int i = 0; i < 16; ++i) maClipState[i] = rhs.maClipState[i];
    for (int i = 0; i < 9; ++i) maProjectionScalars[i] = rhs.maProjectionScalars[i];
    return *this;
}

// The two static tables BrnSimpleParticleArray.cpp owns are not linked here (only the render half
// is); the render half reads neither.
CgsResource::SafeResourceHandle<renderengine::Texture>
    BrnParticle::Native::BrnSimpleParticleArray::maTextures[BrnParticle::Native::eParticleArray_Max];
BrnParticle::Native::CB4ParticleArrayStandardParams
    BrnParticle::Native::BrnSimpleParticleArray::maStandardParams[BrnParticle::Native::eParticleArray_Max];

namespace
{
    using namespace BrnParticle::Native;
    typedef rw::math::vpu::Vector4 Vector4;

    Vector4 V4(f32 x, f32 y, f32 z, f32 w) { Vector4 v = { x, y, z, w }; return v; }

    // One array + its standard params + one bank of records, from a case.
    struct Fixture
    {
        CB4ParticleArrayStandardParams mParams;
        BrnSimpleParticleArray         mArray;
        CB4Particle*                   mpaRecords;
        u32                            muNumRecords;
        SimpleParticleRenderState      mState;
    };

    void Build(Fixture& f, const RenderCase& c)
    {
        std::memset(&f.mParams, 0, sizeof(f.mParams));
        f.mParams.meBlendMode                 = eParticleBlendNormal;
        f.mParams.mLightingMinMax.x           = c.mfLightMin;
        f.mParams.mLightingMinMax.y           = c.mfLightMax;
        f.mParams.mrDragInitialVelocityScale  = c.mfDragInitial;
        f.mParams.mrDragTerminalVelocityScale = c.mfDragTerminal;
        f.mParams.mrDragDuration              = c.mfDragDuration;
        f.mParams.mbUseDrag                   = c.mbUseDrag;
        f.mParams.muTilesWide                 = c.muTilesWide;
        f.mParams.muTilesHigh                 = c.muTilesHigh;

        std::memset(&f.mArray, 0, sizeof(f.mArray));
        f.mArray.mpStandardParams = &f.mParams;
        CB4ParticleArrayXenon& d = f.mArray.mParticleData;
        d.mStartColour  = V4(c.mafStart[0], c.mafStart[1], c.mafStart[2], c.mafStart[3]);
        d.mMidColour    = V4(c.mafMid[0], c.mafMid[1], c.mafMid[2], c.mafMid[3]);
        d.mEndColour    = V4(c.mafEnd[0], c.mafEnd[1], c.mafEnd[2], c.mafEnd[3]);
        d.mAcceleration.x = 0.0f; d.mAcceleration.y = c.mfGravity; d.mAcceleration.z = 0.0f; d.mAcceleration.w = 0.0f;
        d.mrLifeTime  = c.mfLife;
        d.mrMidTime   = c.mfMidTime;
        d.mrNearFade  = c.mfNearFade;
        d.mrFarFade   = c.mfFarFade;
        d.mrNearClip  = c.mfNearClip;
        d.mrFarClip   = c.mfFarClip;
        d.mSizeParams = V4(c.mafSize[0], c.mafSize[1], c.mafSize[2], c.mafSize[3]);

        f.muNumRecords = (c.muNumRecords + 15u) & ~15u;
        f.mpaRecords = static_cast<CB4Particle*>(_aligned_malloc(sizeof(CB4Particle) * f.muNumRecords, 16));
        for (u32 i = 0; i < f.muNumRecords; ++i)
        {
            CB4Particle& p = f.mpaRecords[i];
            if (i < c.muNumRecords)
            {
                const RenderCaseRecord& r = c.mpaRecords[i];
                p.mPositionTime.x = r.mafPos[0]; p.mPositionTime.y = r.mafPos[1]; p.mPositionTime.z = r.mafPos[2];
                p.mPositionTime.w = r.mfTime;
                p.mVelocityRotation.x = r.mafVel[0]; p.mVelocityRotation.y = r.mafVel[1];
                p.mVelocityRotation.z = r.mafVel[2]; p.mVelocityRotation.w = r.mfRot;
                p.mScaleAlpha = V4(0.0f, 0.0f, r.mfScale, r.mfAlpha);
            }
            else
            {
                p.mPositionTime.x = p.mPositionTime.y = p.mPositionTime.z = 0.0f;
                p.mPositionTime.w = -9999.0f;
                p.mVelocityRotation.x = p.mVelocityRotation.y = p.mVelocityRotation.z = p.mVelocityRotation.w = 0.0f;
                p.mScaleAlpha = V4(0.0f, 0.0f, 0.0f, 0.0f);
            }
        }
        f.mArray.mBankRegular.mpaParticles    = f.mpaRecords;
        f.mArray.mBankRegular.muNumParticles  = f.muNumRecords;
        f.mArray.mBankRegular.muNextParticle  = 0;
        f.mArray.mBankRegular.mrLastSpawnTime = c.mfTime;
        f.mArray.mBankCrash = f.mArray.mBankRegular;

        std::memset(&f.mState, 0, sizeof(f.mState));
        std::memcpy(&f.mState.mCamera.mView, c.mafView, 64);
        std::memcpy(&f.mState.mCamera.mProjection, c.mafProj, 64);
        std::memcpy(&f.mState.mCamera.mViewProjection, c.mafViewProj, 64);
        for (u32 i = 0; i < 9; ++i)
            f.mState.mCamera.maProjectionScalars[i] = c.mafScalars[i];
        f.mState.mvScreenSize  = V4(1280.0f, 720.0f, 0.0f, 0.0f);
        f.mState.mfCurrentTime = c.mfTime;
        f.mState.mfWhiteLevel  = c.mfWhite;
    }

    bool Near(f32 a, f32 b, f32 lfRelative, f32 lfAbsolute)
    {
        if (a != a || b != b) return (a != a) && (b != b);
        const f32 d = std::fabs(a - b);
        return d <= lfAbsolute || d <= lfRelative * std::fmax(std::fabs(a), std::fabs(b));
    }

    // Render one case into a fresh buffer; return the vertex count and compare against the console.
    void RunCase(const RenderCase& c)
    {
        Fixture f;
        Build(f, c);

        const u32 luCapacity = c.muFreeVertices;
        u8* const lpBuffer = static_cast<u8*>(_aligned_malloc(24u * (luCapacity + 1u) + 64u, 16));
        std::memset(lpBuffer, 0xCD, 24u * (luCapacity + 1u) + 64u);
        u8* const lpBase = lpBuffer + 16;

        BrnParticle::NativeParticleVertex::VertexIterator lIterator;
        lIterator.SetBaseAddress(lpBase);
        lIterator.SetCurrentAddress(lpBase - 4);
        lIterator.SetTopAddress(lpBase - 4 + 24u * luCapacity);
        lIterator.SetStride(24u);

        const unsigned luAssertsBefore = gAsserts;
        f.mArray.mBankRegular.Render(lIterator, f.mArray, f.mState);
        const unsigned luAssertsFired = gAsserts - luAssertsBefore;

        const u32 luWritten = static_cast<u32>((lIterator.GetCurrentAddress() - (lpBase - 4)) / 24);
        char lacLabel[256];
        std::snprintf(lacLabel, sizeof(lacLabel), "%s: %u vertices written (console %u)", c.mpcName,
                      luWritten, c.muNumVertices);
        Check(luWritten == c.muNumVertices, lacLabel);

        std::snprintf(lacLabel, sizeof(lacLabel), "%s: asserts fired %u (console printed %u)", c.mpcName,
                      luAssertsFired, c.muConsoleAsserts);
        Check((luAssertsFired != 0) == (c.muConsoleAsserts != 0), lacLabel);

        u32 luBadPosition = 0, luBadColour = 0, luBadUv = 0;
        const u32 luCompare = (luWritten < c.muNumVertices) ? luWritten : c.muNumVertices;
        for (u32 v = 0; v < luCompare; ++v)
        {
            const u8* const lpVertex = lpBase + 24u * v;
            f32 lafPos[3], lafUv[2];
            u8  lau8Colour[4];
            std::memcpy(lafPos, lpVertex, 12);
            std::memcpy(lau8Colour, lpVertex + 12, 4);
            std::memcpy(lafUv, lpVertex + 16, 8);
            const RenderCaseVertex& e = c.mpaVertices[v];
            for (u32 k = 0; k < 3; ++k)
            {
                if (!Near(lafPos[k], e.mafPos[k], 4e-6f, 2e-6f))
                {
                    if (luBadPosition < 4)
                        std::printf("  %s v%u pos[%u] %.9g vs console %.9g\n", c.mpcName, v, k, lafPos[k], e.mafPos[k]);
                    ++luBadPosition;
                }
            }
            // The console's word is (R<<24)|(G<<16)|(B<<8)|A: memory [R][G][B][A] on the console.
            const u8 lau8Expected[4] = { static_cast<u8>(e.muColourRGBA >> 24), static_cast<u8>(e.muColourRGBA >> 16),
                                         static_cast<u8>(e.muColourRGBA >> 8),  static_cast<u8>(e.muColourRGBA) };
            for (u32 k = 0; k < 4; ++k)
            {
                const int liDelta = static_cast<int>(lau8Colour[k]) - static_cast<int>(lau8Expected[k]);
                if (liDelta < -1 || liDelta > 1)
                {
                    if (luBadColour < 4)
                        std::printf("  %s v%u colour[%u] %u vs console %u\n", c.mpcName, v, k, lau8Colour[k], lau8Expected[k]);
                    ++luBadColour;
                }
            }
            for (u32 k = 0; k < 2; ++k)
            {
                if (!Near(lafUv[k], e.mafUv[k], 0.0f, 1e-7f))
                {
                    if (luBadUv < 4)
                        std::printf("  %s v%u uv[%u] %.9g vs console %.9g\n", c.mpcName, v, k, lafUv[k], e.mafUv[k]);
                    ++luBadUv;
                }
            }
        }
        std::snprintf(lacLabel, sizeof(lacLabel), "%s: positions match the console (%u off)", c.mpcName, luBadPosition);
        Check(luCompare == c.muNumVertices && luBadPosition == 0, lacLabel);
        std::snprintf(lacLabel, sizeof(lacLabel), "%s: RGBA8 corner colours match the console (%u off)", c.mpcName, luBadColour);
        Check(luCompare == c.muNumVertices && luBadColour == 0, lacLabel);
        std::snprintf(lacLabel, sizeof(lacLabel), "%s: tile UVs match the console (%u off)", c.mpcName, luBadUv);
        Check(luCompare == c.muNumVertices && luBadUv == 0, lacLabel);

        _aligned_free(lpBuffer);
        _aligned_free(f.mpaRecords);
    }

    // BuildDispatchData over a two-type list: the lifetime gate, the crash-bank flag, the batch record.
    void RunBuilder()
    {
        const RenderCase& c0 = kRenderCases[0];   // drag_2x2_max400 -> type 3
        const RenderCase& c1 = kRenderCases[1];   // nodrag_1x1_max120 -> type 1
        static Fixture laFixtures[2];
        Build(laFixtures[0], c0);
        Build(laFixtures[1], c1);

        static BrnSimpleParticleArray laArrays[eParticleArray_Max];
        std::memset(laArrays, 0, sizeof(laArrays));
        laArrays[3] = laFixtures[0].mArray;
        laArrays[1] = laFixtures[1].mArray;
        laArrays[1].mParticleData = laFixtures[1].mArray.mParticleData;
        // Type 1's regular bank is too old to hold a live particle: time - last >= lifetime.
        laArrays[1].mBankRegular.mrLastSpawnTime = c1.mfTime - c1.mfLife;
        laFixtures[1].mParams.meBlendMode = eParticleBlendAdditive;

        const u32 luBytes = 163840u;
        u8* const lpBuffer = static_cast<u8*>(_aligned_malloc(luBytes, 16));
        EffectsVertexBuffer lBuffer;
        lBuffer.Construct(lpBuffer, luBytes);
        EffectsVertexBufferLocked& lLocked = lBuffer.Lock();

        SimpleParticleBatchArray lBatches;
        lBatches.Clear();
        const u32 lauTypes[2] = { 3u, 1u };
        const u32 luQuadsBefore = gauSimpleParticleQuadsBuilt;
        SimpleParticleVertexBufferBuilder::BuildDispatchData(&lLocked, lBatches, laArrays, lauTypes, 2u,
                                                            c0.mfTime, laFixtures[0].mState.mCamera,
                                                            c0.mfWhite, false);
        Check(lBatches.GetLength() == 1u, "BuildDispatchData: one batch -- type 1's bank is past its lifetime gate");
        Check(lBatches.GetLength() >= 1u && lBatches[0].muVertexCount == c0.muNumVertices
              && lBatches[0].muStartVertex == 0u && lBatches[0].meParticleType == 3u
              && lBatches[0].meBlendMode == static_cast<u32>(eParticleBlendNormal),
              "BuildDispatchData: the batch is {start 0, the console's vertex count, type 3, blend Normal}");
        Check(gauSimpleParticleQuadsBuilt - luQuadsBefore == c0.muNumVertices / 4u,
              "BuildDispatchData: the quad counter advances by the quads written");

        // The crash bank renders into the SAME batch when asked.
        lBuffer.UnLock();
        EffectsVertexBufferLocked& lLocked2 = lBuffer.Lock();
        lBatches.Clear();
        laArrays[1].mBankRegular.mrLastSpawnTime = c1.mfTime;
        SimpleParticleVertexBufferBuilder::BuildDispatchData(&lLocked2, lBatches, laArrays, lauTypes, 2u,
                                                            c0.mfTime, laFixtures[0].mState.mCamera,
                                                            c0.mfWhite, true);
        Check(lBatches.GetLength() == 2u && lBatches[0].muVertexCount == 2u * c0.muNumVertices,
              "BuildDispatchData: lbRenderCrashBanks draws the crash bank into the same batch");
        Check(lBatches.GetLength() == 2u && lBatches[1].meParticleType == 1u
              && lBatches[1].meBlendMode == static_cast<u32>(eParticleBlendAdditive)
              && lBatches[1].muVertexCount > 0u,
              "BuildDispatchData: the second type appends its own batch with its own blend mode");
        lBatches.SetPreLionCount();
        Check(lBatches.GetPreLionCount() == 2u, "SimpleParticleBatchArray::SetPreLionCount stores GetLength()");
        lBatches.Clear();
        Check(lBatches.GetLength() == 0u && lBatches.GetPreLionCount() == 0u,
              "SimpleParticleBatchArray::Clear zeroes the count AND the pre-Lion split");
        lBuffer.UnLock();
        _aligned_free(lpBuffer);
    }
}

int main()
{
    for (const RenderCase& c : kRenderCases)
        RunCase(c);
    RunBuilder();
    std::printf("FxCrashVfxSimpleRender: %u checks, %u failures\n", gChecks, gFailures);
    return gFailures == 0 ? 0 : 1;
}
