// FX-DIRECTOR2 (crash parity 2026-09-24): BrnDirector::CrashAnalyser::Update @0x82209290.
//
// Compiles the PRODUCTION BrnCrashAnalyser.cpp (the runner writes the revision's text into
// fxdirector2_crash_analyser.inc -- or a labelled stand-in when the revision has no body, which
// is every revision before FX-DIRECTOR2: the analyser was an opaque zero span and its Update call
// in MainDirector::PreSceneQueryUpdate was gated) against the real InputBuffer / GameState /
// VehicleInfo / PlayerCrashInfo headers, and runs it over a fixture table GENERATED BY EXECUTING THE
// CONSOLE'S OWN WORDS (scratch/CRASHPARITY_0922/fixes/FX-DIRECTOR2.emu/crashanemu.py +
// crashan_fixtures.py: the FX-FX VMX emulator on the ARTIST export of @0x82209290; the two calls it
// makes -- sub_82207040 (GetRaceCarInfo, `addi r3, r28, 0x990`) and the CRT `cos` -- are run
// natively). Each row gives the analyser's three records before the call and the inputs, and the
// console's three records after it. Direction rows whose X / Z angle falls within 1e-3 of
// +-cos(67.5 deg) are excluded by the generator (the console's vrefp / vrsqrtefp estimates vs the
// PC's exact 1/x and 1/sqrt, see the FLAG in BrnCrashAnalyser.cpp).
//
// The two InputBuffer accessors the body calls are defined HERE over the fixture data (their
// production bodies live in BrnDirectorModuleIOInputBuffer.cpp and only add the read-lock tripwire).

#include <cmath>
#include <cstdio>
#include <cstring>
#include <limits>
#include "types.hpp"
#include "GameSource/Director/BrnCrashAnalyser.h"
#include "GameSource/Director/DirectorModule/BrnDirectorModuleIO.h"
#include "GameSource/Director/DirectorModule/BrnDirectorGameState.h"
#include "GameSource/Director/Camera/SharedIO/BrnPlayerInfo.h"
#include "GameSource/Director/Utils/BrnDirectorVehicleTracker.h"
#include "GameSource/Director/DirectorModule/BrnDirectorModuleDebugPrinter.h"
#include "GameShared/GameClasses/System/Timer/CgsTimerStatusInterface.h"
#include "GameShared/GameClasses/Containers/CgsBitArray.h"

static int giAsserts = 0;

namespace CgsDev
{
namespace Assert
{
    int   BeginAssert() { return 0; }
    int   FireAssert(const char* lpcText, const char*, int) { ++giAsserts; std::printf("ASSERT %s\n", lpcText); return 0; }
    void* EndAssert() { return nullptr; }
}
}

// VehicleInfo's constructor clears its RaceCarState; the physics TU that owns Clear is not linked here
// (the FxDirectorMoments precedent).
void BrnPhysics::Vehicle::RaceCarState::Clear() { std::memset(static_cast<void*>(this), 0, sizeof(*this)); }

namespace
{
    BrnDirector::Camera::PlayerCrashInfo gCrashInfo;
    BrnDirector::Camera::VehicleInfo     gaRaceCars[8];
    CgsContainers::BitArray<8u>          gUsedRaceCars;
    CgsSystem::TimerStatusInterface      gTimers;
    int                                  giAccessorCalls = 0;
}

namespace BrnDirector
{
namespace DirectorIO
{
    const Camera::PlayerCrashInfo*          InputBuffer::GetPlayerCrashInfo() const      { ++giAccessorCalls; return &gCrashInfo; }
    const Camera::VehicleInfo*              InputBuffer::GetRaceCarInfo() const          { ++giAccessorCalls; return gaRaceCars; }
    const CgsContainers::BitArray<8u>*      InputBuffer::GetUsedRaceCars() const         { return &gUsedRaceCars; }
    const CgsSystem::TimerStatusInterface*  InputBuffer::GetTimerStatusInterface() const { return &gTimers; }
}
}

// The production body under test (or the runner's labelled stand-in).
#include "fxdirector2_crash_analyser.inc"

using namespace BrnDirector;

static int giChecks = 0;
static int giFailures = 0;

static void Check(bool lbPass, const char* lpcName)
{
    ++giChecks;
    if (!lbPass)
    {
        ++giFailures;
        std::printf("FAIL  %s\n", lpcName);
    }
}

static const f32 KF_NAN = std::numeric_limits<f32>::quiet_NaN();
static const f32 KF_INF = std::numeric_limits<f32>::infinity();

struct Record { u32 muFlags; int miCrashing; int miLeft; };
struct Row
{
    const char* mpcName;
    Record      maBefore[3];
    int         miCrashActive, miWall, miAI;
    f32         mafNormal[3];
    f32         mafTransform[12];
    f32         mafMin[3];
    f32         mafMax[3];
    Record      maAfter[3];
};

// GENERATED by crashan_fixtures.py from the console words (see the banner). Do not hand-edit.
static const Row kaRows[] =
{
    { "wall head-on (normal -Z)", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.0f, 0.0f, -1.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {169u,1,1, 0u,0,0, 0u,0,0} },
    { "wall from behind (normal +Z)", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.0f, 0.0f, 1.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {105u,1,1, 0u,0,0, 0u,0,0} },
    { "wall on the left flank (normal +X)", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {1.0f, 0.0f, 0.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {43u,1,1, 0u,0,0, 0u,0,0} },
    { "wall on the right flank (normal -X)", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-1.0f, 0.0f, 0.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {45u,1,1, 0u,0,0, 0u,0,0} },
    { "AI hard stop, front corner", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {0.699999988079071f, 0.0f, -0.699999988079071f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {179u,1,0, 0u,0,0, 0u,0,0} },
    { "wall and AI together", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,1, {0.20000000298023224f, 0.10000000149011612f, -0.9700000286102295f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {187u,1,1, 0u,0,0, 0u,0,0} },
    { "crash start, no hard stop", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,0, {0.0f, 0.0f, -1.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {32u,1,0, 0u,0,0, 0u,0,0} },
    { "second crashing frame: no edge", {41u,1,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.0f, 0.0f, -1.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {0u,1,0, 41u,1,0, 0u,0,0} },
    { "not crashing", {169u,1,1, 32u,1,0, 33u,0,1}, 0,1,0, {0.0f, 0.0f, -1.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {0u,0,1, 169u,1,1, 33u,0,1} },
    { "zero normal -> Clear()", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.0f, 0.0f, 0.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {0u,0,1, 0u,0,0, 0u,0,0} },
    { "sub-epsilon normal -> Clear()", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {9.99999993922529e-09f, -9.99999993922529e-09f, 5.000000058430487e-08f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {0u,0,1, 0u,0,0, 0u,0,0} },
    { "vertical normal: NaN direction, no face bits", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.0f, 1.0f, 0.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {41u,1,1, 0u,0,0, 0u,0,0} },
    { "NaN normal -> Clear()", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {KF_NAN, 0.0f, 0.0f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.949999988079071f, 0.0f, -2.200000047683716f}, {0.949999988079071f, 1.4500000476837158f, 2.299999952316284f},
      {0u,0,1, 0u,0,0, 0u,0,0} },
    { "long car: a side-ish hit on a long box is a side hit", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.800000011920929f, 0.0f, -0.6000000238418579f}, {1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 3.0f, 0.25f, -7.5f}, {-0.8999999761581421f, 0.0f, -2.5999999046325684f}, {0.8999999761581421f, 1.399999976158142f, 2.5999999046325684f},
      {43u,1,1, 0u,0,0, 0u,0,0} },
    { "random 0", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {0.3409433662891388f, -0.9229617118835449f, 0.178603857755661f}, {-0.9278272390365601f, 0.363781601190567f, -0.08245950937271118f, 0.3627946376800537f, 0.8287081718444824f, -0.4261723458766937f, -0.08669878542423248f, -0.42533019185066223f, -0.900875985622406f, 3.0f, 0.25f, -7.5f}, {-1.044105052947998f, -2.3857367038726807f, -1.6466200351715088f}, {1.4266135692596436f, 1.2191369533538818f, 2.359250545501709f},
      {53u,1,0, 0u,0,0, 0u,0,0} },
    { "random 1", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.7008225321769714f, -0.46635156869888306f, 0.5397814512252808f}, {-0.8927639722824097f, -0.2525666058063507f, -0.3730717897415161f, -0.2559099495410919f, 0.9658114910125732f, -0.04145195707678795f, 0.3707863986492157f, 0.05846596509218216f, -0.9268760085105896f, 3.0f, 0.25f, -7.5f}, {-2.3269898891448975f, -1.7608811855316162f, -1.5594007968902588f}, {1.6998164653778076f, -0.45884254574775696f, 1.295709490776062f},
      {171u,1,1, 0u,0,0, 0u,0,0} },
    { "random 2", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,1, {-0.09890914708375931f, 0.9065279960632324f, -0.4103948771953583f}, {0.8710424304008484f, 0.44628360867500305f, 0.20522181689739227f, -0.42166250944137573f, 0.8936408162117004f, -0.15364493429660797f, -0.2519637942314148f, 0.047296907752752304f, 0.9665801525115967f, 3.0f, 0.25f, -7.5f}, {-0.8670259714126587f, -1.3835707902908325f, -1.4015300273895264f}, {2.755768299102783f, 2.0333926677703857f, 0.07053055614233017f},
      {185u,1,0, 0u,0,0, 0u,0,0} },
    { "random 3", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.8258868455886841f, 0.5630242824554443f, -0.030241720378398895f}, {-0.3463338315486908f, 0.007549609523266554f, -0.9380809664726257f, 0.07379621267318726f, 0.9970880746841431f, -0.01922062411904335f, 0.935204267501831f, -0.07588357478380203f, -0.34588247537612915f, 3.0f, 0.25f, -7.5f}, {-0.9288220405578613f, -0.6219974160194397f, -1.670483112335205f}, {0.5811684727668762f, 0.9306515455245972f, -0.6161483526229858f},
      {105u,1,1, 0u,0,0, 0u,0,0} },
    { "random 4", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.032845888286828995f, 0.7350756525993347f, 0.6771889925003052f}, {0.7485708594322205f, 0.3578207492828369f, -0.5582168102264404f, 0.027332233265042305f, 0.8245184421539307f, 0.5651745796203613f, 0.6624912023544312f, -0.4383305311203003f, 0.6074304580688477f, 3.0f, 0.25f, -7.5f}, {-1.753290057182312f, -0.6040210127830505f, -1.0001024007797241f}, {2.810835123062134f, 1.9037911891937256f, 0.08204007893800735f},
      {117u,1,1, 0u,0,0, 0u,0,0} },
    { "random 5", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {0.6541746854782104f, 0.6248971223831177f, -0.426097571849823f}, {0.2835892140865326f, -0.1783534735441208f, -0.9422140121459961f, -0.19276848435401917f, 0.951892077922821f, -0.23820525407791138f, 0.9393707513809204f, 0.2491815984249115f, 0.2355654090642929f, 3.0f, 0.25f, -7.5f}, {-2.4998605251312256f, -1.9080065488815308f, -2.3080661296844482f}, {-0.3350791335105896f, -0.065789133310318f, 2.417083501815796f},
      {115u,1,1, 0u,0,0, 0u,0,0} },
    { "random 6", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.24985246360301971f, -0.9154453873634338f, 0.3154892921447754f}, {0.9867194294929504f, 0.10035432875156403f, -0.12772560119628906f, -0.1391342729330063f, 0.9279491901397705f, -0.34576281905174255f, 0.08382408320903778f, 0.3589418828487396f, 0.9295881986618042f, 3.0f, 0.25f, -7.5f}, {-0.9093341827392578f, -1.1534099578857422f, -1.4970606565475464f}, {0.9590668082237244f, 2.522284746170044f, 1.7482595443725586f},
      {43u,1,1, 0u,0,0, 0u,0,0} },
    { "random 7", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.35643503069877625f, -0.8263958692550659f, 0.43591734766960144f}, {-0.8098180294036865f, -0.42857852578163147f, -0.4006434679031372f, -0.37038981914520264f, 0.903081476688385f, -0.21738272905349731f, 0.45497927069664f, -0.027646197006106377f, -0.890072762966156f, 3.0f, 0.25f, -7.5f}, {-1.7402827739715576f, -1.5957505702972412f, -1.632089376449585f}, {2.81532621383667f, 0.9508500099182129f, 1.8760268688201904f},
      {171u,1,1, 0u,0,0, 0u,0,0} },
    { "random 8", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.3913063704967499f, -0.9148386716842651f, -0.09974740445613861f}, {0.7451601028442383f, 0.4574858546257019f, 0.48522475361824036f, -0.20709699392318726f, 0.8503695726394653f, -0.48371732234954834f, -0.6339141726493835f, 0.25995826721191406f, 0.7284054160118103f, 3.0f, 0.25f, -7.5f}, {-0.6732649803161621f, -2.3129608631134033f, -1.5209251642227173f}, {4.2454118728637695f, 1.0664441585540771f, 0.4969440698623657f},
      {181u,1,0, 0u,0,0, 0u,0,0} },
    { "random 9", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.3496719002723694f, -0.9258297681808472f, 0.14341817796230316f}, {0.8980834484100342f, -0.08932710438966751f, 0.4306585192680359f, 0.17032259702682495f, 0.9733929634094238f, -0.15328510105609894f, -0.40550747513771057f, 0.21101368963718414f, 0.8894025683403015f, 3.0f, 0.25f, -7.5f}, {-2.4732165336608887f, -1.2312631607055664f, -1.270575761795044f}, {-0.7040817141532898f, 2.103347063064575f, 1.249799370765686f},
      {117u,1,0, 0u,0,0, 0u,0,0} },
    { "random 10", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.22280317544937134f, 0.7309232950210571f, 0.6450658440589905f}, {0.060959041118621826f, -0.26739606261253357f, 0.9616565704345703f, 0.45478111505508423f, 0.8650735020637512f, 0.21171197295188904f, -0.8885145783424377f, 0.4244374930858612f, 0.17434072494506836f, 3.0f, 0.25f, -7.5f}, {-0.6725435853004456f, -1.3499022722244263f, -2.3621978759765625f}, {1.2854886054992676f, 0.928672194480896f, -0.037542521953582764f},
      {115u,1,0, 0u,0,0, 0u,0,0} },
    { "random 11", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.2114182412624359f, 0.6385066509246826f, 0.7400078177452087f}, {-0.9991911053657532f, -0.005979752633720636f, -0.03976649418473244f, -0.02095179446041584f, 0.9214711785316467f, 0.38788124918937683f, 0.034324243664741516f, 0.388400673866272f, -0.9208511114120483f, 3.0f, 0.25f, -7.5f}, {-1.6636642217636108f, -0.6438607573509216f, -0.5438351631164551f}, {0.10368350148200989f, 1.3096654415130615f, 2.606773853302002f},
      {171u,1,0, 0u,0,0, 0u,0,0} },
    { "random 12", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {0.9797596335411072f, 0.056382276117801666f, 0.1920732706785202f}, {0.7963600158691406f, 0.2137044370174408f, 0.5658102035522461f, -0.2509899437427521f, 0.9679113626480103f, -0.012316141277551651f, -0.5502861142158508f, -0.1322045773267746f, 0.824443519115448f, 3.0f, 0.25f, -7.5f}, {-1.0883300304412842f, -0.7222477197647095f, -0.7703127264976501f}, {0.08404551446437836f, 0.9380471706390381f, 2.7929465770721436f},
      {179u,1,0, 0u,0,0, 0u,0,0} },
    { "random 13", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {0.31924259662628174f, 0.5904635190963745f, -0.7412401437759399f}, {-0.981622040271759f, 0.12919367849826813f, 0.14045332372188568f, 0.12556633353233337f, 0.9914877414703369f, -0.03442609682679176f, -0.14370538294315338f, -0.016157208010554314f, -0.9894886016845703f, 3.0f, 0.25f, -7.5f}, {-2.292977809906006f, -1.4500306844711304f, -1.6358968019485474f}, {-0.8836997747421265f, 3.1890413761138916f, 2.8537685871124268f},
      {117u,1,1, 0u,0,0, 0u,0,0} },
    { "random 14", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,1, {0.7673801183700562f, -0.5464144945144653f, 0.33549803495407104f}, {0.9958932399749756f, -0.09024904668331146f, 0.007191769313067198f, 0.09047752618789673f, 0.9949479699134827f, -0.043500710278749466f, -0.003229538444429636f, 0.04397276043891907f, 0.9990274906158447f, 3.0f, 0.25f, -7.5f}, {-1.1516108512878418f, -2.186985492706299f, -1.16254723072052f}, {1.388832926750183f, 0.05575428530573845f, 3.1277167797088623f},
      {59u,1,0, 0u,0,0, 0u,0,0} },
    { "random 15", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.3389705419540405f, -0.8176717758178711f, -0.46530836820602417f}, {-0.9811938405036926f, 0.010073868557810783f, -0.1927618682384491f, -0.01620069332420826f, 0.9908156991004944f, 0.13424526154994965f, 0.19234386086463928f, 0.13484349846839905f, -0.9720190763473511f, 3.0f, 0.25f, -7.5f}, {-1.4870615005493164f, -1.5582494735717773f, -2.033940553665161f}, {0.6392321586608887f, 0.3405267596244812f, -0.3295855224132538f},
      {115u,1,1, 0u,0,0, 0u,0,0} },
    { "random 16", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.2246420830488205f, -0.6074755191802979f, -0.7619116902351379f}, {-0.9168330430984497f, -0.31291136145591736f, 0.2479993849992752f, -0.2882307469844818f, 0.9485260248184204f, 0.13123057782649994f, -0.2762974202632904f, 0.048835478723049164f, -0.959830641746521f, 3.0f, 0.25f, -7.5f}, {-1.6435900926589966f, -0.8525320887565613f, -1.8976000547409058f}, {2.2383646965026855f, 2.0314154624938965f, 0.9974343180656433f},
      {105u,1,1, 0u,0,0, 0u,0,0} },
    { "random 17", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.23112079501152039f, -0.4889674484729767f, -0.8411266207695007f}, {0.5331571698188782f, 0.12539301812648773f, -0.8366720080375671f, 0.1907338798046112f, 0.9456787109375f, 0.26327240467071533f, 0.8242353796958923f, -0.29994726181030273f, 0.48027870059013367f, 3.0f, 0.25f, -7.5f}, {-1.7287285327911377f, -1.347187876701355f, -0.8394435048103333f}, {0.06518886238336563f, 2.2887372970581055f, 2.6559174060821533f},
      {179u,1,1, 0u,0,0, 0u,0,0} },
    { "random 18", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.836999773979187f, 0.250515341758728f, -0.48649099469184875f}, {-0.7708956003189087f, -0.19235002994537354f, -0.6072243452072144f, -0.3582180440425873f, 0.9191924929618835f, 0.16360020637512207f, 0.526687502861023f, 0.3436374068260193f, -0.7775046825408936f, 3.0f, 0.25f, -7.5f}, {-1.2469731569290161f, -1.0332882404327393f, -0.5082751512527466f}, {0.910354495048523f, 2.4025025367736816f, 2.2999179363250732f},
      {43u,1,1, 0u,0,0, 0u,0,0} },
    { "random 19", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.38104048371315f, -0.6532162427902222f, -0.6543062329292297f}, {0.08144128322601318f, -0.29393160343170166f, 0.9523504972457886f, -0.14606639742851257f, 0.9416877031326294f, 0.30313169956207275f, -0.985916793346405f, -0.16379384696483612f, 0.03375872224569321f, 3.0f, 0.25f, -7.5f}, {-1.2525544166564941f, -0.7760257124900818f, -1.534116506576538f}, {0.8986557126045227f, 2.2433409690856934f, 2.1948089599609375f},
      {109u,1,0, 0u,0,0, 0u,0,0} },
    { "random 20", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,1, {-0.5301933288574219f, 0.7712840437889099f, 0.3521589934825897f}, {-0.13910585641860962f, -0.12885957956314087f, 0.9818578362464905f, -0.4065529406070709f, 0.9115191102027893f, 0.062029413878917694f, -0.9029752016067505f, -0.3905485272407532f, -0.1791858822107315f, 3.0f, 0.25f, -7.5f}, {-1.8803648948669434f, -2.4875736236572266f, -0.8855815529823303f}, {0.2289382666349411f, -0.9155336022377014f, 0.5768219232559204f},
      {59u,1,0, 0u,0,0, 0u,0,0} },
    { "random 21", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.3364226222038269f, 0.12236622720956802f, 0.9337270855903625f}, {0.8385375142097473f, 0.1566344052553177f, -0.5218433737754822f, -0.0008724858635105193f, 0.9581699371337891f, 0.2861984670162201f, 0.5448431968688965f, -0.23953284323215485f, 0.8035981059074402f, 3.0f, 0.25f, -7.5f}, {-0.8238884806632996f, -2.3745086193084717f, -1.1974678039550781f}, {2.190500020980835f, 1.299513816833496f, 1.9938254356384277f},
      {109u,1,1, 0u,0,0, 0u,0,0} },
    { "random 22", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.9311085939407349f, 0.3094232380390167f, 0.19311657547950745f}, {-0.09859513491392136f, -0.27241504192352295f, -0.9571149349212646f, -0.3645063638687134f, 0.9048426151275635f, -0.2199884057044983f, 0.9259665608406067f, 0.3271847069263458f, -0.18851009011268616f, 3.0f, 0.25f, -7.5f}, {-0.5034652352333069f, -1.3579882383346558f, -0.5113533735275269f}, {0.5447100400924683f, 1.9835638999938965f, 2.543548345565796f},
      {105u,1,1, 0u,0,0, 0u,0,0} },
    { "random 23", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.7526828646659851f, -0.6565229296684265f, -0.0494593121111393f}, {0.23358365893363953f, 0.28010863065719604f, -0.9311164617538452f, 0.2451479583978653f, 0.9097064137458801f, 0.3351666331291199f, 0.9409257173538208f, -0.3065507411956787f, 0.143824502825737f, 3.0f, 0.25f, -7.5f}, {-1.8763115406036377f, -0.6875507235527039f, -1.2968076467514038f}, {2.3462777137756348f, 0.5869948863983154f, 3.534966230392456f},
      {181u,1,1, 0u,0,0, 0u,0,0} },
    { "random 24", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.8700091242790222f, 0.2859436869621277f, 0.40164700150489807f}, {-0.4701980650424957f, -0.19946469366550446f, 0.859725296497345f, -0.07019476592540741f, 0.9794918298721313f, 0.18886101245880127f, -0.8797650337219238f, 0.02845386415719986f, -0.4745565354824066f, 3.0f, 0.25f, -7.5f}, {-0.8074930310249329f, -1.1793136596679688f, -0.9741901159286499f}, {3.625424861907959f, 1.323287844657898f, 0.4664558470249176f},
      {169u,1,0, 0u,0,0, 0u,0,0} },
    { "random 25", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.6084573268890381f, 0.6296964287757874f, 0.482972115278244f}, {-0.531671404838562f, -0.19178223609924316f, -0.8249515891075134f, -0.3735453188419342f, 0.927270233631134f, 0.0251765139400959f, 0.7601246237754822f, 0.3215424120426178f, -0.5646424293518066f, 3.0f, 0.25f, -7.5f}, {-1.4850358963012695f, -0.8843382596969604f, -1.157170295715332f}, {2.138700008392334f, 3.0594873428344727f, 1.0184446573257446f},
      {173u,1,1, 0u,0,0, 0u,0,0} },
    { "random 26", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.9375337958335876f, 0.011363931931555271f, 0.347708523273468f}, {0.882906436920166f, 0.06446682661771774f, 0.4651023745536804f, 0.0037692037876695395f, 0.9895251989364624f, -0.14431102573871613f, -0.469533771276474f, 0.12916620075702667f, 0.8734152317047119f, 3.0f, 0.25f, -7.5f}, {-0.6975441575050354f, -1.9264625310897827f, -1.1388014554977417f}, {1.813549518585205f, 2.8249351978302f, 0.0549158900976181f},
      {117u,1,0, 0u,0,0, 0u,0,0} },
    { "random 27", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.15307092666625977f, 0.008864502422511578f, 0.9881754517555237f}, {0.8362297415733337f, -0.16178813576698303f, 0.523969829082489f, 0.34826239943504333f, 0.894747793674469f, -0.27953481674194336f, -0.4235954284667969f, 0.4162343144416809f, 0.8045594692230225f, 3.0f, 0.25f, -7.5f}, {-1.9210548400878906f, -1.129615306854248f, -1.2937085628509521f}, {2.012176036834717f, 0.5290831923484802f, 1.904681921005249f},
      {105u,1,0, 0u,0,0, 0u,0,0} },
    { "random 28", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.9230812788009644f, 0.32180216908454895f, 0.21062837541103363f}, {-0.4287151098251343f, 0.43406349420547485f, 0.7923334240913391f, -0.16137650609016418f, 0.8261208534240723f, -0.539890706539154f, -0.8889099955558777f, -0.35932332277297974f, -0.28412285447120667f, 3.0f, 0.25f, -7.5f}, {-0.5802358984947205f, -2.184156656265259f, -1.855576753616333f}, {2.690427541732788f, 0.8186222314834595f, 2.0675506591796875f},
      {115u,1,0, 0u,0,0, 0u,0,0} },
    { "random 29", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.34325721859931946f, 0.7432637214660645f, 0.5742242932319641f}, {0.9757097959518433f, 0.2184119075536728f, -0.01693182811141014f, -0.20067185163497925f, 0.8601021766662598f, -0.4689936637878418f, -0.08787069469690323f, 0.46099942922592163f, 0.8830392360687256f, 3.0f, 0.25f, -7.5f}, {-2.2278921604156494f, -0.5208327174186707f, -1.8773657083511353f}, {2.0249600410461426f, 1.4582692384719849f, 1.701228380203247f},
      {107u,1,0, 0u,0,0, 0u,0,0} },
    { "random 30", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {0.9631108045578003f, -0.12260483205318451f, -0.23955291509628296f}, {0.42030373215675354f, 0.31411013007164f, 0.8512811660766602f, -0.18028326332569122f, 0.9483754634857178f, -0.2609250843524933f, -0.889293372631073f, -0.043803952634334564f, 0.455234557390213f, 3.0f, 0.25f, -7.5f}, {-0.8881508708000183f, -0.603726327419281f, -1.1037375926971436f}, {1.7310466766357422f, 1.1457583904266357f, -0.016321493312716484f},
      {177u,1,0, 0u,0,0, 0u,0,0} },
    { "random 31", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.5679460763931274f, 0.578151285648346f, -0.5858142971992493f}, {-0.9940378069877625f, 0.09117497503757477f, -0.059799712151288986f, 0.10495409369468689f, 0.9487466216087341f, -0.2981015145778656f, 0.029555372893810272f, -0.3026004135608673f, -0.9526591300964355f, 3.0f, 0.25f, -7.5f}, {-1.1500329971313477f, -1.231992244720459f, -0.570145845413208f}, {2.3609864711761475f, 3.5290699005126953f, 0.5323814153671265f},
      {105u,1,1, 0u,0,0, 0u,0,0} },
    { "random 32", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.5541771054267883f, -0.7675141096115112f, -0.32219529151916504f}, {-0.963272213935852f, -0.2373523861169815f, 0.12558065354824066f, -0.17582476139068604f, 0.9109755158424377f, 0.3731076121330261f, -0.202958881855011f, 0.33732402324676514f, -0.9192498326301575f, 3.0f, 0.25f, -7.5f}, {-1.9139238595962524f, -1.4451041221618652f, -0.5614535212516785f}, {2.4294583797454834f, 2.135286331176758f, 3.5555777549743652f},
      {43u,1,1, 0u,0,0, 0u,0,0} },
    { "random 33", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.6035795211791992f, 0.6930071711540222f, 0.39424967765808105f}, {-0.08041451871395111f, 0.40282952785491943f, -0.9117356538772583f, 0.0633745864033699f, 0.9149134755134583f, 0.39864397048950195f, 0.9947447776794434f, -0.025724105536937714f, -0.0991014763712883f, 3.0f, 0.25f, -7.5f}, {-2.009164333343506f, -1.7831071615219116f, -2.0925700664520264f}, {2.4498660564422607f, 0.263377845287323f, 1.1779985427856445f},
      {177u,1,1, 0u,0,0, 0u,0,0} },
    { "random 34", {0u,0,0, 0u,0,0, 0u,0,0}, 1,0,1, {-0.7608262300491333f, -0.13697700202465057f, 0.634334921836853f}, {-0.6813123226165771f, 0.3465558886528015f, -0.6447577476501465f, 0.518438994884491f, 0.8502792716026306f, -0.09080866724252701f, 0.5167538523674011f, -0.396136611700058f, -0.7589738368988037f, 3.0f, 0.25f, -7.5f}, {-1.0901011228561401f, -0.6665481328964233f, -0.9259591102600098f}, {3.375218152999878f, 0.5931541919708252f, 0.8561848402023315f},
      {177u,1,1, 0u,0,0, 0u,0,0} },
    { "random 35", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.7988171577453613f, 0.6015731692314148f, 0.0009498841827735305f}, {-0.9395663738250732f, 0.04245917499065399f, -0.3397238552570343f, -0.08611522614955902f, 0.9310694336891174f, 0.35453328490257263f, 0.3313596844673157f, 0.36236292123794556f, -0.8711451292037964f, 3.0f, 0.25f, -7.5f}, {-1.7533267736434937f, -1.9563204050064087f, -1.4734641313552856f}, {1.1111676692962646f, -0.24522382020950317f, 3.347569465637207f},
      {109u,1,1, 0u,0,0, 0u,0,0} },
    { "random 36", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.6114702820777893f, 0.7145056128501892f, 0.3399791419506073f}, {0.8008877038955688f, 0.3602726459503174f, -0.4783121347427368f, -0.0066382321529090405f, 0.8040575385093689f, 0.5945144295692444f, 0.5987777709960938f, -0.4729641377925873f, 0.6463513970375061f, 3.0f, 0.25f, -7.5f}, {-0.8852728605270386f, -1.604089379310608f, -1.7102375030517578f}, {4.03032112121582f, 0.7837471961975098f, 0.46752238273620605f},
      {173u,1,1, 0u,0,0, 0u,0,0} },
    { "random 37", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.15437735617160797f, -0.6930363178253174f, -0.7041791677474976f}, {0.9478543996810913f, 0.1717970073223114f, -0.26843589544296265f, -0.04054458439350128f, 0.9004309773445129f, 0.4331052303314209f, 0.3161141872406006f, -0.3996370732784271f, 0.8604429364204407f, 3.0f, 0.25f, -7.5f}, {-1.9754093885421753f, -0.8561084270477295f, -1.5362273454666138f}, {1.433486819267273f, 2.0013113021850586f, 3.079535961151123f},
      {169u,1,1, 0u,0,0, 0u,0,0} },
    { "random 38", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {-0.9509438276290894f, -0.2887587249279022f, -0.1110147014260292f}, {-0.5274268388748169f, -0.17936213314533234f, 0.8304517865180969f, 0.09815949201583862f, 0.9580512046813965f, 0.2692631483078003f, -0.8439109325408936f, 0.22353333234786987f, -0.4876958131790161f, 3.0f, 0.25f, -7.5f}, {-1.9294911623001099f, -2.201472282409668f, -1.2954689264297485f}, {0.8343589901924133f, 2.3258817195892334f, 1.4111789464950562f},
      {107u,1,0, 0u,0,0, 0u,0,0} },
    { "random 39", {0u,0,0, 0u,0,0, 0u,0,0}, 1,1,0, {0.5173949003219604f, 0.5964308381080627f, -0.6136552691459656f}, {-0.2844782769680023f, -0.3413609266281128f, -0.8958486914634705f, -0.06653017550706863f, 0.9392348527908325f, -0.3367663621902466f, 0.9563711881637573f, -0.03620174527168274f, -0.2899027168750763f, 3.0f, 0.25f, -7.5f}, {-0.7745893001556396f, -1.9407038688659668f, -2.1613974571228027f}, {2.421924114227295f, 1.7699462175369263f, 1.0517895221710205f},
      {105u,1,1, 0u,0,0, 0u,0,0} },
};

static void Set(CrashAnalysis& lrAnalysis, const Record& lrRecord)
{
    lrAnalysis.mxEventFlags                = lrRecord.muFlags;
    lrAnalysis.mbIsPlayerCrashing          = lrRecord.miCrashing != 0;
    lrAnalysis.mbSuggestLeftOfLineOfAction = lrRecord.miLeft != 0;
}

static bool Same(const CrashAnalysis& lrAnalysis, const Record& lrRecord)
{
    return lrAnalysis.mxEventFlags == lrRecord.muFlags
        && lrAnalysis.mbIsPlayerCrashing == (lrRecord.miCrashing != 0)
        && lrAnalysis.mbSuggestLeftOfLineOfAction == (lrRecord.miLeft != 0);
}

int main()
{
    alignas(16) static u8 saInputStorage[64] = {};
    const DirectorIO::InputBuffer* lpInput = reinterpret_cast<const DirectorIO::InputBuffer*>(saInputStorage);
    static GameState sGameState;
    const EActiveRaceCarIndex lePlayer = static_cast<EActiveRaceCarIndex>(2);

    char lacName[256];
    const int kiRows = static_cast<int>(sizeof(kaRows) / sizeof(kaRows[0]));
    for (int liRow = 0; liRow < kiRows; ++liRow)
    {
        const Row& lrRow = kaRows[liRow];
        std::memset(&gCrashInfo, 0, sizeof(gCrashInfo));
        gCrashInfo.mvCollisionNormal = Vector3{ lrRow.mafNormal[0], lrRow.mafNormal[1], lrRow.mafNormal[2], 0.0f };
        gCrashInfo.mbHardstopVsWall = lrRow.miWall != 0;
        gCrashInfo.mbHardStopVsAI   = lrRow.miAI != 0;
        Camera::VehicleInfo& lrCar = gaRaceCars[lePlayer];
        Matrix44Affine& lrM = lrCar.mRaceCarState.mTransform;
        lrM.xAxis = Vector3{ lrRow.mafTransform[0], lrRow.mafTransform[1], lrRow.mafTransform[2], 0.0f };
        lrM.yAxis = Vector3{ lrRow.mafTransform[3], lrRow.mafTransform[4], lrRow.mafTransform[5], 0.0f };
        lrM.zAxis = Vector3{ lrRow.mafTransform[6], lrRow.mafTransform[7], lrRow.mafTransform[8], 0.0f };
        lrM.wAxis = Vector3{ lrRow.mafTransform[9], lrRow.mafTransform[10], lrRow.mafTransform[11], 0.0f };
        lrCar.mAABB.mMin = Vector3{ lrRow.mafMin[0], lrRow.mafMin[1], lrRow.mafMin[2], 0.0f };
        lrCar.mAABB.mMax = Vector3{ lrRow.mafMax[0], lrRow.mafMax[1], lrRow.mafMax[2], 0.0f };
        sGameState.mbCrashActive = lrRow.miCrashActive != 0;

        CrashAnalyser lAnalyser;
        Set(lAnalyser.mAnalysis, lrRow.maBefore[0]);
        Set(lAnalyser.mLastAnalysis, lrRow.maBefore[1]);
        Set(lAnalyser.mAnalysisAtLastShotChange, lrRow.maBefore[2]);

        lAnalyser.Update(lpInput, &sGameState, lePlayer);

        std::snprintf(lacName, sizeof(lacName), "Update [%s]: mAnalysis == console (got 0x%X/%d/%d)", lrRow.mpcName,
                      lAnalyser.mAnalysis.mxEventFlags, lAnalyser.mAnalysis.mbIsPlayerCrashing ? 1 : 0,
                      lAnalyser.mAnalysis.mbSuggestLeftOfLineOfAction ? 1 : 0);
        Check(Same(lAnalyser.mAnalysis, lrRow.maAfter[0]), lacName);
        std::snprintf(lacName, sizeof(lacName), "Update [%s]: mLastAnalysis == console", lrRow.mpcName);
        Check(Same(lAnalyser.mLastAnalysis, lrRow.maAfter[1]), lacName);
        std::snprintf(lacName, sizeof(lacName), "Update [%s]: mAnalysisAtLastShotChange untouched", lrRow.mpcName);
        Check(Same(lAnalyser.mAnalysisAtLastShotChange, lrRow.maAfter[2]), lacName);
    }

    // The accessor pair is reached once each per call (GetPlayerCrashInfo, GetRaceCarInfo).
    Check(giAccessorCalls == 2 * kiRows, "Update: GetPlayerCrashInfo + GetRaceCarInfo once each per call");

    // The inline surface (DWARF :46 / :82 / :85 / :88).
    {
        CrashAnalyser lAnalyser;
        Set(lAnalyser.mAnalysis, Record{ 0xA9u, 1, 0 });
        Set(lAnalyser.mLastAnalysis, Record{ 0x2Bu, 1, 1 });
        Set(lAnalyser.mAnalysisAtLastShotChange, Record{ 0u, 0, 0 });
        lAnalyser.SetShotChanged();
        Check(Same(lAnalyser.mAnalysisAtLastShotChange, Record{ 0x2Bu, 1, 1 }),
              "SetShotChanged: mAnalysisAtLastShotChange = mLastAnalysis (PS3 @0x15048; X360 inline 0x82274F90)");
        Check(&lAnalyser.GetAnalysis() == &lAnalyser.mAnalysis, "GetAnalysis: mAnalysis");
        Check(&lAnalyser.GetAnalysisAtLastShotChange() == &lAnalyser.mAnalysisAtLastShotChange,
              "GetAnalysisAtLastShotChange: mAnalysisAtLastShotChange");
        CrashAnalysis lCleared;
        Set(lCleared, Record{ 0xFFu, 1, 0 });
        lCleared.Clear();
        Check(Same(lCleared, Record{ 0u, 0, 1 }),
              "CrashAnalysis::Clear: flags 0, crashing false, suggest-left TRUE (0x82209570..78)");
        Check(sizeof(CrashAnalysis) == 8 && sizeof(CrashAnalyser) == 0x18,
              "layout: CrashAnalysis 8 bytes, CrashAnalyser 0x18 (the console's word copies)");
    }

    // ShotSelector::Prepare / Update / SetLastUsedToNow (PS3 @0x15000 / @0x2E4AC / @0x2E33C; inlined on the
    // X360 at MainDirector::Prepare 0x8224FBE4 and MainDirector::Update 0x82274FB0..0x82274FE4).
    {
        static ShotSelector sSelector;
        for (u32 luList = 0; luList < ShotSelector::KU_NUM_SHOT_LISTS; ++luList)
        {
            sSelector.maaShotTimes[luList].SetFullCount();
            for (u32 luSlot = 0; luSlot < ShotSelector::KU_SHOT_LIST_SIZE; ++luSlot)
                sSelector.maaShotTimes[luList].GetItem(luSlot) = 0;
        }
        sSelector.miCurrentTimeID = 77;
        const bool lbPrepared = sSelector.Prepare();
        Check(lbPrepared, "ShotSelector::Prepare: returns true");
        Check(sSelector.miCurrentTimeID == 0, "ShotSelector::Prepare: miCurrentTimeID = 0 (stw 0 -> +0x264)");

        static Camera::Camera sCamera;
        sCamera.mShotSelectionInfo.miType = -1;
        sCamera.mShotSelectionInfo.miId   = -1;
        sSelector.Update(sCamera);
        Check(sSelector.miCurrentTimeID == 1, "ShotSelector::Update: the clock ticks every frame");
        bool lbAnyStamp = false;
        for (u32 luList = 0; luList < ShotSelector::KU_NUM_SHOT_LISTS; ++luList)
            for (u32 luSlot = 0; luSlot < ShotSelector::KU_SHOT_LIST_SIZE; ++luSlot)
                lbAnyStamp = lbAnyStamp || sSelector.maaShotTimes[luList].GetItem(luSlot) != 0;
        Check(!lbAnyStamp, "ShotSelector::Update: a camera with no shot (miType == -1) stamps nothing");

        sCamera.mShotSelectionInfo.miType = 1;
        sCamera.mShotSelectionInfo.miId   = 7;
        sSelector.Update(sCamera);
        Check(sSelector.miCurrentTimeID == 2, "ShotSelector::Update: ticks again");
        Check(sSelector.maaShotTimes[1].GetItem(7) == 2, "ShotSelector::Update: stamps maaShotTimes[type][id] = now");
        Check(sSelector.maaShotTimes[0].GetItem(7) == 0 && sSelector.maaShotTimes[1].GetItem(6) == 0
              && sSelector.maaShotTimes[2].GetItem(7) == 0,
              "ShotSelector::Update: only that one slot");
    }

    // VehicleTracker::Update's crash-energy band @0x8223B3B8..0x8223B414 (the production
    // BrnDirectorVehicleTracker.cpp). Expected values are the asm's branches, stated per row:
    //   force && mbHardstopVsWall                -> HIGH (3)     0x8223B3C8 -> 0x8223B410
    //   speed <  max - 50 (flt_82CDA548)        -> LOW (1)      fcmpu / bge  @0x8223B3F4
    //   speed <  max - 20 (flt_82CDA54C)        -> NORMAL (2)   fcmpu / blt  @0x8223B404
    //   otherwise (incl. a NaN speed)            -> HIGH (3)
    {
        struct TrackerRow { const char* mpcName; f32 mfSpeed; f32 mfMax; int miForce; int miWall; int miExpected; };
        const TrackerRow kaTrackerRows[] =
        {
            { "60 mph in a 120 mph car: LOW",                  60.0f, 120.0f, 0, 0, 1 },
            { "69.99 mph (just under max - 50): LOW",          69.99f, 120.0f, 0, 0, 1 },
            { "70 mph (== max - 50, not <): NORMAL",           70.0f, 120.0f, 0, 0, 2 },
            { "80 mph: NORMAL",                                80.0f, 120.0f, 0, 0, 2 },
            { "100 mph (== max - 20, not <): HIGH",           100.0f, 120.0f, 0, 0, 3 },
            { "130 mph: HIGH",                                130.0f, 120.0f, 0, 0, 3 },
            { "NaN speed: HIGH (both compares fail)",          KF_NAN, 120.0f, 0, 0, 3 },
            { "force + wall hard stop at 10 mph: HIGH",        10.0f, 120.0f, 1, 1, 3 },
            { "force without a wall hard stop: the band",      10.0f, 120.0f, 1, 0, 1 },
            { "wall hard stop without force: the band",        80.0f, 120.0f, 0, 1, 2 },
        };
        GameState lGameState;
        lGameState.mEventState.SetAll(GameState::E_EVENT_STATE_PRE_INTRO);   // not racing: the ramp holds 0
        gUsedRaceCars.UnSetAll();
        gUsedRaceCars.SetBit(2u);
        char lacTracker[256];
        for (const TrackerRow& lrRow : kaTrackerRows)
        {
            std::memset(&gCrashInfo, 0, sizeof(gCrashInfo));
            gCrashInfo.mfSpeedMPH       = lrRow.mfSpeed;
            gCrashInfo.mbHardstopVsWall = lrRow.miWall != 0;
            Camera::VehicleInfo& lrCar = gaRaceCars[2];
            lrCar.mRaceCarState.mfMaxSpeedMPH = lrRow.mfMax;

            static VehicleTracker sTracker;
            sTracker.Construct();
            sTracker.SetVehicleIndex(2);

            lrCar.mRaceCarState.mbCrashing = false;
            sTracker.Update(&lGameState, lpInput, lePlayer, lrRow.miForce != 0);
            lrCar.mRaceCarState.mbCrashing = true;
            sTracker.Update(&lGameState, lpInput, lePlayer, lrRow.miForce != 0);
            std::snprintf(lacTracker, sizeof(lacTracker), "VehicleTracker band [%s] (got %d)", lrRow.mpcName,
                          static_cast<int>(sTracker.GetCrashType()));
            Check(static_cast<int>(sTracker.GetCrashType()) == lrRow.miExpected, lacTracker);
            std::snprintf(lacTracker, sizeof(lacTracker), "VehicleTracker [%s]: first frame of crash", lrRow.mpcName);
            Check(sTracker.IsFirstFrameOfCrash(), lacTracker);

            // The band is taken once, on the crash's first frame: a later frame keeps it.
            gCrashInfo.mfSpeedMPH = 1.0f;
            sTracker.Update(&lGameState, lpInput, lePlayer, false);
            std::snprintf(lacTracker, sizeof(lacTracker), "VehicleTracker [%s]: held while crashing", lrRow.mpcName);
            Check(static_cast<int>(sTracker.GetCrashType()) == lrRow.miExpected && !sTracker.IsFirstFrameOfCrash(),
                  lacTracker);
            lrCar.mRaceCarState.mbCrashing = false;
            sTracker.Update(&lGameState, lpInput, lePlayer, false);
            std::snprintf(lacTracker, sizeof(lacTracker), "VehicleTracker [%s]: back to NOT_CRASHING", lrRow.mpcName);
            Check(sTracker.GetCrashType() == VehicleTracker::E_CRASH_NOT_CRASHING, lacTracker);
        }
        Check(VehicleTracker::sfMinSpeedBelowMaxMPHForNormalCrash == 50.0f
              && VehicleTracker::sfMinSpeedBelowMaxMPHForHighSpeedCrash == 20.0f,
              "VehicleTracker bands: 50.0 @0x82CDA548 / 20.0 @0x82CDA54C (x360rd)");
    }

    // DebugLog::Construct / Clear (PS3 @0x22158 / @0x21F48; inlined by MainDirector::Construct
    // 0x8225B824..0x8225B87C) over the zero memory the director module starts from, then 25 appends
    // through the production ActualAppend (the pool holds 20; the oldest is recycled).
    {
        const int kiAssertsBefore = giAsserts;
        alignas(16) static u8 saLogStorage[sizeof(DebugLog)];
        std::memset(saLogStorage, 0, sizeof(saLogStorage));
        DebugLog& lrLog = *reinterpret_cast<DebugLog*>(saLogStorage);
        lrLog.Construct();
        Check(lrLog.mfStringDuration == 10.0f, "DebugLog::Construct: mfStringDuration = 10.0 (flt_82004A20)");
        Check(lrLog.mStringPool.miNumObjectsFree == 20 && lrLog.mStringIndices.GetLength() == 0,
              "DebugLog::Construct: the pool all free (20), the live order empty");
        Check(lrLog.mStringPool.maiObjectFreeQueue[0] == 19 && lrLog.mStringPool.maiObjectFreeQueue[19] == 0,
              "DebugLog::Clear: the free queue 19..0 (0x8225B858 loop)");
        char lacLine[32];
        for (int liLine = 0; liLine < 25; ++liLine)
        {
            std::snprintf(lacLine, sizeof(lacLine), "line %d", liLine);
            lrLog.Append(lacLine, CgsDev::RGBA());
        }
        Check(giAsserts == kiAssertsBefore, "DebugLog: 25 appends into the constructed log fire no assert");
        Check(lrLog.mStringIndices.GetLength() == 20
              && std::strcmp(lrLog.mStringPool[lrLog.mStringIndices[0]].macString, "line 5") == 0
              && std::strcmp(lrLog.mStringPool[lrLog.mStringIndices[19]].macString, "line 24") == 0,
              "DebugLog: a full log recycles its oldest line (lines 5..24 live, in order)");
        lrLog.Clear();
        Check(lrLog.mStringPool.miNumObjectsFree == 20 && lrLog.mStringIndices.GetLength() == 0,
              "DebugLog::Clear: back to all free / empty");
    }

    // MomentHardStop's "still upright" gate, KF_MAX_DOT_PRODUCT_FOR_HARD_STOP (PS3 name; X360 .bss
    // 0x82FAA848, written by the dyn-init thunk 0x82C484E0: (f32)cos(lfd 0x8200D520) -> 0x3F12D5E8).
    // The runner lifts the production definition out of BrnMomentHardStop.cpp into fxd2_hardstop.
    {
        u32 luBits = 0;
        std::memcpy(&luBits, &fxd2_hardstop::KF_MAX_DOT_PRODUCT_FOR_HARD_STOP, sizeof(luBits));
        char lacUpright[160];
        std::snprintf(lacUpright, sizeof(lacUpright),
                      "KF_MAX_DOT_PRODUCT_FOR_HARD_STOP == 0x3F12D5E8 (cos 55 deg; got 0x%08X)", luBits);
        Check(luBits == 0x3F12D5E8u, lacUpright);
        // The gate is `yAxis.y > KF` (vcmpgtfp. @0x82271938): a car tilted 54 deg passes, 56 deg does not.
        const f32 kfDegToRad = 0.017453292f;
        Check(static_cast<f32>(std::cos(54.0f * kfDegToRad)) > fxd2_hardstop::KF_MAX_DOT_PRODUCT_FOR_HARD_STOP,
              "upright gate: a 54-degree tilt is still a hard stop");
        Check(!(static_cast<f32>(std::cos(56.0f * kfDegToRad)) > fxd2_hardstop::KF_MAX_DOT_PRODUCT_FOR_HARD_STOP),
              "upright gate: a 56-degree tilt is not");
    }

    Check(giAsserts == 0, "no assert fired");

    std::printf("fxdirector2_crash_analyser: %d checks, %d failures\n", giChecks, giFailures);
    return giFailures == 0 ? 0 : 1;
}
