// FX-OCTREE (crash parity 2026-09-25): the loose octree's ADAPTIVE DEPTH, checked against the console's own words.
//
//   LooseOctree::Update @0x828D0180                          RemoveNodes -> AddNodes -> UpdateRecursive
//   LooseOctree::AdaptiveDepthUpdateRemoveNodesRecursive @0x828CA4F8 / AdaptiveDepthUpdateAddNodesRecursive @0x828CA360
//   LooseOctree::SplitAndPropogateRecursive @0x828BBBD0 / MergeSubTreeRecursive @0x828BC340
//   IndexedPool<LooseOctreeNodeAllocation, u16> Pop (sub_828B8DC0) / PushIndex (sub_828AE988)
//   LooseOctree::Construct @0x828C99D8 (the pool's two carves) and AllocRecursive @0x828BB4A0 (groups from the pool)
//
// run_fxoctree_adaptive.py compiles the WHOLE production CgsLooseOctree.cpp of the revision under test (its headers
// shadowed in) with CgsSpatialPartition.cpp, CgsLineTests.cpp and CgsStrStream.cpp beside this fixture. The
// rwcollision / monitor / assert seams are stubs here (the volume walk's state is not what this test reads).
//
// FxOctreeAdaptiveData.h is the EXPECTATION, generated by scratch/CRASHPARITY_0922/fxoctree_emu/gen_octree_data.py:
// the console's words of Construct / Prepare / AddEntityInternal / RemoveEntityInternal / SetEntityPosition /
// SetEntityRadius / Update (and everything they call) run on emu64 over ten scripted cases -- split at 33 and not at
// 32, the recursive split of a cluster, a spread split, the depth cap at 10, merge and refill, a radius mix, moves and
// radius changes, pool exhaustion, and a 1140-entity world. This fixture replays the same op list through the
// production bodies and compares, at every CHECK, the tree reachable from the root (depth first, children in order):
// node indices, parents, children, depths, chain order, counts, flags, type masks, the raw bits of the position /
// params vectors and of the half dimensions' x, y, z; the pool's used / free / capacity / static counts and its
// free-index list in order; every entity's owning node; the number of asserts.
#include "types.hpp"
#include "BrnCommonTypes.h"
#include "GameShared/GameClasses/SceneManager/SpatialPartitionModule/SpatialPartitions/CgsLooseOctree.h"
#ifdef GetFreeSpace
#undef GetFreeSpace
#endif
#include "GameShared/GameClasses/SceneManager/SpatialPartitionModule/CgsCoarseQueryResultBuffer.h"
#include "GameShared/GameClasses/SceneManager/SpatialPartitionModule/CgsSpatialPartitionManager.h"
#include "rw/rwcore_structs.h"
#include "vendor/renderware/collision/CollisionVolume.hpp"
#include "GameShared/GameClasses/Development/PerfMon/Cpu/CgsPerfMonCpu.h"
#include "GameShared/GameClasses/Development/Log/CgsLog.h"

#include "FxOctreeAdaptiveData.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <malloc.h>
#include <new>
#include <string>
#include <vector>

namespace CgsDev { namespace Log { DebugPrint* gpDebugPrint = nullptr; } }

// ---- the assert seam: count and record every message -----------------------------------------------------------
static std::vector<std::string> gaAsserts;
namespace CgsDev { namespace Assert {
int BeginAssert() { return 0; }
int FireAssert(const char* lpcMessage, const char*, int) { gaAsserts.push_back(lpcMessage ? lpcMessage : ""); return 0; }
void* EndAssert() { return nullptr; }
} }

namespace CgsDev { namespace PerfMonCpu {
void StartMonitor(s32) {}
void StopMonitor(s32) {}
} }

// ---- the resource allocator Construct carves from: zeroed, aligned blocks, every request recorded ----------------
namespace EA { namespace Allocator { ICoreAllocator::~ICoreAllocator() {} } }
namespace rw
{
    void* IResourceAllocator::Alloc(size_t, const char*, uint32_t, uint32_t, uint32_t) { return nullptr; }
    void* IResourceAllocator::Alloc(size_t, const char*, uint32_t) { return nullptr; }
    void IResourceAllocator::Free(void*, size_t) {}
    ::rw::Resource IResourceAllocator::DoAllocate(const ::rw::ResourceDescriptor&, const char*) { return ::rw::Resource(); }
    void IResourceAllocator::DoFreeDisposable(::rw::Resource&) {}
}
struct TestAllocator : rw::IResourceAllocator
{
    struct Request { u32 muSize; u32 muAlignment; };
    std::vector<void*>   maBlocks;
    std::vector<Request> maRequests;
    ::rw::Resource DoAllocate(const ::rw::ResourceDescriptor& lrDescriptor, const char*) override
    {
        const u32 luSize  = lrDescriptor.m_baseResourceDescriptors[0].m_size;
        const u32 luAlign = lrDescriptor.m_baseResourceDescriptors[0].m_alignment;
        maRequests.push_back(Request{ luSize, luAlign });
        void* lpBlock = _aligned_malloc(luSize ? luSize : 16u, luAlign < 16u ? 16u : luAlign);
        std::memset(lpBlock, 0, luSize ? luSize : 16u);
        maBlocks.push_back(lpBlock);
        ::rw::Resource lResource;
        lResource.m_baseResources[0] = lpBlock;
        return lResource;
    }
    ~TestAllocator() { for (void* lpBlock : maBlocks) { _aligned_free(lpBlock); } }
};

// ---- the rwcollision seams Construct builds the volume walk with (never read by the tree) ------------------------
namespace rw { namespace collision {
void* VolumeVolumeQuery::GetResourceDescriptor(void* lpOut, int, int)
{
    u32* lpu = static_cast<u32*>(lpOut);
    for (int i = 0; i < 10; ++i) lpu[i] = 0;
    lpu[0] = KU_VOLUME_VOLUME_QUERY_HOST_SIZE_R100;
    lpu[1] = 16;
    return lpOut;
}
void* VolumeVolumeQuery::Initialize(void** lppBuffer, int, int) { return lppBuffer[0]; }
BoxVolume* BoxVolume::Initialize(const ::rw::Resource& arResource, const Vec4&)
{
    return static_cast<BoxVolume*>(arResource.m_baseResources[0]);
}
SphereVolume* SphereVolume::Initialize(const ::rw::Resource& arResource, f32)
{
    return static_cast<SphereVolume*>(arResource.m_baseResources[0]);
}
int VolumeVolumeQuery::GetPrimitiveIntersections() { return 0; }
} }

using namespace CgsSceneManager;

// ---- the revision's pool accessors (the runner writes the real ones, or a revision-without-a-pool fallback) -------
#include "fxoct_pool.inc"

static int giChecks = 0, giFailures = 0;
static void Check(bool lbPassed, const std::string& lrName)
{
    ++giChecks;
    if (!lbPassed) { ++giFailures; std::printf("FAIL  %s\n", lrName.c_str()); }
    else           { std::printf("ok    %s\n", lrName.c_str()); }
}

static u32 Bits(f32 lf) { u32 lu; std::memcpy(&lu, &lf, 4); return lu; }
static f32 Float(u32 lu) { f32 lf; std::memcpy(&lf, &lu, 4); return lf; }
static Vector3 V3(f32 x, f32 y, f32 z) { Vector3 v; v.x = x; v.y = y; v.z = z; v.w = 0.0f; return v; }

struct Walked
{
    LooseOctreeNode* mpNode;
    u32              muIndex;
    u32              muDepth;
};

static void Walk(LooseOctree* lpTree, u32 luIndex, u32 luDepth, std::vector<Walked>& lraOut)
{
    if (lraOut.size() > 20000) { return; }   // a broken tree must not recurse for ever
    LooseOctreeNode* lpNode = &lpTree->mpNodes[luIndex];
    lraOut.push_back(Walked{ lpNode, luIndex, luDepth });
    if (lpNode->muFirstChildIndex != KU_INVALID_NODE)
    {
        for (u32 luChild = 0; luChild < KU_NUM_SUBNODES; ++luChild)
        {
            Walk(lpTree, lpNode->muFirstChildIndex + luChild, luDepth + 1, lraOut);
        }
    }
}

static std::vector<u16> Chain(LooseOctree* lpTree, const LooseOctreeNode* lpNode)
{
    std::vector<u16> laChain;
    u16 lu16Link = lpNode->muHeadIndex;
    for (u32 luStep = 0; luStep < lpNode->muNumElements && luStep < 20000u; ++luStep)
    {
        laChain.push_back(lu16Link);
        lu16Link = lpTree->maEntityLinks[lu16Link].mu16NextEntity;
    }
    return laChain;
}

template <typename TVector>
static bool SameBits4(const TVector& lrValue, const unsigned int* lpuExpected, u32 luLanes)
{
    const f32* lpf = &lrValue.x;
    for (u32 luLane = 0; luLane < luLanes; ++luLane)
    {
        if (Bits(lpf[luLane]) != lpuExpected[luLane]) { return false; }
    }
    return true;
}

static void CompareCheck(LooseOctree* lpTree, const FxOctreeData::Case& lrCase, u32 luCheck)
{
    const FxOctreeData::Check& lrCheck = FxOctreeData::kaChecks[lrCase.muCheckStart + luCheck];
    const std::string lTag = std::string(lrCase.mpcName) + " check " + std::to_string(luCheck) + ": ";

    std::vector<Walked> laWalk;
    Walk(lpTree, 0, 0, laWalk);

    // 1. the shape: the same nodes, in the same depth-first order, with the same topology
    bool lbShape = laWalk.size() == lrCheck.muNodeCount;
    std::string lFirstShapeMiss;
    for (u32 k = 0; lbShape && k < lrCheck.muNodeCount; ++k)
    {
        const FxOctreeData::NodeRecord& lrWant = FxOctreeData::kaNodes[lrCheck.muNodeStart + k];
        const Walked& lrHave = laWalk[k];
        if (lrHave.muIndex != lrWant.muIndex || lrHave.mpNode->muParentIndex != lrWant.muParent ||
            lrHave.mpNode->muFirstChildIndex != lrWant.muFirstChild || lrHave.muDepth != lrWant.muDepth)
        {
            lbShape = false;
            char lac[160];
            std::snprintf(lac, sizeof(lac), " (walk %u: node %u parent %u child %u depth %u, console %u / %u / %u / %u)",
                          k, lrHave.muIndex, lrHave.mpNode->muParentIndex, lrHave.mpNode->muFirstChildIndex,
                          lrHave.muDepth, lrWant.muIndex, lrWant.muParent, lrWant.muFirstChild, lrWant.muDepth);
            lFirstShapeMiss = lac;
        }
    }
    if (laWalk.size() != lrCheck.muNodeCount)
    {
        lFirstShapeMiss = " (" + std::to_string(laWalk.size()) + " nodes reachable, console " +
                          std::to_string(lrCheck.muNodeCount) + ")";
    }
    Check(lbShape, lTag + "tree shape -- node indices, parents, first children, depths" + lFirstShapeMiss);

    // 2..4 per node (only meaningful on the same shape)
    bool lbChains = lbShape, lbCounts = lbShape, lbFloats = lbShape;
    for (u32 k = 0; lbShape && k < lrCheck.muNodeCount; ++k)
    {
        const FxOctreeData::NodeRecord& lrWant = FxOctreeData::kaNodes[lrCheck.muNodeStart + k];
        LooseOctreeNode* lpNode = laWalk[k].mpNode;
        const std::vector<u16> laChain = Chain(lpTree, lpNode);
        if (laChain.size() != lrWant.muCount) { lbChains = false; }
        for (u32 c = 0; c < laChain.size() && c < lrWant.muCount; ++c)
        {
            if (laChain[c] != FxOctreeData::kau16Chains[lrWant.muChainStart + c]) { lbChains = false; }
        }
        if (lpNode->muNumElements != lrWant.muCount || lpNode->muHeadIndex != lrWant.muHead ||
            lpNode->muTailIndex != lrWant.muTail || lpNode->muFlags != lrWant.muFlags ||
            lpNode->mxNodeEntityFlags != lrWant.mx32OwnTypes || lpNode->muSubTreeEntityCount != lrWant.muSubTree ||
            lpTree->mpNodesEntityInfo[laWalk[k].muIndex].mxSubTreeEntityFlags != lrWant.mx32SubTreeTypes)
        {
            lbCounts = false;
        }
        // The half dimensions' w lane: the console's vperm (unk_82CDA350) leaves HalfSize there (UpdateRecursive
        // 0x828B16FC, PrepareRecursive 0x828BB408); the PC writes 0 and nothing reads it. x, y, z here.
        if (!SameBits4(lpNode->mPosition, lrWant.mauPosition, 4) || !SameBits4(lpNode->mHalfDimensions, lrWant.mauHalf, 3) ||
            !SameBits4(lpNode->mParams0, lrWant.mauParams0, 4) || !SameBits4(lpNode->mParams1, lrWant.mauParams1, 4))
        {
            lbFloats = false;
        }
    }
    Check(lbChains, lTag + "every node's own chain, entity by entity, in link order");
    Check(lbCounts, lTag + "chain counts, head / tail, flags, own and sub-tree type masks, sub-tree counts");
    Check(lbFloats, lTag + "centres, half dimensions (x y z), params0 / params1 -- the same bits");

    // 5. the pool
    bool lbPool = PoolPresent() && PoolUsed(lpTree) == lrCheck.muPoolUsed && PoolFree(lpTree) == lrCheck.muPoolFree &&
                  PoolCapacity(lpTree) == lrCheck.muPoolCapacity && lpTree->miNumStaticNodes == lrCheck.miPoolStatic;
    for (u32 f = 0; lbPool && f < lrCheck.muPoolFree; ++f)
    {
        if (PoolFreeIndex(lpTree, f) != FxOctreeData::kau16Free[lrCheck.muFreeStart + f]) { lbPool = false; }
    }
    char lacPool[200];
    std::snprintf(lacPool, sizeof(lacPool), " (used %u free %u capacity %u static %d; console %u / %u / %u / %d)",
                  PoolPresent() ? PoolUsed(lpTree) : 0xFFFFu, PoolPresent() ? PoolFree(lpTree) : 0xFFFFu,
                  PoolPresent() ? PoolCapacity(lpTree) : 0xFFFFu, lpTree->miNumStaticNodes, lrCheck.muPoolUsed,
                  lrCheck.muPoolFree, lrCheck.muPoolCapacity, lrCheck.miPoolStatic);
    Check(lbPool, lTag + "the node-group pool: used / free / capacity / static and the free list in order" + lacPool);

    // 6. every entity's owning node
    bool lbOwners = true;
    for (u32 e = 0; e < lrCase.muEntities; ++e)
    {
        if (lpTree->maEntityNodeIndex[e] != FxOctreeData::kau16Owners[lrCheck.muOwnerStart + e]) { lbOwners = false; }
    }
    Check(lbOwners, lTag + "every entity's owning node");

    // 7. asserts
    Check(gaAsserts.size() == lrCheck.muAsserts,
          lTag + "asserts fired: " + std::to_string(gaAsserts.size()) + " (console " + std::to_string(lrCheck.muAsserts) + ")");
}

static void RunCase(const FxOctreeData::Case& lrCase)
{
    gaAsserts.clear();
    TestAllocator lAllocator;
    void* lpStorage = _aligned_malloc(sizeof(LooseOctree), 128);
    std::memset(lpStorage, 0, sizeof(LooseOctree));
    LooseOctree* lpTree = ::new (lpStorage) LooseOctree();

    // WorldModule::Prepare @0x827D53B0's literal block: type 1, depth 3, centre 0, 11000 (flt_820CD52C),
    // 0.30000001 (flt_82004740), split threshold 32, adaptive max depth 10.
    SpatialPartitionConstructParams lParams;
    std::memset(&lParams, 0, sizeof(lParams));
    lParams.meType                       = static_cast<ESpatialPartitionType>(1);
    lParams.muDepth                      = 3;
    lParams.mCentrePos                   = V3(0.0f, 0.0f, 0.0f);
    lParams.mfBaseSize                   = 11000.0f;
    lParams.mfLooseness                  = 0.30000001f;
    lParams.muAdaptiveNodeSplitThreshold = 32;
    lParams.muAdaptiveMaxDepth           = 10;
    lpTree->Construct(&lParams, &lAllocator);
    lpTree->Prepare();

    // Construct's carves (the console's 0x828C9B08 / 0x828C9B74 / 0x828C9BD8 / 0x828C9C2C, recorded on emu64):
    // 788448 / 16, 32852 / 128, 4106 / 16, 4106 / 16 -- the host sizes are the console's.
    if (lrCase.muCheckStart == 0)
    {
        bool lbCarves = lAllocator.maRequests.size() == 4 &&
                        lAllocator.maRequests[0].muSize == 788448u && lAllocator.maRequests[0].muAlignment == 16u &&
                        lAllocator.maRequests[1].muSize == 32852u  && lAllocator.maRequests[1].muAlignment == 128u &&
                        lAllocator.maRequests[2].muSize == 4106u   && lAllocator.maRequests[2].muAlignment == 16u &&
                        lAllocator.maRequests[3].muSize == 4106u   && lAllocator.maRequests[3].muAlignment == 16u;
        Check(lbCarves, "Construct carves nodes 788448/16, sub-tree masks 32852/128, pool entries 4106/16, free "
                        "indices 4106/16 from the scene allocator, in that order (" +
                        std::to_string(lAllocator.maRequests.size()) + " carves)");

        // BUDGET (host layout): the octree's whole carve from the scene allocator -- RW-linear bank 49 "Scene
        // Manager", 0x17A800 on the console (BrnMemoryMapData.h, from the ARTIST memory map unk_82F2A788) and twice
        // that on the host (KU_HOST_RWLINEAR_HEADROOM, BrnGameDataModule.cpp): the object itself (operator new,
        // 16-aligned) plus Construct's carves, each rounded up to its alignment.
        const unsigned long long luBank = 0x17A800ull * 2ull;
        unsigned long long luCarve = (sizeof(LooseOctree) + 15ull) & ~15ull;
        for (const TestAllocator::Request& lrRequest : lAllocator.maRequests)
        {
            const unsigned long long luAlign = lrRequest.muAlignment ? lrRequest.muAlignment : 1ull;
            luCarve = ((luCarve + luAlign - 1ull) / luAlign) * luAlign + lrRequest.muSize;
        }
        Check(luCarve <= luBank, "BUDGET: the host octree carve " + std::to_string(luCarve) + " bytes (object " +
                                 std::to_string(sizeof(LooseOctree)) + ") fits bank 49's host " +
                                 std::to_string(luBank) + " (margin " + std::to_string(luBank - luCarve) + ")");
    }

    u32 luCheck = 0;
    for (u32 o = 0; o < lrCase.muOpCount; ++o)
    {
        const FxOctreeData::Op& lrOp = FxOctreeData::kaOps[lrCase.muOpStart + o];
        const u16 lu16Entity = static_cast<u16>(lrOp.muEntity);
        switch (lrOp.muOp)
        {
            case FxOctreeData::OP_ADD:
                lpTree->AddEntity(lu16Entity, lrOp.mx32Type,
                                  V3(Float(lrOp.mauBits[0]), Float(lrOp.mauBits[1]), Float(lrOp.mauBits[2])),
                                  Float(lrOp.mauBits[3]));
                break;
            case FxOctreeData::OP_REMOVE:
                lpTree->RemoveEntityFromGraph(lu16Entity);
                break;
            case FxOctreeData::OP_SETPOS:
                lpTree->SetEntityPosition(lu16Entity,
                                          V3(Float(lrOp.mauBits[0]), Float(lrOp.mauBits[1]), Float(lrOp.mauBits[2])));
                break;
            case FxOctreeData::OP_SETRAD:
                lpTree->SetEntityRadius(lu16Entity, Float(lrOp.mauBits[0]));
                break;
            case FxOctreeData::OP_UPDATE:
                lpTree->Update();
                break;
            case FxOctreeData::OP_DRAIN:
                for (u32 k = 0; k < lrOp.muEntity; ++k) { PoolDrainOne(lpTree); }
                break;
            case FxOctreeData::OP_CHECK:
                CompareCheck(lpTree, lrCase, luCheck++);
                break;
        }
    }

    lpTree->~LooseOctree();
    _aligned_free(lpStorage);
}

int main()
{
    for (u32 c = 0; c < FxOctreeData::KU_NUM_CASES; ++c)
    {
        RunCase(FxOctreeData::kaCases[c]);
    }
    std::printf("FxOctreeAdaptive: %d checks, %d failures\n", giChecks, giFailures);
    return giFailures ? 1 : 0;
}
