// FX-POPUP (crash parity 2026-09-25): the immediate-mode 2D colour transform against the console.
//
// The junkyard car-select "DwnldTitleUp" popup is a FLAPT movie (FLAPTHUD clip 432
// singleOverlay_mc); FLAPT reaches D3D9 through CgsGraphics::Im2dBase<V> (CgsIm2d.cpp). The
// console shades every Im2d batch with program 0 (Criterion's tools/nushaders/Source/Executable
// 0.fx + 1.fx; Im2d::Construct @0x827FBDB8 binds its constants gOffsetXYZ / gRightUp /
// gColourShift / gColourScale by name):
//     oColour = tex2D(DiffuseSampler, uv) * (iColour * gColourScale) + gColourShift
// The PC folded the shift into the vertex colour as well -- texel * (vertex * scale + shift) --
// which is wrong wherever a flat colour (scale 0 + shift, MovieClipRef::SetColour @0x8241E0D0)
// sits on a dark atlas texel.
//
// This driver links the REAL CgsIm2d.cpp (the runner compiles the production file, or an older
// snapshot passed on its command line), drives Im2dBase::BatchTransformTextureBlendRenderStatic
// and RenderEnd with the popup's own FLAPTHUD cxf records, records the fixed-function state
// each draw is shaded with, evaluates the texture-stage cascade for real atlas texels and
// compares the pixel with the console formula. It also checks that texture stage 1 is left
// DISABLED after every batch (the next batch must find the cascade the way it expects).
//
// Records (FLAPTHUD cxf, scale RGBA / shift RGBA; console bundle == PC bundle per dump_flapt.py):
//   clip 432 obj 6  (-1 = white tex)  1,1,1,0.421875 / 0,0,0,0              the popup's white wash
//   clip 432 obj 7  (atlas 7)         0,0,0,1        / 0.2,0.2,0.2,0          BlackDirt
//   clip 432 obj 11 (atlas 7)         0,0,0,1        / 0.215686,0.078431,0.078431,0  RedDirt
//   clip 432 obj 12 (atlas 17)        0,0,0,1        / 0.4,0.015686,0.015686,0       banner stripe
//   clip 432 obj 10 (atlas 7)         1,1,1,0.5      / 0,0,0,0                MenuGrad (no shift)
//   clip 433 obj 4  (atlas 6)         0.5,0.5,0.5,1  / 0.501961 x3,0          logo flash (tinted)
// Texels (decoded from the shipped atlases): atlas 17 stripe median (148,8,8,251); atlas 7 dark
// dirt (0,0,0,248); atlas 7 red texels (59,16,16,240).
#include <Windows.h>
#include <d3d9.h>

#include "mock_d3d9_device.h"   // generated by run_fxpopup_im2d_colour_shift.py from the SDK d3d9.h

#include "GameShared/GameClasses/Graphics/ImmediateMode/CgsIm2d.h"
#include "pc/gcm/renderengine/device.h"
#include "pc/gcm/renderengine/texture.h"

#include <cmath>
#include <cstdio>
#include <cstring>

// ---- the externals the TU under test reads (device.cpp / the log / the assert TU in the exe) ----
namespace renderengine
{
    IDirect3DDevice9* gDevice = nullptr;
    s32 gDisplayWidth  = 1280;
    s32 gDisplayHeight = 720;
    u32 guPresentCount = 1;
}
namespace CgsDev
{
    namespace Log { void WriteToLog(const char*) {} }
    namespace Assert
    {
        static unsigned gsuAssertions = 0;
        int   BeginAssert() { return 0; }
        int   FireAssert(const char*, const char*, int) { ++gsuAssertions; return 0; }
        void* EndAssert() { return nullptr; }
    }
}

namespace
{
    // The fixed-function state a draw was shaded with.
    struct DrawRecord
    {
        DWORD mauColorOp[3], mauColorArg1[3], mauColorArg2[3];
        DWORD mauAlphaOp[3], mauAlphaArg1[3], mauAlphaArg2[3];
        DWORD muTextureFactor;
        bool  mbStage0Textured;
        DWORD muVertexColour;   // vertex 0's D3DCOLOR (every test run is one colour)
        UINT  muPrimitives;
    };

    struct RecordingDevice : public MockDevice9Base
    {
        DWORD maauStage[8][33];
        DWORD mauRender[256];
        IDirect3DBaseTexture9* mapTexture[8];
        DrawRecord maDraws[16];
        int miDraws;

        RecordingDevice()
        {
            std::memset(maauStage, 0, sizeof(maauStage));
            std::memset(mauRender, 0, sizeof(mauRender));
            std::memset(mapTexture, 0, sizeof(mapTexture));
            miDraws = 0;
            // D3D9's documented initial texture-stage states.
            for (int liStage = 0; liStage < 8; ++liStage)
            {
                maauStage[liStage][D3DTSS_COLOROP]   = (liStage == 0) ? D3DTOP_MODULATE : D3DTOP_DISABLE;
                maauStage[liStage][D3DTSS_ALPHAOP]   = (liStage == 0) ? D3DTOP_SELECTARG1 : D3DTOP_DISABLE;
                maauStage[liStage][D3DTSS_COLORARG1] = D3DTA_TEXTURE;
                maauStage[liStage][D3DTSS_COLORARG2] = D3DTA_CURRENT;
                maauStage[liStage][D3DTSS_ALPHAARG1] = D3DTA_TEXTURE;
                maauStage[liStage][D3DTSS_ALPHAARG2] = D3DTA_CURRENT;
            }
            mauRender[D3DRS_TEXTUREFACTOR] = 0xFFFFFFFFu;
        }

        HRESULT STDMETHODCALLTYPE SetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD Value) override
        {
            if (Stage < 8 && static_cast<DWORD>(Type) < 33) maauStage[Stage][Type] = Value;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetTextureStageState(DWORD Stage, D3DTEXTURESTAGESTATETYPE Type, DWORD* pValue) override
        {
            *pValue = (Stage < 8 && static_cast<DWORD>(Type) < 33) ? maauStage[Stage][Type] : 0;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE SetRenderState(D3DRENDERSTATETYPE State, DWORD Value) override
        {
            if (static_cast<DWORD>(State) < 256) mauRender[State] = Value;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE GetRenderState(D3DRENDERSTATETYPE State, DWORD* pValue) override
        {
            *pValue = (static_cast<DWORD>(State) < 256) ? mauRender[State] : 0;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE SetTexture(DWORD Stage, IDirect3DBaseTexture9* pTexture) override
        {
            if (Stage < 8) mapTexture[Stage] = pTexture;
            return S_OK;
        }
        HRESULT STDMETHODCALLTYPE DrawPrimitiveUP(D3DPRIMITIVETYPE, UINT PrimitiveCount,
                                                  CONST void* pVertexStreamZeroData,
                                                  UINT VertexStreamZeroStride) override
        {
            if (miDraws >= 16) return S_OK;
            DrawRecord& lrDraw = maDraws[miDraws++];
            for (int liStage = 0; liStage < 3; ++liStage)
            {
                lrDraw.mauColorOp[liStage]   = maauStage[liStage][D3DTSS_COLOROP];
                lrDraw.mauColorArg1[liStage] = maauStage[liStage][D3DTSS_COLORARG1];
                lrDraw.mauColorArg2[liStage] = maauStage[liStage][D3DTSS_COLORARG2];
                lrDraw.mauAlphaOp[liStage]   = maauStage[liStage][D3DTSS_ALPHAOP];
                lrDraw.mauAlphaArg1[liStage] = maauStage[liStage][D3DTSS_ALPHAARG1];
                lrDraw.mauAlphaArg2[liStage] = maauStage[liStage][D3DTSS_ALPHAARG2];
            }
            lrDraw.muTextureFactor  = mauRender[D3DRS_TEXTUREFACTOR];
            lrDraw.mbStage0Textured = mapTexture[0] != nullptr;
            // The immediate path's screen vertex: x, y, z, rhw (4 floats), then the D3DCOLOR.
            std::memcpy(&lrDraw.muVertexColour,
                        static_cast<const unsigned char*>(pVertexStreamZeroData) + 16, sizeof(DWORD));
            lrDraw.muPrimitives = PrimitiveCount;
            (void)VertexStreamZeroStride;
            return S_OK;
        }
    };

    struct Rgba { double r, g, b, a; };

    Rgba FromD3DColour(DWORD luColour)
    {
        return { ((luColour >> 16) & 0xFFu) / 255.0, ((luColour >> 8) & 0xFFu) / 255.0,
                 (luColour & 0xFFu) / 255.0, ((luColour >> 24) & 0xFFu) / 255.0 };
    }
    double Saturate(double lfValue) { return lfValue < 0.0 ? 0.0 : (lfValue > 1.0 ? 1.0 : lfValue); }

    // One operand of the fixed-function cascade, per channel.
    double Argument(DWORD luArg, int liChannel, const Rgba& lrTexel, const Rgba& lrDiffuse,
                    const Rgba& lrCurrent, const Rgba& lrFactor)
    {
        const Rgba* lpSource = nullptr;
        switch (luArg & D3DTA_SELECTMASK)
        {
        case D3DTA_TEXTURE: lpSource = &lrTexel;   break;
        case D3DTA_DIFFUSE: lpSource = &lrDiffuse; break;
        case D3DTA_CURRENT: lpSource = &lrCurrent; break;
        case D3DTA_TFACTOR: lpSource = &lrFactor;  break;
        default: return -1000.0;   // an argument this path never uses: fail loudly
        }
        const double lafChannels[4] = { lpSource->r, lpSource->g, lpSource->b, lpSource->a };
        return lafChannels[liChannel];
    }

    double Operation(DWORD luOp, double lfArg1, double lfArg2)
    {
        switch (luOp)
        {
        case D3DTOP_SELECTARG1: return lfArg1;
        case D3DTOP_SELECTARG2: return lfArg2;
        case D3DTOP_MODULATE:   return lfArg1 * lfArg2;
        case D3DTOP_ADD:        return Saturate(lfArg1 + lfArg2);
        default:                return -1000.0;
        }
    }

    // The pixel the D3D9 fixed-function texture cascade produces for one texel.
    Rgba ShadeFixedFunction(const DrawRecord& lrDraw, const Rgba& lrTexel)
    {
        const Rgba lDiffuse = FromD3DColour(lrDraw.muVertexColour);
        const Rgba lFactor  = FromD3DColour(lrDraw.muTextureFactor);
        Rgba lCurrent = lDiffuse;
        for (int liStage = 0; liStage < 3; ++liStage)
        {
            if (lrDraw.mauColorOp[liStage] == D3DTOP_DISABLE)
                break;
            double lafOut[4];
            for (int liChannel = 0; liChannel < 3; ++liChannel)
            {
                lafOut[liChannel] = Operation(lrDraw.mauColorOp[liStage],
                    Argument(lrDraw.mauColorArg1[liStage], liChannel, lrTexel, lDiffuse, lCurrent, lFactor),
                    Argument(lrDraw.mauColorArg2[liStage], liChannel, lrTexel, lDiffuse, lCurrent, lFactor));
            }
            lafOut[3] = Operation(lrDraw.mauAlphaOp[liStage],
                Argument(lrDraw.mauAlphaArg1[liStage], 3, lrTexel, lDiffuse, lCurrent, lFactor),
                Argument(lrDraw.mauAlphaArg2[liStage], 3, lrTexel, lDiffuse, lCurrent, lFactor));
            lCurrent = { Saturate(lafOut[0]), Saturate(lafOut[1]), Saturate(lafOut[2]), Saturate(lafOut[3]) };
        }
        return lCurrent;
    }

    // The console's program 0: texel * (vertexColour * scale) + shift, saturated at the export.
    Rgba ShadeConsole(const Rgba& lrTexel, const Rgba& lrVertex, const float* lpfScale, const float* lpfShift)
    {
        return { Saturate(lrTexel.r * lrVertex.r * lpfScale[0] + lpfShift[0]),
                 Saturate(lrTexel.g * lrVertex.g * lpfScale[1] + lpfShift[1]),
                 Saturate(lrTexel.b * lrVertex.b * lpfScale[2] + lpfShift[2]),
                 Saturate(lrTexel.a * lrVertex.a * lpfScale[3] + lpfShift[3]) };
    }

    unsigned gsuChecks = 0, gsuFailures = 0;
    void Check(bool lbPass, const char* lpcWhat)
    {
        ++gsuChecks;
        if (!lbPass) { ++gsuFailures; std::fprintf(stderr, "FAIL: %s\n", lpcWhat); }
    }

    struct CxfCase
    {
        const char* mpcName;
        float mafScale[4];
        float mafShift[4];
        unsigned char mau8Texel[4];   // RGBA 0..255
    };

    CgsGraphics::Im2dTransform ScreenTransformWithColour(const float* lpfScale, const float* lpfShift)
    {
        CgsGraphics::Im2dTransform lTransform;
        std::memset(&lTransform, 0, sizeof(lTransform));
        lTransform.mOriginXYZ.x = -1.0f;            // BrnFlapt::FlaptRenderer::Construct's screen transform
        lTransform.mOriginXYZ.y =  1.0f;
        lTransform.mRightUp.x   =  1.0f / 640.0f;
        lTransform.mRightUp.w   = -1.0f / 360.0f;
        lTransform.mColourScale.x = lpfScale[0]; lTransform.mColourScale.y = lpfScale[1];
        lTransform.mColourScale.z = lpfScale[2]; lTransform.mColourScale.w = lpfScale[3];
        lTransform.mColourShift.x = lpfShift[0]; lTransform.mColourShift.y = lpfShift[1];
        lTransform.mColourShift.z = lpfShift[2]; lTransform.mColourShift.w = lpfShift[3];
        return lTransform;
    }

    void FillQuad(CgsGraphics::Basic2dColouredTexturedVertex* lpVertices)
    {
        const float lafCorners[4][2] = { { 100.0f, 100.0f }, { 100.0f, 200.0f },
                                         { 300.0f, 100.0f }, { 300.0f, 200.0f } };
        for (int liIndex = 0; liIndex < 4; ++liIndex)
        {
            lpVertices[liIndex].mv2Pos.x = lafCorners[liIndex][0];
            lpVertices[liIndex].mv2Pos.y = lafCorners[liIndex][1];
            lpVertices[liIndex].mv4Colour.r = 255;   // FLAPT vertices carry opaque white
            lpVertices[liIndex].mv4Colour.g = 255;
            lpVertices[liIndex].mv4Colour.b = 255;
            lpVertices[liIndex].mv4Colour.a = 255;
            lpVertices[liIndex].mv2Tex0UV.x = lafCorners[liIndex][0] / 512.0f;
            lpVertices[liIndex].mv2Tex0UV.y = lafCorners[liIndex][1] / 512.0f;
        }
    }

    void CheckPixel(const char* lpcCase, const char* lpcPath, const DrawRecord& lrDraw,
                    const CxfCase& lrCase)
    {
        const Rgba lTexel = { lrCase.mau8Texel[0] / 255.0, lrCase.mau8Texel[1] / 255.0,
                              lrCase.mau8Texel[2] / 255.0, lrCase.mau8Texel[3] / 255.0 };
        const Rgba lVertex = { 1.0, 1.0, 1.0, 1.0 };
        const Rgba lPc      = ShadeFixedFunction(lrDraw, lTexel);
        const Rgba lConsole = ShadeConsole(lTexel, lVertex, lrCase.mafScale, lrCase.mafShift);
        // 8-bit vertex colour + 8-bit TFACTOR quantisation: allow 1.5/255 per channel.
        const double lfTolerance = 1.5 / 255.0;
        const bool lbMatch = std::fabs(lPc.r - lConsole.r) <= lfTolerance &&
                             std::fabs(lPc.g - lConsole.g) <= lfTolerance &&
                             std::fabs(lPc.b - lConsole.b) <= lfTolerance &&
                             std::fabs(lPc.a - lConsole.a) <= lfTolerance;
        char lacWhat[256];
        std::snprintf(lacWhat, sizeof(lacWhat),
                      "%s via %s: PC pixel (%.0f,%.0f,%.0f,%.0f) == console (%.0f,%.0f,%.0f,%.0f)",
                      lpcCase, lpcPath, lPc.r * 255.0, lPc.g * 255.0, lPc.b * 255.0, lPc.a * 255.0,
                      lConsole.r * 255.0, lConsole.g * 255.0, lConsole.b * 255.0, lConsole.a * 255.0);
        std::printf("  %s %s\n", lbMatch ? "ok  " : "FAIL", lacWhat);
        Check(lbMatch, lacWhat);
    }
}

int main()
{
    static RecordingDevice sDevice;
    renderengine::gDevice = &sDevice;

    // A stand-in raster: SetTexture binds its D3D pointer to stage 0 (never dereferenced here).
    static renderengine::Texture sAtlas;
    std::memset(&sAtlas, 0, sizeof(sAtlas));
    sAtlas.mpD3DTexture = reinterpret_cast<IDirect3DBaseTexture9*>(static_cast<uintptr_t>(0x5A5A0000u));

    const CxfCase kaCases[] =
    {
        { "white wash (432 obj 6)",   { 1.0f, 1.0f, 1.0f, 0.421875f }, { 0.0f, 0.0f, 0.0f, 0.0f },             { 255, 255, 255, 255 } },
        { "BlackDirt (432 obj 7)",    { 0.0f, 0.0f, 0.0f, 1.0f },      { 0.2f, 0.2f, 0.2f, 0.0f },             {   0,   0,   0, 248 } },
        { "RedDirt (432 obj 11)",     { 0.0f, 0.0f, 0.0f, 1.0f },      { 0.215686f, 0.078431f, 0.078431f, 0.0f }, {  59,  16,  16, 240 } },
        { "banner stripe (432 obj 12)", { 0.0f, 0.0f, 0.0f, 1.0f },    { 0.4f, 0.015686f, 0.015686f, 0.0f },   { 148,   8,   8, 251 } },
        { "MenuGrad (432 obj 10)",    { 1.0f, 1.0f, 1.0f, 0.5f },      { 0.0f, 0.0f, 0.0f, 0.0f },             {  59,  16,  16, 240 } },
        { "logo flash (433 obj 4)",   { 0.5f, 0.5f, 0.5f, 1.0f },      { 0.501961f, 0.501961f, 0.501961f, 0.0f }, { 148,   8,   8, 251 } },
    };

    for (const CxfCase& lrCase : kaCases)
    {
        const bool lbHasShift = lrCase.mafShift[0] > 0.0f || lrCase.mafShift[1] > 0.0f || lrCase.mafShift[2] > 0.0f;

        // ---- the FLAPT mesh path: FlaptRenderer::RenderMesh -> BatchTransformTextureBlendRenderStatic
        {
            static CgsGraphics::Im2d sIm2d;
            sIm2d.BeginRendering();      // BrnFlapt::FlaptRenderer::StartRenderingFrame's open
            CgsGraphics::Basic2dColouredTexturedVertex laQuad[4];
            FillQuad(laQuad);
            sDevice.miDraws = 0;
            sIm2d.BatchTransformTextureBlendRenderStatic(
                ScreenTransformWithColour(lrCase.mafScale, lrCase.mafShift), &sAtlas, nullptr,
                static_cast<renderengine::PrimitiveType>(6), laQuad, 4u, 3u);
            Check(sDevice.miDraws == 1, "BatchTransformTextureBlendRenderStatic issues exactly one draw");
            if (sDevice.miDraws == 1)
            {
                CheckPixel(lrCase.mpcName, "mesh batch", sDevice.maDraws[0], lrCase);
                if (!lbHasShift)
                {
                    Check(sDevice.maDraws[0].mauColorOp[1] == D3DTOP_DISABLE,
                          "a shift-free batch leaves texture stage 1 disabled during the draw");
                }
            }
            Check(sDevice.maauStage[1][D3DTSS_COLOROP] == D3DTOP_DISABLE &&
                  sDevice.maauStage[1][D3DTSS_ALPHAOP] == D3DTOP_DISABLE,
                  "texture stage 1 is DISABLED again after the mesh batch");
        }

        // ---- the FLAPT text path: RenderTextField -> SetTransform, TextRenderer -> RenderStart/RenderEnd
        {
            static CgsGraphics::Im2d sIm2d;
            sIm2d.BeginRendering();
            sIm2d.SetTransform(ScreenTransformWithColour(lrCase.mafScale, lrCase.mafShift));
            sIm2d.SetTexture(&sAtlas);   // the glyph page the TextRenderer binds
            CgsGraphics::Basic2dColouredTexturedVertex* lpRun = sIm2d.RenderStart(4u);
            FillQuad(lpRun);
            sDevice.miDraws = 0;
            sIm2d.RenderEnd(static_cast<renderengine::PrimitiveType>(6), lpRun, 4u);
            Check(sDevice.miDraws == 1, "RenderEnd issues exactly one draw");
            if (sDevice.miDraws == 1)
            {
                CheckPixel(lrCase.mpcName, "text run", sDevice.maDraws[0], lrCase);
            }
            Check(sDevice.maauStage[1][D3DTSS_COLOROP] == D3DTOP_DISABLE &&
                  sDevice.maauStage[1][D3DTSS_ALPHAOP] == D3DTOP_DISABLE,
                  "texture stage 1 is DISABLED again after the text run");
        }
    }

    Check(CgsDev::Assert::gsuAssertions == 0, "no assertion fired");
    std::printf("fxpopup im2d colour shift: %u/%u checks passed\n", gsuChecks - gsuFailures, gsuChecks);
    return gsuFailures == 0 ? 0 : 1;
}
