// L3 RACEINTRO (2026-09-27): the race intro's traffic-light space.
// The production body, extracted by run_fxraceintro_trafficlight_space.py from BrnMainDirector.cpp:
//   MainDirector::CalcTrafficLightSpace @0x8221A3A8, with its file-scope constant and its (default-off) witness;
// over the REAL JunctionLogicBox (its GetNumLights / GetLight inlines, the h:181 tripwire), the REAL
// TrafficLightCollection (its GetInstancePos inline, the h:266 / h:267 tripwires -- the header of the BL-1 merge) and
// the REAL ConsoleVpu::Dot3 (vmsum3fp128, ROUNDING_RULE 1). The world map, the traffic data, the game state and the
// player are stand-ins holding exactly what the body reads; CalcArbitraryAmberCoronaTransform is a double that
// records the instance and returns a MARKER matrix built from it, exactly as the emu64 run hooked the console's.
// Every expected value comes from the console's own words run on emu64 (FxRaceIntroTrafficLightSpaceData.h,
// generated by scratch/OWNERLIST_0927/L3/emu/gen_tlspace_data.py).
#include "types.hpp"
#include "BrnCommonTypes.h"
#include "GameShared/GameClasses/Core/CgsAssert.h"
#include "GameShared/GameClasses/Development/Log/CgsLog.h"
#include "SharedClasses/Traffic/Junctions/BrnJunctionLogicBox.h"
#include "SharedClasses/Traffic/Junctions/BrnTrafficLightCollection.h"
#include "GameSource/Director/Camera/Utils/BrnConsoleVpu.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "FxRaceIntroTrafficLightSpaceData.h"

static unsigned gChecks = 0, gFailures = 0;
static std::string gAsserts;
static std::vector<u32> gCalls;

namespace CgsDev
{
namespace Assert
{
    char* gpcMessageBuffer = nullptr;
    int   BeginAssert() { return 0; }
    int   FireAssert(const char* lpcMessage, const char*, int)
    {
        gAsserts += lpcMessage;
        gAsserts += "|";
        return 0;
    }
    void* EndAssert() { return nullptr; }
}
namespace Log { DebugPrint* gpDebugPrint = nullptr; }
namespace Message { unsigned long long gxMessageFilterFlags = 0; }
}

static f32 Val(u32 luBits)
{
    f32 lfValue;
    std::memcpy(&lfValue, &luBits, sizeof(lfValue));
    return lfValue;
}

static u32 Bits(f32 lfValue)
{
    u32 luBits;
    std::memcpy(&luBits, &lfValue, sizeof(luBits));
    return luBits;
}

static Vector3 Lane(const u32* lpuBits)
{
    const Vector3 lLane = { Val(lpuBits[0]), Val(lpuBits[1]), Val(lpuBits[2]), Val(lpuBits[3]) };
    return lLane;
}

// The generator's marker(): every lane of the returned transform names the instance.
static Matrix44Affine Marker(u32 luInstance)
{
    const f32 k = static_cast<f32>(luInstance);
    Matrix44Affine lMatrix;
    lMatrix.xAxis = { k + 0.25f, 1.0f, 2.0f, 3.0f };
    lMatrix.yAxis = { 4.0f, k + 0.5f, 6.0f, 7.0f };
    lMatrix.zAxis = { 8.0f, 9.0f, k + 0.75f, 11.0f };
    lMatrix.wAxis = { 1000.0f + k, 2000.0f + k, 3000.0f + k, 1.0f };
    return lMatrix;
}

// ---- the double for the collection's out-of-line member (its real body is BrnTrafficLightCollection.cpp's) --------
namespace BrnTraffic
{
    const Matrix44Affine TrafficLightCollection::CalcArbitraryAmberCoronaTransform(u32 luInstance) const
    {
        gCalls.push_back(luInstance);
        return Marker(luInstance);
    }

    // The traffic data: the collection by value, as TrafficData::mTrafficLights.
    struct TrafficData
    {
        TrafficLightCollection mTrafficLights;
    };
}

namespace BrnDirector
{
    // The world map: the h:90 LOADED tripwire, then the resource (WorldMap::GetTrafficData @0x82219128's shape).
    class WorldMap
    {
    public:
        enum ELoadingState { E_LOADING_STATE_LOADED = 6 };
        const BrnTraffic::TrafficData* GetTrafficData() const
        {
            CGS_ASSERT(meLoadingState == E_LOADING_STATE_LOADED, "meLoadingState == E_LOADING_STATE_LOADED");
            return mpTrafficData;
        }
        s32                            meLoadingState;
        const BrnTraffic::TrafficData* mpTrafficData;
    };

    struct DirectorInputOutput
    {
        WorldMap* mpWorldMap;
    };

    struct GameState
    {
        const BrnTraffic::JunctionLogicBox* mpEventJLBox;
        Matrix44Affine                      mTrafficLightSpace;
    };

    struct RaceCarState
    {
        Matrix44Affine mTransform;
    };

    struct VehicleInfo
    {
        RaceCarState mRaceCarState;
    };

    class AllVehicleData
    {
    public:
        const VehicleInfo& GetPlayer() const
        {
            ++miGetPlayerCalls;
            return mPlayer;
        }
        VehicleInfo         mPlayer;
        mutable s32         miGetPlayerCalls;
    };

    class MainDirector
    {
    public:
        void CalcTrafficLightSpace(const DirectorInputOutput* lpIO);

        AllVehicleData mAllVehicleData;
        GameState      maGameState;
    };

#include "tlspace_bodies.inc"
}

using namespace BrnDirector;

static void Check(bool lbPass, const std::string& lrWhat)
{
    ++gChecks;
    if (!lbPass)
    {
        ++gFailures;
        std::printf("FAIL: %s\n", lrWhat.c_str());
    }
}

static unsigned Count(const std::string& lrHaystack, const char* lpcNeedle)
{
    unsigned luCount = 0;
    const std::string lNeedle = std::string(lpcNeedle) + "|";
    for (size_t at = lrHaystack.find(lNeedle); at != std::string::npos; at = lrHaystack.find(lNeedle, at + 1))
    {
        ++luCount;
    }
    return luCount;
}

int main()
{
    const size_t luNumCases = sizeof(kaTlsCases) / sizeof(kaTlsCases[0]);
    unsigned luCallsChosen = 0;
    for (size_t luCase = 0; luCase < luNumCases; ++luCase)
    {
        const TlsCase& lrCase = kaTlsCases[luCase];
        const std::string lName = std::string("[") + lrCase.mpcName + "] ";

        // The collection: muNumTrafficLights and the position lanes (the Y rotation in w).
        static Vector3Plus saPos[32];
        for (u32 i = 0; i < 32; ++i)
        {
            saPos[i].x = Val(lrCase.maaPos[i][0]);
            saPos[i].y = Val(lrCase.maaPos[i][1]);
            saPos[i].z = Val(lrCase.maaPos[i][2]);
            saPos[i].w = Val(lrCase.maaPos[i][3]);
        }
        BrnTraffic::TrafficData lData;
        std::memset(&lData, 0, sizeof(lData));
        lData.mTrafficLights.muNumTrafficLights  = static_cast<u16>(lrCase.muNumInstances);
        lData.mTrafficLights.mpaPosAndYRotations = saPos;

        // The event junction box: the controller count and each controller's two ids and count.
        BrnTraffic::JunctionLogicBox lBox;
        std::memset(&lBox, 0, sizeof(lBox));
        lBox.muNumLights = static_cast<u8>(lrCase.muNumControllers);
        for (u32 i = 0; i < 8; ++i)
        {
            lBox.maTrafficLightControllers[i].mauTrafficLightIds[0] = lrCase.maaIds[i][0];
            lBox.maTrafficLightControllers[i].mauTrafficLightIds[1] = lrCase.maaIds[i][1];
            lBox.maTrafficLightControllers[i].muNumTrafficLights    = lrCase.mauCounts[i];
        }

        WorldMap lWorldMap;
        lWorldMap.meLoadingState = static_cast<s32>(lrCase.muLoadingState);
        lWorldMap.mpTrafficData  = &lData;
        DirectorInputOutput lIO;
        lIO.mpWorldMap = &lWorldMap;

        MainDirector lDirector;
        std::memset(&lDirector, 0, sizeof(lDirector));
        lDirector.mAllVehicleData.mPlayer.mRaceCarState.mTransform.xAxis = Lane(&lrCase.mauPlayer[0]);
        lDirector.mAllVehicleData.mPlayer.mRaceCarState.mTransform.yAxis = Lane(&lrCase.mauPlayer[4]);
        lDirector.mAllVehicleData.mPlayer.mRaceCarState.mTransform.zAxis = Lane(&lrCase.mauPlayer[8]);
        lDirector.mAllVehicleData.mPlayer.mRaceCarState.mTransform.wAxis = Lane(&lrCase.mauPlayer[12]);
        lDirector.maGameState.mpEventJLBox = lrCase.muHasBox ? &lBox : nullptr;
        lDirector.maGameState.mTrafficLightSpace.xAxis = Lane(&lrCase.mauSeed[0]);
        lDirector.maGameState.mTrafficLightSpace.yAxis = Lane(&lrCase.mauSeed[4]);
        lDirector.maGameState.mTrafficLightSpace.zAxis = Lane(&lrCase.mauSeed[8]);
        lDirector.maGameState.mTrafficLightSpace.wAxis = Lane(&lrCase.mauSeed[12]);

        gCalls.clear();
        gAsserts.clear();
        lDirector.CalcTrafficLightSpace(&lIO);

        // (1) the same lights chosen, in the same order, as the console (each CalcArbitraryAmberCoronaTransform call)
        bool lbCalls = (gCalls.size() == lrCase.muNumCalls);
        for (size_t i = 0; lbCalls && i < gCalls.size(); ++i)
        {
            lbCalls = (gCalls[i] == lrCase.mauCalls[i]);
        }
        char lacDetail[160];
        std::snprintf(lacDetail, sizeof(lacDetail), "the light chosen, call by call: %u call(s), console %u",
                      static_cast<unsigned>(gCalls.size()), lrCase.muNumCalls);
        Check(lbCalls, lName + lacDetail);
        luCallsChosen += lrCase.muNumCalls;

        // (2) the space the take reads, bit for bit (the seed when nothing is chosen)
        const Matrix44Affine& lrSpace = lDirector.maGameState.mTrafficLightSpace;
        const f32* lpfSpace = &lrSpace.xAxis.x;
        bool lbSpace = true;
        for (u32 i = 0; i < 16; ++i)
        {
            lbSpace = lbSpace && (Bits(lpfSpace[i]) == lrCase.mauSpace[i]);
        }
        Check(lbSpace, lName + "GameState::mTrafficLightSpace, all 16 words, as the console's +0x337F0");

        // (3) the tripwires, kind by kind
        Check(Count(gAsserts, "meLoadingState == E_LOADING_STATE_LOADED") == lrCase.muAsserts90
                  && Count(gAsserts, "luLight < muNumLights") == lrCase.muAsserts181
                  && Count(gAsserts, "luInstance < muNumTrafficLights") == lrCase.muAsserts266
                  && Count(gAsserts, "mpaPosAndYRotations") == lrCase.muAsserts267,
              lName + "the tripwires (WorldMap h:90, GetLight h:181, GetInstancePos h:266 / h:267) as the console's");
    }

    // The player is read through GetPlayer twice (0x8221A414 / 0x8221A428), whatever the junction holds.
    {
        MainDirector lDirector;
        std::memset(&lDirector, 0, sizeof(lDirector));
        BrnTraffic::JunctionLogicBox lBox;
        std::memset(&lBox, 0, sizeof(lBox));
        BrnTraffic::TrafficData lData;
        std::memset(&lData, 0, sizeof(lData));
        WorldMap lWorldMap;
        lWorldMap.meLoadingState = 6;
        lWorldMap.mpTrafficData  = &lData;
        DirectorInputOutput lIO;
        lIO.mpWorldMap = &lWorldMap;
        lDirector.maGameState.mpEventJLBox = &lBox;
        lDirector.CalcTrafficLightSpace(&lIO);
        Check(lDirector.mAllVehicleData.miGetPlayerCalls == 2,
              "GetPlayer 0x82205C58 is called twice (the position and the forward), once each");
    }

    Check(luCallsChosen > 40, "the data exercises the choice (more than 40 console calls across the cases)");

    std::printf("FxRaceIntroTrafficLightSpace: %u checks, %u failures\n", gChecks, gFailures);
    return gFailures == 0 ? 0 : 1;
}
