// L3 RACEINTRO (2026-09-28): the traffic-light corona renderers of the light manager.
// The production bodies, extracted by run_fxtrafficlight_coronas.py from BrnTrafficLightManager.cpp:
//   TrafficLightManager::RenderLightsForHull @0x8275DBF0 and RenderAllLightsToBeInStateForHull @0x8275DE50, with
//   TrafficLightRuntimeState::IsSmashed / GetLightState (DWARF .cpp:100 / :118) and the default-off [tl-corona] witness;
// over the REAL BrnTrafficLightManager.h (the manager, its 600 records, the countdown members, the const GetLightState
// inline with its h:217 tripwire) and the REAL Hull. TrafficLightCollection::RenderCoronasForInstance @0x827571B8 is a
// double that records each call, exactly as the emu64 run hooked the console's.
// Every expected value comes from the console's own words run on emu64 (FxTrafficLightCoronasData.h, generated by
// scratch/OWNERLIST_0927/L3/emu/gen_tlcorona_data.py).
#include "types.hpp"
#include "BrnCommonTypes.h"
#include "GameShared/GameClasses/Core/CgsAssert.h"
#include "GameShared/GameClasses/Development/Log/CgsLog.h"
#include "GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficLightManager.h"
#include "SharedClasses/Traffic/BrnTrafficHull.h"
#include "SharedClasses/Traffic/Junctions/BrnTrafficLightCollection.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "FxTrafficLightCoronasData.h"

static unsigned gChecks = 0, gFailures = 0;
static std::string gAsserts;

struct RecordedCall
{
    u32         muInstance;
    u32         muMask;
    const void* mpCollection;
    const void* mpInterface;
    u32         mauV[12];
};
static std::vector<RecordedCall> gCalls;

namespace CgsDev
{
namespace Assert
{
    char* gpcMessageBuffer = nullptr;
    int   BeginAssert() { return 0; }
    int   FireAssert(const char* lpcMessage, const char*, int)
    {
        gAsserts += lpcMessage;
        gAsserts += "|";
        return 0;
    }
    void* EndAssert() { return nullptr; }
}
namespace Log { DebugPrint* gpDebugPrint = nullptr; }
namespace Message { unsigned long long gxMessageFilterFlags = 0; }
}

static f32 Val(u32 luBits)
{
    f32 lfValue;
    std::memcpy(&lfValue, &luBits, sizeof(lfValue));
    return lfValue;
}

static u32 Bits(f32 lfValue)
{
    u32 luBits;
    std::memcpy(&luBits, &lfValue, sizeof(luBits));
    return luBits;
}

static Vector3 Lane(const u32* lpuBits)
{
    const Vector3 lLane = { Val(lpuBits[0]), Val(lpuBits[1]), Val(lpuBits[2]), Val(lpuBits[3]) };
    return lLane;
}

static Vector4 Lane4(const u32* lpuBits)
{
    const Vector4 lLane = { Val(lpuBits[0]), Val(lpuBits[1]), Val(lpuBits[2]), Val(lpuBits[3]) };
    return lLane;
}

namespace BrnTraffic
{
    // ---- the double for the collection's out-of-line member (its real body is BrnTrafficLightCollection.cpp's) ----
    void TrafficLightCollection::RenderCoronasForInstance(u32 luInstance, u32 luActiveStates,
                                                          BrnCoronaManager::BrnSubmissionInterface* lpCoronaSubmissionInterface,
                                                          Vector3 lCameraPosition, Vector3 lCameraDirection,
                                                          VecFloat lfCullDistSq) const
    {
        RecordedCall lCall;
        lCall.muInstance   = luInstance;
        lCall.muMask       = luActiveStates;
        lCall.mpCollection = this;
        lCall.mpInterface  = lpCoronaSubmissionInterface;
        const f32 lafV[12] = { lCameraPosition.x, lCameraPosition.y, lCameraPosition.z, lCameraPosition.w,
                               lCameraDirection.x, lCameraDirection.y, lCameraDirection.z, lCameraDirection.w,
                               lfCullDistSq.x, lfCullDistSq.y, lfCullDistSq.z, lfCullDistSq.w };
        for (u32 i = 0; i < 12; ++i)
        {
            lCall.mauV[i] = Bits(lafV[i]);
        }
        gCalls.push_back(lCall);
    }

#include "tlcorona_manager_bodies.inc"
}

using namespace BrnTraffic;

static void Check(bool lbPass, const std::string& lrWhat)
{
    ++gChecks;
    if (!lbPass)
    {
        ++gFailures;
        std::printf("FAIL: %s\n", lrWhat.c_str());
    }
}

static unsigned Count(const std::string& lrHaystack, const char* lpcNeedle)
{
    unsigned luCount = 0;
    const std::string lNeedle = std::string("|") + lpcNeedle + "|";
    const std::string lHaystack = "|" + lrHaystack;
    for (size_t at = lHaystack.find(lNeedle); at != std::string::npos; at = lHaystack.find(lNeedle, at + 1))
    {
        ++luCount;
    }
    return luCount;
}

int main()
{
    static TrafficLightManager sManager;
    static TrafficLightCollection sCollection;
    static int siInterfaceTag;   // the interface is passed through, never read: any distinct address will do
    BrnCoronaManager::BrnSubmissionInterface* const lpInterface =
        reinterpret_cast<BrnCoronaManager::BrnSubmissionInterface*>(&siInterfaceTag);

    const size_t luNumCases = sizeof(kManagerCases) / sizeof(kManagerCases[0]);
    unsigned luConsoleCalls = 0;
    for (size_t luCase = 0; luCase < luNumCases; ++luCase)
    {
        const ManagerCase& lrCase = kManagerCases[luCase];
        const std::string lName = std::string("[") + lrCase.mpcName + "] ";

        std::memset(&sManager, 0, sizeof(sManager));
        for (u32 r = 0; r < lrCase.muNumRecords; ++r)
        {
            const u32* lpuRecord = &kManagerRecords[3 * (lrCase.muRecordStart + r)];
            TrafficLightRuntimeState& lrState = reinterpret_cast<TrafficLightRuntimeState&>(sManager.maLightStates[lpuRecord[0]]);
            lrState.muState = static_cast<u8>(lpuRecord[1]);
            lrState.muFlags = static_cast<u8>(lpuRecord[2]);
        }
        sManager.mbCountdownLights = lrCase.muCountdown != 0;
        sManager.meCountdownState  = static_cast<s32>(lrCase.muCountdownState);

        Hull lHull;
        std::memset(&lHull, 0, sizeof(lHull));
        lHull.muFirstTrafficLight = static_cast<u16>(lrCase.muFirst);
        lHull.muLastTrafficLight  = static_cast<u16>(lrCase.muLast);

        gCalls.clear();
        gAsserts.clear();
        if (lrCase.muAll)
        {
            sManager.RenderAllLightsToBeInStateForHull(&lHull, &sCollection, lrCase.muMask, lpInterface,
                                                       Lane(&lrCase.mauV[0]), Lane(&lrCase.mauV[4]), Lane4(&lrCase.mauV[8]));
        }
        else
        {
            sManager.RenderLightsForHull(&lHull, &sCollection, lpInterface, Lane(&lrCase.mauV[0]), Lane(&lrCase.mauV[4]),
                                         Lane4(&lrCase.mauV[8]));
        }

        // (1) the lights drawn, call by call: the instance, the active-state mask and the three vector arguments bitwise
        bool lbCalls = (gCalls.size() == lrCase.muNumCalls);
        for (size_t i = 0; lbCalls && i < gCalls.size(); ++i)
        {
            const u32* lpuExpected = &kManagerCalls[14 * (lrCase.muCallStart + i)];
            lbCalls = gCalls[i].muInstance == lpuExpected[0] && gCalls[i].muMask == lpuExpected[1]
                      && gCalls[i].mpCollection == &sCollection && gCalls[i].mpInterface == lpInterface
                      && std::memcmp(gCalls[i].mauV, lpuExpected + 2, sizeof(gCalls[i].mauV)) == 0;
        }
        char lacDetail[200];
        std::snprintf(lacDetail, sizeof(lacDetail),
                      "RenderCoronasForInstance call by call (instance, mask, v1/v2/v3 bitwise): %u call(s), console %u",
                      static_cast<unsigned>(gCalls.size()), lrCase.muNumCalls);
        Check(lbCalls, lName + lacDetail);
        luConsoleCalls += lrCase.muNumCalls;

        // (2) the tripwires, kind by kind (the console counted them by line)
        const unsigned luHull     = lrCase.mu296 + lrCase.mu359;
        const unsigned luData     = lrCase.mu297 + lrCase.mu360;
        const unsigned luInstance = lrCase.mu217;
        const unsigned luState    = lrCase.mu309 + lrCase.mu327 + lrCase.mu366;
        Check(Count(gAsserts, "lpHull") == luHull && Count(gAsserts, "lpTrafficLightData") == luData
                  && Count(gAsserts, "meCountdownState != E_TRAFFICLIGHTSTATE_COUNT") == lrCase.mu301
                  && Count(gAsserts, "luInstance < KU_MAX_TRAFFIC_LIGHT_INSTANCES") == luInstance
                  && Count(gAsserts, "lpLightState") == luState && lrCase.muOther == 0,
              lName + "the tripwires (.cpp:296/297/301/309/327/359/360/366, h:217) as the console's");
    }

    Check(luConsoleCalls > 100, "the data exercises the renderers (more than 100 console calls across the cases)");

    std::printf("FxTrafficLightCoronasManager: %u checks, %u failures\n", gChecks, gFailures);
    return gFailures == 0 ? 0 : 1;
}
