// L3 RACEINTRO (2026-09-28): the traffic-light corona pass and its frustum.
// The production bodies, extracted by run_fxtrafficlight_coronas.py:
//   CgsGraphics::Camera::GetFrustumPerspectiveVertices @0x827E70E0 (+ its anonymous-namespace lane helpers), from
//     CgsCamera.cpp;
//   TrafficEntityModule::RenderTrafficLightCoronas @0x8271EC80 (+ its file-scope constants, the VMX min / max lanes and
//     the default-off [tl-coronas] witness), from BrnTrafficEntityModule_Render.cpp;
// over the REAL CgsGraphics::Camera (CgsCamera.h: the view rows, the projection scalars, the inline SetFarClipPlane),
// the REAL Pvs (BrnTrafficPvs.h + BrnTrafficPvs.cpp: GetHullIndexForPoint, GetHullIndexForIndices) and the REAL Set.
// The module is a stand-in holding exactly the members the pass reads; the two manager renderers, the director
// camera's CopyToCgsCamera and the graphics camera's UpdatePerspectiveProjectionMatrix are doubles, exactly as the
// emu64 run hooked the console's (UpdatePerspectiveProjectionMatrix touches neither mView nor the four scalars the
// vertices read; the double records the far plane the pass set).
// Every expected value comes from the console's own words run on emu64 (FxTrafficLightCoronasData.h, generated by
// scratch/OWNERLIST_0927/L3/emu/gen_tlcorona_data.py).
#include "types.hpp"
#include "BrnCommonTypes.h"
#include "GameShared/GameClasses/Core/CgsAssert.h"
#include "GameShared/GameClasses/Development/Log/CgsLog.h"
#include "GameShared/GameClasses/Containers/CgsSet.h"
#include "GameShared/GameClasses/Graphics/CgsCamera.h"
#include "SharedClasses/Traffic/BrnTrafficPvs.h"
#include "SharedClasses/Traffic/BrnTrafficSharedConstants.h"
#include "GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficConstants.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "FxTrafficLightCoronasData.h"

static unsigned gChecks = 0, gFailures = 0;
static std::string gAsserts;
static std::vector<u32> gFarPlanes;

namespace CgsDev
{
namespace Assert
{
    char* gpcMessageBuffer = nullptr;
    int   BeginAssert() { return 0; }
    int   FireAssert(const char* lpcMessage, const char*, int)
    {
        gAsserts += lpcMessage;
        gAsserts += "|";
        return 0;
    }
    void* EndAssert() { return nullptr; }
}
namespace Log { DebugPrint* gpDebugPrint = nullptr; }
namespace Message { unsigned long long gxMessageFilterFlags = 0; }
}

static f32 Val(u32 luBits)
{
    f32 lfValue;
    std::memcpy(&lfValue, &luBits, sizeof(lfValue));
    return lfValue;
}

static u32 Bits(f32 lfValue)
{
    u32 luBits;
    std::memcpy(&luBits, &lfValue, sizeof(luBits));
    return luBits;
}

static Vector3 Lane(const u32* lpuBits)
{
    const Vector3 lLane = { Val(lpuBits[0]), Val(lpuBits[1]), Val(lpuBits[2]), Val(lpuBits[3]) };
    return lLane;
}

static Vector4 Lane4(const u32* lpuBits)
{
    const Vector4 lLane = { Val(lpuBits[0]), Val(lpuBits[1]), Val(lpuBits[2]), Val(lpuBits[3]) };
    return lLane;
}

static void LoadCamera(CgsGraphics::Camera& lrCamera, const u32* lpuView, u32 luTanH, u32 luTanV, u32 luNear, u32 luFar)
{
    lrCamera.mView.xAxis = Lane4(&lpuView[0]);
    lrCamera.mView.yAxis = Lane4(&lpuView[4]);
    lrCamera.mView.zAxis = Lane4(&lpuView[8]);
    lrCamera.mView.wAxis = Lane4(&lpuView[12]);
    lrCamera.maProjectionScalars[2] = Val(luTanH);   // +0x148 m_tanHalfFovHorizontal
    lrCamera.maProjectionScalars[5] = Val(luTanV);   // +0x154 m_tanHalfFovVertical
    lrCamera.maProjectionScalars[7] = Val(luNear);   // +0x15C m_nearClipPlane
    lrCamera.maProjectionScalars[8] = Val(luFar);    // +0x160 m_farClipPlane
}

// The interface is passed through, never read: a stand-in type at the production spelling.
class BrnCoronaManager
{
public:
    class BrnSubmissionInterface
    {
    public:
        int miTag;
    };
};

namespace CgsGraphics
{
    // The double for the projection rebuild (0x827EC778, hooked the same way on emu64).
    void Camera::UpdatePerspectiveProjectionMatrix()
    {
        gFarPlanes.push_back(Bits(maProjectionScalars[8]));
    }

#include "tlcorona_frustum_bodies.inc"
}

static const u32* gpuCaseView = nullptr;
static u32 gauCaseScalars[4];
static unsigned guCopies = 0;

namespace BrnTraffic
{
    struct Hull
    {
        u32 muIndex;
    };

    struct TrafficLightCollection
    {
        u32 muUnused;
    };

    struct TrafficData
    {
        u16                    muNumHulls;
        Pvs*                   mpPvs;
        Hull**                 mpapHulls;
        TrafficLightCollection mTrafficLights;
    };

    // CgsResource::ResourcePtr<TrafficData>'s operator-> (0x82719B90): the CgsResourcePtr.h:544 tripwire, then the pointer.
    struct TrafficDataPtr
    {
        TrafficData* operator->() const
        {
            CGS_ASSERT(mpResource != nullptr, "Can not instance resource pointer - it has no main memory resource\n");
            return mpResource;
        }
        TrafficData* mpResource;
    };

    struct PassCall
    {
        u32         muPhase;
        u32         muHull;
        u32         muMask;
        const void* mpManager;
        const void* mpCollection;
        const void* mpInterface;
        u32         mauV[12];
    };
    static std::vector<PassCall> gPassCalls;

    static void Record(u32 luPhase, const void* lpManager, const Hull* lpHull, const TrafficLightCollection* lpData,
                       u32 luMask, const void* lpInterface, const Vector3& lrV1, const Vector3& lrV2, const Vector4& lrV3)
    {
        PassCall lCall;
        lCall.muPhase      = luPhase;
        lCall.muHull       = lpHull->muIndex;
        lCall.muMask       = luMask;
        lCall.mpManager    = lpManager;
        lCall.mpCollection = lpData;
        lCall.mpInterface  = lpInterface;
        const f32 lafV[12] = { lrV1.x, lrV1.y, lrV1.z, lrV1.w, lrV2.x, lrV2.y, lrV2.z, lrV2.w,
                               lrV3.x, lrV3.y, lrV3.z, lrV3.w };
        for (u32 i = 0; i < 12; ++i)
        {
            lCall.mauV[i] = Bits(lafV[i]);
        }
        gPassCalls.push_back(lCall);
    }

    // The two manager renderers (bl 0x8275DBF0 / 0x8275DE50), recorded as the emu64 run hooked them.
    class TrafficLightManager
    {
    public:
        void RenderLightsForHull(const Hull* lpHull, const TrafficLightCollection* lpTrafficLightData,
                                 BrnCoronaManager::BrnSubmissionInterface* lpCoronaSubmissionInterface,
                                 Vector3 lCameraPosition, Vector3 lCameraDirection, VecFloat lfCullDistSq) const
        {
            Record(1, this, lpHull, lpTrafficLightData, 0, lpCoronaSubmissionInterface, lCameraPosition,
                   lCameraDirection, lfCullDistSq);
        }
        void RenderAllLightsToBeInStateForHull(const Hull* lpHull, const TrafficLightCollection* lpTrafficLightData,
                                               u32 luActiveStates,
                                               BrnCoronaManager::BrnSubmissionInterface* lpCoronaSubmissionInterface,
                                               Vector3 lCameraPosition, Vector3 lCameraDirection,
                                               VecFloat lfCullDistSq) const
        {
            Record(2, this, lpHull, lpTrafficLightData, luActiveStates, lpCoronaSubmissionInterface, lCameraPosition,
                   lCameraDirection, lfCullDistSq);
        }
        u32 muUnused;
    };

    // BrnDirector::Camera::Camera's CopyToCgsCamera (bl 0x8220AC48): writes the case's graphics camera.
    struct FixtureDirectorCamera
    {
        void CopyToCgsCamera(CgsGraphics::Camera* lpOutCamera) const
        {
            ++guCopies;
            LoadCamera(*lpOutCamera, gpuCaseView, gauCaseScalars[0], gauCaseScalars[1], gauCaseScalars[2],
                       gauCaseScalars[3]);
        }
    };

    class TrafficEntityModule
    {
    public:
        void RenderTrafficLightCoronas(BrnCoronaManager::BrnSubmissionInterface* lpCoronaSubmissionInterface,
                                       Vector3 lCameraPosition, Vector3 lCameraDirection);

        // GetHull, inlined by the console (BrnTrafficEntityModule.h:2229).
        const Hull* GetHull(u32 luIndex) const
        {
            CGS_ASSERT(luIndex < mpData->muNumHulls, "luIndex < (mpData->muNumHulls)");
            return mpData->mpapHulls[luIndex];
        }

        TrafficLightManager             mTrafficLightManager;
        ::Set<u16, KU_MAX_ACTIVE_HULLS> mActiveHullsForLocalPlayer;
        TrafficDataPtr                  mpData;
        FixtureDirectorCamera           mCameraLastFrame;
    };

#include "tlcorona_pass_bodies.inc"
}

using namespace BrnTraffic;

static void Check(bool lbPass, const std::string& lrWhat)
{
    ++gChecks;
    if (!lbPass)
    {
        ++gFailures;
        std::printf("FAIL: %s\n", lrWhat.c_str());
    }
}

int main()
{
    // ---- GetFrustumPerspectiveVertices: the 32 words of the 8 corners, bitwise ----
    const size_t luNumFrustum = sizeof(kFrustumCases) / sizeof(kFrustumCases[0]);
    for (size_t luCase = 0; luCase < luNumFrustum; ++luCase)
    {
        const FrustumCase& lrCase = kFrustumCases[luCase];
        CgsGraphics::Camera lCamera;
        std::memset(&lCamera, 0, sizeof(lCamera));
        LoadCamera(lCamera, lrCase.mauView, lrCase.muTanH, lrCase.muTanV, lrCase.muNear, lrCase.muFar);
        Vector3 laVerts[8];
        std::memset(laVerts, 0xCD, sizeof(laVerts));
        lCamera.GetFrustumPerspectiveVertices(laVerts);
        u32 luFirstBad = 32;
        for (u32 i = 0; i < 32 && luFirstBad == 32; ++i)
        {
            const Vector3& lrV = laVerts[i / 4];
            const f32 lfLane = (i % 4 == 0) ? lrV.x : (i % 4 == 1) ? lrV.y : (i % 4 == 2) ? lrV.z : lrV.w;
            if (Bits(lfLane) != lrCase.mauVerts[i])
            {
                luFirstBad = i;
            }
        }
        char lacDetail[240];
        if (luFirstBad < 32)
        {
            const Vector3& lrV = laVerts[luFirstBad / 4];
            const f32 lfLane = (luFirstBad % 4 == 0) ? lrV.x : (luFirstBad % 4 == 1) ? lrV.y : (luFirstBad % 4 == 2) ? lrV.z : lrV.w;
            std::snprintf(lacDetail, sizeof(lacDetail), " (first difference: corner %u lane %u, PC %08X console %08X)",
                          luFirstBad / 4, luFirstBad % 4, Bits(lfLane), lrCase.mauVerts[luFirstBad]);
        }
        else
        {
            lacDetail[0] = 0;
        }
        Check(luFirstBad == 32, std::string("[frustum: ") + lrCase.mpcName
                                    + "] the 8 corners, all 32 words, as the console's 0x827E70E0" + lacDetail);
    }

    // ---- RenderTrafficLightCoronas: the renderers' calls, phase by phase ----
    const u32 luNumCells = kGridX * kGridZ;
    static Pvs sPvs;
    std::memset(&sPvs, 0, sizeof(sPvs));
    sPvs.mGridMin       = Lane(kGridMin);
    sPvs.mRecipCellSize = Lane(kGridRecip);
    sPvs.muNumCells_X   = kGridX;
    sPvs.muNumCells_Z   = kGridZ;
    sPvs.muNumCells     = luNumCells;
    static Hull saHulls[kGridX * kGridZ];
    static Hull* sapHulls[kGridX * kGridZ];
    for (u32 k = 0; k < luNumCells; ++k)
    {
        saHulls[k].muIndex = k;
        sapHulls[k]        = &saHulls[k];
    }
    static TrafficData sData;
    sData.muNumHulls = static_cast<u16>(luNumCells);
    sData.mpPvs      = &sPvs;
    sData.mpapHulls  = sapHulls;

    static int siInterfaceTag;
    BrnCoronaManager::BrnSubmissionInterface* const lpInterface =
        reinterpret_cast<BrnCoronaManager::BrnSubmissionInterface*>(&siInterfaceTag);

    const size_t luNumPass = sizeof(kPassCases) / sizeof(kPassCases[0]);
    unsigned luConsolePhase2 = 0;
    for (size_t luCase = 0; luCase < luNumPass; ++luCase)
    {
        const PassCase& lrCase = kPassCases[luCase];
        const std::string lName = std::string("[pass: ") + lrCase.mpcName + "] ";

        static TrafficEntityModule sModule;
        std::memset(&sModule, 0, sizeof(sModule));
        sModule.mpData.mpResource = &sData;
        sModule.mActiveHullsForLocalPlayer.Construct();
        for (u32 a = 0; a < lrCase.muNumActive; ++a)
        {
            sModule.mActiveHullsForLocalPlayer.Insert(static_cast<u16>(kPassActive[lrCase.muActiveStart + a]));
        }
        gpuCaseView       = lrCase.mauView;
        gauCaseScalars[0] = lrCase.muTanH;
        gauCaseScalars[1] = lrCase.muTanV;
        gauCaseScalars[2] = lrCase.muNear;
        gauCaseScalars[3] = lrCase.muFar;

        gPassCalls.clear();
        gFarPlanes.clear();
        gAsserts.clear();
        guCopies = 0;
        sModule.RenderTrafficLightCoronas(lpInterface, Lane(lrCase.mauV1), Lane(lrCase.mauV2));

        std::vector<const PassCall*> laPhase1, laPhase2;
        bool lbOrder = true;   // every phase-1 call precedes every phase-2 call, as on the console
        for (const PassCall& lrCall : gPassCalls)
        {
            if (lrCall.muPhase == 1)
            {
                lbOrder = lbOrder && laPhase2.empty();
                laPhase1.push_back(&lrCall);
            }
            else
            {
                laPhase2.push_back(&lrCall);
            }
        }

        bool lbPhase1 = lbOrder && (laPhase1.size() == lrCase.muNumPhase1);
        for (size_t i = 0; lbPhase1 && i < laPhase1.size(); ++i)
        {
            const u32* lpuExpected = &kPassPhase1[13 * (lrCase.muPhase1Start + i)];
            lbPhase1 = laPhase1[i]->muHull == lpuExpected[0] && laPhase1[i]->mpManager == &sModule.mTrafficLightManager
                       && laPhase1[i]->mpCollection == &sData.mTrafficLights && laPhase1[i]->mpInterface == lpInterface
                       && std::memcmp(laPhase1[i]->mauV, lpuExpected + 1, sizeof(laPhase1[i]->mauV)) == 0;
        }
        char lacDetail[200];
        std::snprintf(lacDetail, sizeof(lacDetail),
                      "the active hulls -> RenderLightsForHull, call by call (hull, v1/v2/v3 bitwise): %u, console %u",
                      static_cast<unsigned>(laPhase1.size()), lrCase.muNumPhase1);
        Check(lbPhase1, lName + lacDetail);

        bool lbPhase2 = (laPhase2.size() == lrCase.muNumPhase2);
        for (size_t i = 0; lbPhase2 && i < laPhase2.size(); ++i)
        {
            const u32* lpuExpected = &kPassPhase2[14 * (lrCase.muPhase2Start + i)];
            lbPhase2 = laPhase2[i]->muHull == lpuExpected[0] && laPhase2[i]->muMask == lpuExpected[1]
                       && laPhase2[i]->mpManager == &sModule.mTrafficLightManager
                       && laPhase2[i]->mpCollection == &sData.mTrafficLights && laPhase2[i]->mpInterface == lpInterface
                       && std::memcmp(laPhase2[i]->mauV, lpuExpected + 2, sizeof(laPhase2[i]->mauV)) == 0;
        }
        std::snprintf(lacDetail, sizeof(lacDetail),
                      "the frustum's other hulls -> RenderAllLightsToBeInStateForHull, call by call (hull, mask, "
                      "v1/v2/v3 bitwise): %u, console %u",
                      static_cast<unsigned>(laPhase2.size()), lrCase.muNumPhase2);
        Check(lbPhase2, lName + lacDetail);
        luConsolePhase2 += lrCase.muNumPhase2;

        Check(guCopies == 1 && gFarPlanes.size() == 1 && gFarPlanes[0] == 0x43FA0000u,
              lName + "the frustum camera: mCameraLastFrame copied once, its far plane set to 500 (flt_8200A034) once");

        Check(gAsserts.empty() && lrCase.muAsserts == 0, lName + "no tripwire fires, as on the console");
    }

    Check(luConsolePhase2 > 300, "the data exercises the frustum walk (more than 300 console phase-2 calls)");

    std::printf("FxTrafficLightCoronasPass: %u checks, %u failures\n", gChecks, gFailures);
    return gFailures == 0 ? 0 : 1;
}
