// Harness for run_fxxlane_rw_epsilons.py (crash parity H2-D3 / H2-D4 / H2-D5; FX-XLANE).
//
// The three rw::collision guard rows that were an inferred 1.0e-12f, read from the image:
//   H2-D3 FeatureEdge::FeatureEdge @0x82BA85B8   unk_8327EEA0 = splat(flt_821801B4 = FLT_EPSILON)
//         vcmpgtfp lenSq > row (0x82BA8608) -> else length = 0 and dir = 0
//   H2-D4 Feature::BuildEdgePlanes @0x82BB9D68   unk_8327EFD0 = splat(flt_82180A28 = FLT_EPSILON)
//         vcmpgtfp |cross|^2 > row (0x82BB9DDC / 0x82BB9E80) -> else pn = 0
//   H2-D5 RimToEdge @0x82BB53F8 / RimToRim @0x82BB56C8  unk_8327EFB0 = splat(flt_82180894 = FLT_MIN)
//         vcmpgefp lenSq >= row + vnot -> the radial pipeline's valid arm is V * r1 * r1 (~V / lenSq)
// FeatureEdge.cpp and Feature.cpp are compiled WHOLE from the revision under test; the rim test
// calls the production RimRadialDirection (anonymous namespace) through a generated wrapper TU.
#include "vendor/renderware/collision/Feature.hpp"
#include "vendor/renderware/collision/FeatureEdge.hpp"
#include <cmath>
#include <cstdio>
#include <cstring>

namespace rw { namespace collision {
Vec4 FxXlaneRimRadialDirection(const Vec4& arV);   // rim.cpp (generated by the runner)
} }

using namespace rw::collision;

static int giChecks = 0, giFailures = 0;
static void Check(bool lbPass, const char* lpcName)
{
    ++giChecks;
    if (!lbPass) { ++giFailures; std::printf("FAIL: %s\n", lpcName); }
}
static Vec4 V(float x, float y, float z, float w) { Vec4 v; v.x = x; v.y = y; v.z = z; v.w = w; return v; }
static bool AllZero(const Vec4& v) { return v.x == 0.0f && v.y == 0.0f && v.z == 0.0f && v.w == 0.0f; }
static bool Near(float a, float b, float tol) { return std::fabs(a - b) <= tol; }

int main()
{
    // ---- H2-D3: FeatureEdge ctor ----
    {
        const FeatureEdge lEdge(V(0, 0, 0, 0), V(1.0e-4f, 0, 0, 0));   // lenSq 1e-8: (1e-12, FLT_EPSILON]
        Check(AllZero(lEdge.length) && AllZero(lEdge.dir),
              "H2-D3 edge of lenSq 1e-8 <= FLT_EPSILON: length and dir zeroed (vcmpgtfp @0x82BA8608)");
    }
    {
        const float lfA = std::ldexp(1.0f, -12);                          // lenSq == 2^-23 == FLT_EPSILON
        const FeatureEdge lEdge(V(0, 0, 0, 0), V(lfA, lfA, 0, 0));
        Check(AllZero(lEdge.length) && AllZero(lEdge.dir),
              "H2-D3 boundary lenSq == FLT_EPSILON: strict '>' zeroes it");
    }
    {
        const FeatureEdge lEdge(V(0, 0, 0, 0), V(1.0e-3f, 0, 0, 0));   // lenSq 1e-6 > FLT_EPSILON
        Check(Near(lEdge.length.x, 1.0e-3f, 1.0e-9f) && Near(lEdge.dir.x, 1.0f, 1.0e-6f)
              && lEdge.dir.y == 0.0f && lEdge.dir.z == 0.0f, "H2-D3 control: a 1 mm edge keeps length and dir");
    }

    // ---- H2-D4: Feature::BuildEdgePlanes ----
    {
        static Feature lFeature;
        std::memset(&lFeature, 0, sizeof(lFeature));
        lFeature.numedges = 1;
        lFeature.edges[0].dir = V(1, 0, 0, 0);
        lFeature.BuildEdgePlanes(1, V(1, 0, 1.0e-4f, 0));             // cross (0,-1e-4,0): |c|^2 = 1e-8
        Check(AllZero(lFeature.edges[0].pn), "H2-D4 |cross|^2 = 1e-8 <= FLT_EPSILON: pn zeroed (vcmpgtfp @0x82BB9DDC)");
    }
    {
        static Feature lFeature;
        std::memset(&lFeature, 0, sizeof(lFeature));
        lFeature.numedges = 1;
        lFeature.edges[0].dir = V(1, 0, 0, 0);
        lFeature.BuildEdgePlanes(1, V(0, 0, 1, 0));                   // cross (0,-1,0)
        Check(Near(lFeature.edges[0].pn.x, 0.0f, 1e-6f) && Near(lFeature.edges[0].pn.y, -1.0f, 1e-6f)
              && Near(lFeature.edges[0].pn.z, 0.0f, 1e-6f), "H2-D4 control: a unit cross normalises to (0,-1,0)");
    }

    // ---- H2-D5: the rim radial pipeline (RimToEdge / RimToRim) ----
    {
        const Vec4 lDir = FxXlaneRimRadialDirection(V(1.0e-7f, 0, 0, 0));    // lenSq ~1e-14 >= FLT_MIN
        Check(Near(lDir.x, 1.0e7f, 1.0e3f) && lDir.y == 0.0f && lDir.z == 0.0f,
              "H2-D5 lenSq ~1e-14 >= FLT_MIN: the valid arm V * r1 * r1 (~(1e7,0,0)), not V/|V|");
    }
    {
        const Vec4 lDir = FxXlaneRimRadialDirection(V(0.5f, 0, 0, 0));
        Check(Near(lDir.x, 2.0f, 1e-5f) && lDir.y == 0.0f && lDir.z == 0.0f, "H2-D5 control: (0.5,0,0) -> (2,0,0)");
    }

    std::printf("FxXlaneRwEpsilons: %d checks, %d failures\n", giChecks, giFailures);
    return giFailures ? 1 : 0;
}
