// GENERATED by scratch/OWNERLIST_0927/L1/emu/gen_construct_flags_l1.py -- do not edit by hand.
// The car-attached policy as the console's behaviour Constructs leave it (the ARTIST words on emu64, from a 0xA5-filled
// behaviour): its eight bools +0x248..+0x24F (mbAutoElevate, mbSmoothRadiusChanges, mbFailOnContact,
// mbUseGroundConstraint, mbTestAgainstWorldOnly, mbUseFrustrumResolver, mbResetVehicleCollision (Construct leaves it:
// the pattern), mbDoVehicleCollision) and its two tail floats (mfDesiredNearClip +0x23C, mfMaxRadius +0x240).
#pragma once
#include "types.hpp"

struct L1ConstructFlags
{
    const char* mpcBehaviour;
    u32         muAddress;      // the behaviour's Construct
    u8          mauBools[8];    // policy +0x248..+0x24F
    u32         mauFloats[2];   // policy +0x23C, +0x240 (the console's words)
};

static const u8 KU_L1_FLAGS_PATTERN = 0xA5u;

static const L1ConstructFlags kaL1ConstructFlags[2] = {
    { "BehaviourGameplayExternal", 0x82224A18u, { 0x00, 0x01, 0x00, 0x00, 0x01, 0x01, 0xA5, 0x01 }, { 0x3E19999Au, 0x7F7FFFFFu } },
    { "BehaviourIceAnim", 0x82256100u, { 0x01, 0x00, 0x00, 0x00, 0x01, 0x01, 0xA5, 0x00 }, { 0x3E19999Au, 0x7F7FFFFFu } },
};
