#include <Windows.h>
#include <d3d9.h>
#include <shlobj.h>
#include <cstdio>
#include <cstring>
#include <initializer_list>
#include "pc/gcm/renderengine/GraphicsSettings.h"
#include "pc/debug/DebugIni.h"

namespace renderengine {
    bool gFullscreen = false;
    s32 gDisplayWidth = 640, gDisplayHeight = 360, gAdapterIndex = 0, gVSync = 1;
    s32 gAntiAliasing = 0, gAlphaToCoverage = 1, gEnvironmentMap = 1;
    s32 gCoronas = 1, gSunCorona = 1;
    IDirect3DDevice9* gDevice = nullptr;
}
namespace BrnGame { bool gbDecoupleSimulationFromRenderRate = true; }
namespace CgsDev { namespace Log { void WriteToLog(const char* lpcText) { std::printf("%s", lpcText); } } }
static char gacTestDirectory[MAX_PATH];
static char gacTestIni[MAX_PATH];
static IDirect3DDevice9* Dev() { return renderengine::gDevice; }
static void getGameSaveDir(char* lpcPath, const char* lpcFile)
{
    std::snprintf(lpcPath, MAX_PATH, "%s%s", gacTestDirectory, lpcFile);
}
#include "pc_graphics_settings.inc"

static int giChecks, giFailures;
static void Check(bool lbGood, const char* lpcMessage)
{
    ++giChecks;
    if (!lbGood) { ++giFailures; std::printf("FAIL %s\n", lpcMessage); }
}
static void Set(const char* lpcKey, const char* lpcValue)
{
    WritePrivateProfileStringA("Graphics", lpcKey, lpcValue, gacTestIni);
}
static void ConfigChecks()
{
    LoadConfig();
    const auto& lrGraphics = renderengine::GetGraphicsSettingsPC();
    Check(lrGraphics.miAnisotropicFiltering == 1, "absent filtering retains original sampler choice");
    Check(lrGraphics.miShadowResolutionScale==1 && lrGraphics.mfShadowDistance==120.0f && lrGraphics.mfShadowSlopeBias==0.0f,
          "absent native shadow controls preserve original settings");
    Set("AnisotropicFiltering","16"); Set("ShadowResolutionScale","2");
    Set("ShadowDistance","240"); Set("ShadowSlopeBias","1");
    WritePrivateProfileStringA("Debug","Environment/Bloom luminance scale","0.3",gacTestIni);
    WritePrivateProfileStringA("Other","KeepMe","yes",gacTestIni);
    LoadConfig();
    Check(lrGraphics.miAnisotropicFiltering==16 && lrGraphics.miShadowResolutionScale==2 &&
          lrGraphics.mfShadowDistance==240 && lrGraphics.mfShadowSlopeBias==1,
          "native controls still load while engine controls are generic");
    renderengine::gFullscreen=true; SaveFullscreenConfigPC();
    SaveConfig(); renderengine::GetGraphicsSettingsPC()=renderengine::GraphicsSettingsPC(); LoadConfig();
    Check(lrGraphics.miAnisotropicFiltering==16 && lrGraphics.miShadowResolutionScale==2 &&
          lrGraphics.mfShadowDistance==240 && lrGraphics.mfShadowSlopeBias==1,
          "native settings round-trip");
    char lacText[128];
    GetPrivateProfileStringA("Debug","Environment/Bloom luminance scale","",lacText,sizeof(lacText),gacTestIni);
    Check(std::strcmp(lacText,"0.3")==0,"shutdown preserves the requested generic initial value");
    GetPrivateProfileStringA("Other","KeepMe","",lacText,sizeof(lacText),gacTestIni);
    Check(std::strcmp(lacText,"yes")==0,"unrelated sections survive saving");
    Check(GetPrivateProfileIntA("Display","Fullscreen",0,gacTestIni)==1,"fullscreen persistence is retained");
    for (const char* p : {"BloomLuminanceScale","EnvironmentMapLOD","TrafficShadows",
                          "WorldLODOverrideDistance","PropLODOverrideDistance","VehicleLODPreset"})
    {
        GetPrivateProfileStringA("Graphics",p,"absent",lacText,sizeof(lacText),gacTestIni);
        Check(std::strcmp(lacText,"absent")==0,"removed dedicated keys are not regenerated by SaveConfig");
    }
    GetPrivateProfileStringA("Settings","EnvironmentMap30Hz","absent",lacText,sizeof(lacText),gacTestIni);
    Check(std::strcmp(lacText,"absent")==0,"obsolete refresh global is not written back");
    for (const char* p : {"0","3","17","NaN","16garbage",""})
    { Set("AnisotropicFiltering",p); LoadConfig(); Check(lrGraphics.miAnisotropicFiltering==1,"invalid anisotropy uses original filtering"); }
    for (const char* p : {"0","3","2oops","99999999999999999",""})
    { Set("ShadowResolutionScale",p); LoadConfig(); Check(lrGraphics.miShadowResolutionScale==1,"invalid atlas scale preserves original dimensions"); }
    for (const char* p : {"NaN","inf","29","501","120oops",""})
    { Set("ShadowDistance",p); LoadConfig(); Check(lrGraphics.mfShadowDistance==120,"invalid distance preserves original cascade ranges"); }
    for (const char* p : {"NaN","inf","-0.1","4.1","1oops",""})
    { Set("ShadowSlopeBias",p); LoadConfig(); Check(lrGraphics.mfShadowSlopeBias==0,"invalid slope option preserves material bias"); }
}

static void NativeAA()
{
    IDirect3D9* lpD3D = Direct3DCreate9(D3D_SDK_VERSION);
    Check(lpD3D != nullptr, "native D3D9 available"); if (!lpD3D) return;
    HWND lhWindow = CreateWindowExA(0,"STATIC","Graphics settings AA regression",WS_OVERLAPPEDWINDOW,0,0,200,160,nullptr,nullptr,GetModuleHandleA(nullptr),nullptr);
    D3DPRESENT_PARAMETERS lPresent = {};
    lPresent.Windowed = TRUE; lPresent.hDeviceWindow = lhWindow; lPresent.SwapEffect = D3DSWAPEFFECT_DISCARD;
    lPresent.BackBufferWidth = 128; lPresent.BackBufferHeight = 128; lPresent.BackBufferFormat = D3DFMT_X8R8G8B8;
    lPresent.PresentationInterval = D3DPRESENT_INTERVAL_IMMEDIATE;
    const HRESULT lhCreate = lpD3D->CreateDevice(0,D3DDEVTYPE_HAL,lhWindow,
        D3DCREATE_SOFTWARE_VERTEXPROCESSING|D3DCREATE_FPU_PRESERVE,&lPresent,&renderengine::gDevice);
    Check(SUCCEEDED(lhCreate), "native HAL device created");
    if (FAILED(lhCreate)) { DestroyWindow(lhWindow); lpD3D->Release(); return; }
    Check(MultisampleSampleCountForConsoleFormat(1) == 2 && MultisampleSampleCountForConsoleFormat(2) == 4,
          "console multisample formats mean 2x/4x, not raw enum samples");
    for (const int liRequest : {0,1,2,4,8,16})
    {
        renderengine::gAntiAliasing = liRequest;
        const u32 luOverride = MultisampleOverrideSampleCount();
        Check(luOverride == (liRequest == 0 ? 0u : (liRequest > 8 ? 8u : static_cast<u32>(liRequest))),
              "native AA override maps default/off/sample count and existing 8x maximum");
        const u32 luRequest = luOverride == 0 ? MultisampleSampleCountForConsoleFormat(1) : luOverride;
        const MultisampleChoice lChoice = ChooseMultisampleType(luRequest,D3DFMT_A8R8G8B8);
        Check(lChoice.muSamples >= 1 && lChoice.muSamples <= luRequest, "unsupported AA requests fall back downward");
        DWORD luColourLevels = 0, luDepthLevels = 0;
        if (lChoice.muSamples > 1)
        {
            Check(SUCCEEDED(lpD3D->CheckDeviceMultiSampleType(0,D3DDEVTYPE_HAL,D3DFMT_A8R8G8B8,TRUE,lChoice.meType,&luColourLevels)) &&
                  SUCCEEDED(lpD3D->CheckDeviceMultiSampleType(0,D3DDEVTYPE_HAL,lChoice.meDepthFormat,TRUE,lChoice.meType,&luDepthLevels)),
                  "AA choice supports both actual surface formats");
        }
        DWORD luEightLevels = 0;
        if (liRequest == 8 && SUCCEEDED(lpD3D->CheckDeviceMultiSampleType(0,D3DDEVTYPE_HAL,D3DFMT_A8R8G8B8,TRUE,D3DMULTISAMPLE_8_SAMPLES,&luEightLevels)) &&
            SUCCEEDED(lpD3D->CheckDeviceMultiSampleType(0,D3DDEVTYPE_HAL,D3DFMT_D24S8,TRUE,D3DMULTISAMPLE_8_SAMPLES,&luEightLevels)))
            Check(lChoice.muSamples == 8, "8x-capable hardware really selects 8x");
        IDirect3DSurface9* lpColour = CreateMultisampledColourSurface(128,128,D3DFMT_A8R8G8B8,lChoice);
        IDirect3DSurface9* lpDepth = CreateMultisampledDepthSurface(128,128,lChoice);
        Check(lpColour && lpDepth, "production AA surface pair allocates");
        if (lpColour && lpDepth)
        {
            D3DSURFACE_DESC lColour = {}, lDepth = {}; lpColour->GetDesc(&lColour); lpDepth->GetDesc(&lDepth);
            Check(lColour.MultiSampleType == lChoice.meType && lDepth.MultiSampleType == lChoice.meType &&
                  lColour.MultiSampleQuality == lDepth.MultiSampleQuality, "colour/depth use matching sample count and quality");
            auto* lpDevice = renderengine::gDevice;
            Check(SUCCEEDED(lpDevice->SetRenderTarget(0,lpColour)) && SUCCEEDED(lpDevice->SetDepthStencilSurface(lpDepth)), "matching AA surfaces bind");
            const D3DVIEWPORT9 lViewport = {0,0,128,128,0,1}; lpDevice->SetViewport(&lViewport);
            Check(SUCCEEDED(lpDevice->Clear(0,nullptr,D3DCLEAR_TARGET|D3DCLEAR_ZBUFFER,0xff000000,1,0)), "native AA target clears");
            struct Vertex { float x,y,z,rhw; DWORD colour; };
            const Vertex kaVertices[3] = {{8.25f,8.25f,0.5f,1,0xffffffff},{110.25f,20.25f,0.5f,1,0xffffffff},{20.25f,110.25f,0.5f,1,0xffffffff}};
            lpDevice->SetFVF(D3DFVF_XYZRHW|D3DFVF_DIFFUSE); lpDevice->SetRenderState(D3DRS_LIGHTING,FALSE);
            lpDevice->SetRenderState(D3DRS_CULLMODE,D3DCULL_NONE); lpDevice->SetRenderState(D3DRS_MULTISAMPLEANTIALIAS,TRUE);
            lpDevice->SetTextureStageState(0,D3DTSS_COLOROP,D3DTOP_SELECTARG1);
            lpDevice->SetTextureStageState(0,D3DTSS_COLORARG1,D3DTA_DIFFUSE);
            const HRESULT lhBegin = lpDevice->BeginScene();
            const HRESULT lhDraw = lpDevice->DrawPrimitiveUP(D3DPT_TRIANGLELIST,1,kaVertices,sizeof(Vertex));
            const HRESULT lhEnd = lpDevice->EndScene();
            Check(SUCCEEDED(lhBegin) && SUCCEEDED(lhDraw) && SUCCEEDED(lhEnd), "native AA triangle draws");
            IDirect3DSurface9* lpResolved = nullptr; IDirect3DSurface9* lpRead = nullptr;
            lpDevice->CreateRenderTarget(128,128,D3DFMT_A8R8G8B8,D3DMULTISAMPLE_NONE,0,FALSE,&lpResolved,nullptr);
            lpDevice->CreateOffscreenPlainSurface(128,128,D3DFMT_A8R8G8B8,D3DPOOL_SYSTEMMEM,&lpRead,nullptr);
            Check(lpResolved && lpRead, "AA readback targets allocate");
            if (lpResolved && lpRead)
            {
                const HRESULT lhResolve = lpDevice->StretchRect(lpColour,nullptr,lpResolved,nullptr,D3DTEXF_NONE);
                Check(SUCCEEDED(lhResolve) && SUCCEEDED(lpDevice->GetRenderTargetData(lpResolved,lpRead)), "MSAA colour resolves and reads back");
                D3DLOCKED_RECT lLocked = {}; bool lbCoverage = false, lbWhite = false;
                if (SUCCEEDED(lpRead->LockRect(&lLocked,nullptr,D3DLOCK_READONLY)))
                {
                    for (u32 luY = 0; luY < 128; ++luY)
                    {
                        const auto* lpRow = reinterpret_cast<const DWORD*>(static_cast<const char*>(lLocked.pBits) + luY*lLocked.Pitch);
                        for (u32 luX = 0; luX < 128; ++luX)
                        { const DWORD luRgb = lpRow[luX]&0xffffff; lbWhite |= luRgb == 0xffffff; lbCoverage |= luRgb != 0 && luRgb != 0xffffff; }
                    }
                    lpRead->UnlockRect();
                }
                Check(lbWhite && (lChoice.muSamples == 1 ? !lbCoverage : lbCoverage), "resolved pixels show real multisample edge coverage");
            }
            if (lpRead) lpRead->Release(); if (lpResolved) lpResolved->Release();
            lpDevice->SetDepthStencilSurface(nullptr);
        }
        std::printf("AA requested=%u actual=%u\n",luRequest,lChoice.muSamples);
        if (lpColour) lpColour->Release(); if (lpDepth) lpDepth->Release();
    }
    renderengine::gDevice->Release(); renderengine::gDevice = nullptr;
    DestroyWindow(lhWindow); lpD3D->Release();
}

int main()
{
    GetTempPathA(MAX_PATH,gacTestDirectory);
    const size_t luLength = std::strlen(gacTestDirectory);
    std::snprintf(gacTestDirectory + luLength,MAX_PATH-luLength,"brn_graphics_%lu\\",GetCurrentProcessId());
    CreateDirectoryA(gacTestDirectory,nullptr); getGameSaveDir(gacTestIni,"config.ini");
    ConfigChecks(); NativeAA();
    DeleteFileA(gacTestIni); RemoveDirectoryA(gacTestDirectory);
    std::printf("PCGraphicsSettings: %d checks, %d failures\n",giChecks,giFailures);
    return giFailures ? 1 : 0;
}
