"""Compare production AboveCar banking/projection with fixed raw ARTIST gold.

Run from the workflow checkout. External renderer/font/localisation/camera-rebuild
and Array calls are recorded fixtures, as in the original-opcode oracle. The
complete production functions are extracted unchanged; real GPU/glyph drawing
is a separate live requirement. Gold: ARTIST8245BF28 and82222060, generated by
scratch/PLAYTEST_1005/above-car/banking_oracle.py;19 cases/24 draws/0 asserts.
"""
from pathlib import Path
import json
import os
import subprocess
import sys
import tempfile

sys.dont_write_bytecode=True
from run_render_part_interpolation import REPO, WORKFLOW, settings
from fxdeformlat_common import definition

HERE=Path(__file__).resolve().parent


def number(value):
    text=format(float(value),'.17g')
    return text+('f' if '.' in text or 'e' in text else '.0f')


def vector(values):
    return '{'+','.join(number(x) for x in values)+'}'


def case_cpp(case):
    matrix=case.get('matrix',[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])
    scores=[]
    for score in case.get('scores',[]):
        scores.append('{'+vector([*score.get('screen',[200,300]),score.get('lane2',17),score.get('lane3',19)])+','+
                      vector([*score.get('world',[0,0,0]),score.get('worldw',0)])+','+
                      ','.join(str(score.get(key,default)).lower() for key,default in [('base',100),('bonus',0),('road',False)])+'}')
    return ('{'+json.dumps(case['name'])+','+str(case.get('mode',16))+','+str(case.get('language',0))+','+
            str(case.get('autosize',False)).lower()+','+str(case.get('pending',True)).lower()+','+
            ','.join(number(case.get(key,value)) for key,value in [('near',.4),('targetx',0),('width',12.25)])+','+
            '{'+','.join(vector(matrix[i:i+4]) for i in range(0,16,4))+'},'+str(len(scores))+',{' + ','.join(scores)+'}}')


def main():
    gold=json.loads((HERE/'PlaytestAboveCarBankingData.json').read_text(encoding='utf-8'))
    banking_source=(REPO/'src/GameSource/Gui/CustomRenderer/Renderers/BrnAboveCarRenderer.cpp').read_text(encoding='utf-8-sig')
    camera_source=(REPO/'src/GameSource/Director/Camera/Utils/CameraUtils.cpp').read_text(encoding='utf-8-sig')
    banking=definition(banking_source,'void AboveCarRenderer::RenderBankingScores(')
    projection=definition(camera_source,'bool BrnDirector::Camera::Utils::ProjectWorldSpacePointToScreen(')
    with tempfile.TemporaryDirectory(prefix='brn_above_car_banking_') as path:
        out=Path(path)
        (out/'playtest_above_car_banking.inc').write_text(banking,encoding='utf-8')
        (out/'playtest_above_car_projection.inc').write_text(projection,encoding='utf-8')
        (out/'playtest_above_car_cases.inc').write_text('static const Case K_CASES[]={\n'+
            ',\n'.join(case_cpp(row['case']) for row in gold)+'\n};',encoding='utf-8')
        includes=' '.join('/I"'+str(WORKFLOW/p)+'"' for p in settings('msvc_includes.txt'))
        cmd='cl '+' '.join(settings('msvc_flags.txt'))+' '+includes+' /I"'+str(out)+'" "'+str(HERE/'PlaytestAboveCarBanking.cpp')+'" /Fe:regression.exe /link /OPT:REF'
        script=out/'run.cmd'
        script.write_text('@echo off\ncall "'+str(WORKFLOW/'tools/build/msvc_env.bat')+'" >nul 2>&1\nif errorlevel 1 exit /b 1\n'+
                          cmd+'\nif errorlevel 1 exit /b 1\nregression.exe\nexit /b %ERRORLEVEL%\n',encoding='utf-8',newline='\r\n')
        env=dict(os.environ);env.pop('NoDefaultCurrentDirectoryInExePath',None)
        result=subprocess.run(['cmd','/c',str(script)],cwd=out,env=env,capture_output=True,text=True,check=True)
        lines=result.stdout.splitlines()
        print('\n'.join(lines[:-1]))
        native=json.loads(lines[-1])
    checks=0
    errors=[]
    def compare(want,got,path):
        nonlocal checks
        if isinstance(want,dict):
            for key in want:
                if key!='case':compare(want[key],got[key],path+'.'+key)
        elif isinstance(want,list):
            checks+=1
            if len(want)!=len(got):errors.append((path+'.length',len(want),len(got)));return
            for i,(w,g) in enumerate(zip(want,got)):compare(w,g,path+f'[{i}]')
        else:
            checks+=1
            ok=abs(want-got)<=max(1e-7,abs(want)*5e-9) if isinstance(want,float) else want==got
            if not ok:errors.append((path,want,got))
    compare([x for x in gold],native,'cases')
    print(f'Production banking/original: {len(native)} cases, {checks} checks, {len(errors)} failures')
    for error in errors[:30]:print(error)
    raise SystemExit(1 if errors else 0)


if __name__=='__main__':main()
