"""L3 RACEINTRO (2026-09-28): the traffic lights' lamps -- the traffic-light corona pass.

The owner's report: "The races intro doesn't show the traffic light going green". A traffic light's lit lamps are its
CORONAS. The lights cycled on the PC (0802404c) and followed the event countdown (30d481f4), but nothing drew them:
  TrafficEntityModule::RenderTrafficLightCoronas @0x8271EC80 (GenerateDispatchLists' bl at 0x8273B4C4, off the shadow
    pass) had no body and no call -- gate G5;
  TrafficLightManager::RenderLightsForHull @0x8275DBF0 and RenderAllLightsToBeInStateForHull @0x8275DE50 had no body;
  CgsGraphics::Camera::GetFrustumPerspectiveVertices @0x827E70E0 had no declaration.
The pass draws every active hull's lights in their own state -- or, through an event countdown, in the countdown's (RED
at 3 and 2, AMBER at 1, GREEN at 0) -- and every other hull inside the camera frustum's Pvs box GREEN.

NUMERIC, two fixtures, every expected value from the console's own words run on emu64 (FxTrafficLightCoronasData.h,
generated by scratch/OWNERLIST_0927/L3/emu/gen_tlcorona_data.py):
  FxTrafficLightCoronasManager.cpp: the production renderers over the REAL manager header and Hull, RenderCoronasForInstance
    recorded -- 25 cases (the lights' own states, each countdown state, COUNT's tripwire, empty / inverted / last-ten
    ranges, smashed lights, the pass's GREEN and other masks, random hulls): each call (instance, mask, v1/v2/v3
    bitwise) and the tripwire counts.
  FxTrafficLightCoronasPass.cpp: GetFrustumPerspectiveVertices over the REAL CgsGraphics::Camera -- 47 cameras (12 near the origin, where fused and unfused differ), the 32
    words of the 8 corners bitwise (ROUNDING_RULE 1 / 3 / 5); RenderTrafficLightCoronas over the REAL Pvs and Set -- 14
    cases (grid middle, corner clamp, off the grid, narrow / wide fov, random): each renderer call in order (hull, mask,
    v1/v2/v3 bitwise), the camera copy and its 500 m far plane, the tripwires.
WIRING: GenerateDispatchLists' call off the shadow pass, and the three declarations.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxtrafficlight_coronas.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import Tree, definition, code_only, compile_and_run, report, STRSTREAM_CPP, REPO

MANAGER_CPP = "src/GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficLightManager.cpp"
MANAGER_H = "src/GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficLightManager.h"
CAMERA_CPP = "src/GameShared/GameClasses/Graphics/CgsCamera.cpp"
CAMERA_H = "src/GameShared/GameClasses/Graphics/CgsCamera.h"
RENDER_CPP = "src/GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficEntityModule_Render.cpp"
MODULE_H = "src/GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficEntityModule.h"
COLLECTION_H = "src/SharedClasses/Traffic/Junctions/BrnTrafficLightCollection.h"
PVS_H = "src/SharedClasses/Traffic/BrnTrafficPvs.h"
PVS_CPP = REPO / "src/SharedClasses/Traffic/BrnTrafficPvs.cpp"
MANAGER_CHECKS = 25 * 2 + 1
PASS_CHECKS = 47 + 14 * 4 + 1


def lf(text):
    return text.replace("\r\n", "\n")


def shadow_of(tree, *headers):
    shadow = {}
    for header in headers:
        text = tree.read(header)
        if text:
            shadow[header] = text
    return shadow


def manager_numeric(tree):
    source = lf(tree.read(MANAGER_CPP))
    try:
        parts = [definition(source, "namespace\n{\n    // [FLAG PC witness] (L3 RACEINTRO; NOT console code). "
                                    "BRN_TRAFFIC_LIGHT_CORONA_DIAG"),
                 definition(source, "bool TrafficLightRuntimeState::IsSmashed() const"),
                 definition(source, "u8 TrafficLightRuntimeState::GetLightState() const"),
                 definition(source, "void TrafficLightManager::RenderLightsForHull("),
                 definition(source, "void TrafficLightManager::RenderAllLightsToBeInStateForHull(")]
    except ValueError as error:
        print("NUMERIC (manager): cannot build -- " + str(error))
        return None
    return compile_and_run(Path(__file__).with_name("FxTrafficLightCoronasManager.cpp"), "tlcorona_manager_bodies.inc",
                           "\n".join(parts), "FxTrafficLightCoronasManager",
                           shadow=shadow_of(tree, MANAGER_H, COLLECTION_H), extra_sources=[STRSTREAM_CPP])


def pass_numeric(tree):
    camera = lf(tree.read(CAMERA_CPP))
    render = lf(tree.read(RENDER_CPP))
    try:
        frustum = [definition(camera, "namespace\n    {\n        // One VMX register's four lanes"),
                   definition(camera, "void Camera::GetFrustumPerspectiveVertices(Vector3* frustumVerts) const")]
        corona = [definition(render, "namespace\n{\n    // DWARF BrnTrafficTweakConstants.h:177 KF_RENDER_CULL_CORONA_DISTANCE"),
                  definition(render, "void\nTrafficEntityModule::RenderTrafficLightCoronas(")]
    except ValueError as error:
        print("NUMERIC (pass): cannot build -- " + str(error))
        return None
    return compile_and_run(Path(__file__).with_name("FxTrafficLightCoronasPass.cpp"), "tlcorona_frustum_bodies.inc",
                           "\n".join(frustum), "FxTrafficLightCoronasPass",
                           shadow=shadow_of(tree, CAMERA_H, PVS_H),
                           extra_sources=[STRSTREAM_CPP, PVS_CPP],
                           extra_files={"tlcorona_pass_bodies.inc": "\n".join(corona)})


def numeric(tree):
    results = [(manager_numeric(tree), MANAGER_CHECKS), (pass_numeric(tree), PASS_CHECKS)]
    checks = sum(r[0] if r else total for r, total in results)
    failures = sum(r[1] if r else total for r, total in results)
    return checks, failures


def body(source, signature):
    try:
        return code_only(definition(source, signature))
    except ValueError:
        return ""


def wiring(tree):
    render = lf(tree.read(RENDER_CPP))
    dispatch = body(render, "void\nTrafficEntityModule::GenerateDispatchLists(")
    module_h = code_only(lf(tree.read(MODULE_H)))
    manager_h = code_only(lf(tree.read(MANAGER_H)))
    camera_h = code_only(lf(tree.read(CAMERA_H)))
    call = re.search(r"if\s*\(\s*!lpShadowMap->IsRenderingShadowMap\(\)\s*\)\s*\{(.*?)\n    \}", dispatch, re.S)
    return [
        ("GenerateDispatchLists calls RenderTrafficLightCoronas(interface, lCameraPosition, lCameraDirection) off the "
         "shadow pass (bl 0x8271EC80 at 0x8273B4C4)",
         call is not None and re.search(r"RenderTrafficLightCoronas\(\s*lpCoronaSubmissionInterface,\s*lCameraPosition,"
                                        r"\s*lCameraDirection\s*\)", call[1]) is not None),
        ("BrnTrafficEntityModule.h declares RenderTrafficLightCoronas (DWARF :1845)",
         re.search(r"void\s+RenderTrafficLightCoronas\(\s*BrnCoronaManager::BrnSubmissionInterface\*\s*\w+,\s*Vector3\s+"
                   r"\w+,\s*Vector3\s+\w+\s*\);", module_h) is not None),
        ("BrnTrafficLightManager.h declares RenderLightsForHull / RenderAllLightsToBeInStateForHull (DWARF :144 / :154)",
         re.search(r"void\s+RenderLightsForHull\(", manager_h) is not None
         and re.search(r"void\s+RenderAllLightsToBeInStateForHull\(", manager_h) is not None),
        ("CgsCamera.h declares GetFrustumPerspectiveVertices(Vector3*) const (DWARF :174)",
         re.search(r"void\s+GetFrustumPerspectiveVertices\(\s*Vector3\*\s*\w+\s*\)\s*const;", camera_h) is not None),
    ]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxtrafficlight_coronas", wiring(tree), numeric(tree), MANAGER_CHECKS + PASS_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
