"""FX-DIRECTOR2 (crash parity 2026-09-25): THE TIMER LEGS RUN IN THE CONSOLE'S ORDER.

  The console's DoUpdate @0x823F0AF8 snapshots the timers FIRST (BridgeTimers @0x823BD150, called at
  0x823F0DE4: accumulator reset + TimerStatusInterface::StoreTimers @0x828D7518) and applies the
  step's time-scale requests LAST (UpdateTimers @0x823BCFD0, called at 0x823F1CFC after
  DoUpdate_NetworkPostSim). So the director's request of step N (MainDirector::Update,
  SetTimestepMultiplier @0x82275148) is integrated by the world in step N+1. The PC ran UpdateTimers
  mid-step, between the world and the director, and took the snapshot inside DoUpdate_Director: every
  director request reached the world one step late -- on the h225 s80 crash the hard stop's 0.000125
  arrived on the crash's fourth frame, so the impact frame (197 -> 102 mph) ran at full dt.

Numeric: tests/FxDirector2TimerOrder.cpp runs the hard-stop scenario (1.0, then 0.0075 for 400 steps,
then 1.0) and a game-state request through the PRODUCTION timer primitives (CgsTimer.cpp,
CgsTimerRequestInterface.cpp, CgsTimerStatusInterface.cpp) in the leg order this runner reads out of the
revision's BrnGameModule::GameMain sub-step loop and DoUpdate_Director. On the old order the first
slowed world step is k+2 instead of k+1 and real time returns a step late (3 checks fail).
Wiring: where the snapshot and UpdateTimers sit, DoUpdate_Director's copy, the null-safe BridgeTimers,
no measurement toggle left, the retired F-P3-13 deferral.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_timer_order.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import REPO, Tree, definition, code_only, compile_and_run, report

GAME_CPP = "src/GameSource/Game/BrnGameModule.cpp"
TIMER_DIR = REPO / "src/GameShared/GameClasses/System/Timer"
TIMER_SOURCES = (TIMER_DIR / "CgsTimer.cpp", TIMER_DIR / "CgsTimerRequestInterface.cpp",
                 TIMER_DIR / "CgsTimerStatusInterface.cpp")
NUMERIC_CHECKS = 10


def squash(text):
    return re.sub(r"\s+", "", code_only(text))


def body(source, signature):
    try:
        return definition(source, signature)
    except ValueError:
        return ""


def sub_step_loop(source):
    """The GameMain sub-step loop, comments stripped: CreateStaticIOBuffers() .. the do-while tail."""
    game_main = code_only(body(source, "bool BrnGameModule::GameMain()"))
    start = game_main.find("CreateStaticIOBuffers();")
    end = game_main.find("while (liStep < miNumSimFramesRequired);")
    if start < 0 or end < 0:
        return ""
    return game_main[start:end]


def leg_order(source):
    """The order of the five timer-relevant legs in one sub-step, or (None, reason)."""
    loop = sub_step_loop(source)
    director = code_only(body(source, "void BrnGameModule::DoUpdate_Director(bool lbPostGui)"))
    if not loop or not director:
        return None, "GameMain's sub-step loop or DoUpdate_Director not found"
    marks = {
        "S": [m.start() for m in re.finditer(r"\bBridgeTimers\s*\(", loop)],
        "G": [m.start() for m in re.finditer(r"PreWorldUpdateStuntBringUp\s*\(", loop)],
        "W": [m.start() for m in re.finditer(r"lpState->Update\(\)\s*;", loop)],
        "D": [m.start() for m in re.finditer(r"DoUpdate_Director\(\s*false\s*\)\s*;", loop)],
        "U": [m.start() for m in re.finditer(r"\bUpdateTimers\(\)\s*;", loop)],
    }
    for leg in "GWDU":
        if len(marks[leg]) != 1:
            return None, f"leg {leg}: {len(marks[leg])} matches in the sub-step loop (want 1)"
    if len(marks["S"]) > 1:
        return None, f"{len(marks['S'])} BridgeTimers calls in the sub-step loop (want 0 or 1)"
    legs = sorted((pos[0], leg) for leg, pos in marks.items() if pos)
    order = "".join(leg for _, leg in legs)
    # A snapshot taken inside DoUpdate_Director (the old PC placement) comes before its publish.
    if re.search(r"\bBridgeTimers\s*\(", director):
        order = order.replace("D", "SD")
    if order.count("S") != 1:
        return None, f"order {order!r}: want exactly one snapshot per step"
    return order, ""


def numeric(tree):
    order, why = leg_order(tree.read(GAME_CPP))
    if order is None:
        print(f"[fxdirector2] leg order: NOT READ ({why}) -- the numeric test cannot run", flush=True)
        return None
    print(f"[fxdirector2] leg order read from the revision's GameMain: {order} "
          f"(console: SGWDU)", flush=True)
    inc = f'// GENERATED by run_fxdirector2_timer_order.py\nstatic const char kacOrder[] = "{order}";\n'
    return compile_and_run(Path(__file__).with_name("FxDirector2TimerOrder.cpp"),
                           "fxdirector2_timer_order.inc", inc, "fxdirector2_timer_order",
                           extra_sources=TIMER_SOURCES)


def wiring(tree):
    source = tree.read(GAME_CPP)
    loop = sub_step_loop(source)
    director = squash(body(source, "void BrnGameModule::DoUpdate_Director(bool lbPostGui)"))
    bridge = squash(body(source, "void BrnGameModule::BridgeTimers(BrnDirector::DirectorIO::InputBuffer* lpDirectorInput)"))

    snapshot = [m.start() for m in re.finditer(r"\bBridgeTimers\s*\(", loop)]
    first_leg = loop.find("DoUpdate_InputPreWorld(")
    yield ("GameMain: ONE BridgeTimers per sub-step, before the first leg (DoUpdate_InputPreWorld) -- the console's "
           "0x823F0DE4",
           len(snapshot) == 1 and 0 <= snapshot[0] < first_leg)
    timers = [m.start() for m in re.finditer(r"\bUpdateTimers\(\)\s*;", loop)]
    post_sim = loop.find("DoUpdate_NetworkPostSim(")
    retire = loop.find("GetTimerRequestInterface()->Clear();")
    yield ("GameMain: ONE UpdateTimers per sub-step, after DoUpdate_NetworkPostSim (the console's 0x823F1CFC) and "
           "before the retire that clears the game-state request slot it drains",
           len(timers) == 1 and 0 <= post_sim < timers[0] < retire)
    yield ("DoUpdate_Director copies the start-of-step snapshot into the director input and takes no snapshot of "
           "its own (no BridgeTimers call)",
           "BridgeTimers(" not in director
           and "if(!lbPostGui){lpDirectorInput->LockForWrite();*lpDirectorInput->GetTimerStatusInterface()="
               "mTimerStatusInterface;lpDirectorInput->UnlockForWrite();}" in director)
    yield ("BridgeTimers: reset + StoreTimers, and the copy half only when a director input is passed",
           bridge.startswith("voidBrnGameModule::BridgeTimers(BrnDirector::DirectorIO::InputBuffer*lpDirectorInput)"
                             "{mTimerRequestInterface.Clear();mTimerStatusInterface.StoreTimers(&mGameTimer,&mSimTimer);"
                             "if(lpDirectorInput!=0){"))
    yield ("no measurement toggle left in the main loop (BRN_FXD2_TIMER_ORDER_OLD / Fxd2TimerOrderOld)",
           "Fxd2TimerOrderOld" not in source and "BRN_FXD2_TIMER_ORDER_OLD" not in source)
    yield ("the F-P3-13 deferral note is retired ('the position moves with F-P3-1, not before it')",
           "the position moves with F-P3-1, not before it" not in source)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="b5-decomp revision to read the sources from (default: the working tree)")
    args = parser.parse_args()
    tree = Tree(args.rev)
    checks = list(wiring(tree))
    result = numeric(tree)
    sys.exit(report("fxdirector2_timer_order", checks, result, NUMERIC_CHECKS))


if __name__ == "__main__":
    main()
