"""crash parity FX-NETCRASH (2026-09-25), online hull set piece 1: the traffic module publishes its
network snapshot, and the snapshot reaches the network module.

Before this piece, the online host fired `mbActiveHullsValid` (BrnTrafficNetworkInterfaces.h:434)
on every frame it wanted to restart the traffic. TrafficManager::HandleSendingRestartTrafficMessages
reads GetActiveHulls(), and on PC nothing ever wrote the table. The console chain, every hop
checked here:

  1. TrafficEntityModule::GenerateNetworkUpdateEvents @0x827287A8, called every frame by
     PostPhysicsUpdate at 0x8274EEA0 (after UpdateEventStarts, before ProcessTrafficTypeRequests).
     It writes the active hull per race car, the divergence byte, the online hull broadcast and the
     data hash. The hash leg stays a named gate (Logger).
  2. OutputBuffer_PostPhysics::GetNetworkInterface(), the write half (0x82711AF0, baked 395).
  3. BridgeEntityModulesToOutput_PostPhysics leg 13 (0x827AF0D4..0x827AF0E4):
     out->SetTrafficNetworkOutputInterface(trafficOut->GetNetworkInterface()).
  4. UpdateOutputBuffer::Construct runs TrafficNetworkOutputInterface::Construct on the world copy
     (0x827CA280). Leg 13's operator= Appends into that queue.
  5. The traffic InputBuffer_PreScene::Construct (0x82761538). It binds the hull-sync INPUT queue
     that SetTrafficNetworkInputInterface Appends a peer's activations into, plus the read accessor
     GetTrafficNetworkInputInterface (0x82710C80, baked 163).

NUMERIC: the production GenerateNetworkUpdateEvents body is compiled against a member fixture and
linked with the production TrafficNetworkOutputInterface and Pvs bodies. The expected hull table
below is computed here from the console predicate:
    hull = 0xFFFF unless IsRaceCarActive(i) and dd > 100 and (p.y > 0.5 or dd > 40000),
where dd = x*x + z*z (vrlimi128 zeroes y, vmsum3fp128). The thresholds are dyn-init splats of
flt_820BA5C8 100.0, flt_820BA62C 0.5 and flt_8201C220 40000.0 (tools/re/findinit.py, x360rd.py).
Otherwise the hull is the Pvs cell 16*z + x of a 16x16 grid of 128 m cells at (-1024, -1024).

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxnetcrash_network_update.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import math
import re
import struct
import sys

sys.dont_write_bytecode = True
from fxgs_common import REPO, Tree, definition, code_only, compile_and_run, report, STRSTREAM_CPP

MODULE_CPP = "src/GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficEntityModule.cpp"
IO_CPP = "src/GameSource/World/EntityModules/TrafficEntityModule/BrnTrafficEntityModuleIO.cpp"
BRIDGE_CPP = "src/GameSource/World/Bridges/WorldBridgeEntityModulesToOutput.cpp"
WORLD_OUT_CPP = "src/GameSource/World/BrnWorldModuleIO_UpdateOutputBuffer.cpp"
NETOUT_CPP = "src/GameSource/World/EntityModules/TrafficEntityModule/SharedIO/BrnTrafficNetworkOutputInterface.cpp"
PVS_CPP = "src/SharedClasses/Traffic/BrnTrafficPvs.cpp"
GNUE = "void TrafficEntityModule::GenerateNetworkUpdateEvents("

NAN = float("nan")
# (active, x, y, z): one car per active-race-car slot, each on a different arm of the predicate.
CARS = [
    (1, 500.0, 1.0, 300.0),     # far, above 0.5 m                     -> a hull
    (0, 500.0, 1.0, 500.0),     # inactive                              -> 0xFFFF
    (1, 5.0, 3.0, 5.0),         # dd = 50, within 10 m of the origin    -> 0xFFFF
    (1, 50.0, 0.25, 50.0),      # dd = 5000, y 0.25, not beyond 200 m   -> 0xFFFF
    (1, 150.0, 0.25, 150.0),    # dd = 45000 > 40000 although y < 0.5   -> a hull
    (1, 8.0, 2.0, 8.0),         # dd = 128 > 100, y 2                   -> a hull
    (1, NAN, 5.0, 0.0),         # NaN fails every compare               -> 0xFFFF
    (1, 10.0, 5.0, 0.0),        # dd == 100 exactly: not > 100          -> 0xFFFF
]


def f32(x):
    return struct.unpack("<f", struct.pack("<f", x))[0]


def bits(x):
    return struct.unpack("<I", struct.pack("<f", x))[0]


def console_hull(active, x, y, z):
    if not active:
        return 0xFFFF
    dd = f32(f32(x * x) + f32(z * z))
    if not dd > 100.0:
        return 0xFFFF
    if not (y > 0.5 or dd > 40000.0):
        return 0xFFFF
    cx = min(max(int(f32((x + 1024.0) * f32(1.0 / 128.0))), 0), 15)
    cz = min(max(int(f32((z + 1024.0) * f32(1.0 / 128.0))), 0), 15)
    return 16 * cz + cx


def cases_inc():
    lines = ["// generated by run_fxnetcrash_network_update.py",
             "struct CarCase { u32 active; u32 pos[3]; };",
             "static const CarCase KA_CARS[8] = {"]
    for active, x, y, z in CARS:
        lines.append(f"    {{ {active}u, {{ 0x{bits(x):08X}u, 0x{bits(y):08X}u, 0x{bits(z):08X}u }} }},")
    lines.append("};")
    hulls = [console_hull(*car) for car in CARS]
    assert sorted(set(hulls)) != [0xFFFF], "the cases must publish at least one real hull"
    lines.append("static const u16 KA_EXPECTED_HULLS[8] = { " + ", ".join(f"{h}u" for h in hulls) + " };")
    return "\n".join(lines) + "\n"


NUMERIC_CHECKS = 16


def numeric(tree):
    module = tree.read(MODULE_CPP)
    try:
        body = definition(module, GNUE)
    except ValueError as error:
        print("NUMERIC: cannot build -- production body absent: " + str(error))
        return None
    body = body.replace("TrafficEntityModule::GenerateNetworkUpdateEvents", "NetFixture::GenerateNetworkUpdateEvents", 1)
    body = re.sub(r"const\s+BrnTrafficIO::InputBuffer_PostPhysics\*\s*lpInput", "const FakeInput* lpInput", body, 1)
    body = re.sub(r"BrnTrafficIO::OutputBuffer_PostPhysics\*\s*lpOutput", "FakeOutput* lpOutput", body, 1)
    return compile_and_run(Path(__file__).with_name("FxNetcrashNetworkUpdate.cpp"), "gnue_body.inc", body,
                           "FxNetcrashNetworkUpdate",
                           extra_sources=[STRSTREAM_CPP, REPO / NETOUT_CPP, REPO / PVS_CPP],
                           extra_files={"network_cases.inc": cases_inc()})


def body_of(source, signature):
    try:
        return code_only(definition(source, signature))
    except ValueError:
        return ""


def wiring(tree):
    module = tree.read(MODULE_CPP)
    post = body_of(module, "void TrafficEntityModule::PostPhysicsUpdate(")
    call = post.find("GenerateNetworkUpdateEvents(lpInput, lpOutput);")
    answer = post.find("ProcessTrafficTypeRequests(")

    io = tree.read(IO_CPP)
    write_half = body_of(io, "TrafficNetworkOutputInterface* OutputBuffer_PostPhysics::GetNetworkInterface()\n")
    if not write_half:
        write_half = body_of(io, "TrafficNetworkOutputInterface* OutputBuffer_PostPhysics::GetNetworkInterface()\r\n")
    construct = body_of(io, "void InputBuffer_PreScene::Construct()")
    getter = body_of(io, "const TrafficNetworkInputInterface* InputBuffer_PreScene::GetTrafficNetworkInputInterface() const")

    bridge = body_of(tree.read(BRIDGE_CPP), "void BridgeEntityModulesToOutput_PostPhysics(")
    world = body_of(tree.read(WORLD_OUT_CPP), "void UpdateOutputBuffer::Construct()")
    vault = world.find("mAttribSysVaultRequestInterface.mRequestQueue.Clear();")
    net = world.find("mTrafficNetworkOutputInterface.Construct();")
    types = world.find("mTrafficTypeResponseQueue.Construct();")

    order = [m.group(0) for m in re.finditer(
        r"CgsModule::IOBuffer::Construct\(\)|mTrafficNetworkInputInterface\.Construct\(\)|mTimerStatusInterface\.Clear\(\)"
        r"|mActiveRaceCarOutputInterface\.Clear\(\)|mGlobalRaceCarOutputInterface\.Clear\(\)", construct)]
    return [
        ("PostPhysicsUpdate calls GenerateNetworkUpdateEvents(lpInput, lpOutput) before ProcessTrafficTypeRequests (0x8274EEA0)",
         0 <= call < answer),
        ("OutputBuffer_PostPhysics::GetNetworkInterface() write half, write-locked (0x82711AF0, baked 395)",
         "IsBufferLockedForWriting()" in write_half and "return &mNetworkInterface;" in write_half),
        ("world bridge leg 13: out->SetTrafficNetworkOutputInterface(trafficOut->GetNetworkInterface()) (0x827AF0D4..0x827AF0E4)",
         re.search(r"lpOutputBuffer\s*->\s*SetTrafficNetworkOutputInterface\(\s*lpTrafficOutput_PostPhysics\s*->\s*"
                   r"GetNetworkInterface\(\)\s*\)", bridge) is not None),
        ("UpdateOutputBuffer::Construct constructs mTrafficNetworkOutputInterface between the vault queue and "
         "the traffic-type queue (0x827CA280)", 0 <= vault < net < types),
        ("traffic InputBuffer_PreScene::Construct, store for store (0x82761538): IOBuffer, network, timer, "
         "active, global, network",
         order == ["CgsModule::IOBuffer::Construct()", "mTrafficNetworkInputInterface.Construct()",
                   "mTimerStatusInterface.Clear()", "mActiveRaceCarOutputInterface.Clear()",
                   "mGlobalRaceCarOutputInterface.Clear()", "mTrafficNetworkInputInterface.Construct()"]),
        ("InputBuffer_PreScene::GetTrafficNetworkInputInterface() const, read-locked (0x82710C80, baked 163)",
         "IsBufferLockedForReading()" in getter and "return &mTrafficNetworkInputInterface;" in getter),
    ]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxnetcrash_network_update", wiring(tree), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
