"""FX-FPUMAX call-site group A: the rw::math::fpu Min / Max / Clamp sites whose console form is the fsel
inline in a DIFFERENT operand order than the PC spelling (or not the fsel at all), plus the PC input leaf's
axis clamp. The shipped statements are EXTRACTED from the production files and compiled, with the shipped
scalar_operation.h, into small harness functions (fxfpumax_order_sites.inl); FxFpumaxOrderSites.cpp checks
them against the console forms read off ARTIST:

  BehaviourGameplayExternal::Update  0x82241C4C/0x82241C54  1 - Clamp(t, 0, 1)            (.cpp:440)
                                     0x82241F40/4C/58       Max(f, Clamp(s, 0, 0.8))
  Looker::Zoom                       0x82222EE4..0x82222F08 ble -> Min(vd, t-F) ; else Max(-vd, t-F)
  KeyAnimController::Update          0x8223D190/0x8223D194  fcmpu ; bge keeps 1.0
  KeyAnimController::UpdateFocus     0x821F7FF0 Min(1, I) ; 0x821F8000 Max(0, n-f) ; 0x821F8010..24
  WheelStateMachine::Update          0x82294058             Max(0, x)
  CgsInputPadsPC ClampAxis           InputPads::FillRawData 0x828E7484/0x828E748C Clamp(s, -1, 1)

usage: run_fxfpumax_order_sites.py [--rev <b5-decomp git revision>]
    default   the working tree's five source files
    --rev R   the five source files as of revision R (e.g. the fix commit's parent, to show the pre-fix
              spellings fail); scalar_operation.h always comes from the working tree.
"""
from pathlib import Path
import argparse
import re
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
from run_showtime_impulse import definition, settings, REPO, WORKFLOW

FILES = {
    "external": "src/GameSource/Director/Camera/Behaviours/BrnBehaviourGameplayExternal.cpp",
    "looker": "src/GameSource/Director/Camera/Utils/BrnLooker.cpp",
    "keyanim": "src/GameSource/Director/Shots/ShotControllers/BrnKeyAnimController.cpp",
    "wheel": "src/GameSource/Effects/Wheel/WheelStateMachine.cpp",
    "pads": "src/GameShared/GameClasses/System/Input/PC/CgsInputPadsPC.cpp",
}


def statement_end(text, start):
    """Index just past the first `;` at bracket depth 0 from `start`, skipping comments and literals."""
    depth = 0
    i = start
    while i < len(text):
        if text.startswith("//", i):
            i = text.index("\n", i)
            continue
        if text.startswith("/*", i):
            i = text.index("*/", i) + 2
            continue
        c = text[i]
        if c == '"':
            i = re.compile(r'"(?:\\.|[^"\\])*"').match(text, i).end()
            continue
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == ";" and depth == 0:
            return i + 1
        i += 1
    raise ValueError("unterminated statement")


def statement(text, pattern, what):
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"[fxfpumax] extraction failed: {what} ({pattern!r}) not found")
    return text[match.start():statement_end(text, match.start())]


def span(text, start_anchor, end_anchor, what, include_end_statement=True):
    start = text.find(start_anchor)
    if start < 0:
        raise SystemExit(f"[fxfpumax] extraction failed: {what} start {start_anchor!r} not found")
    end = text.find(end_anchor, start)
    if end < 0:
        raise SystemExit(f"[fxfpumax] extraction failed: {what} end {end_anchor!r} not found")
    return text[start:statement_end(text, end) if include_end_statement else end]


def generate(sources):
    external, looker, keyanim, wheel, pads = (sources[k] for k in ("external", "looker", "keyanim", "wheel", "pads"))
    grounded = statement(external, r"const f32 lfGrounded\s*=", "GameplayExternal lfGrounded")
    impact = statement(external, r"mfImpactShakeFactor\s*=\s*rw::math::fpu::Max\(\s*mfImpactShakeFactor",
                       "GameplayExternal mfImpactShakeFactor")
    step = span(looker, "f32 lfStep;", "lfFOV += lfStep;", "Looker::Zoom step")
    parameter = span(keyanim, "// Seek the take.", "mPlaybackTake.SetParameter(", "KeyAnimController::Update parameter",
                     include_end_statement=False)
    band = span(keyanim, "lfBlurriness = rw::math::fpu::Min(", "lfFocusEndDistanceMeters =", "UpdateFocus band")
    dof_constants = [statement(keyanim, rf"static const f32 {name}\s*=", name)
                     for name in ("KI_DEPTH_OF_FIELD_MAX_FALLOFF_DISTANCE", "KI_DEPTH_OF_FIELD_MIN_FALLOFF_DISTANCE")]
    reverse = statement(wheel, r"const f32 lfReverseThrustScale\s*=", "WheelStateMachine lfReverseThrustScale")
    wheel_constants = [statement(wheel, rf"const f32 {name}\s*=", name)
                       for name in ("KF_WHEEL_REVERSE_THRUST_CUTOFF_SPEED", "KF_WHEEL_REVERSE_THRUST_SCALE")]
    clamp_axis = definition(pads, "    f32 ClampAxis(f32 lfValue)")
    return "\n".join([
        "// GENERATED by run_fxfpumax_order_sites.py -- every body below is text extracted from the shipped sources.",
        "namespace fxfpumax_sites",
        "{",
        "typedef float f32;",
        *dof_constants,
        *wheel_constants,
        "f32 Grounded(f32 lfTimeInAir)",
        "{",
        "    struct { f32 mfTimeInAir; } lrCarState = { lfTimeInAir };",
        grounded,
        "    return lfGrounded;",
        "}",
        "f32 ImpactShake(f32 mfImpactShakeFactor, f32 lfImpactShake)",
        "{",
        impact,
        "    return mfImpactShakeFactor;",
        "}",
        "struct LookerFixture",
        "{",
        "    f32 mfMaxFOVVelocity;",
        "    f32 mfTargetFOV;",
        "    f32 Step(f32 lfFOV, f32 lfTimeStep, f32* lpfFOVOut)",
        "    {",
        step,
        "        *lpfFOVOut = lfFOV;",
        "        return lfStep;",
        "    }",
        "};",
        "struct KeyAnimFixture",
        "{",
        "    f32 mfPlaybackTimer;",
        "    f32 mfLength;",
        "    f32 GetLength() const { return mfLength; }",
        "    f32 Parameter()",
        "    {",
        parameter,
        "        return lfParameter;",
        "    }",
        "};",
        "void FocusBand(f32 lfBlurIntensity, f32 lfNearFocus, f32 lfFarFocus, f32 lfFalloffMeters, f32* lpfOut)",
        "{",
        "    f32 lfBlurriness = 0.0f, lfFocusStartDistanceMeters = 0.0f, lfPerfectFocusStartDistanceMeters = 0.0f;",
        "    f32 lfPerfectFocusEndDistanceMeters = 0.0f, lfFocusEndDistanceMeters = 0.0f;",
        band,
        "    lpfOut[0] = lfBlurriness;",
        "    lpfOut[1] = lfFocusStartDistanceMeters;",
        "    lpfOut[2] = lfPerfectFocusStartDistanceMeters;",
        "    lpfOut[3] = lfPerfectFocusEndDistanceMeters;",
        "    lpfOut[4] = lfFocusEndDistanceMeters;",
        "}",
        "f32 ReverseThrustScale(f32 lfWheelSpeed)",
        "{",
        reverse,
        "    return lfReverseThrustScale;",
        "}",
        clamp_axis,
        "}",
        "",
    ])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="b5-decomp revision to take the five source files from")
    args = parser.parse_args()
    if args.rev:
        sources = {key: subprocess.run(["git", "-C", str(REPO), "show", f"{args.rev}:{path}"], check=True,
                                       capture_output=True).stdout.decode("utf-8") for key, path in FILES.items()}
    else:
        sources = {key: (REPO / path).read_text(encoding="utf-8") for key, path in FILES.items()}
    with tempfile.TemporaryDirectory(prefix="brn_fxfpumax_sites_") as directory:
        output = Path(directory)
        (output / "fxfpumax_order_sites.inl").write_text(generate(sources), encoding="utf-8")
        includes = [output] + [WORKFLOW / path for path in settings("msvc_includes.txt")]
        command = ("cl " + " ".join(settings("msvc_flags.txt")) + " "
                   + " ".join(f'/I"{path}"' for path in includes) + " "
                   + f'"{Path(__file__).with_name("FxFpumaxOrderSites.cpp")}"'
                   + " /Fe:regression.exe /link /OPT:REF")
        script = output / "run.cmd"
        script.write_text('@echo off\ncall "' + str(WORKFLOW / "tools/build/msvc_env.bat")
                          + '" >nul 2>&1\nif errorlevel 1 exit /b 1\n' + command
                          + '\nif errorlevel 1 exit /b 1\nregression.exe\nexit /b %ERRORLEVEL%\n',
                          encoding="utf-8", newline="\r\n")
        sys.exit(subprocess.run(["cmd", "/c", str(script)], cwd=output).returncode)


if __name__ == "__main__":
    main()
