"""FX-DIRECTOR2 (crash parity 2026-09-25): Looker::Zoom's depth-of-field blurriness ramp rates and its one fused write.

  Looker::Zoom @0x82222A78 ramps the camera's blurriness toward 0 (assessing / on target) or 1 (moving) at
  flt_82CDAD18 / flt_82CDAD1C / flt_82CDAD20 = 0.1 / 0.1 / 0.15 a frame, with one fmadds (0x82222F48). The PC carried
  the three rates as 0.0f "ungroundable" placeholders. The .rdata reader reads them, and they have one lfs reader each
  and no writer. So every looker (the bystander, rig, gyro and spiralling-death cameras) froze the blurriness. The
  write was also a separate multiply and add.

Numeric: tests/FxDirector2LookerDofRamp.cpp compiles the PRODUCTION constants and write -- 6 checks.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_looker_dof_ramp.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import Tree, code_only, compile_and_run, report

LOOKER_CPP = "src/GameSource/Director/Camera/Utils/BrnLooker.cpp"
CONSTANTS = r"const\s+f32\s+KF_DOF_(?:UNBLUR|HOLD|BLUR)_RATE\s*=\s*[^;]+;"
WRITE = r"lrCamera\.GetDepthOfField\(\)\.SetBlurriness\([^;]*\);"
NUMERIC_CHECKS = 6


def numeric(tree):
    source = code_only(tree.read(LOOKER_CPP))
    constants = re.findall(CONSTANTS, source)
    writes = re.findall(WRITE, source)
    if len(constants) != 3 or len(writes) != 1:
        print("NUMERIC: the revision's BrnLooker.cpp lacks the three rates or its one blurriness write")
        return None
    return compile_and_run(Path(__file__).with_name("FxDirector2LookerDofRamp.cpp"), "fxd2_dof_write.inc",
                           "// GENERATED by run_fxdirector2_looker_dof_ramp.py\n" + writes[0] + "\n",
                           "FxDirector2LookerDofRamp",
                           extra_files={"fxd2_dof_const.inc": "\n".join(constants) + "\n"})


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_looker_dof_ramp", [], numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
