"""FX-DIRECTOR2 (crash parity 2026-09-25, CC-12): MomentSelector::Update's max-active-moments rebalance.

  MomentSelector::Update @0x82239FC0 ends with a rebalance (0x8223A41C..0x8223A660) for a selector with a max-active
  limit. It un-inhibits the best held-back moments while under budget, and swaps the best held-back moment in for the
  worst idle one while any moment waits on its conditions. The pickers are PickBestInhibitedMoment @0x8221C028 and
  PickWorstUninhibitedMoment @0x8221C358. ArbStateCrashing::Construct @0x82259EA0 sets a limit of ONE on every crash
  (0x82259FBC). The PC gated the tail on the stale premise that nothing sets a limit, and the pickers had no body. So
  the second tumbling moment Prepare starts inhibited could never swap in, and a moment the (E) arm inhibited never
  came back during the crash.

Wiring: Update's tail calls both pickers. Numeric: tests/FxDirector2MomentSelectorRebalance.cpp compiles the PRODUCTION
Update + both pickers (lifted out of the TU with their constants) against FakeMoments -- 16 checks.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_moment_selector_rebalance.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys
import tempfile

sys.dont_write_bytecode = True
from fxgs_common import Tree, code_only, definition, compile_and_run, report

SELECTOR_CPP = "src/GameSource/Director/MomentController/BrnMomentSelector.cpp"
SOURCES = ("src/GameShared/GameClasses/Development/CgsStrStream.cpp",)
HEADERS = (
    "src/GameSource/Director/MomentController/BrnMomentSelector.h",
    "src/GameSource/Director/MomentController/BrnMoment.h",
    "src/GameSource/Director/MomentController/BrnMomentController.h",
    "src/GameShared/GameClasses/Containers/CgsArray.h",
)
FUNCTIONS = (
    "void MomentSelector::Update(",
    "bool MomentSelector::PickBestInhibitedMoment(",
    "bool MomentSelector::PickWorstUninhibitedMoment(",
)
CONSTANTS = (r"const\s+f32\s+KF_PICK_ZERO\s*=\s*[^;]+;", r"const\s+f32\s+KF_PICK_ONE\s*=\s*[^;]+;")
NUMERIC_CHECKS = 16


def wiring(tree):
    source = tree.read(SELECTOR_CPP)
    try:
        update = re.sub(r"\s+", "", code_only(definition(source, FUNCTIONS[0])))
    except ValueError:
        update = ""
    yield ("MomentSelector::Update's rebalance calls PickBestInhibitedMoment and PickWorstUninhibitedMoment "
           "(0x8223A454 / 0x8223A5CC)",
           "PickBestInhibitedMoment(&" in update and "PickWorstUninhibitedMoment(&" in update)


def numeric(tree):
    source = tree.read(SELECTOR_CPP)
    try:
        bodies = [definition(source, signature) for signature in FUNCTIONS]
    except ValueError:
        print("NUMERIC: the revision's BrnMomentSelector.cpp lacks the pickers")
        return None
    constants = [re.search(pattern, code_only(source)) for pattern in CONSTANTS]
    if not all(constants):
        print("NUMERIC: the revision's BrnMomentSelector.cpp lacks the pickers' constants")
        return None
    try:
        diag = definition(source, "void BrnDiag_Rebalance(")   # the [DIAG] helper the tail calls (NOT X360)
    except ValueError:
        diag = ""
    inc = ("// GENERATED by run_fxdirector2_moment_selector_rebalance.py\nnamespace\n{\n"
           + "\n".join(m.group(0) for m in constants) + "\n" + diag + "\n}\n" + "\n\n".join(bodies) + "\n")
    shadow = {relative: tree.read(relative) for relative in HEADERS} if tree.rev is not None else None
    with tempfile.TemporaryDirectory(prefix="brn_fxd2_rebalance_") as directory:
        extra = []
        for relative in SOURCES:
            target = Path(directory) / Path(relative).name
            target.write_text(tree.read(relative), encoding="utf-8")
            extra.append(target)
        return compile_and_run(Path(__file__).with_name("FxDirector2MomentSelectorRebalance.cpp"), "fxd2_rebalance.inc",
                               inc, "FxDirector2MomentSelectorRebalance", shadow=shadow, extra_sources=tuple(extra))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_moment_selector_rebalance", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
