"""FX-CRASHVFX (crash parity 2026-09-24, item 7 render half): the native simple particles reach the screen.

A simple particle (impact smoke, crash impact dust, the ten skid-smoke surfaces) is a 48-byte spawn record;
everything visible about it is computed by the particle job at render time. Before this fix every link of
that chain was missing: CB4ParticleBank::Render @0x8291E600 and ShadedRotatingRenderMethod::BuildQuad
@0x8291E150 were asserting stubs, SimpleParticleVertexBufferBuilder::BuildDispatchData @0x8291F870 had no
body, the particle job's simple arm and RenderQuarterResParticles' two Dispatch calls were announced, the
Im3dSmokeRenderer was a 12-byte placeholder, and BrnSimpleParticleRenderer was an unmounted misshape.

  1. WIRING -- BeginParticleRenderJob runs the simple job (two BuildDispatchData passes split by
     SetPreLionCount, under the particle manager's lock); RenderQuarterResParticles dispatches both halves
     around the Lion pass; Prepare constructs the smoke renderer and the simple renderer; Dispatch draws a
     Xenos QUADLIST per batch through a blend table indexed Normal / Subtractive / Additive; the smoke
     renderer builds TWO program pairs and resolves its four handles.
  2. NUMERIC -- tests/FxCrashVfxSimpleRender.cpp compiles the PRODUCTION Render / BuildQuad / Write /
     BuildDispatchData (+ the real EffectsVertexBuffer.cpp) and checks every vertex against the CONSOLE'S
     OWN OUTPUT for seven seeded inputs (tests/FxCrashVfxSimpleRenderData.h, generated by executing the
     real instruction words in a VMX emulator), plus the builder's lifetime gate, crash-bank flag, batch
     record and the batch array's pre-Lion split -- and (FX-GATE NaN sweep) a NaN last-spawn time SKIPS its
     bank, regular and crash (`fcmpu ; bge` 0x8291F944 / 0x8291F974).

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxcrashvfx_simple_render.py [--rev <b5 rev>]
                                                                               [--root <shadow tree root>]
"""
from pathlib import Path
import argparse
import re
import sys
import tempfile

sys.dont_write_bytecode = True
from fxgs_common import REPO, Tree, body_or_empty, code_only, compile_and_run, report

RENDER_CPP = "src/GameSource/Effects/Particles/Native/BrnSimpleParticleArray_CB4ParticleBank_Render.cpp"
QUAD_CPP = "src/GameSource/Effects/Particles/Native/ShadedRotatingRenderMethod.cpp"
VERTEX_CPP = "src/GameSource/Effects/Particles/Native/BrnNativeParticleVertex.cpp"
EVB_CPP = "src/GameSource/Effects/Particles/EffectsVertexBuffer.cpp"
HEADERS = [
    "src/GameSource/Effects/Particles/Native/BrnSimpleParticleArray.h",
    "src/GameSource/Effects/Particles/Native/ShadedRotatingRenderMethod.h",
    "src/GameSource/Effects/Particles/Native/BrnNativeParticleVertex.h",
    "src/GameSource/Effects/Particles/Native/BrnSimpleParticleBatch.h",
    "src/GameSource/Effects/Particles/EffectsVertexBuffer.h",
]
MODULE_CPP = "src/GameSource/Effects/Particles/ParticleModule.cpp"
LIFECYCLE_CPP = "src/GameSource/Effects/Particles/ParticleModule_Lifecycle.cpp"
MODULE_H = "src/GameSource/Effects/Particles/ParticleModule.h"
RENDERER_CPP = "src/GameSource/Effects/Particles/Native/BrnSimpleParticleRenderer.cpp"
SMOKE_CPP = "src/GameSource/Effects/Particles/Native/BrnIm3dSmokeRenderer.cpp"

NUMERIC_CHECKS = 44   # 7 cases x 5 + 9 builder checks (two of them the NaN bank skips)


class RootTree(Tree):
    def __init__(self, rev=None, root=None):
        super().__init__(rev)
        self.root = Path(root) if root else None

    def read(self, relative):
        if self.root is not None and (self.root / relative).exists():
            return (self.root / relative).read_text(encoding="utf-8-sig")
        return super().read(relative)


def wiring(tree):
    module = tree.read(MODULE_CPP).replace("\r\n", "\n")
    job = body_or_empty(module, "    void ParticleModule::BeginParticleRenderJob(")
    first = job.find("BuildDispatchData(", job.find("mVertexBufferManagerParticles.Lock()"))
    split = job.find("SetPreLionCount()", first)
    second = job.find("BuildDispatchData(", split)
    yield ("BeginParticleRenderJob runs the simple job: lock, BuildDispatchData({3..12}), SetPreLionCount, "
           "BuildDispatchData({1,2}), unlock (ParticleRenderJob::RenderSimpleParticles 0x8291DE88)",
           first > 0 and split > first and second > split
           and "mVertexBufferManagerParticles.UnLock()" in job[second:]
           and "eRenderDataFlagRenderSimple" in job
           and re.search(r"\{\s*3u,\s*4u,\s*5u,\s*6u,\s*7u,\s*8u,\s*9u,\s*10u,\s*11u,\s*12u\s*\}", module) is not None
           and re.search(r"\{\s*1u,\s*2u\s*\}", module) is not None)

    quarter = body_or_empty(module, "    void ParticleModule::RenderQuarterResParticles(")
    lion = quarter.find("cLionFX::Dispatch(")
    yield ("RenderQuarterResParticles dispatches [0, preLion) BEFORE the Lion pass and [preLion, count) "
           "AFTER it (0x82294B64 / 0x82294C04)",
           lion > 0 and quarter.count("mSimpleParticleRenderer.Dispatch(") == 2
           and quarter.find("mSimpleParticleRenderer.Dispatch(") < lion
           and quarter.rfind("mSimpleParticleRenderer.Dispatch(") > lion
           and "GetPreLionCount()" in quarter and "LogNotReconstructed" not in quarter)

    lifecycle = tree.read(LIFECYCLE_CPP).replace("\r\n", "\n")
    prepare = body_or_empty(lifecycle, "bool ParticleModule::Prepare(")
    yield ("ParticleModule::Prepare constructs the smoke renderer (0x8229C0D0) and the simple renderer "
           "over it (0x8229C2A4)",
           "mSmokeRenderer.Construct(" in prepare
           and "mSimpleParticleRenderer.Construct(mpHeapMalloc, &mSmokeRenderer)" in prepare)

    header = code_only(tree.read(MODULE_H))
    yield ("ParticleModule::mSmokeRenderer is a BrnGraphics::Im3dSmokeRenderer, not a ContainedInterface",
           re.search(r"BrnGraphics::Im3dSmokeRenderer\s+mSmokeRenderer\s*;", header) is not None)

    renderer = tree.read(RENDERER_CPP).replace("\r\n", "\n")
    dispatch = body_or_empty(renderer, "    void BrnSimpleParticleRenderer::Dispatch(")
    yield ("BrnSimpleParticleRenderer::Dispatch draws one Xenos QUADLIST (13) per batch, blend table "
           "{Standard, Subtractive, Additive} (0x8228CA18)",
           "D3DDevice_DrawVertices(" in dispatch and "KU_XENOS_QUADLIST" in dispatch
           and re.search(r"KU_XENOS_QUADLIST\s*=\s*13u", renderer) is not None
           and re.search(r"mpStandardBlend,\s*mpSubtractiveBlend,\s*mpAdditiveBlend", dispatch) is not None
           and "shadow::Device::SetState(" in dispatch and "shadow::Device::SetResource(" in dispatch)

    smoke = tree.read(SMOKE_CPP).replace("\r\n", "\n")
    construct = body_or_empty(smoke, "    void Im3dSmokeRenderer::Construct(")
    yield ("Im3dSmokeRenderer::Construct uploads TWO program pairs and resolves gOffset / gScale / "
           "gDepthConversion / gDepthFadeConstants (0x82295260)",
           all(name in construct for name in ('"gOffset"', '"gScale"', '"gDepthConversion"',
                                             '"gDepthFadeConstants"'))
           and re.search(r"lauPixelProgramSize,\s*2\s*\)", construct) is not None)


def numeric(tree):
    texts = {path: tree.read(path) for path in (RENDER_CPP, QUAD_CPP, VERTEX_CPP, EVB_CPP)}
    render = texts[RENDER_CPP].replace("\r\n", "\n")
    missing = []
    if "void SimpleParticleVertexBufferBuilder::BuildDispatchData(" not in render:
        missing.append("SimpleParticleVertexBufferBuilder::BuildDispatchData")
    if "NativeParticleVertex::VertexIterator& lrIterator" not in render:
        missing.append("CB4ParticleBank::Render (still the asserting stub)")
    if "lpaPositions" not in texts[QUAD_CPP]:
        missing.append("ShadedRotatingRenderMethod::BuildQuad (still the asserting stub)")
    if missing:
        print("NUMERIC: cannot build -- production bodies absent: " + "; ".join(missing))
        return None
    shadow = {path: tree.read(path) for path in HEADERS}
    with tempfile.TemporaryDirectory(prefix="brn_fxcv_src_") as directory:
        sources = []
        for path, text in texts.items():
            target = Path(directory) / Path(path).name
            target.write_text(text, encoding="utf-8")
            sources.append(target)
        return compile_and_run(Path(__file__).with_name("FxCrashVfxSimpleRender.cpp"), "fxcrashvfx_render.inc",
                               "// (the production sources are separate TUs)\n", "FxCrashVfxSimpleRender",
                               shadow=shadow, extra_sources=tuple(sources))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", default=None, help="b5 revision to test (default: the working tree)")
    parser.add_argument("--root", default=None, help="a shadow tree root whose src/ files take precedence")
    args = parser.parse_args()
    tree = RootTree(args.rev, args.root)
    checks = list(wiring(tree))
    result = numeric(tree)
    return report("run_fxcrashvfx_simple_render", checks, result, NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
