"""FX-DIRECTOR2 (crash parity 2026-09-25): MomentPlayerJumping, the jump moment (type 7) -- allocated, INERT ON RETAIL.

  ArbStateRoaming::Construct @0x82259C00 registers {7, 0}, so the console allocates the jump moment and ticks it on
  every roaming frame. The PC's MomentController::NewMoment returned TRUE for type 7 with the handle unallocated (a
  GATE), so Roaming's selector held two moments where the console holds three. On the console the moment never
  leaves SEARCHING: its third gate is MainDirector::mbAllowJumpMoment, which Construct seeds false (0x8225B97C) and
  nothing in the image writes again. The retail path -- Construct, Prepare's eleven bank shots and the clamped ice
  ShotList, SEARCHING's landing cooldown and three gates, Release -- is re-derived and reads the record BY NAME. The
  camera side behind the gate (the collections' Prepare / HasFailed / CanSwitchToMeNow, UpdateCamera @0x8223AB78)
  is a LOUD trap: announced once in the game log, asserted every time.

Numeric: tests/FxDirector2PlayerJumping.cpp includes the revision's PRODUCTION BrnMomentPlayerJumping.cpp and runs it
against recording stand-ins for its leaves (28 checks). Wiring: the exe mounts the TU, and NewMoment allocates type 7.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_player_jumping.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys
import tempfile

sys.dont_write_bytecode = True
from fxgs_common import WORKFLOW, Tree, code_only, definition, compile_and_run, report

JUMPING_CPP = "src/GameSource/Director/MomentController/Moments/BrnMomentPlayerJumping.cpp"
CONTROLLER_CPP = "src/GameSource/Director/MomentController/BrnMomentController.cpp"
# The shared-info record holds a VehicleInfo by value, whose RaceCarState constructor calls Clear().
SOURCES = ("src/GameSource/Physics/VehicleManager/SharedIO/BrnVehicleEvents.cpp",)
HEADERS = (
    "src/GameSource/Director/MomentController/Moments/BrnMomentPlayerJumping.h",
    "src/GameSource/Director/MomentController/BrnMoment.h",
    "src/GameSource/Director/MomentController/BrnMomentSharedInfo.h",
    "src/GameSource/Director/Camera/BrnBehaviourManager.h",
    "src/GameSource/Director/Camera/BrnBehaviourParameterBank.h",
    "src/GameSource/Director/Camera/Behaviours/BehaviourRig.h",
    "src/GameSource/Director/Camera/Behaviours/BehaviourBystanderCam.h",
    "src/GameSource/Director/Camera/Behaviours/BrnBehaviourInterpolate.h",
    "src/GameSource/Director/Camera/Camera.h",
    "src/GameSource/Director/Camera/BrnCameraEffects.h",
    "src/GameSource/Director/Camera/BrnCameraState.h",
    "src/GameSource/Director/BrnDirectorResourceManager.h",
    "src/GameSource/Director/DirectorModule/BrnDirectorGameState.h",
    "src/GameSource/AttribSys/Generated/classes/shotgroup.h",
    "src/GameShared/GameClasses/Containers/CgsArray.h",
)
BUILD_BAT = WORKFLOW / "tools/build/build_game_exe.bat"
NUMERIC_CHECKS = 28


def wiring(tree):
    bat = BUILD_BAT.read_text(encoding="utf-8", errors="replace") if BUILD_BAT.exists() else ""
    yield ("the exe mounts MomentController\\Moments\\BrnMomentPlayerJumping.cpp (tools/build/build_game_exe.bat)",
           'echo "%SRC%\\GameSource\\Director\\MomentController\\Moments\\BrnMomentPlayerJumping.cpp"' in bat)
    try:
        new_moment = re.sub(r"\s+", "", code_only(definition(tree.read(CONTROLLER_CPP),
                                                             "bool MomentController::NewMoment(")))
    except ValueError:
        new_moment = ""
    yield ("MomentController::NewMoment allocates type 7 (jpt_822558C4 case 7: AllocateVoid<MomentPlayerJumping> "
           "@0x82252DB8), ungated", "caseMoment::E_MOMENT_PLAYER_JUMPING:lVoidHandle=mMomentPool.AllocateVoid<"
           "MomentPlayerJumping>();break;" in new_moment)


def numeric(tree):
    jumping = tree.read(JUMPING_CPP)
    texts = {relative: tree.read(relative) for relative in SOURCES}
    if not jumping or not all(texts.values()):
        print("NUMERIC: the revision lacks the jump moment's TU or its leaves")
        return None
    shadow = {relative: tree.read(relative) for relative in HEADERS} if tree.rev is not None else None
    with tempfile.TemporaryDirectory(prefix="brn_fxd2_pjump_") as directory:
        extra = []
        for relative, text in texts.items():
            target = Path(directory) / Path(relative).name
            target.write_text(text, encoding="utf-8")
            extra.append(target)
        return compile_and_run(Path(__file__).with_name("FxDirector2PlayerJumping.cpp"), "fxd2_player_jumping.inc",
                               "// GENERATED by run_fxdirector2_player_jumping.py\n" + jumping,
                               "FxDirector2PlayerJumping", shadow=shadow, extra_sources=tuple(extra))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_player_jumping", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
