"""FX-POPUP: replay the production immediate-mode 2D colour transform against the console formula.

The FLAPT HUD (and the DwnldTitleUp popup it draws) reaches D3D9 through
CgsGraphics::Im2dBase<V>::BatchTransformTextureBlendRenderStatic / RenderEnd in
src/GameShared/GameClasses/Graphics/ImmediateMode/CgsIm2d.cpp. This runner compiles that REAL
translation unit (not a copy of its functions) together with FxPopupIm2dColourShift.cpp, whose
recording IDirect3DDevice9 captures the fixed-function state each draw is shaded with and
evaluates the texture-stage cascade for a set of texels; the result is compared with the console's
program-0 formula  texel * (vertexColour * gColourScale) + gColourShift.

The mock device's 119 pass-through methods are GENERATED from the Windows SDK's own d3d9.h, so the
test never hand-copies the COM interface.

Optional first argument: a pre-fix CgsIm2d.cpp snapshot (e.g. `git show HEAD~1:<path> > old.cpp`),
compiled in place of the tree's file to prove the test is RED on the old body.
"""
from pathlib import Path
import os
import re
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
from run_showtime_impulse import settings, REPO, WORKFLOW

KD3D9_CANDIDATES = [
    Path(r'C:/Program Files (x86)/Windows Kits/10/Include'),
]


def find_d3d9_header():
    for root in KD3D9_CANDIDATES:
        if not root.exists():
            continue
        for version in sorted((p for p in root.iterdir() if p.is_dir()), reverse=True):
            header = version / 'shared' / 'd3d9.h'
            if header.exists():
                return header
            header = version / 'um' / 'd3d9.h'
            if header.exists():
                return header
    raise SystemExit('d3d9.h not found under the Windows 10 SDK include roots')


def generate_mock(header_text):
    """-> C++ source for MockDevice9Base: every IDirect3DDevice9 method overridden with a default."""
    start = header_text.index('DECLARE_INTERFACE_(IDirect3DDevice9, IUnknown)')
    end = header_text.index('};', start)
    block = header_text[start:end]
    methods = re.findall(r'STDMETHOD(_?)\(([^)]*)\)\s*\(([^;]*?)\)\s*PURE;', block, re.S)
    lines = ['// GENERATED by run_fxpopup_im2d_colour_shift.py from the SDK d3d9.h -- do not edit.',
             'struct MockDevice9Base : public IDirect3DDevice9', '{']
    count = 0
    for underscore, head, params in methods:
        if underscore:
            ret, name = [p.strip() for p in head.split(',', 1)]
        else:
            ret, name = 'HRESULT', head.strip()
        params = ' '.join(params.split())
        params = re.sub(r'^THIS_\s*', '', params)
        params = '' if params == 'THIS' else params
        if ret == 'void':
            body = '{}'
        elif ret == 'HRESULT':
            body = '{ return S_OK; }'
        else:
            body = '{ return 0; }'
        lines.append('    %s STDMETHODCALLTYPE %s(%s) override %s' % (ret, name, params, body))
        count += 1
    lines.append('};')
    if count != 119:
        raise SystemExit('expected 119 IDirect3DDevice9 methods in d3d9.h, parsed %d' % count)
    return '\n'.join(lines) + '\n'


def main():
    im2d = Path(sys.argv[1]) if len(sys.argv) > 1 else \
        REPO / 'src/GameShared/GameClasses/Graphics/ImmediateMode/CgsIm2d.cpp'
    header = find_d3d9_header()
    with tempfile.TemporaryDirectory(prefix='brn_fxpopup_im2d_') as directory:
        output = Path(directory)
        (output / 'mock_d3d9_device.h').write_text(
            generate_mock(header.read_text(encoding='latin1')), encoding='utf-8')
        # The TU under test, compiled as its own object exactly as the exe build compiles it.
        unit = output / 'CgsIm2d_under_test.cpp'
        unit.write_text(im2d.read_text(encoding='utf-8-sig'), encoding='utf-8')
        includes = ' '.join(f'/I"{WORKFLOW / path}"' for path in settings('msvc_includes.txt'))
        command = ('cl ' + ' '.join(settings('msvc_flags.txt')) + ' ' + includes
                   + f' /I"{output}" "{Path(__file__).with_name("FxPopupIm2dColourShift.cpp")}" "{unit}"'
                   + ' /Fe:regression.exe /link /OPT:REF')
        script = output / 'run.cmd'
        script.write_text('@echo off\ncall "' + str(WORKFLOW / 'tools/build/msvc_env.bat')
                          + '" >nul 2>&1\nif errorlevel 1 exit /b 1\n' + command
                          + '\nif errorlevel 1 exit /b 1\nregression.exe\nexit /b %ERRORLEVEL%\n',
                          encoding='utf-8', newline='\r\n')
        subprocess.run(['cmd', '/c', str(script)], cwd=output, check=True)


if __name__ == '__main__':
    main()
