"""FX-DIRECTOR2 (crash parity 2026-09-25, CC-16): MainDirector requests the "Event_Win(50)" screen effect.

  MainDirector::Update @0x82274070 runs a check on every live frame, at the join point after the dev-only ICE-editor
  preview block (0x82274524..0x82274554). It fires when the frame camera's requested post-FX id is 578869 (0x8D535). An
  ICE take authors that id in POSTFX_HOOK: 26 of the 549 retail takes do (Event_Win2..5, the 21 World_Win_*,
  Online_End_Win, and Takedown_ICE_Shut's fourth interval). The director then asks its EffectInterface for the
  "Event_Win(50)" GUI hook at blend 0.75, through Camera::EnsureEffectIsPlaying. The PC dropped it inside Update's
  broad GATE, so the event-win screen effect never played.

Wiring: the statement sits after UpdateArbitrator and before the game-camera blend (0x822749D4). Numeric:
tests/FxDirector2EventWinHook.cpp compiles the PRODUCTION statement and constants (lifted out of the TU) in a fixture
that holds the director's EffectInterface span by name -- 5 checks.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_event_win_hook.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import Tree, code_only, definition, compile_and_run, report

DIRECTOR_CPP = "src/GameSource/Director/BrnMainDirector.cpp"
HEADERS = (
    "src/GameSource/Director/Camera/Camera.h",
    "src/GameSource/Director/Camera/BrnCameraEffects.h",
    "src/GameSource/Director/Utils/BrnDirectorEffectTrigger.h",
)
EVENT_WIN_IF = "if (lCamera.GetEffects().muRequestedPostFxId == KU_EVENT_WIN_POSTFX_ID)"
CONSTANTS = (r"const\s+u32\s+KU_EVENT_WIN_POSTFX_ID\s*=\s*[^;]+;",
             r"const\s+char\s*\*\s*const\s+KPC_EVENT_WIN_HOOK\s*=\s*\"[^\"]*\"\s*;",
             r"const\s+f32\s+KF_EVENT_WIN_HOOK_BLEND\s*=\s*[^;]+;")
NUMERIC_CHECKS = 5


def update_code(tree):
    try:
        return code_only(definition(tree.read(DIRECTOR_CPP), "void MainDirector::Update("))
    except ValueError:
        return ""


def wiring(tree):
    update = update_code(tree)
    arbitrator = update.find("UpdateArbitrator(lpIO, lCamera, liPlayerCarIndex);")
    event_win = update.find(EVENT_WIN_IF)
    blend = update.find("if (lCamera.GetEffects().mfGameCameraBlend")
    yield ("Update requests the Event_Win hook (0x82274524) after UpdateArbitrator and before the game-camera blend "
           "(0x822749D4)", -1 < arbitrator < event_win < blend)


def numeric(tree):
    update = update_code(tree)
    source = code_only(tree.read(DIRECTOR_CPP))
    constants = [re.search(pattern, source) for pattern in CONSTANTS]
    if EVENT_WIN_IF not in update or not all(constants):
        print("NUMERIC: the revision's MainDirector::Update has no Event_Win(50) request")
        return None
    statement = definition(update, EVENT_WIN_IF)
    shadow = {relative: tree.read(relative) for relative in HEADERS} if tree.rev is not None else None
    return compile_and_run(Path(__file__).with_name("FxDirector2EventWinHook.cpp"), "fxd2_eventwin_block.inc",
                           "// GENERATED by run_fxdirector2_event_win_hook.py\n" + statement + "\n",
                           "FxDirector2EventWinHook", shadow=shadow,
                           extra_files={"fxd2_eventwin_const.inc": "\n".join(m.group(0) for m in constants) + "\n"})


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_event_win_hook", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
