"""FX-DIRECTOR2 (crash parity 2026-09-25): the ICE scene space follows the published camera.

  MainDirector::Update @0x82274070 copies the frame camera's transform into the director's ICE scene space (+0x12170).
  It does this on every live frame whose camera is not in a scene-space shot (0x82274A28..0x82274A80, camera state flag
  13 E_FLAG_DONT_UPDATE_SCENESPACE, which KeyAnimController::UpdateTransformationMatrix raises for a take authored in
  eICE_SCENE_SPACE). UpdateCameraBehavioursPostScene stages that matrix into every frame's ICE::CameraSpaceHandler.
  So a scene-space take is anchored to the last camera before it. The PC never wrote the matrix: it stayed at
  Construct's zero, and a BrnMainDirector comment claimed nothing but the ICE editor writes it. 43 of the 549 retail
  takes author scene space (Race_StartFX, Race_Event_Start, the RaceIntros, Road_Rage_Start, Stunt_Intro / Loop, the
  World_Signature_* outros, CrashBreaker_lvl1_v3/4, End_State, Burning_Finish ...), and all of them projected through
  the zero matrix.

Wiring:
- the statement sits after the game-camera blend (0x822749D4) and before the hook hand-over;
- the producer's flag is 13 (BrnKeyAnimController.cpp KU_CAMERA_FLAG_SCENE_SPACE);
- CameraState names 13 E_FLAG_DONT_UPDATE_SCENESPACE.
Numeric: tests/FxDirector2IceSceneSpace.cpp compiles the PRODUCTION statement in a fixture holding the director's
matrix by name -- 5 checks.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_ice_scene_space.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import Tree, code_only, definition, compile_and_run, report

DIRECTOR_CPP = "src/GameSource/Director/BrnMainDirector.cpp"
KEYANIM_CPP = "src/GameSource/Director/Shots/ShotControllers/BrnKeyAnimController.cpp"
STATE_H = "src/GameSource/Director/Camera/BrnCameraState.h"
HEADERS = (
    "src/GameSource/Director/Camera/Camera.h",
    STATE_H,
)
SCENE_IF = "if (!lCamera.mState.IsFlagSet(Camera::CameraState::E_FLAG_DONT_UPDATE_SCENESPACE))"
NUMERIC_CHECKS = 5


def update_code(tree):
    try:
        return code_only(definition(tree.read(DIRECTOR_CPP), "void MainDirector::Update("))
    except ValueError:
        return ""


def wiring(tree):
    update = update_code(tree)
    blend = update.find("if (lCamera.GetEffects().mfGameCameraBlend")
    scene = update.find(SCENE_IF)
    handover = update.find("RegisterStartingEffectWithName")
    yield ("Update follows the camera into the ICE scene space (0x82274A28) after the game-camera blend and before "
           "the hook hand-over", -1 < blend < scene < handover)
    keyanim = code_only(tree.read(KEYANIM_CPP))
    state = code_only(tree.read(STATE_H))
    yield ("the producer raises flag 13 for a scene-space take, and CameraState names 13 E_FLAG_DONT_UPDATE_SCENESPACE",
           re.search(r"KU_CAMERA_FLAG_SCENE_SPACE\s*=\s*13\s*;", keyanim) is not None
           and re.search(r"E_FLAG_DONT_UPDATE_SCENESPACE\s*=\s*13\s*,", state) is not None)


def numeric(tree):
    update = update_code(tree)
    if SCENE_IF not in update:
        print("NUMERIC: the revision's MainDirector::Update never writes the ICE scene space")
        return None
    statement = definition(update, SCENE_IF)
    shadow = {relative: tree.read(relative) for relative in HEADERS} if tree.rev is not None else None
    return compile_and_run(Path(__file__).with_name("FxDirector2IceSceneSpace.cpp"), "fxd2_scenespace_block.inc",
                           "// GENERATED by run_fxdirector2_ice_scene_space.py\n" + statement + "\n",
                           "FxDirector2IceSceneSpace", shadow=shadow)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_ice_scene_space", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
