"""FX-DIRECTOR2 (crash parity 2026-09-25): MomentTakedownLookback, the takedown look-back moment (type 3).

  Its Update @0x822662F0 read the shared record through six detail:: shims and called three more that had no body
  (the victim's two lanes and the rig's look-at helper), it copied a 64-byte ZERO placeholder over the rig block's
  preset, and it was never allocated: MomentController::NewMoment returned early for type 3. The body is now the
  console's -- the record read by name, CameraRig::ParamsBonnetLow + mbUseShake, BehaviourRig::StartLookingAtRaceCar
  (1, true), and the geometry rounded as the console rounds it (vmsum3fp128 dots, NormalizeFast's vrsqrtefp + one
  Newton step, the divide's vrefp + two).

Numeric: tests/FxDirector2TakedownLookback.cpp includes the revision's PRODUCTION BrnMomentTakedownLookback.cpp and
runs it against a recording behaviour manager. FxDirector2TakedownLookbackGolden.h is the Update's own words run on a
PPC/VMX128 emulator over 103 frames, 12 of which the vendor-form math decides the other way; every frame checks the
helpers bit for bit and the production decision in SEARCHING and VALID. Plus Construct, Prepare, the no-takedown arm,
the shot (NewBehaviour's arguments, the preset, SetParameters, the look-at), inhibited, Release, the switch default.
Wiring: the exe mounts the TU, and NewMoment allocates type 3.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_takedown_lookback.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys
import tempfile

sys.dont_write_bytecode = True
from fxgs_common import WORKFLOW, Tree, code_only, definition, compile_and_run, report

LOOKBACK_CPP = "src/GameSource/Director/MomentController/Moments/BrnMomentTakedownLookback.cpp"
CONTROLLER_CPP = "src/GameSource/Director/MomentController/BrnMomentController.cpp"
SOURCES = (
    "src/GameSource/Director/Utils/BrnVehicleRef.cpp",
    "src/GameSource/Physics/VehicleManager/SharedIO/BrnVehicleEvents.cpp",
    "src/GameSource/Director/Camera/Utils/BrnCameraRigParams.cpp",
)
HEADERS = (
    "src/GameSource/Director/MomentController/Moments/BrnMomentTakedownLookback.h",
    "src/GameSource/Director/MomentController/BrnMoment.h",
    "src/GameSource/Director/MomentController/BrnMomentSharedInfo.h",
    "src/GameSource/Director/Camera/Behaviours/BehaviourRig.h",
    "src/GameSource/Director/Camera/BrnBehaviourManager.h",
    "src/GameSource/Director/Camera/Utils/BrnConsoleVpu.h",
    "src/SDKs/XboxMath/XMVectorSinCos.h",
    "src/GameSource/Director/Utils/BrnVehicleRef.h",
    "src/GameSource/Director/Utils/BrnDirectorAllVehicleData.h",
    "src/GameSource/Director/DirectorModule/BrnDirectorGameState.h",
)
BUILD_BAT = WORKFLOW / "tools/build/build_game_exe.bat"
NUMERIC_CHECKS = 103 + 14


def wiring(tree):
    bat = BUILD_BAT.read_text(encoding="utf-8", errors="replace") if BUILD_BAT.exists() else ""
    yield ("the exe mounts MomentController\\Moments\\BrnMomentTakedownLookback.cpp (tools/build/build_game_exe.bat)",
           'echo "%SRC%\\GameSource\\Director\\MomentController\\Moments\\BrnMomentTakedownLookback.cpp"' in bat)
    try:
        new_moment = re.sub(r"\s+", "", code_only(definition(tree.read(CONTROLLER_CPP),
                                                             "bool MomentController::NewMoment(")))
    except ValueError:
        new_moment = ""
    yield ("MomentController::NewMoment allocates type 3 (jpt_822558C4 case 3: AllocateVoid<MomentTakedownLookback>), "
           "ungated", "caseMoment::E_MOMENT_TAKEDOWN_LOOKBACK:lVoidHandle=mMomentPool.AllocateVoid<"
           "MomentTakedownLookback>();break;" in new_moment)


def numeric(tree):
    lookback = tree.read(LOOKBACK_CPP)
    texts = {relative: tree.read(relative) for relative in SOURCES}
    if not lookback or not all(texts.values()):
        print("NUMERIC: the revision lacks the look-back TU or its leaves")
        return None
    with tempfile.TemporaryDirectory(prefix="brn_fxd2_lookback_") as directory:
        work = Path(directory)
        extra = []
        for relative, text in texts.items():
            target = work / Path(relative).name
            target.write_text(text, encoding="utf-8")
            extra.append(target)
        shadow = {relative: tree.read(relative) for relative in HEADERS} if tree.rev is not None else None
        return compile_and_run(Path(__file__).with_name("FxDirector2TakedownLookback.cpp"), "fxd2_lookback.inc",
                               "// GENERATED by run_fxdirector2_takedown_lookback.py\n" + lookback,
                               "FxDirector2TakedownLookback", shadow=shadow, extra_sources=tuple(extra))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_takedown_lookback", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
