"""FX-DIRECTOR2 (crash parity 2026-09-25): CameraRig::Construct @0x8220B0E8 and the twenty rig presets.

  CameraRig::Construct builds the rig camera's transform relative to its car from an authored preset, the car's box
  and a mirror flag -- the only thing that places a BehaviourRig camera (the takedown look-back, the jump cutaway).
  The PC had a declaration and no body, and the presets did not exist.

Numeric: tests/FxDirector2CameraRig.cpp compiles the revision's BrnCameraRigConstruct.cpp + BrnCameraRigParams.cpp
and compares them with the CONSOLE, not with a restatement of the code: FxDirector2CameraRigGolden.h is the ARTIST
body's own output on a PPC/VMX128 emulator over the raw words -- 20 presets x 2 boxes x mirrored/not, plus 24 random
parameter sets -- and the preset words read out of the image. 20 preset checks + 104 transform checks, all BIT FOR
BIT: written under the campaign rounding rule (the inlined XMVectorSinCos, SDKs/XboxMath/XMVectorSinCos.h; the SDK
Rodrigues builder and Mult cascade with their fused vmaddfp, Utils/BrnConsoleVpu.h) the body is the console's to the
bit. The vendor forms it used first (std::sin / std::cos, unfused mul + add) missed by up to 3.9e-6.
Wiring: BehaviourRig::Parameters::Construct copies ParamsFrontQuarterClose; the mounts.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_camera_rig.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import WORKFLOW, Tree, definition, code_only, compile_and_run, report

CONSTRUCT_CPP = "src/GameSource/Director/Camera/Utils/BrnCameraRigConstruct.cpp"
PRESETS_CPP = "src/GameSource/Director/Camera/Utils/BrnCameraRigParams.cpp"
RIG_H = "src/GameSource/Director/Camera/Behaviours/BehaviourRig.h"
RIG_CPP = "src/GameSource/Director/Camera/Behaviours/BehaviourRig.cpp"
CONSOLE_VPU_H = "src/GameSource/Director/Camera/Utils/BrnConsoleVpu.h"
SINCOS_H = "src/SDKs/XboxMath/XMVectorSinCos.h"
BUILD_BAT = WORKFLOW / "tools/build/build_game_exe.bat"
NUMERIC_CHECKS = 20 + 104


def wiring(tree):
    try:
        construct = re.sub(r"\s+", "", code_only(definition(tree.read(RIG_CPP), "BehaviourRig::Parameters::Construct()")))
    except ValueError:
        construct = ""
    yield ("BehaviourRig::Parameters::Construct copies ParamsFrontQuarterClose into mRigParams (the 8-doubleword copy "
           "from 0x82CDA890 @0x821F9764; PS3 names it)",
           "mRigParams=Utils::CameraRig::ParamsFrontQuarterClose;" in construct)
    bat = BUILD_BAT.read_text(encoding="utf-8", errors="replace") if BUILD_BAT.exists() else ""
    yield ("the build mounts BrnCameraRigConstruct.cpp and BrnCameraRigParams.cpp",
           all(f'echo "%SRC%\\GameSource\\Director\\Camera\\Utils\\{name}.cpp"' in bat
               for name in ("BrnCameraRigConstruct", "BrnCameraRigParams")))


def numeric(tree):
    construct = tree.read(CONSTRUCT_CPP)
    presets = tree.read(PRESETS_CPP)
    if not construct or "void CameraRig::Construct(" not in construct or not presets:
        print("NUMERIC: cannot build -- the revision has no CameraRig::Construct body / no BrnCameraRigParams.cpp")
        return None
    text = ("// GENERATED by run_fxdirector2_camera_rig.py\n"
            f"// ---- {CONSTRUCT_CPP}\n{construct}\n// ---- {PRESETS_CPP}\n{presets}\n")
    shadow = {relative: tree.read(relative) for relative in (RIG_H, CONSOLE_VPU_H, SINCOS_H)}         if tree.rev is not None else None
    return compile_and_run(Path(__file__).with_name("FxDirector2CameraRig.cpp"), "fxdirector2_camera_rig.inc", text,
                           "FxDirector2CameraRig", shadow=shadow)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_camera_rig", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
