"""crash parity FX-NETCRASH (2026-09-25): VehicleDriver::StartCatchupInterpolation's centre-of-mass move is
two FUSED multiply-adds.

@0x825FED30, 0x825FF0C0..0x825FF0EC (all four lanes; raw classic-vmaddfp fields vD = vA * vC + vB):
    t = yAxis * com.y          vmulfp128 v13, v13, v12        one rounding
    t = xAxis * com.x + t      vmaddfp   v13, v12, v13, v11   ONE rounding
    t = zAxis * com.z + t      vmaddfp   v0,  v10, v13, v0    ONE rounding
    wAxis = wAxis + t          vaddfp    v0,  v9,  v0         one rounding
489966db lowered it as wAxis + (x*com.x + y*com.y + z*com.z): three rounded products and two rounded
sums. The network car's catch-up target (and, on a snap, the car's pose) is off by an ulp.

The oracle is independent of the reconstruction: this runner computes the console's lanes with exact
rational arithmetic and one round-to-nearest-even per instruction, on fixed-seed inputs searched so
that every lane of the fused result differs from the twice-rounded one. FxNetcrashCatchupComFma.cpp
compiles the PRODUCTION body (with its file-scope constants) as a member of the real VehicleDriver,
takes the SNAP arm (so the target is written straight into the vehicle), and compares BITWISE.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxnetcrash_catchup_com_fma.py [--pre-fix <b5 rev>]
"""
from fractions import Fraction
import random
import struct
import sys

sys.dont_write_bytecode = True
from fxvmnet_common import REPO, build_and_run, definition, pre_fix_rev, read

DRIVER = "src/GameSource/Physics/VehicleManager/VehiclePhysics/BrnVehicleDriver.cpp"
CONSTANTS = "    namespace\n    {\n        // DWARF BrnVehicleDriver.cpp:239"
SIGNATURE = "    void VehicleDriver::StartCatchupInterpolation("
CASES = 4


def f32(x):
    return struct.unpack("<f", struct.pack("<f", x))[0]


def bits(x):
    return struct.unpack("<I", struct.pack("<f", x))[0]


def rn(value):
    """A Fraction rounded to the nearest f32, ties to even (normal range)."""
    if value == 0:
        return 0.0
    sign = -1 if value < 0 else 1
    a = abs(value)
    e = a.numerator.bit_length() - a.denominator.bit_length()
    if Fraction(2) ** e > a:
        e -= 1
    assert -126 <= e <= 127
    quantum = Fraction(2) ** (e - 23)
    m = a / quantum
    n = m.numerator // m.denominator
    rest = m - n
    if rest > Fraction(1, 2) or (rest == Fraction(1, 2) and n & 1):
        n += 1
    return sign * float(n * quantum)


F = Fraction


def console_lane(x, y, z, w, cx, cy, cz):
    t = rn(F(y) * F(cy))                 # vmulfp128
    t = rn(F(x) * F(cx) + F(t))          # vmaddfp, fused
    t = rn(F(z) * F(cz) + F(t))          # vmaddfp, fused
    return rn(F(w) + F(t))               # vaddfp


def unfused_lane(x, y, z, w, cx, cy, cz):
    s = rn(F(rn(F(x) * F(cx))) + F(rn(F(y) * F(cy))))
    s = rn(F(s) + F(rn(F(z) * F(cz))))
    return rn(F(w) + F(s))


def cases():
    rng = random.Random(0x825FF0E4)
    found = []
    while len(found) < CASES:
        com = [f32(rng.uniform(-0.6, 0.6)) for _ in range(3)]
        rows = [[f32(rng.uniform(-1.0, 1.0)) for _ in range(4)] for _ in range(3)]
        w = [f32(rng.uniform(-3.0, 3.0)) for _ in range(4)]
        want = [console_lane(rows[0][i], rows[1][i], rows[2][i], w[i], *com) for i in range(4)]
        old = [unfused_lane(rows[0][i], rows[1][i], rows[2][i], w[i], *com) for i in range(4)]
        if all(want[i] != old[i] for i in range(4)):
            found.append((rows, w, com, want))
    return found


def cases_inc():
    lines = ["// generated by run_fxnetcrash_catchup_com_fma.py: rows x/y/z, w, com, console wAxis (bit patterns)",
             "struct ComCase { unsigned rows[3][4]; unsigned w[4]; unsigned com[3]; unsigned want[4]; };",
             "static const ComCase KA_COM_CASES[] = {"]
    for rows, w, com, want in cases():
        def u(vs):
            return "{ " + ", ".join(f"0x{bits(v):08X}u" for v in vs) + " }"
        lines.append("    { { " + ", ".join(u(r) for r in rows) + " }, " + u(w) + ", " + u(com) + ", " + u(want) + " },")
    lines.append("};")
    return "\n".join(lines)


def main():
    rev = pre_fix_rev(sys.argv)
    source = read(DRIVER, rev)
    failures = []
    try:
        body = definition(source, CONSTANTS) + "\n" + definition(source, SIGNATURE)
    except ValueError:
        print("FAIL: VehicleDriver::StartCatchupInterpolation has no body in this revision")
        sys.exit(1)
    fused = "std::fma(" in body and "vmulfp128 0x825FF0C0" in body
    if not fused:
        failures.append("the COM move is not the console's vmulfp128 + two fused vmaddfp (0x825FF0C0..0x825FF0E8)")
    rc = build_and_run(REPO / "tests" / "FxNetcrashCatchupComFma.cpp",
                       {"catchup_body.inc": body, "com_cases.inc": cases_inc()}, "fxnetcrash_catchup_com")
    for failure in failures:
        print("FAIL:", failure)
    print(f"structural: {len(failures)} of 1 failed; harness rc={rc}")
    sys.exit(1 if (rc or failures) else 0)


if __name__ == "__main__":
    main()
