"""FX-DIRECTOR2 (crash parity 2026-09-25, CC-13): BehaviourIceAnim::Update's BYSTANDER look space aims the camera.

  BehaviourIceAnim::Update @0x82247108 re-focuses a take that looks in eICE_BYSTANDER_SPACE (11) and then runs the
  behaviour's Looker on the bystander vehicle (0x82247710..0x82247888): a Looker::Parameters block (Construct, then
  eleven overrides read from the image), the behaviour's own timestep, the shared Random, and the bystander's transform,
  velocity and AABB. The PC left the looker as a FLAG, so the camera never aimed, framed or zoomed onto the bystander.
  36 retail takes look in space 11: Takedown_ICE_1 (the shutdown takedown), the 21 World_Win_* and 13 World_Signature_*.
  The shake that follows (0x822478A8..0x822478E4) read E_WORLD instead of the behaviour's own timestep type.

Wiring: the BYSTANDER arm calls mLooker.Update. Numeric: tests/FxDirector2IceAnimBystanderLooker.cpp compiles the
PRODUCTION arms (lifted out of Update with the arm's constants) in a fixture with the behaviour's member names -- 20
checks.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_iceanim_bystander_looker.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys
import tempfile

sys.dont_write_bytecode = True
from fxgs_common import Tree, code_only, definition, compile_and_run, report

ICEANIM_CPP = "src/GameSource/Director/Camera/Behaviours/BrnBehaviourIceAnim.cpp"
# VehicleInfo embeds a RaceCarState whose constructor calls Clear(); the DOF SetParams / GetBlurriness are the real ones.
SOURCES = (
    "src/GameSource/Physics/VehicleManager/SharedIO/BrnVehicleEvents.cpp",
    "src/GameSource/Director/Camera/BrnDepthOfField.cpp",
)
HEADERS = (
    "src/GameSource/Director/Camera/Utils/BrnLooker.h",
    "src/GameSource/Director/Camera/Utils/BrnCameraShake.h",
    "src/GameSource/Director/Camera/Utils/CameraUtils.h",
    "src/GameSource/Director/Camera/Camera.h",
    "src/GameSource/Director/Camera/BrnDepthOfField.h",
    "src/GameSource/Director/Camera/SharedIO/BrnPlayerInfo.h",
    "src/GameSource/Director/Utils/BrnDirectorTimestep.h",
)
UPDATE = "bool BehaviourIceAnim::Update("
BYSTANDER_IF = "if (leLookSpace == ICE::eICE_BYSTANDER_SPACE)"
CONSTANTS = r"static\s+const\s+f32\s+KF_BYSTANDER_LOOKER_\w+\s*=\s*[^;]+;"
NUMERIC_CHECKS = 20


def bystander_arms(update):
    """The production text from the first BYSTANDER arm through the end of the second one, or None."""
    first = update.find(BYSTANDER_IF)
    if first < 0:
        return None
    looker = definition(update[first:], BYSTANDER_IF)
    rest = update[first + len(looker):]
    second = rest.find(BYSTANDER_IF)
    if second < 0:
        return None
    return looker + rest[:second] + definition(rest[second:], BYSTANDER_IF)


def wiring(tree):
    source = tree.read(ICEANIM_CPP)
    try:
        update = code_only(definition(source, UPDATE))
    except ValueError:
        update = ""
    first = update.find(BYSTANDER_IF)
    arm = definition(update[first:], BYSTANDER_IF) if first >= 0 else ""
    yield ("BehaviourIceAnim::Update's BYSTANDER arm runs the behaviour's looker (Looker::Update @0x82247888)",
           "mLooker.Update(" in arm)


def numeric(tree):
    source = tree.read(ICEANIM_CPP)
    try:
        update = code_only(definition(source, UPDATE))
    except ValueError:
        update = ""
    arms = bystander_arms(update)
    if arms is None:
        print("NUMERIC: the revision's BehaviourIceAnim::Update has no BYSTANDER arms")
        return None
    constants = "\n".join(match.group(0) for match in re.finditer(CONSTANTS, code_only(source)))
    shadow = {relative: tree.read(relative) for relative in HEADERS} if tree.rev is not None else None
    with tempfile.TemporaryDirectory(prefix="brn_fxd2_iceanim_") as directory:
        extra = []
        for relative in SOURCES:
            target = Path(directory) / Path(relative).name
            target.write_text(tree.read(relative), encoding="utf-8")
            extra.append(target)
        return compile_and_run(Path(__file__).with_name("FxDirector2IceAnimBystanderLooker.cpp"),
                               "fxd2_iceanim_bystander.inc",
                               "// GENERATED by run_fxdirector2_iceanim_bystander_looker.py\n" + arms + "\n",
                               "FxDirector2IceAnimBystanderLooker", shadow=shadow,
                               extra_files={"fxd2_iceanim_const.inc": constants + "\n"},
                               extra_sources=tuple(extra))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_iceanim_bystander_looker", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
