"""FX-CAMRIG (crash-parity defect CC-4): the Showtime / crash-mode camera rig,
BrnDirector::Camera::BehaviourAftertouchCrash::Update @0x82228158 and its bounce detector
CheckForPlayerCarBouncing @0x8220F340, plus the two CameraImpactEffect bodies the rig inlines
(Construct, Update -- PS3 @0x28074) and the rig-sub-object seeding in Construct @0x822461F8.

Every body under test is TEXT EXTRACTED from the shipped sources:
  src/GameSource/Director/Camera/Behaviours/BrnBehaviourAftertouchCrash.cpp   (helpers, KF statics,
      Construct, Prepare, Update, CheckForPlayerCarBouncing)
  src/GameSource/Director/Camera/Utils/BrnCameraImpactEffectRegisterImpact.cpp (RegisterImpact,
      Construct, Update)
  src/GameSource/Director/Camera/Utils/BrnPositionLag.cpp                     (PositionLag::Construct)
and compiled against the REAL headers (private/protected opened with /Dprivate=public, the pattern
run_showtime_impulse.py uses) and the fixtures in FxCamrigRig.cpp, which stand in for the rig's
out-of-TU callees and record every call (CreateLookAt / CameraShake::Update / PositionLag::Update /
SineLerp / SetFlag / the asserts). The numeric expectations in the driver are written from the ARTIST
asm, not from the production text.

A body the given revision does not have is replaced by what that revision DISPATCHED:
  BehaviourAftertouchCrash::Update            -> the base Behaviour::Update (`return true`, camera untouched)
  CheckForPlayerCarBouncing                   -> never called (false)
  CameraImpactEffect::Construct / ::Update    -> never called (no-ops)
so the pre-fix source runs the SAME checks and fails them for the reason the game did.

usage: run_fxcamrig_rig.py [--rev <b5-decomp git revision>]
    default   the working tree's sources
    --rev R   the three .cpp files as of revision R (headers always from the working tree)
"""
from pathlib import Path
import argparse
import re
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
from run_showtime_impulse import definition, settings, REPO, WORKFLOW

RIG = "src/GameSource/Director/Camera/Behaviours/BrnBehaviourAftertouchCrash.cpp"
IMPACT = "src/GameSource/Director/Camera/Utils/BrnCameraImpactEffectRegisterImpact.cpp"
LAG = "src/GameSource/Director/Camera/Utils/BrnPositionLag.cpp"

KF_STATIC = re.compile(r"^(?:f32|::VecFloat)\s+BehaviourAftertouchCrash::KF_\w+\s*=[^;]*;", re.M)


def read(path, rev):
    if rev:
        text = subprocess.run(["git", "-C", str(REPO), "show", f"{rev}:{path}"], check=True,
                              capture_output=True).stdout.decode("utf-8")
    else:
        text = (REPO / path).read_text(encoding="utf-8")
    return text.replace("\r\n", "\n")


def optional(source, signature):
    return definition(source, signature) if signature in source else None


def generate(rig, impact, lag):
    helpers = optional(rig, "namespace\n{")
    construct = definition(rig, "void BehaviourAftertouchCrash::Construct(")
    prepare = definition(rig, "bool BehaviourAftertouchCrash::Prepare(")
    update = optional(rig, "bool BehaviourAftertouchCrash::Update(")
    bounce = optional(rig, "bool BehaviourAftertouchCrash::CheckForPlayerCarBouncing(")
    register = definition(impact, "void CameraImpactEffect::RegisterImpact(")
    impact_construct = optional(impact, "void CameraImpactEffect::Construct(")
    impact_update = optional(impact, "void CameraImpactEffect::Update(")
    lag_construct = definition(lag, "void PositionLag::Construct(")
    statics = KF_STATIC.findall(rig)

    found = {
        "helpers": helpers is not None, "Update": update is not None,
        "CheckForPlayerCarBouncing": bounce is not None,
        "CameraImpactEffect::Construct": impact_construct is not None,
        "CameraImpactEffect::Update": impact_update is not None, "KF statics": len(statics),
    }
    print("[fxcamrig] extracted: " + ", ".join(f"{k}={v}" for k, v in found.items()), flush=True)

    lines = ["// GENERATED by run_fxcamrig_rig.py -- every body below is text extracted from the shipped source,",
             "// except the marked stand-ins for bodies the revision under test does not have."]
    lines += [helpers if helpers else "// (no file-local helper block in this revision)"]
    lines += ["#define FXCAMRIG_HAVE_HELPERS %d" % (1 if helpers else 0),
              "#define FXCAMRIG_HAVE_RIG %d" % (1 if update else 0),
              "namespace BrnDirector { namespace Camera {", *statics, construct, prepare]
    lines += [update if update else
              "bool BehaviourAftertouchCrash::Update(Camera&, const BehaviourSharedInfo&)\n"
              "{\n    return true;   // STAND-IN: the pre-fix build dispatched the base Behaviour::Update\n}"]
    lines += [bounce if bounce else
              "bool BehaviourAftertouchCrash::CheckForPlayerCarBouncing(const BehaviourSharedInfo&)\n"
              "{\n    return false;  // STAND-IN: no pre-fix caller\n}"]
    lines += ["namespace Utils {", register]
    lines += [impact_construct if impact_construct else
              "void CameraImpactEffect::Construct() {}   // STAND-IN: no pre-fix caller"]
    lines += [impact_update if impact_update else
              "void CameraImpactEffect::Update(Camera&, const Parameters&, Random&, f32) {}   // STAND-IN"]
    lines += [lag_construct, "} } }", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="b5-decomp revision to take the three .cpp files from")
    args = parser.parse_args()
    text = generate(read(RIG, args.rev), read(IMPACT, args.rev), read(LAG, args.rev))
    with tempfile.TemporaryDirectory(prefix="brn_fxcamrig_rig_") as directory:
        output = Path(directory)
        (output / "fxcamrig_rig.inl").write_text(text, encoding="utf-8")
        includes = [output] + [WORKFLOW / path for path in settings("msvc_includes.txt")]
        command = ("cl " + " ".join(settings("msvc_flags.txt"))
                   + " /D_ALLOW_KEYWORD_MACROS=1 /Dprivate=public /Dprotected=public "
                   + " ".join(f'/I"{path}"' for path in includes) + " "
                   + f'"{Path(__file__).with_name("FxCamrigRig.cpp")}"'
                   + " /Fe:regression.exe /link /OPT:REF")
        script = output / "run.cmd"
        script.write_text('@echo off\ncall "' + str(WORKFLOW / "tools/build/msvc_env.bat")
                          + '" >nul 2>&1\nif errorlevel 1 exit /b 1\n' + command
                          + '\nif errorlevel 1 exit /b 1\nregression.exe\nexit /b %ERRORLEVEL%\n',
                          encoding="utf-8", newline="\r\n")
        sys.exit(subprocess.run(["cmd", "/c", str(script)], cwd=output).returncode)


if __name__ == "__main__":
    main()
