"""FX-DIRECTOR2 (crash parity 2026-09-24): the CRASH ANALYSER and the SHOT SELECTOR are real.

  MainDirector::PreSceneQueryUpdate @0x8225BA00 calls CrashAnalyser::Update @0x82209290 at 0x8225BCDC
  (unconditionally, after the sim-paused VehicleTracker block, before ReleaseBehaviours). It is the only
  producer of the CrashAnalysis every moment reads through MomentSharedInfo::mpCrashAnalysis -- the
  CrashStart / WorldImpact / CarImpact / HardStop bits of a crash's first frame, the Left / Right / Front /
  Rear face the hard stop hit, and the side of the line of action to film from. On the PC the analyser
  and the shot selector were opaque zero spans in MainDirector, the Update call and
  ShotSelector::Construct were gated, so MomentHardStop's CrashStart gate never held and the console's
  head-on wall-stop shot could never be selected.

Numeric: tests/FxDirector2CrashAnalyser.cpp compiles the PRODUCTION BrnCrashAnalyser.cpp over a
fixture table generated by EXECUTING THE CONSOLE WORDS of @0x82209290 (FX-DIRECTOR2.emu/crashanemu.py)
-- 54 rows x 3 records -- plus the extracted ShotSelector::Prepare / Update / SetLastUsedToNow, the
production BrnDirectorVehicleTracker.cpp's crash-energy band (@0x8223B3B8..0x8223B414, bands 50 / 20
read at 0x82CDA548 / 0x82CDA54C) and the extracted DebugLog::Construct / Clear / ActualAppend over a
zero-filled log (the director's log was a never-constructed zero span: MomentHardStop's first Append
wrote through index -1). A revision without the bodies gets labelled stand-ins (and fails).
Wiring: the MainDirector sites the console touches the objects at (Construct 0x8225B7F8 and the inlined
DebugLog::Construct 0x8225B824..0x8225B87C, Prepare stage 1 0x8224FBE4, PreSceneQueryUpdate 0x8225BCDC +
the tracker's 4th argument 0x8225BCBC + the latch clear 0x8225BCEC, Update 0x82274F6C..0x82274FE4,
UpdateMoments), the members, the retired VehicleTracker slice, the CrashEvents home, the MomentHardStop
field names, and the mount line.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_crash_analyser.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import REPO, WORKFLOW, STRSTREAM_CPP, Tree, definition, code_only, compile_and_run, report

ANALYSER_CPP = "src/GameSource/Director/BrnCrashAnalyser.cpp"
ANALYSER_H = "src/GameSource/Director/BrnCrashAnalyser.h"
EVENTS_H = "src/GameSource/AttribSys/Enums/CrashEvents.h"
SELECTOR_CPP = "src/GameSource/Director/Utils/BrnShotSelector.cpp"
SELECTOR_H = "src/GameSource/Director/Utils/BrnShotSelector.h"
MAIN_CPP = "src/GameSource/Director/BrnMainDirector.cpp"
MAIN_H = "src/GameSource/Director/BrnMainDirector.h"
TRACKER_H = "src/GameSource/Director/Utils/BrnDirectorVehicleTracker.h"
HARDSTOP_CPP = "src/GameSource/Director/MomentController/Moments/BrnMomentHardStop.cpp"
TRACKER_CPP = "src/GameSource/Director/Utils/BrnDirectorVehicleTracker.cpp"
DEBUGLOG_CPP = "src/GameSource/Director/DirectorModule/BrnDirectorModuleDebugPrinter.cpp"
DEBUGLOG_H = "src/GameSource/Director/DirectorModule/BrnDirectorModuleDebugPrinter.h"
STRING_UTILS_CPP = REPO / "src/GameShared/GameClasses/Core/CgsStringUtils.cpp"
BUILD_BAT = WORKFLOW / "tools/build/build_game_exe.bat"
NUMERIC_CHECKS = 54 * 3 + 1 + 5 + 7 + 10 * 4 + 1 + 6 + 3 + 1

# MomentHardStop's upright gate: the production definition is lifted into the test, or this stand-in
# (the value the old body compared against: a 0.0f "speed-diff threshold", the .bss zero of 0x82FAA848).
UPRIGHT_RX = re.compile(r"^\s*const f32 KF_MAX_DOT_PRODUCT_FOR_HARD_STOP\s*=[^;]*;", re.M)
UPRIGHT_STAND_IN = "const f32 KF_MAX_DOT_PRODUCT_FOR_HARD_STOP = 0.0f;   // STAND-IN: the old gfHardStopSpeedDiffThreshold"

UPDATE_SIG = "void CrashAnalyser::Update(const DirectorIO::InputBuffer* lpInput, const GameState* lpGameState,"
ANALYSER_STAND_IN = """// STAND-IN (labelled): this revision has no CrashAnalyser::Update body -- the analyser was an opaque zero
// span in MainDirector and PreSceneQueryUpdate's call to it was gated.
namespace BrnDirector {
void CrashAnalyser::Update(const DirectorIO::InputBuffer*, const GameState*, EActiveRaceCarIndex) {}
}
"""
SELECTOR_SIGS = {
    "Prepare": ("bool\nShotSelector::Prepare()", "bool ShotSelector::Prepare()"),
    "Update": ("void\nShotSelector::Update(const Camera::Camera& lrSelectedCamera)",
               "void ShotSelector::Update(const Camera::Camera& lrSelectedCamera)"),
    "SetLastUsedToNow": ("void\nShotSelector::SetLastUsedToNow(", "void ShotSelector::SetLastUsedToNow("),
}
SELECTOR_STAND_INS = {
    "Prepare": "bool ShotSelector::Prepare() { return false; }   // STAND-IN: declaration-only in this revision",
    "Update": "void ShotSelector::Update(const Camera::Camera&) {}   // STAND-IN: declaration-only in this revision",
    "SetLastUsedToNow": "void ShotSelector::SetLastUsedToNow(const Camera::Camera::ShotSelectionInfo&) {}   // STAND-IN",
}


def squash(text):
    return re.sub(r"\s+", "", code_only(text))


def selector_bodies(tree):
    source = tree.read(SELECTOR_CPP)
    out, missing = [], []
    for name, signatures in SELECTOR_SIGS.items():
        text = None
        for signature in signatures:
            if signature in source:
                text = definition(source, signature)
                break
        if text is None:
            missing.append(name)
            text = SELECTOR_STAND_INS[name]
        out.append(text)
    return out, missing


DEBUGLOG_SIGS = {
    "Construct": "void DebugLog::Construct()",
    "Clear": "void DebugLog::Clear()",
    "ActualAppend": "void DebugLog::ActualAppend(const char* lpcString, CgsDev::RGBA lRGBA)",
}
DEBUGLOG_STAND_INS = {
    "Construct": "void DebugLog::Construct() {}   // STAND-IN: no body in this revision (the director's log was a zero span)",
    "Clear": "void DebugLog::Clear() {}   // STAND-IN: no body in this revision",
    "ActualAppend": "void DebugLog::ActualAppend(const char*, CgsDev::RGBA) {}   // STAND-IN",
}


def debuglog_bodies(tree):
    source = tree.read(DEBUGLOG_CPP)
    out, missing = [], []
    for name, signature in DEBUGLOG_SIGS.items():
        if signature in source:
            out.append(definition(source, signature))
        else:
            missing.append(name)
            out.append(DEBUGLOG_STAND_INS[name])
    return out, missing


def numeric(tree):
    analyser = tree.read(ANALYSER_CPP)
    have_analyser = UPDATE_SIG in analyser
    selectors, missing = selector_bodies(tree)
    print(f"[fxdirector2] CrashAnalyser::Update body: {'production' if have_analyser else 'STAND-IN'}; "
          f"ShotSelector stand-ins: {missing or 'none'}", flush=True)
    text = "// GENERATED by run_fxdirector2_crash_analyser.py\n"
    text += analyser if have_analyser else ANALYSER_STAND_IN
    text += "\n#include \"GameSource/Director/Utils/BrnShotSelector.h\"\nnamespace BrnDirector {\n"
    text += "\n".join(selectors) + "\n}\n"
    # The production tracker TU as the revision has it (its crash-energy classifier is under test).
    text += "\n// ---- " + TRACKER_CPP + "\n" + tree.read(TRACKER_CPP) + "\n"
    logs, log_missing = debuglog_bodies(tree)
    print(f"[fxdirector2] DebugLog stand-ins: {log_missing or 'none'}", flush=True)
    text += '\n#include "GameShared/GameClasses/Core/CgsStringUtils.h"\nnamespace BrnDirector {\n'
    text += "\n".join(logs) + "\n}\n"
    upright = UPRIGHT_RX.search(tree.read(HARDSTOP_CPP))
    print(f"[fxdirector2] KF_MAX_DOT_PRODUCT_FOR_HARD_STOP: {'production' if upright else 'STAND-IN'}", flush=True)
    text += "\n#include <cmath>\nnamespace fxd2_hardstop {\n" + (upright.group(0).strip() if upright else UPRIGHT_STAND_IN) + "\n}\n"
    shadow = {}
    for header in (ANALYSER_H, EVENTS_H, SELECTOR_H, TRACKER_H, DEBUGLOG_H):
        header_text = tree.read(header)
        if header_text and tree.rev is not None:
            shadow[header] = header_text
    return compile_and_run(Path(__file__).with_name("FxDirector2CrashAnalyser.cpp"),
                           "fxdirector2_crash_analyser.inc", text, "fxdirector2_crash_analyser",
                           shadow=shadow, extra_sources=(STRSTREAM_CPP, STRING_UTILS_CPP))


def wiring(tree):
    main_cpp = tree.read(MAIN_CPP)
    main_h = squash(tree.read(MAIN_H))
    tracker_h = squash(tree.read(TRACKER_H))
    hardstop = squash(tree.read(HARDSTOP_CPP))
    events = tree.read(EVENTS_H)

    def body(signature):
        try:
            return squash(definition(main_cpp, signature))
        except ValueError:
            return ""

    pre = body("void MainDirector::PreSceneQueryUpdate(")
    construct = body("void MainDirector::Construct(")
    prepare = body("bool MainDirector::Prepare(")
    moments = body("void MainDirector::UpdateMoments(")
    update = body("void MainDirector::Update(")

    call = "mCrashAnalyser.Update(lpIO->mpInputBuffer,&maGameState,static_cast<EActiveRaceCarIndex>(liPlayerCarIndex));"
    at = pre.find(call)
    tracker = pre.find("mVehicleTracker.Update(")
    release = pre.find("mBehaviourManager.ReleaseBehaviours();")
    yield ("PreSceneQueryUpdate calls mCrashAnalyser.Update(input, &maGameState, playerIndex) (0x8225BCDC) after the "
           "tracker block and before ReleaseBehaviours",
           at > tracker >= 0 and release > at)
    yield ("... UNCONDITIONALLY: straight after the sim-paused block closes (no getenv / opt-in gate in front of it)",
           at > 0 and pre[at - 1] == "}")
    yield ("... then the latch clear (0x8225BCEC): mbDisableAftertouchCamera -> maGameState.mbImpactTimeActive = false",
           "mBehaviourManager.ReleaseBehaviours();if(maStateFlagTail[E_FLAG_TAIL_DISABLE_AFTERTOUCH_CAMERA])"
           "maGameState.mbImpactTimeActive=false;" in pre)
    yield ("Construct: ShotSelector::Construct(this + 0x121F0, lpResourceManager) between the finaliser and the ICE "
           "wrapper (0x8225B7F8)",
           "mCameraFinaliser.Construct(lpResourceManager);mShotSelector.Construct(lpResourceManager);"
           "mICEWrapper.Construct();" in construct)
    yield ("Prepare stage 1: the inlined ShotSelector::Prepare (stw 0 -> +0x12454 @0x8224FBE4)",
           "case1:miPrepareStage=1;mShotSelector.Prepare();case2:" in prepare)
    yield ("Update: SetShotChanged on E_FLAG_NEW_THIS_FRAME, then ShotSelector::Update, right before the finaliser "
           "(0x82274F6C..0x82274FE4)",
           "if(lCamera.mState.IsFlagSet(Camera::CameraState::E_FLAG_NEW_THIS_FRAME))mCrashAnalyser.SetShotChanged();"
           "mShotSelector.Update(lCamera);mCameraFinaliser.Update(" in update)
    yield ("UpdateMoments publishes &mShotSelector and &mCrashAnalyser.GetAnalysis() (+0x121F0 / +0x1245C)",
           "lSharedInfo.mpShotSelector=&mShotSelector;lSharedInfo.mpCrashAnalysis=&mCrashAnalyser.GetAnalysis();"
           in moments)
    yield ("MainDirector holds ShotSelector mShotSelector and CrashAnalyser mCrashAnalyser (the opaque spans are gone)",
           "ShotSelectormShotSelector;" in main_h and "CrashAnalysermCrashAnalyser;" in main_h
           and "maShotSelector[" not in main_h and "maCrashAnalyser[" not in main_h)
    yield ("the VehicleTracker CrashAnalysis slice is retired (one definition: BrnCrashAnalyser.h)",
           "structCrashAnalysis" not in tracker_h and '#include"GameSource/Director/BrnCrashAnalyser.h"' in tracker_h)
    yield ("MomentHardStop reads the DWARF names (mxEventFlags / mbSuggestLeftOfLineOfAction) and CrashEvents::CrashStart",
           "mxFlags" not in hardstop and "mbUseLeftSide" not in hardstop
           and "lpLiveAnalysis->mxEventFlags&AttribSys::Enums::CrashEvents::CrashStart" in hardstop)
    yield ("AttribSys::Enums::CrashEvents carries the gaNames @0x82CDA518 bits (HardStop 1 .. RearImpact 128)",
           all(re.search(rf"\b{name}\s*=\s*{value}\b", events) for name, value in (
               ("None", 0), ("HardStop", 1), ("LeftImpact", 2), ("RightImpact", 4), ("WorldImpact", 8),
               ("CarImpact", 16), ("CrashStart", 32), ("FrontImpact", 64), ("RearImpact", 128))))
    yield ("Construct: the inlined DebugLog::Construct straight after GameState::Clear (0x8225B810..0x8225B87C)",
           "maGameState.Clear();mDebugLog.Construct();" in construct)
    yield ("the director's DebugLog is a real member published by address at all three shared-info sites",
           "DebugLogmDebugLog;" in main_h and "maDebugLog[" not in main_h
           and squash(main_cpp).count("const_cast<DebugLog*>(&mDebugLog)") == 3)
    yield ("PreSceneQueryUpdate hands VehicleTracker::Update the console's 4th argument, mbForceNextWorldCrashToBeFastTopDown "
           "(lbzx +0x35437 @0x8225BCBC), not a literal false",
           "maStateFlagTail[E_FLAG_TAIL_FORCE_NEXT_WORLD_CRASH_FAST_TOP_DOWN]!=0);" in pre
           and "/*lbForceNextWorldCrashToBeFastTopDown*/false" not in pre)
    yield ("Update's tail ends with the console's two latches (0x82275290..0x822752D0): the debug single-step, then "
           "the ONE-SHOT clear of mbForceNextWorldCrashToBeFastTopDown on the tracker's first crash frame",
           update.endswith("if(maStateFlagTail[E_FLAG_TAIL_DEBUG_SINGLE_TIMESTEP]){"
                           "maStateFlagTail[E_FLAG_TAIL_DEBUG_SINGLE_TIMESTEP]=0;"
                           "maStateFlagTail[E_FLAG_TAIL_DEBUG_ZERO_TIMESTEP]=1;}"
                           "if(mVehicleTracker.IsFirstFrameOfCrash()){"
                           "maStateFlagTail[E_FLAG_TAIL_FORCE_NEXT_WORLD_CRASH_FAST_TOP_DOWN]=0;}}"))
    yield ("MomentHardStop's eligibility compares the car's up axis against KF_MAX_DOT_PRODUCT_FOR_HARD_STOP "
           "(vcmpgtfp. @0x82271938), not the old 0.0f global",
           "MomentSharedInfo_GetCrashSpeedDiff(lSharedInfo)>KF_MAX_DOT_PRODUCT_FOR_HARD_STOP" in hardstop
           and "gfHardStopSpeedDiffThreshold" not in hardstop)
    bat = BUILD_BAT.read_text(encoding="utf-8", errors="replace") if BUILD_BAT.exists() else ""
    yield ("the build mounts BrnCrashAnalyser.cpp (tools/build/build_game_exe.bat)",
           'echo "%SRC%\\GameSource\\Director\\BrnCrashAnalyser.cpp"' in bat)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="b5-decomp revision to read the sources from (default: the working tree)")
    args = parser.parse_args()
    tree = Tree(args.rev)
    checks = list(wiring(tree))
    result = numeric(tree)
    sys.exit(report("fxdirector2_crash_analyser", checks, result, NUMERIC_CHECKS))


if __name__ == "__main__":
    main()
