"""FX-DIRECTOR2 (crash parity 2026-09-25): SimpleIceTakedownPlayer::SetIceAnim @0x821F58C8 tests the whole u64 class key.

  The console checks the shot it binds with one 64-bit compare: `ld r11, 0(r31)` against 0x4644E379A997C1EE
  (Attrib::Gen::iceanim::ClassKey()), `cmpld ; beq` (0x821F58F0..0x821F5908). The PC read Hex-Rays'
  `a2[1] != (*a2 | 0xC1EE)` as two dwords, which is never true of the real key on a little-endian host. So every
  shutdown takedown asserted, pausing the game (fxdirector2_iceanim_bystander/20260925_220559, Takedown_ICE_Shut). The
  two-dword test also let through a wrong key whose halves are equal.

Wiring: the body compares GetClassKey() with iceanim::ClassKey() and no longer ORs 0xC1EE. Numeric:
tests/FxDirector2SetIceAnim.cpp compiles the PRODUCTION body against real Attrib::RefSpec shots -- 8 checks.

    env -u NoDefaultCurrentDirectoryInExePath python b5-decomp/tests/run_fxdirector2_set_ice_anim.py [--rev <b5 rev>]
"""
from pathlib import Path
import argparse
import re
import sys

sys.dont_write_bytecode = True
from fxgs_common import Tree, code_only, definition, compile_and_run, report

PLAYER_CPP = "src/GameSource/Director/Arbitrator/States/BrnSimpleIceTakedownPlayer.cpp"
SIGNATURE = "void SimpleIceTakedownPlayer::SetIceAnim("
HEADERS = (
    "src/GameSource/AttribSys/Generated/classes/iceanim.h",
    "src/SDKs/Packages/AttribSys/1.2.1.2/AttribSys/runtime/common/attribinstance.h",
)
NUMERIC_CHECKS = 8


def body(tree):
    """The production body of SetIceAnim (from its opening brace), or None."""
    try:
        function = definition(tree.read(PLAYER_CPP), SIGNATURE)
    except ValueError:
        return None
    return function[function.index("{"):]


def wiring(tree):
    text = re.sub(r"\s+", "", code_only(body(tree) or ""))
    yield ("SetIceAnim compares the whole class key with iceanim::ClassKey() (`ld` + `cmpld`, 0x821F58F0..0x821F5904)",
           "GetClassKey())==Attrib::Gen::iceanim::ClassKey()" in text and "0xC1EE" not in text)


def numeric(tree):
    text = body(tree)
    if text is None:
        print("NUMERIC: the revision has no SimpleIceTakedownPlayer::SetIceAnim")
        return None
    shadow = {relative: tree.read(relative) for relative in HEADERS} if tree.rev is not None else None
    return compile_and_run(Path(__file__).with_name("FxDirector2SetIceAnim.cpp"), "fxd2_seticeanim_body.inc",
                           "// GENERATED by run_fxdirector2_set_ice_anim.py\n" + text + "\n",
                           "FxDirector2SetIceAnim", shadow=shadow)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="read the b5 sources from this git revision")
    args = parser.parse_args()
    tree = Tree(args.rev)
    return report("run_fxdirector2_set_ice_anim", list(wiring(tree)), numeric(tree), NUMERIC_CHECKS)


if __name__ == "__main__":
    sys.exit(main())
