"""FX-FPUMAX call-site group B: the BrnBehaviourGameplayExternal.cpp statements whose console form is the
rwmath VPU VecFloat Min / Max / Clamp (vminfp / vmaxfp), not the fsel rw::math::fpu forms:

  ModifyTargetAngles @0x82225580              vmaxfp/vminfp 0x822255DC/0x822255E0 (x), 0x822255EC/0x822255F0 (z)
  InterpolateLastPlayerTransform @0x82224BF0  0x82224C84/C88 (:579), 0x82224CF8 (:584), 0x82224D38/D58 (:589),
                                              0x82224D80/D90 (:590), 0x82224D50 (:591), 0x82224EB8/ED0 (:598)
  Update @0x82240828                          vminfp128 0x82240A04 (:214), vmaxfp128/vminfp128 0x82240CC0/CC4 (:260)

The file-local VecFloatMax / VecFloatMin / VecFloatClamp and the numerically testable statements are
EXTRACTED from the production file into fxfpumax_vecfloat_sites.inl; the statements inside SLerp / acos
arguments are checked structurally here and handed to the C++ side as named results, so the total counts
every check.

usage: run_fxfpumax_vecfloat_sites.py [--rev <b5-decomp git revision>]
    default   the working tree's BrnBehaviourGameplayExternal.cpp
    --rev R   that file as of revision R (e.g. the fix commit's parent); scalar_operation.h always comes
              from the working tree.
"""
from pathlib import Path
import argparse
import re
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
from run_showtime_impulse import definition, settings, REPO, WORKFLOW
from run_fxfpumax_order_sites import statement

SOURCE = "src/GameSource/Director/Camera/Behaviours/BrnBehaviourGameplayExternal.cpp"
FPU_CALL = re.compile(r"rw::math::fpu::(Min|Max|Clamp)\b")


def squash(text):
    return re.sub(r"\s+", "", re.sub(r"//[^\n]*", "", text))


def generate(source):
    modify = definition(source, "void BehaviourGameplayExternal::ModifyTargetAngles(")
    interpolate = definition(source, "void BehaviourGameplayExternal::InterpolateLastPlayerTransform(")
    update = definition(source, "bool BehaviourGameplayExternal::Update(")

    helpers = []
    for name in ("VecFloatMax", "VecFloatMin", "VecFloatClamp"):
        signature = f"    f32 {name}("
        helpers.append(definition(source, signature) if signature in source else None)
    have_helpers = all(helpers)

    constants = [statement(source, rf"const f32 {name}\s*=", name) for name in (
        "KVF_LAST_PLAYER_TRANSFORM_SPEED_TO_INTERP_MPS", "KVF_LAST_PLAYER_TRANSFORM_MAX_INTERP",
        "KVF_LAST_PLAYER_TRANSFORM_MIN_INTERP", "KVF_LAST_PLAYER_TRANSFORM_MIN_DIV_ANGLE",
        "KVF_MAX_PITCH_LIMIT", "KF_MPH_TO_METRES_PER_SECOND")]

    structural = [
        ("ModifyTargetAngles has no fsel rw::math::fpu Min/Max/Clamp left (both clamps are vpu::Clamp)",
         not FPU_CALL.search(modify)),
        ("InterpolateLastPlayerTransform has no fsel rw::math::fpu Min/Max/Clamp left (six VecFloat sites)",
         not FPU_CALL.search(interpolate)),
        (".cpp:579 the acos input is VecFloatClamp(Dot(...), -1.0f, 1.0f) (0x82224C84/0x82224C88)",
         bool(re.search(r"lfCos=VecFloatClamp\(rw::math::vpu::Dot\(.*\),-1\.0f,1\.0f\);",
                        squash(statement(interpolate, r"const f32 lfCos\s*=", "lfCos"))))),
        (".cpp:598 the SLerp blend is VecFloatClamp(lfSpeedMod, 0.0f, 1.0f) (0x82224EB8/0x82224ED0)",
         "VecFloatClamp(lfSpeedMod,0.0f,1.0f),&lvUnusedAngleOut" in squash(interpolate)),
        (".cpp:260 the velocity-frame SLerp blend is VecFloatClamp((speed - 1) * rate, 0, 1) (0x82240CC0/0x82240CC4)",
         "VecFloatClamp((lfPlayerSpeed-1.0f)*KVF_VELOCITY_BLEND_RATE,0.0f,1.0f),&lUnusedAngle" in squash(update)),
        (".cpp:214 the pitch-limit reduction is VecFloatMin(speed, cap) (vminfp128 0x82240A04)",
         "VecFloatMin(lfPlayerSpeed,kfPitchLimitMaxSpeed)"
         in squash(statement(update, r"const f32 lfPitchLimitReduction\s*=", "lfPitchLimitReduction"))),
    ]

    lines = [
        "// GENERATED by run_fxfpumax_vecfloat_sites.py -- every body below is text extracted from the shipped source.",
        "namespace fxfpumax_vecfloat",
        "{",
        "typedef float f32;",
        *constants,
    ]
    if have_helpers:
        lines += ["#define FXFPUMAX_HAVE_VECFLOAT_HELPERS 1", *helpers]
    lines += [
        "struct Vec4 { f32 x, y, z, w; };",
        "void ModifyTargetAngleClamps(Vec4& lrTargetAngles, f32 lfPitchBound, f32 lfRollBound)",
        "{",
        statement(modify, r"lrTargetAngles\.x\s*=", "ModifyTargetAngles x"),
        statement(modify, r"lrTargetAngles\.z\s*=", "ModifyTargetAngles z"),
        "}",
        "f32 ExcessSpeed(f32 lfCarSpeedX)",
        "{",
        "    struct { f32 x; } lvfCarSpeed = { lfCarSpeedX };",
        statement(interpolate, r"const f32 lfExcessSpeed\s*=", "lfExcessSpeed"),
        "    return lfExcessSpeed;",
        "}",
        "void RateLimit(f32 lfOutAngle, f32 lfSpeedModIn, f32* lpfOut)",
        "{",
        "    f32 lfSpeedMod = lfSpeedModIn;",
        statement(interpolate, r"const f32 lfAngleToRotate\s*=", "lfAngleToRotate"),
        statement(interpolate, r"const f32 lfAngleToRotateClamped\s*=", "lfAngleToRotateClamped"),
        statement(interpolate, r"lfSpeedMod\s*=\s*lfAngleToRotateClamped", "lfSpeedMod blend"),
        "    lpfOut[0] = lfAngleToRotate;",
        "    lpfOut[1] = lfAngleToRotateClamped;",
        "    lpfOut[2] = lfSpeedMod;",
        "}",
        "f32 PitchLimitReduction(f32 lfPlayerSpeed)",
        "{",
        statement(update, r"const f32 kfPitchLimitMaxSpeed\s*=", "kfPitchLimitMaxSpeed"),
        statement(update, r"const f32 lfPitchLimitReduction\s*=", "lfPitchLimitReduction"),
        "    return lfPitchLimitReduction;",
        "}",
        "struct StructuralCheck { bool mbOk; const char* mpcWhat; };",
        "const StructuralCheck kaStructural[] =",
        "{",
        *[f'    {{ {"true" if ok else "false"}, "{what}" }},' for what, ok in structural],
        "};",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rev", help="b5-decomp revision to take BrnBehaviourGameplayExternal.cpp from")
    args = parser.parse_args()
    if args.rev:
        source = subprocess.run(["git", "-C", str(REPO), "show", f"{args.rev}:{SOURCE}"], check=True,
                                capture_output=True).stdout.decode("utf-8")
    else:
        source = (REPO / SOURCE).read_text(encoding="utf-8")
    with tempfile.TemporaryDirectory(prefix="brn_fxfpumax_vecfloat_") as directory:
        output = Path(directory)
        (output / "fxfpumax_vecfloat_sites.inl").write_text(generate(source), encoding="utf-8")
        includes = [output] + [WORKFLOW / path for path in settings("msvc_includes.txt")]
        command = ("cl " + " ".join(settings("msvc_flags.txt")) + " "
                   + " ".join(f'/I"{path}"' for path in includes) + " "
                   + f'"{Path(__file__).with_name("FxFpumaxVecFloatSites.cpp")}"'
                   + " /Fe:regression.exe /link /OPT:REF")
        script = output / "run.cmd"
        script.write_text('@echo off\ncall "' + str(WORKFLOW / "tools/build/msvc_env.bat")
                          + '" >nul 2>&1\nif errorlevel 1 exit /b 1\n' + command
                          + '\nif errorlevel 1 exit /b 1\nregression.exe\nexit /b %ERRORLEVEL%\n',
                          encoding="utf-8", newline="\r\n")
        sys.exit(subprocess.run(["cmd", "/c", str(script)], cwd=output).returncode)


if __name__ == "__main__":
    main()
