#ifndef CGS_SERVER_INTERFACE_ERRORS_H
#define CGS_SERVER_INTERFACE_ERRORS_H

#include "types.hpp"

// ===========================================================================
// CgsNetwork::EServerInterfaceError
//   Home: GameShared/GameClasses/Network/ServerInterface/CgsServerInterfaceErrors.h
//
// The unified result enum returned by every DirtySock server-interface component
// (ConvertError maps a raw DirtySock error fourcc to one of these). The enumerator
// set is recovered verbatim from the Feb-2007 partial source
// (CgsServerInterfaceErrors.h); the Jan-2008 ARTIST build retains the same scheme
// (the per-component error tables index into the DOWNLOADABLE_CONFIG / HTTP / ...
// sub-ranges below).
//
// Underlying type is plain int to match the forward declaration
//   enum EServerInterfaceError : s32;
// used by the DirtySock headers.
// ===========================================================================

namespace CgsNetwork
{
    enum EServerInterfaceError
    {
        E_SERVER_INTERFACE_ERROR_NONE,
        E_SERVER_INTERFACE_ERROR_UNHANDLED,

        E_SERVER_INTERFACE_GENERAL_ERROR_START,
        E_SERVER_INTERFACE_GENERAL_ERROR_MISSING_PARAMS = E_SERVER_INTERFACE_GENERAL_ERROR_START,
        E_SERVER_INTERFACE_GENERAL_ERROR_INVALID_PARAMS,
        E_SERVER_INTERFACE_GENERAL_ERROR_MASTER_NOT_AUTH,
        E_SERVER_INTERFACE_GENERAL_ERROR_END,

        E_SERVER_INTERFACE_CONNECTION_ERROR_START,
        E_SERVER_INTERFACE_CONNECTION_ERROR_GENERAL = E_SERVER_INTERFACE_CONNECTION_ERROR_START,
        E_SERVER_INTERFACE_CONNECTION_ERROR_DATABASE_ERROR,
        E_SERVER_INTERFACE_CONNECTION_ERROR_FILTER,
        E_SERVER_INTERFACE_CONNECTION_ERROR_INVALID_MASTER,
        E_SERVER_INTERFACE_CONNECTION_ERROR_MISSING_PARAMETERS,
        E_SERVER_INTERFACE_CONNECTION_ERROR_ALREADY_LOGGED_IN,
        E_SERVER_INTERFACE_CONNECTION_ERROR_LOCKED,
        E_SERVER_INTERFACE_CONNECTION_ERROR_RESERVED,
        E_SERVER_INTERFACE_CONNECTION_ERROR_CONNECTION_TIMEOUT,
        E_SERVER_INTERFACE_CONNECTION_ERROR_SERVER_DOWN,
        E_SERVER_INTERFACE_CONNECTION_ERROR_DISCONNECT,
        E_SERVER_INTERFACE_CONNECTION_ERROR_CHEAT_DEVICE,
        E_SERVER_INTERFACE_CONNECTION_ERROR_DASHBOARD,
        E_SERVER_INTERFACE_CONNECTION_ERROR_PERSONA_SET,
        E_SERVER_INTERFACE_CONNECTION_ERROR_INVALID_PASSWORD,
        E_SERVER_INTERFACE_CONNECTION_ERROR_INVALID_REGKEY,
        E_SERVER_INTERFACE_CONNECTION_ERROR_END,

        E_SERVER_INTERFACE_GAMES_ERROR_START,
        E_SERVER_INTERFACE_GAMES_ERROR_NO_GAMES_FOUND = E_SERVER_INTERFACE_GAMES_ERROR_START,
        E_SERVER_INTERFACE_GAMES_ERROR_UNKOWN_GAME,
        E_SERVER_INTERFACE_GAMES_ERROR_ALREADY_JOINED,
        E_SERVER_INTERFACE_GAMES_ERROR_GAME_FULL,
        E_SERVER_INTERFACE_GAMES_ERROR_INVALID_PASSWORD,
        E_SERVER_INTERFACE_GAMES_ERROR_ALREADY_STARTED,
        E_SERVER_INTERFACE_GAMES_ERROR_GAME_LOCKED,
        E_SERVER_INTERFACE_GAMES_ERROR_INVALID_PARTITION,
        E_SERVER_INTERFACE_GAMES_ERROR_UNKNOWN_USERSET,
        E_SERVER_INTERFACE_GAMES_ERROR_USERSET_NOT_LOCKED,
        E_SERVER_INTERFACE_GAMES_ERROR_PLAYER_BANNED,
        E_SERVER_INTERFACE_GAMES_ERROR_USER_NOT_JOINED,
        E_SERVER_INTERFACE_GAMES_ERROR_ALREADY_IN_GAME,
        E_SERVER_INTERFACE_GAMES_ERROR_ALREADY_QUICK_JOINING,
        E_SERVER_INTERFACE_GAMES_ERROR_NAME_ALREADY_EXISTS,
        E_SERVER_INTERFACE_GAMES_ERROR_UNKNOWN_ROOM,
        E_SERVER_INTERFACE_GAMES_ERROR_NOT_USERSET_HOST,
        E_SERVER_INTERFACE_GAMES_ERROR_TOO_MANY_GAMES_IN_ROOM,
        E_SERVER_INTERFACE_GAMES_ERROR_HOST_CANT_LEAVE,
        E_SERVER_INTERFACE_GAMES_ERROR_NOT_HOST,
        E_SERVER_INTERFACE_GAMES_ERROR_NOT_IN_GAME,
        E_SERVER_INTERFACE_GAMES_ERROR_NOT_OWNER_OF_GUEST,
        E_SERVER_INTERFACE_GAMES_ERROR_NOT_ENOUGH_PLAYERS,
        E_SERVER_INTERFACE_GAMES_ERROR_UNKNOWN_USER,
        E_SERVER_INTERFACE_GAMES_ERROR_BOGUS_RESULT,
        E_SERVER_INTERFACE_GAMES_ERROR_QUIT,
        E_SERVER_INTERFACE_GAMES_ERROR_RESULT_TOO_SOON,
        E_SERVER_INTERFACE_GAMES_ERROR_END,

        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_START,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_FIND_BUSY = E_SERVER_INTERFACE_PLAYER_INFO_ERROR_START,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_REQUEST_TOO_SOON,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_FIND_INVALID_PARAMETERS,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_STAT_MISC,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_STAT_INVALID_VIEW,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_STAT_PLAYER_NOT_FOUND,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_STAT_VIEW_NOT_SELECTED,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_STAT_BAD_SLOT,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_STAT_BUSY,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_STAT_TIMEOUT,
        E_SERVER_INTERFACE_PLAYER_INFO_ERROR_END,

        E_SERVER_INTERFACE_FEEDBACK_START,
        E_SERVER_INTERFACE_FEEDBACK_MASTER_AUTH = E_SERVER_INTERFACE_FEEDBACK_START,
        E_SERVER_INTERFACE_FEEDBACK_PERSONA_AUTH,
        E_SERVER_INTERFACE_FEEDBACK_REPORTING_DISABLED,
        E_SERVER_INTERFACE_FEEDBACK_INVALID_PLAYER,
        E_SERVER_INTERFACE_FEEDBACK_SELF,
        E_SERVER_INTERFACE_FEEDBACK_PLAYER_NOT_POSTED,
        E_SERVER_INTERFACE_FEEDBACK_COUNT,

        E_SERVER_INTERFACE_HTTP_ERROR_START,
        E_SERVER_INTERFACE_HTTP_ERROR_CONNECTION_TIMEOUT = E_SERVER_INTERFACE_HTTP_ERROR_START,
        E_SERVER_INTERFACE_HTTP_ERROR_DOWNLOAD_FAILURE,
        E_SERVER_INTERFACE_HTTP_ERROR_INVALID_DOWNLOAD_DATA,
        E_SERVER_INTERFACE_HTTP_ERROR_END,

        E_SERVER_INTERFACE_SERVER_INFO_ERROR_START,
        E_SERVER_INTERFACE_SERVER_INFO_ITEM_NOT_FOUND = E_SERVER_INTERFACE_SERVER_INFO_ERROR_START,
        E_SERVER_INTERFACE_SERVER_INFO_ERROR_END,

        E_SERVER_INTERFACE_DOWNLOADABLE_CONFIG_ERROR_START,
        E_SERVER_INTERFACE_DOWNLOADABLE_CONFIG_ERROR_MISSING_CONFIG_FILE = E_SERVER_INTERFACE_DOWNLOADABLE_CONFIG_ERROR_START,
        E_SERVER_INTERFACE_DOWNLOADABLE_CONFIG_ERROR_DOWNLOAD_IN_PROGRESS,
        E_SERVER_INTERFACE_DOWNLOADABLE_CONFIG_ERROR_TIMEOUT,
        E_SERVER_INTERFACE_DOWNLOADABLE_CONFIG_ERROR_END,

        E_SERVER_INTERFACE_TELEMETRY_ERROR_START,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_NOT_CONNECTED = E_SERVER_INTERFACE_TELEMETRY_ERROR_START,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_UPLOAD_IN_PROGRESS,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_NOT_INITIALISED,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_BUFFER_FULL,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_SAVE_BUFFER_TOO_SMALL,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_NOTHING_TO_SAVE,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_NOTHING_TO_LOAD,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_FAILED_TO_LOAD_SNAPSHOT,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_NO_AUTH_STRING,
        E_SERVER_INTERFACE_TELEMETRY_ERROR_END,

        E_SERVER_INTERFACE_RANKINGS_START,
        E_SERVER_INTERFACE_RANKINGS_INVALID_CATEGORY = E_SERVER_INTERFACE_RANKINGS_START,
        E_SERVER_INTERFACE_RANKINGS_INVALID_INDEX,
        E_SERVER_INTERFACE_RANKINGS_INVALID_VARIATION,
        E_SERVER_INTERFACE_RANKINGS_INVALID_VIEW,
        E_SERVER_INTERFACE_RANKINGS_LIST_NOT_DOWNLOADED,
        E_SERVER_INTERFACE_RANKINGS_RANKINGS_NOT_DOWNLOADED,
        E_SERVER_INTERFACE_RANKINGS_MISC,
        E_SERVER_INTERFACE_RANKINGS_TIMEOUT,
        E_SERVER_INTERFACE_RANKINGS_OUT_OF_MEMORY,
        E_SERVER_INTERFACE_RANKINGS_LOBBY_INVALID,
        E_SERVER_INTERFACE_RANKINGS_DOWNLOAD_IN_PROGRESS,
        E_SERVER_INTERFACE_RANKINGS_INVALID_COL,
        E_SERVER_INTERFACE_RANKINGS_INVALID_ROW,
        E_SERVER_INTERFACE_RANKINGS_END,

        E_SERVER_INTERFACE_ERROR_COUNT
    };
}

#endif // CGS_SERVER_INTERFACE_ERRORS_H
