#include "GameSource/Sound/Module/LogicModule/BrnEffectControl.h"

// =============================================================================
// BrnSound::Logic::BrnEffectControl — out-of-line bodies.
// Reconstructed from BURNOUT_X360_ARTIST.XEX. See BrnEffectControl.h for the
// dual-base layout rationale and the X360-32-bit-vs-host-64-bit offset note.
//
// This TU's recon'd function set is exactly two entries:
//   ~BrnEffectControl  (the X360 `vector deleting destructor`)  @ 0x826AEF68
//   `vector deleting destructor' adjustor{4}                    @ 0x82696868
// Both are reproduced below (the second is a compiler-generated thunk; see note).
//
// dep_flags: none un-homed for THIS TU. The destructor teardown touches only
// meAttachState / meDetachState / mbResourcesReady (all modelled BY NAME). The
// (a2 & 1) deallocation tail dispatches the global sound allocator (off_82FFB954);
// that allocator vtable is not homed here, so the `delete` half of the X360 vector
// deleting destructor is left to the host toolchain rather than reproducing the raw
// allocator vtable call (same treatment as the BrnEffectObject sibling home).
// =============================================================================

namespace BrnSound
{
namespace Logic
{

// ---------------------------------------------------------------------------
// ~BrnEffectControl  @ 0x826AEF68  (the X360 `vector deleting destructor`)
//
//   stw  off_820AEA6C, 0(r31)      ; primary vptr (EffectControl path)
//   stw  off_820AEA38, 4(r31)      ; (transient) base-class IResourceRequester vptr
//   li   r7, 3 ; stw r7, 0x28(r31)  ; meDetachState = E_DETACH_STATE_FINISHED
//   stw  off_820AA820, 4(r31)      ; final IResourceRequester sub-object vptr
//   stb  0, 0x31(r31)              ; mbResourcesReady = false
//   stw  0, 0x24(r31)             ; meAttachState = E_ATTACH_STATE_NONE
//   if (a2 & 1) { ... deallocate via off_82FFB954 (the MemBase allocator) }
//   return this
//
// The leading vptr stores are the compiler-emitted devirtualization of the
// destructor base sub-objects; in reconstructed C++ they are produced implicitly
// by the destructor chain, so the BODY here is the observable member teardown.
// The store ORDER below mirrors the asm: meDetachState (+0x28), then mbResourcesReady
// (+0x31), then meAttachState (+0x24).
// FLAG: the (a2 & 1) tail invokes the global sound allocator (off_82FFB954) to free
// the object; that allocator is not homed here, so operator-delete dispatch is left
// to the host toolchain (the `delete` half of the X360 vector deleting destructor).
// ---------------------------------------------------------------------------
BrnEffectControl::~BrnEffectControl()
{
    meDetachState    = CgsSound::Logic::EffectBase::E_DETACH_STATE_FINISHED; // stw 3, 0x28
    mbResourcesReady = false;                                               // stb 0, 0x31
    meAttachState    = CgsSound::Logic::EffectBase::E_ATTACH_STATE_NONE;     // stw 0, 0x24
}

// ---------------------------------------------------------------------------
// `vector deleting destructor' adjustor{4}  @ 0x82696868
//
//   addi r3, r3, -4
//   b    ~BrnEffectControl (vector deleting destructor @ 0x826AEF68)
//
// The IResourceRequester sub-object lives at this+4; a delete through an
// IResourceRequester* enters here, recovers the primary BrnEffectControl `this`
// (this - 4), and forwards to the real destructor. In reconstructed C++ this thunk
// is generated by the compiler from the multiple-inheritance vtable layout (the
// destructor declared in the header is virtual and reached through the
// IResourceRequester base), so no hand-written body is emitted.
// FLAG: thunk reproduced structurally by the dual-base declaration in the header;
// not a hand-bodied function.
// ---------------------------------------------------------------------------

} // namespace Logic
} // namespace BrnSound
