// Compile-only instantiation harness for BrnGameState::OnlineFlybyManager.
// Embeds the manager by value and exercises several of the twelve recovered functions so their
// bodies are code-generated by the gate (cl /c). Not shipped; not linked.

#include "types.hpp"

#include "GameSource/GameState/FlybyManager/BrnGameStateOnlineFlybyManager.h"

namespace
{
struct OnlineFlybyManagerEmbed
{
    BrnGameState::OnlineFlybyManager mManager;
};

void ExerciseOnlineFlybyManager(OnlineFlybyManagerEmbed& lEmbed)
{
    BrnGameState::OnlineFlybyManager& lManager = lEmbed.mManager;

    BrnGameState::FlybyManager::RivalRating lRating;
    lRating.mbHasValidRelationship = false;
    lRating.mPlayerID = 7;
    lRating.miRivalWeighting = 0;

    volatile s32 liCars = lManager.CalculateNumberOfCarsInFlyby();
    (void)liCars;

    lManager.CalculateOnlineRivals();
    lManager.CalculateRivalryRating(&lRating);
    lManager.CalculateNewOrOngoingRivalryRating(&lRating);
    lManager.CalculateMarkedManRivalryRating(&lRating);
    lManager.CalculatePointsLeaderRating(&lRating);

    const u8* lpName = lManager.GetRivalName(lRating.mPlayerID);
    (void)lpName;

    volatile s32 liOngoing = lManager.GetOngoingStat(
        &lRating, BrnGameState::OnlineFlybyManager::E_ONGOING_RIVALRY_MARKS,
        BrnGameState::OnlineFlybyManager::E_MESSAGE_STYLE_POSITIVE);
    volatile s32 liNew = lManager.GetNewRivalryStat(
        &lRating, BrnGameState::OnlineFlybyManager::E_NEW_RIVALRY_EVENTS,
        BrnGameState::OnlineFlybyManager::E_MESSAGE_STYLE_NEGATIVE);
    volatile s32 liNo = lManager.GetNoRivalryStat(
        &lRating, BrnGameState::OnlineFlybyManager::E_NO_RIVALRY_WINS);
    volatile s32 liCntOngoing = lManager.CountAvailableOngoingRivalryMessages(
        BrnGameState::OnlineFlybyManager::E_ONGOING_RIVALRY_WINS,
        BrnGameState::OnlineFlybyManager::E_MESSAGE_STYLE_POSITIVE);
    volatile s32 liCntNew = lManager.CountAvailableNewRivalryMessages(
        BrnGameState::OnlineFlybyManager::E_NEW_RIVALRY_LONGEST_STREAK,
        BrnGameState::OnlineFlybyManager::E_MESSAGE_STYLE_NEGATIVE);

    (void)liOngoing;
    (void)liNew;
    (void)liNo;
    (void)liCntOngoing;
    (void)liCntNew;
}
}

extern "C" void BrnGameStateOnlineFlybyManager_EmbedCheckAnchor(void* lpEmbed)
{
    ExerciseOnlineFlybyManager(*static_cast<OnlineFlybyManagerEmbed*>(lpEmbed));
}
