#pragma once

#include "types.hpp"

// ===================================================================================================
// BrnGameState::ModeManager -- THE OWNING HEADER (wave-B keystone grow, 2026-08-26)
// ===================================================================================================
// This header was a POINTER-ONLY / bounded slice until wave B. It now carries the FULL offline-spine
// member layout recovered from the X360 layout oracle ModeManager::Construct @0x82340008 (every
// console byte offset below is quoted from that body's stores or from the spine reader that pins it),
// cross-checked against the DecFIGS PS3 DWARF (references/DecFIGS/dwarfdump/GameSource/GameState/
// ModeManager/BrnModeManager.h). WHERE THE TWO DISAGREE THE X360 ASM WINS -- see the ORDER NOTES.
//
// ---------------------------------------------------------------------------------------------------
// FROZEN-HEADER CONTRACT (wave B): agents 2..9 body their functions against THIS declaration set and
// do NOT edit this file. Header friction goes to the conductor as a requested edit.
// ---------------------------------------------------------------------------------------------------
//
// [!!] MOUNT CONTRACT -- READ BEFORE MOUNTING ANYTHING.
// The grow embeds FOURTEEN concrete GameMode-derived objects, the HUDMessageLogic and the
// ScoringSystemDebugComponent BY VALUE. That makes ModeManager's implicit default constructor
// reference (a) BrnGameState::GameMode::GameMode(), (b) the fourteen concrete modes' vtables --
// i.e. EVERY virtual each of them declares -- and (c) CgsDev::DebugComponent::DebugComponent() plus
// ScoringSystemDebugComponent's two overrides. GameStateModule embeds ModeManager by value and
// BrnMain.cpp holds the game module in static storage, so that constructor IS emitted in the shipping
// link -- this is already true today: BrnBaselineLinkStubs.cpp:97 exists precisely because
// ModeManager::ModeManager() references ScoringSystem::ScoringSystem().
// => THE CORE MOUNT (BrnGameMode.cpp + BrnOfflineGameMode.cpp + BrnOnlineGameMode.cpp + the fourteen
//    concrete mode TUs + Hud/BrnHUDMessageLogic.cpp + Debug/BrnScoringSystemDebugComponent.cpp +
//    CgsDebugComponent.cpp) MUST LAND IN THE SAME COMMIT AS THIS HEADER, or
//    tools/build/build_game_exe.bat stops linking. The compile gate (selfcheck.py) CANNOT see this --
//    it is /c only.
//
// [x][x] THE 2026-08-26 FIX-ROUND AMENDMENT THAT USED TO SIT HERE IS WITHDRAWN -- ALL THREE OF ITS
// BLOCKING CLAIMS WERE OVERTAKEN BY THE 12:04 BrnGameMode.h/.cpp LANDING AND ARE NOW FALSE.
// Re-verified against the on-disk tree, 2026-08-26 (stuntrace waveB CLOSURE round):
//   * It listed FOUR GameMode base symbols as "DECLARED and DEFINED NOWHERE IN src/" --
//     GameMode::GameMode(), GetName(), ShouldCountdownEnd() and Start(). All four have bodies:
//     BrnGameMode.cpp:60, :570, :612, :557. So do the other twenty-two virtuals; the file defines
//     all 26 slots plus the ctor (the amendment's shorter "defines only ..." list is stale).
//     No LNK2019 remains from this lane, and no BrnBaselineLinkStubs.cpp entry is needed for it.
//   * (a) GameMode+0xAC IS mbIsOnline, not mbConstructed -- CORRECT, and APPLIED. The member is
//     spelled mbIsOnline at GameModes/BrnGameMode.h:373 (+172), IsOnline() returns it, and both
//     writers are re-pointed (BrnOfflineGameMode.cpp:41 `mbIsOnline = false`,
//     BrnOnlineGameMode.cpp:21 `mbIsOnline = true`). Every `mpCurrentGameMode->IsOnline()` in this
//     TU is live again -- see BrnModeManager_Start.cpp:536 and :621.
//   * (b) The 12-virtual block is gone: BrnGameMode.h now carries the 26-slot console order with a
//     slot-by-slot map dumped from the fifteen concrete mode vtables, PreWorldUpdate at slot 2 in
//     its real arity and ShouldExit at slot 13 taking const ScoringSystem*. [!] READ THAT MAP'S
//     ROWS, NOT ITS COLUMN HEAD: the value column is RaceMode's OWN vtable word, and row 16
//     (GetOutroTimeout) is the one row where RaceMode overrides the base -- corrected in the
//     closure round, with the eight-vtable consensus that pins the 0.1f base spelled out in place.
// [x] THE TWO GameModes/ ARITY BREAKS THIS BLOCK USED TO NAME AS THE REMAINING MOUNT BLOCKER ARE
// CLOSED (re-checked on disk, closure round): BrnOnlineStuntRunMode.h:41 and BrnOnlineRaceMode.h:27
// now declare PreWorldUpdate in the six-argument slot-2 shape, both .cpp bodies forward the buffers
// to their base (BrnOnlineStuntRunMode.cpp:103, BrnOnlineRaceMode.cpp:78), and each header carries
// the member-pointer static_assert that re-binds the base signature onto the derived class
// (BrnOnlineStuntRunMode.h:91, BrnOnlineRaceMode.h:54) -- so a future silent slot-mint is a compile
// error, not a runtime ghost. StuntAttackMode declares and bodies slot 2 as well.
// STILL TRUE, AND STILL THE MOUNT RULE: the CORE MOUNT listed above must land in the SAME commit as
// this header, and the compile gate (selfcheck.py, /c only) cannot see that -- it is /c only, so
// NOTHING in this lane's gate can prove the link. Full evidence:
// scratch/stuntrace_waveb/vtable_ground_truth.md and seam_audit.md S6.
// ===================================================================================================

#include "BrnCommonTypes.h"                             // Vector3, CgsID
#include "GameSource/GameState/BrnGameStateSharedIO.h"  // GameStateModuleIO::EGameModeType/EGameModeState, CarCheckpointData, KI_MAX_LANDMARKS_IN_MODE
#include "GameSource/GameState/BrnGameEvents.h"         // GameStateModuleIO::StartNetworkGameEvent (SetOnlineRaceCars signature)
#include "GameSource/GameState/BrnGameStateTypes.h"     // BrnGameState::LandmarkIndex (mPlayerCurrentLandmark)
#include "GameSource/BurnoutConstants.h"                // EGlobalRaceCarIndex / EActiveRaceCarIndex (the 35 / 8 car spaces)
#include "GameShared/GameClasses/Containers/CgsBitArray.h" // CgsContainers::BitArray<35> (the two reached-sets)
#include "GameShared/GameClasses/Core/CgsAssert.h"      // CGS_ASSERT (house assert macro)

// -- embedded sub-objects, by value (console offsets in the member run below) -----------------------
#include "GameSource/GameState/ModeManager/Scoring/BrnScoringSystem.h"   // ScoringSystem                @+3504
#include "GameSource/GameState/ModeManager/Hud/BrnHUDMessageLogic.h"     // HUDMessageLogic              @+27392
#include "GameShared/GameClasses/Numeric/CgsRandom.h"                    // CgsNumeric::Random           @+28016
#include "GameShared/GameClasses/System/Timer/CgsTimerStatusInterface.h" // TimerStatusInterface         @+28064
#include "GameSource/GameState/ModeManager/Debug/BrnScoringSystemDebugComponent.h" // ScoringSystemDebugComponent @+28136
#include "GameSource/GameState/BrnGameActions.h"                         // GameStateModuleIO::PrepareForModeAction @+35856
                                                                         //   (BY VALUE -- the memcpy'd wire record) and,
                                                                         //   transitively, BrnGameModeParams.h:
                                                                         //   StartGameModeParams @+32832 / GameModeParams @+33664
// [X][X] DO NOT INCLUDE BrnGameStateModuleIO.h HERE. It was tried and REVERTED on 2026-08-26:
// it reaches BrnTakedownManagerTypes.h through GameSource/Network/BrnNetworkModuleIO.h, and that
// header defines a SECOND `enum EActiveRaceCarIndex : s32` inside `namespace BrnGameState` (the
// known dual-scope hazard BrnGameStateModuleIO.h:630 documents). Pulling it in here made every
// unqualified `EActiveRaceCarIndex` in this class body -- and in every TU that includes this header
// -- bind to BrnGameState::EActiveRaceCarIndex instead of the global BurnoutConstants.h one, i.e.
// silently re-mangled the already-committed ModeManager signatures. The spine buffers are used BY
// POINTER / REFERENCE only in the declarations below, so forward declarations are enough; each
// agent includes BrnGameStateModuleIO.h in its OWN partfile, where the scope question is local.

// -- the fourteen embedded concrete game modes (ORDER NOTE 2: fourteen, not the DWARF's fifteen) ----
#include "GameSource/GameState/ModeManager/GameModes/BrnGameMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnRaceMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnFaceOffMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnCrashMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnRoadRageMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnPursuitMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnBurningRoute.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnStuntAttackMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnSurvivor.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnOnlineRaceMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnOnlineRoadRageMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnOnlineStuntRunMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnOnlineBurningHomeRunMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnOnlineFreeBurnLobbyMode.h"
#include "GameSource/GameState/ModeManager/GameModes/BrnOnlineShowtimeMode.h"

// -- reader-side types the bodied methods walk ------------------------------------------------------
#include "SharedClasses/Trigger/BrnTriggerData.h"       // BrnTrigger::TriggerData (checkpoint landmark lookup)
#include "SharedClasses/Trigger/BrnLandmark.h"          // BrnTrigger::Landmark / BoxRegion::GetPosition

namespace BrnProgression
{
// Pointer-only: mpProgressionManager + GetProgressionManager(). Owning header is
// GameSource/GameState/Progression/BrnProgressionManager.h (the .cpp files that walk it include it).
class ProgressionManager;
}

namespace BrnResource
{
// Pointer-only: ModeManager::Prepare's freeburn-challenge list argument (DWARF :128).
class ChallengeList;
}

namespace CgsMemory
{
// Pointer-only: ModeManager::Prepare's heap argument, forwarded to ScoringSystem::Prepare (DWARF :128).
class HeapMalloc;
}

namespace BrnTraffic
{
// Pointer-only: GetTrafficData() / GetStartDataForTrafficLight() returns. Owning headers are
// SharedClasses/Traffic/BrnTrafficDataResourceType.h and .../BrnTrafficLightTrigger.h.
struct TrafficData;
struct LightTriggerStartData;
}

namespace BrnNetwork { namespace BrnNetworkModuleIO { struct InGamePlayerStatusInterface; } }

namespace CgsModule { template <typename T> class BaseEventQueue; }          // ProcessPlayerCrashes(queue) overload
namespace BrnPhysics { namespace Vehicle { struct RaceCarCrashEvent; } }      // (element type; complete in the .cpp)

namespace BrnGameState
{
class GameStateModule;
class NetworkRoundManager;
class TriggerQueryManager;
class StreetManager;
class MugshotManager;
class RoadRulesManager;
class ModeManagerDebugComponent;   // [X] NOT embedded -- see the DIVERGENCE at its console seat below.
class ChallengeManager;            // [X] NOT embedded -- see the DIVERGENCE at its console seat below.

namespace GameStateModuleIO
{
    // Spine-parameter buffers -- BY POINTER / REFERENCE ONLY in this header (see the
    // BrnGameStateModuleIO.h include ban above). Real definitions: BrnGameStateModuleIO.h.
    struct OutputBuffer;
    struct PreWorldInputBuffer;
    struct PostWorldInputBuffer;

    // FLAG (declared-only, used by pointer): the event record PlayerFinishedMode consumes
    // (DWARF BrnModeManager.h:397). No owning definition exists in the tree yet; a declaration may
    // name an incomplete type, and agent 6 bodies PlayerFinishedMode against whatever the event TU
    // lands. DO NOT invent a layout for it here.
    struct PlayerFinishedModeEvent;
}

// ===================================================================================================
//  ModeManager
// ===================================================================================================
class ModeManager
{
public:
    // -----------------------------------------------------------------------------------------------
    // KI_GAME_MODE_SLOTS -- the E_MODE_COUNT 17-vs-18 resolution (conductor decision #3).
    //
    // AUDIT RESULT (2026-08-26; every consumer of GameStateModuleIO::E_MODE_COUNT in the tree grepped.
    // The E_MODE_COUNT enumerators in BrnRaceEventData.h (== 6), BrnMomentSelector.h (== 2) and
    // BrnEventPanel.h are DIFFERENT enums and are not affected):
    //   1. BrnGameStateRichPresenceManagerBase.cpp:235 declares
    //      KE_GAME_MODES_TO_RICH_PRESENCE_STATES[E_MODE_COUNT + 1]. The console's rodata table at
    //      X360 0x8202AF20 is EIGHTEEN entries == E_MODE_COUNT(17) + 1. Raising E_MODE_COUNT to 18
    //      would silently make that a 19-entry table.
    //   2. BrnInGame.cpp:473 asserts liGameModeType < E_MODE_COUNT + 1 (i.e. < 18), with its own
    //      comment saying the console's bound is 18. Raising E_MODE_COUNT would weaken it to < 19.
    //   3. BrnGameStateSharedIO.h:81-82 spells E_MODE_ONLINE_MODE_END == E_MODE_COUNT == 17 -- the
    //      same deliberate aliasing as E_MODE_OFFLINE_COUNT == E_MODE_ONLINE_MODE_START == 10, and the
    //      GUI TUs (BrnOnlineGameOptions_wI_01/_wI_07) comment on that alias as intentional. Mode 17
    //      is a REAL dispatchable mode (BrnScoringSystem_Timer.cpp:362, _Lookup.cpp:430,
    //      _Lifecycle.cpp:317; UpdateCurrentMode case 0x11), so on this build E_MODE_COUNT is not a
    //      count at all -- it is the last enumerator.
    // => TWO consumers semantically depend on E_MODE_COUNT == 17, so the enum is LEFT ALONE and the
    //    real count lands here as the sidecar decision #3 authorised. THIS is the dispatch-array
    //    extent and the console's own bound: Construct zeroes 18 slots and ctor-loops 18 slots;
    //    StartGameMode / GetCountdownTimeForMode assert `< 0x12`; the countdown table at X360
    //    0x82020E98 is 18 f32s; CarSelectMain::KPAC_MODE_STRINGS is [18].
    static const s32 KI_GAME_MODE_SLOTS = 18;

    // The per-mode pre-race countdown table, recovered big-endian from the image @0x82020E98 (18
    // entries, indexed by EGameModeType). Recorded here so GetCountdownTimeForMode's TU (agent 8)
    // defines it once from a cited dump instead of guessing:
    //   { 2.5f, 6.0f, 0.0f, 3.3f, 3.0f, 5.0f, 5.0f, 2.5f, 3.3f,
    //     5.0f, 3.0f, 3.0f, 3.0f, 3.0f, 3.0f, 0.0f, 0.0f, 3.0f }
    // [!] AUTHORED ZEROES: entries 2 (OFFLINE_SHOWTIME), 15 (ONLINE_FREE_BURN_LOBBY) and 16
    // (ONLINE_SHOWTIME) are 0.0f IN THE SHIPPED ROM -- design, not placeholders. Any placeholder-zero
    // sweep must leave them alone. Entries 3 and 8 are 0x40533333 (3.2999999523f): author them 3.3f.
    // [!] HEX CORRECTED 2026-08-26 (was 0x3F533333, which is 0.825f -- an error inherited from
    // header_grow_spec section 3.4). The whole table was re-dumped from image.bin this pass:
    //   40200000 40C00000 00000000 40533333 40400000 40A00000 40A00000 40200000 40533333
    //   40A00000 40400000 40400000 40400000 40400000 40400000 00000000 00000000 40400000
    // The VALUE 3.3f was always right; only the hex was wrong. Author from the value, not the hex.
    // Team bonuses: +5.0 s for team 1 in mode 11, +3.0 s for team 1 in mode 13.

    // ===============================================================================================
    // LIFECYCLE
    // ===============================================================================================

    // X360 0x82340008 -- THE LAYOUT ORACLE. Eight arguments (DWARF BrnModeManager.h:122; IDA's 28-int
    // prototype is "local variable allocation has failed" garbage -- hazards H9). Argument identity is
    // proven from the asserts the body fires: "lpGameStateModule" / "lpProgressionManager" /
    // "lpNetworkRoundManager" (BrnModeManager.cpp:202/205/210), "lpStreetManager" / "lpMugshotManager"
    // (BrnOnlineFreeBurnLobbyMode.h:175/190 AND BrnBurnoutSkillzManager.h:265/280 -- the console fires
    // BOTH because both inline setters are inlined), the RoadRules pointer forwarded as
    // ChallengeManager::Construct's 4th argument, and the AchievementManager forwarded to
    // ScoringSystem::Construct.
    void Construct(GameStateModule*                      lpGameStateModule,
                   BrnProgression::ProgressionManager*   lpProgressionManager,
                   TriggerQueryManager*                  lpTriggerQueryManager,
                   NetworkRoundManager*                  lpNetworkRoundManager,
                   StreetManager*                        lpStreetManager,
                   MugshotManager*                       lpMugshotManager,
                   const RoadRulesManager*               lpRoadRulesManager,
                   StuntModeScoring::AchievementManager* lpAchievementManager);

    // X360 0x823407A0 (DWARF :128). ChallengeManager::Prepare && ScoringSystem::Prepare.
    bool Prepare(const BrnResource::ChallengeList* lpFreeburnChallengeList,
                 CgsMemory::HeapMalloc*            lpHeapMalloc);

    // [tut-ticker] THE BRING-UP SEAM (kept; see the supersession banner in ModeManager_gUI_00.cpp).
    // Construct above is landed but UNCALLED: four of its eight arguments are not reachable at
    // GameStateModule::Construct's call position today. This is the ONLY armed construction path.
    // DELETE-WHEN the four land (the exact condition is spelled out in the partfile banner).
    void ConstructInterModeStateBringUp(GameStateModule* lpGameStateModule);

    // The extracted CLOCK leg of ModeManager::PreWorldUpdate @0x823537B8 (bring-up; superseded by the
    // full PreWorldUpdate below the moment THAT is mounted -- never both armed).
    void PreWorldUpdateClocksBringUp(f32 lfGameTimestep);

    // ===============================================================================================
    // PER-FRAME SPINE  (agents 7a / 7b)
    // ===============================================================================================

    // DWARF BrnModeManager.h:150 -- the ten-argument shape, verbatim.
    void PreWorldUpdate(GameStateModuleIO::OutputBuffer*              lpOutputBuffer,
                        const GameStateModuleIO::PreWorldInputBuffer* lpPreWorldInputBuffer,
                        const CgsSystem::TimerStatusInterface&        lrTimerStatusInterface,
                        EActiveRaceCarIndex                           lePlayerActiveRaceCarIndex,
                        EGlobalRaceCarIndex                           lePlayerGlobalRaceCarIndex,
                        bool                                          lbIsOnline,
                        GameStateModuleIO::GameActionQueue*           lpGameActionQueue,
                        const BrnWorld::RaceCarEntityModuleIO::RCEntityGlobalRaceCarOutputInterface* lpGlobalRaceCarOutput,
                        const BrnWorld::RaceCarEntityModuleIO::RCEntityActiveRaceCarOutputInterface* lpActiveRaceCarOutput,
                        bool                                          lbPaused);

    // DWARF :156 (X360 0x8234A9E0). The console's middle argument is the takedown-event queue --
    // CgsModule::EventQueue<TakedownEvent, 8> in the GameState flavour. It is NOT spelled here
    // because no GameStateModuleIO typedef for it exists yet and a template instantiation cannot be
    // forward-declared; agent 7a needs it and it is filed as a header_request. Until then the
    // takedown leg is reached from the PostWorldInputBuffer, which carries the same queue.
    void PostWorldUpdate(const GameStateModuleIO::PostWorldInputBuffer* lpPostWorldInputBuffer,
                         f32                                            lfDelta);

    void ProcessPlayerCrashes(const GameStateModuleIO::PostWorldInputBuffer* lpPostWorldInputBuffer);                 // DWARF :160 / X360 0x8231E638
    // [road-rage wave 2026-09-02, conductor] THE SAME BODY, taking the queue the buffer version
    // reads (PostWorldInputBuffer +0x10 == the world output's VehicleManagerOutputInterface
    // +0x3A0 crash queue, copied there by BridgeWorldToGameState leg 1). Nothing on this build
    // creates a PostWorldInputBuffer (see GameStateModule_gUI_00.cpp's extracted post-world
    // leg), so the leg hands the world's queue straight in -- "THE ARGUMENTS ARE THE DEVIATION,
    // NOT THE BODY". The buffer version delegates here. DELETE-WHEN the real post-world pass
    // (DoUpdate_GameStatePostWorld @0x823E92A8 + the buffer) lands.
    void ProcessPlayerCrashes(const CgsModule::BaseEventQueue<BrnPhysics::Vehicle::RaceCarCrashEvent>* lpRaceCarCrashEventQueue);
    void CheckForOutOfRangeCarsReachingFinish(const GameStateModuleIO::PostWorldInputBuffer* lpPostWorldInputBuffer); // DWARF :164 / X360 0x82340800

    // X360 0x82340AB8 (DWARF :735 plus an X360-only THIRD parameter). ASM BEATS DWARF: the X360 body
    // keeps f1 live across the ChallengeManager call and forwards it to
    // StuntModeScoring::DealWithInProgressStunt, so the console signature carries the frame delta.
    // IDA renders it `double a4` (PPC float promotion) -- it is an f32 (hazards H9).
    void ProcessEvent(GameStateModuleIO::EGameEventType leEventType,
                      const CgsModule::Event*           lpEvent,
                      f32                               lfDelta);

    // ===============================================================================================
    // START / SETUP / EXIT  (agents 2, 3, 4)
    // ===============================================================================================
    void StartGameMode(GameStateModuleIO::OutputBuffer* lpOutputBuffer,
                       StartGameModeParams*             lpStartGameModeParams);                             // DWARF :174 / X360 0x8234FCE8
    void SetupGameMode(GameStateModuleIO::OutputBuffer* lpOutputBuffer,
                       GameModeParams*                  lpGameModeParams,
                       StartGameModeParams*             lpStartGameModeParams);                             // DWARF :239 / X360 0x8234B158
    void ExitCurrentMode(GameStateModuleIO::OutputBuffer* lpOutputBuffer,
                         bool                             lbTimedOut,
                         GameStateModuleIO::EGameModeType leNextGameModeType);                              // DWARF :258 / X360 0x8234FFE0
    void HandleLoadingScreenLoaded(GameStateModuleIO::GameActionQueue* lpGameActionQueue);                   // DWARF :584 / X360 0x8234B8A8
    void SetupPathfinding(const StartGameModeParams* lpStartGameModeParams, GameModeParams* lpGameModeParams); // DWARF :542 / X360 0x823291B0
    void SetUpCheckPointsForGameMode(const StartGameModeParams* lpStartGameModeParams,
                                     GameModeParams*            lpGameModeParams,
                                     ScoringSystem*             lpScoringSystem);                           // DWARF :548 / X360 0x82328BC8
    void SetupOpponentData(const StartGameModeParams* lpStartGameModeParams, GameModeParams* lpGameModeParams); // DWARF :557 / X360 0x82329348
    void SetupCheckpointDistricts(GameModeParams* lpGameModeParams);                                        // DWARF :561 / X360 0x823296F0
    void ResultsAccept();                                                                                   // DWARF :262 / X360 0x82311858
    void FinishOfflineModeIntro();                                                                          // DWARF :274 / X360 0x823119B0

    // ===============================================================================================
    // INTRO / PLAY / FINISH  (agents 5, 6, 8)
    // ===============================================================================================
    void StartModeIntro(GameStateModuleIO::GameActionQueue* lpGameActionQueue);                             // DWARF :421 / X360 0x82343018
    void ShowModeResults(const BrnWorld::RaceCarEntityModuleIO::RCEntityGlobalRaceCarOutputInterface* lpGlobalRaceCarOutput,
                         GameStateModuleIO::GameActionQueue* lpGameActionQueue);                            // DWARF :414 / X360 0x823436D0
    void PlayerFinishedMode(const GameStateModuleIO::PlayerFinishedModeEvent* lpEvent);                     // DWARF :397 / X360 0x823280D8
    void FinishCurrentModeNextUpdate();                                                                     // DWARF :245
    void FinishCurrentModeNextUpdateWithFinishPosition(s32 liFinishPosition);                               // DWARF :250
    const BrnTraffic::LightTriggerStartData* GetStartDataForTrafficLight(u32 luLightTriggerId) const;        // DWARF :566 / X360 0x82327310

    // ===============================================================================================
    // QUERIES  (agent 9 bodies the small ones)
    // ===============================================================================================
    bool IsInGameMode() const;                                     // DWARF :179
    bool IsInProgress() const;                                     // DWARF :188
    bool IsInPreEvent() const;                                     // DWARF :192
    bool IsInPostEvent() const;                                    // DWARF :196 / X360 0x823113D0  (BODIED, BrnModeManager.cpp)
    GameStateModuleIO::EGameModeState GetCurrentGameModeState() const;                                      // DWARF :227
    u32  GetRoadRageTakedownTarget();                              // DWARF :587 / X360 0x82327518
    s32  GetNumberOfCarsInFlyby();                                 // DWARF :444 / X360 0x82311E38
    bool HasPlayerFinished() const;                                // DWARF :847
    bool IsWaitingForModeDataToLoad() const;                       // DWARF :429 -- returns mbModeDataIsLoading
    bool IsOnlineGameMode() const;                                 // DWARF :432 / X360 0x82311410  (BODIED)
    f32  GetCountdownTimeForMode() const;                          // DWARF :448 / X360 0x82327D10
    bool IsOnlineModeWithInstantIntro() const;                     // (mode == 15 || 16) && mbInstantIntroSplash
    void OnDriveThruRepairAvailable();                             // FLAG: X360 vtbl+0x64 hook; name is conservative (DriveThruManager TU)

    GameStateModuleIO::EGameModeType GetCurrentGameModeType() const { return meCurrentGameModeType; }
    const GameMode* GetCurrentGameMode() const                      { return mpCurrentGameMode; }

    // [tut-ticker] THE THREE MODE CLOCKS. DWARF :1025/:1026/:1027; X360 +0x951C / +0x9520 / +0x9524
    // (== GameStateModule +42300 / +42304 / +42308). Identity proven from the WRITERS, not DWARF
    // order: PreWorldUpdate @0x823537B8 accumulates +0x951C only while no mode is running AND the
    // junkyard id is 0 AND picture-paradise is clear; +0x9520 while a mode IS running; +0x9524 only
    // while that mode is online. All three are zeroed by Construct @0x82340008.
    // [!] NOT OPTIONAL FLAG-ZEROES: TrainingManager::Update's WAIT_FOR_MESSAGE arm only advances when
    // GetTimeInFreeBurn() > 3.0 -- a permanently-zero stand-in kills the whole tutorial ticker.
    f32 GetTimeInFreeBurn() const { return mfTimeInFreeBurn; }
    f32 GetTimeInMode()     const { return mfTimeInMode; }

    ScoringSystem*       GetScoringSystem();                              // == &mScoringSystem (X360 +0xDB0; console inlines the adjust)
    const ScoringSystem* GetScoringSystem() const;

    // == &mHUDMessageLogic (X360 +0x6B00). The console emits NO accessor -- every call site
    // (Construct 0x82340008, Destruct 0x823406E0, StartGameMode 0x8234FCE8, PreWorldUpdate
    // 0x82353CF4, PostWorldUpdate 0x8234B0E8) reaches it through the inlined `this + 27392`
    // pointer adjust. Named here for the SAME reason GetScoringSystem is: the live post-world
    // caller on this build is GameStateModule::PostWorldUpdateStuntBringUp's extracted leg, which
    // is not a member of this class and must not poke a byte offset (hazards H9).
    HUDMessageLogic*     GetHUDMessageLogic()       { return &mHUDMessageLogic; }
    const HUDMessageLogic* GetHUDMessageLogic() const { return &mHUDMessageLogic; }
    GameStateModule*     GetGameStateModule();                            // asserts "mpGameStateModule"
    BrnProgression::ProgressionManager* GetProgressionManager() const;    // returns mpProgressionManager (+0x6D5C)
    const NetworkRoundManager*          GetNetworkRoundManager() const;   // returns mpNetworkRoundManager (+0x6D64)
    const BrnTraffic::TrafficData*      GetTrafficData() const;           // through the TQM's TriggerData resource

    // ---- grid / online-grid helpers (committed declarations; bodies land with agents 5 / 9) -------
    void SetStartingGrid(GameModeParams* lpGameModeParams, s32 liCarCount, bool lbPushForwards) const;   // X360 0x82328608
    void SetOnlineRaceCars(GameModeParams* lpGameModeParams,
                           const GameStateModuleIO::StartNetworkGameEvent* lpStartNetworkGameEvent) const;
    void SetupOnlineStartingGrid(GameModeParams* lpGameModeParams, s32 liNumRaceCars,
                                 CgsNumeric::Random* lpRandom, bool lbPushForwards) const;

    // ===============================================================================================
    // THE 16 COMMITTED BODIES (BrnModeManager.cpp) -- hazards H2: never re-implement these, CALL them.
    // ===============================================================================================
    s32  GetNextLandmarkIndex(EGlobalRaceCarIndex leGlobalRaceCarIndex) const;                       // X360 0x82329890
    u32  CountCheckpointsRemaining(EGlobalRaceCarIndex leGlobalRaceCarIndex) const;                  // X360 0x8231E960
    void MarkCarHittingCheckpoint(u32 luCheckpointIndex, EGlobalRaceCarIndex leGlobalRaceCarIndex);  // X360 0x8231E800
    void ResetCheckpointDataForNextLap(EGlobalRaceCarIndex leGlobalRaceCarIndex);                    // X360 0x8231E8D8
    bool HasRaceCarHitValidCheckpoint(s16 luLandmarkId, EGlobalRaceCarIndex leGlobalRaceCarIndex);   // X360 0x82329910
    bool HasPlayerWon();                                                                             // X360 0x823283E8
    void SetupStuntChallenge();                                                                      // X360 0x8231EB00
    void EndStuntChallenge();                                                                        // X360 0x823120E8
    void SetNetworkStuntScore(BrnNetwork::NetworkPlayerID lNetworkPlayerID, s32 liScore);            // X360 0x82363540
    Vector3 GetCheckpointPosition(u32 luCheckpointId) const;                                         // X360 0x82327388
    void WriteDataToOutput(GameStateModuleIO::ScoringOutputInterface*       lpOutput,
                           GameStateModuleIO::OnlineScoringOutputInterface* lpOnlineOutput,
                           bool                                             lbOnline,
                           EActiveRaceCarIndex                              lePlayerRaceCarIndex);   // X360 0x82337B70
    void FillInRaceDistanceInterface(GameStateModuleIO::RaceCarRaceDistanceInterface* lpRaceDistanceInterface); // X360 0x82327B98
    void SendModeResults(CgsModule::VariableEventQueue<13312, 16>* lpOutputQueue);                   // X360 0x82343438
    void TellGuiToShowOnlineFinalStandings();                                                        // X360 0x82329B68
    s32  GetPlayersFinishPosition();                                                                 // X360 0x823281E8

    // ===============================================================================================
    // THE ACCESSOR GROWS (header_grow_spec section 6). The ModeManager side is declared HERE; the
    // GameStateModule / TriggerQueryManager side landed in agent 9's own lane.
    // [X] DO NOT fabricate the raw offsets in any body -- always go through these.
    //
    // [!!] REVISED 2026-08-26 BY THE WAVE-B FIX ROUND. header_grow_spec section 6 listed FIVE grows;
    // four survive. Every correction below was re-derived from the exports this pass:
    //   * (2a) IS RETIRED. "gsm+0x3C0D0" and "gsm+0x245968" are ONE seat written two ways --
    //     0x3C0D0 == 245968 decimal -- and that seat is the GLOBAL interface, already served by (1).
    //     GameStateModule has no live-ACTIVE embed at all: the live active interface arrives as a
    //     world-module input buffer that this class only ever receives as a function argument
    //     (PreWorldUpdate / UpdateCurrentMode both take one), and GameStateModule::PostWorldUpdate
    //     @0x8238F358 only COPIES it into the two cached snapshots. A sweep of every ModeManager
    //     export for the two numbers accounts for all ten reads: 245968 -> WriteDataToOutput,
    //     HasRaceCarHitValidCheckpoint, TransmitAndIncrementCheckPointsReached,
    //     TransmitAndIncrementFinishReached, HandleBurningHomeRunRunnerSwitch (all GLOBAL);
    //     235488 -> StartGameMode, RemoteRaceCarHitsCheckpoint (mLastActiveRaceCarInterface).
    //     GetActiveRaceCarOutputInterface() had NO console call site and NO source it could be
    //     bodied from, so keeping it declared invited a fabricated body; conductor decision #7's
    //     "never collapse the two embeds" is honoured by DELETING it, not by pointing it somewhere.
    //   * (3) and (4) are RENAMED: their spec names described the wrong quantities (see each).
    // ===============================================================================================
    // (1) X360 mpGameStateModule+0x3C0D0 (== 245968 decimal). The module's cached GLOBAL race-car
    // snapshot, GameStateModule::GetLastGlobalRaceCarInterface().
    const BrnWorld::RaceCarEntityModuleIO::RCEntityGlobalRaceCarOutputInterface* GetGlobalRaceCarOutputInterface() const;
    // (2) DECISION #7 RESOLVED WITHOUT A NEW NAME AND WITHOUT A GROW: the "second active-RC embed"
    // the StartGameMode wreck-count leg reads at gsm+235488 (0x397E0) is ALREADY a named
    // GameStateModule member -- mLastActiveRaceCarInterface (BrnGameStateModule.h:889, "X360
    // +0x397E0"; the accessor cite :626 is the correct one) -- and it ALREADY has an accessor,
    // GameStateModule::GetLastActiveRaceCarInterface(). Its player-car-index field at iface+10328
    // == gsm+245816 matches the offset the scout reported. The two cached embeds are NEVER
    // collapsed with each other, nor with the live input-buffer interface.
    const BrnWorld::RaceCarEntityModuleIO::RCEntityActiveRaceCarOutputInterface* GetLastActiveRaceCarOutputInterface() const;
    // (3) X360 mpGameStateModule+0x32DAC (208300). RENAMED 2026-08-26: the spec called this
    // GetOnlineRoundIndex, but the word it reads is GameStateModule::muNetworkGameRandomSeed
    // (DWARF BrnGameStateModule.h:793) -- written by GameStateModule::ProcessGameEvents @0x823A0A18
    // from the incoming StartNetworkGameEvent's word[3] and cleared to -1 by ClearData @0x8236B3A8.
    // The ROUND index is (4). The two are TellGuiToShowOnlineFinalStandings' first two arguments to
    // ScoringSystem::UpdateCumulativeResults, so swapping them would mis-stamp
    // CarData::miRoundDisconnectedIn.
    s32 GetNetworkGameRandomSeed() const;
    // (4) X360 (nrm+0x12C) - (nrm+0x128) - 1. RENAMED 2026-08-26: the spec called this
    // GetOnlineActiveCarCount and attributed the two words to the GameStateModule. They are the
    // NetworkRoundManager's (miTotalRounds / miRoundsRemaining) -- the base is materialised in
    // TellGuiToShowOnlineFinalStandings @0x82329B68 as `addis r10,r11,1; addi r10,r10,-0x4608` ==
    // gsm+47608, and GameStateModule::Construct @0x82380388 passes `a1 + 47608` as
    // ModeManager::Construct's NetworkRoundManager argument. The value is the 0-based CURRENT ROUND
    // == NetworkRoundManager::GetCurrentRound() (see the ruling in BrnNetworkRoundManager.cpp).
    s32 GetOnlineCurrentRound() const;
    // (5) DWARF :307. The mode's TriggerData, resolved through mpTriggerQueryManager's
    // ResourcePtr<TriggerData> at TQM+1568 (0x620) -- the TQM header already names that accessor in
    // its comments at :151-153. This is what retired the old mpCheckpointTriggerData stand-in member.
    // [!] The TRAFFIC sibling is a DIFFERENT slot: ResourcePtr<TrafficData> at TQM+1600 (0x640).
    // ModeManager::GetStartDataForTrafficLight @0x82327310 reads +0x640, not +0x620.
    const BrnTrigger::TriggerData* GetTriggerData() const;
    const BrnTrigger::TriggerData* GetCheckpointTriggerData() const;

    // [!] FLAG RETIRED 2026-08-26 (it was REFUTED, and it was blocking a body that needs no
    // fabrication). The old text claimed "the interface names only the active->global direction".
    // It does not: BrnRaceCarEntityModuleOutputInterface.h:327 declares
    // `RCEntityGlobalRaceCarOutputInterface::GetActiveRaceCarIndex(EGlobalRaceCarIndex) const`,
    // bodied at BrnRCEntityGlobalRaceCarOutputInterface.cpp:129 (X360 0x821F46C8), over
    // maeActiveRaceCarIndices at interface+0x834 == 4*525 == 2100 -- which is EXACTLY the table the
    // console's `*(4*(global+525)+iface)` indexes, and whose two range asserts
    // (BrnRaceCarEntityModuleOutputInterface.h:1512/1513) are the two assert lines
    // HasRaceCarHitValidCheckpoint @0x82329910 fires around that read. Bodied, not fabricated.
    EActiveRaceCarIndex GlobalToActiveRaceCarIndex(EGlobalRaceCarIndex leGlobalRaceCarIndex) const;

    // -----------------------------------------------------------------------------------------------
    // Debug-menu tunables. PUBLIC ON PURPOSE: ModeManagerDebugComponent::OnActivate registers
    // &mpModeManager->mbEndlessStuntRun / &mbWinIfSecond BY ADDRESS and FinshMode writes
    // mbFinishCurrentEvent / miFinishPosition (BrnModeManagerDebugComponent.cpp:24/27/41/42).
    // [!] FLAG (unchanged from the bounded header): their real X360 seats are NOT proven. What IS now
    // proven is that they are NOT the debug component's own fields -- Construct @0x82340008 seeds the
    // component's OWN three at component+16 / +17 / +20 (mbShowModeInfo = 0, mbInfiniteLives = 0,
    // miFinishPosition = 1, which matches that .cpp's SetRange(&miFinishPosition, 1, 8)). These four
    // are the manager's own.
    // -----------------------------------------------------------------------------------------------
    bool mbEndlessStuntRun;
    bool mbWinIfSecond;
    bool mbFinishCurrentEvent;
    s32  miFinishPosition;

private:
    // ===============================================================================================
    // PRIVATE SPINE (agents 3, 6, 7, 8)
    // ===============================================================================================
    void UpdateCurrentMode(GameStateModuleIO::OutputBuffer*              lpOutputBuffer,
                           const GameStateModuleIO::PreWorldInputBuffer* lpPreWorldInputBuffer,
                           const BrnNetwork::BrnNetworkModuleIO::InGamePlayerStatusInterface* lpPlayerStatusInterface,
                           EActiveRaceCarIndex                           lePlayerActiveRaceCarIndex,
                           bool                                          lbIsOnline,
                           GameStateModuleIO::GameActionQueue*           lpGameActionQueue,
                           const BrnWorld::RaceCarEntityModuleIO::RCEntityGlobalRaceCarOutputInterface* lpGlobalRaceCarOutput,
                           const BrnWorld::RaceCarEntityModuleIO::RCEntityActiveRaceCarOutputInterface* lpActiveRaceCarOutput,
                           bool                                          lbPaused);                    // DWARF :786 / X360 0x82350EC8
    void UpdateCheckpointDistanceRequests(GameStateModuleIO::GameActionQueue* lpGameActionQueue);       // DWARF :791 / X360 0x823279B8
    void FinishCurrentMode(GameStateModuleIO::OutputBuffer* lpOutputBuffer, const CgsSystem::Time& lrTime); // DWARF :799 / X360 0x8234B978
    void CheckCountdownDisplay(GameStateModuleIO::GameActionQueue* lpGameActionQueue);                  // DWARF :804 / X360 0x82342898
    void PrepareForMode(GameStateModuleIO::GameActionQueue* lpGameActionQueue,
                        GameModeParams*                     lpGameModeParams,
                        s32                                 liCurrentRound,
                        StartGameModeParams*                lpStartGameModeParams);                     // DWARF :812 / X360 0x82342930
    void StopModeIntro(GameStateModuleIO::GameActionQueue* lpGameActionQueue);                          // DWARF :822 / X360 0x82343F38
    void StartPlayingMode(GameStateModuleIO::GameActionQueue* lpGameActionQueue);                       // DWARF :828 / X360 0x82343340
    void SendFinishedModeAction(GameStateModuleIO::GameActionQueue* lpGameActionQueue);                 // DWARF :833 / X360 0x82343628
    void SendModeStopMessages(GameStateModuleIO::GameActionQueue* lpGameActionQueue, bool lbTimedOut,
                              GameStateModuleIO::EGameModeType leNextGameModeType);                     // DWARF :840 / X360 0x8234BEC0
    void ResetNextLandmarks(bool lbResetAll);                                                           // DWARF :864 / X360 0x82328460
    void ClearLandmarkAndFinishLineData();                                                              // DWARF :868 / X360 0x82328590
    void TransmitCheckPointDistancesToFinishLine(GameStateModuleIO::OutputBuffer* lpOutputBuffer,
                                                 ScoringSystem&                   lrScoringSystem);     // DWARF :874 / X360 0x82341FF8
    void TransmitAndIncrementCheckPointsReached(GameStateModuleIO::GameActionQueue* lpGameActionQueue); // DWARF :878 / X360 0x82342098
    void TransmitAndIncrementFinishReached(GameStateModuleIO::GameActionQueue* lpGameActionQueue);      // DWARF :882 / X360 0x823424D0
    void SendGameResultsToNetwork(GameStateModuleIO::GameActionQueue* lpGameActionQueue);               // DWARF :899 / X360 0x82343E88

    // [stuntrace waveB fix round, 2026-08-26] DECLARE-ONLY, no body in this wave. X360 0x82337258,
    // three console callers (CheckForOutOfRangeCarsReachingFinish, RemoteRaceCarHitsCheckpoint
    // @0x82340930, TriggerQueryManager::PostWorldUpdate @0x82386BD8) and the ONLY writer of the
    // UNPLACED mauLastLandmarkHit[35] the member block FLAGs below -- which is why declaring it now
    // matters: whoever bodies it is the one who gets to pin that array. Signature is DWARF-exact
    // (references/DecFIGS/dwarfdump/.../BrnModeManager.h:399); the first argument's identity is
    // independently confirmed at the CheckForOutOfRangeCarsReachingFinish call site, where r4 ==
    // sub_8231D2C0(buffer) == PostWorldInputBuffer::GetActiveRaceCarOutputInterface() (+0x7250).
    // [X] It is assigned to NO agent this wave -- do not body it from a ModeManager partfile
    // without pinning mauLastLandmarkHit from this function's own asm first.
    void RaceCarTriggersLandmark(const BrnWorld::RaceCarEntityModuleIO::RCEntityActiveRaceCarOutputInterface* lpActiveRaceCarOutput,
                                 EGlobalRaceCarIndex leGlobalRaceCarIndex,
                                 EActiveRaceCarIndex leActiveRaceCarIndex,
                                 LandmarkIndex       lLandmarkIndex,
                                 bool                lbIsPlayer);                                      // DWARF :399 / X360 0x82337258

    // Compile-only layout oracle; defined in BrnModeManager_AssertLayout.cpp. Never called.
    static void _AssertLayout();

    // ===============================================================================================
    // THE MEMBER RUN -- console DECLARATION ORDER, X360 byte offsets in the comments. "(C)" == written
    // by Construct @0x82340008.
    //
    // The host object is NOT byte-identical (pointers widen 4 -> 8 and every embedded mode / param
    // block has its own host size). What IS load-bearing, and what _AssertLayout() pins, is the ORDER,
    // the array extents, and the deltas inside the pointer-free tail.
    //
    // ORDER NOTE 1  mapGameModes is [18], not the DWARF's [17]: Construct zeroes 18 slots and
    //               ctor-loops 18, StartGameMode / GetCountdownTimeForMode assert `< 0x12`, the
    //               countdown rodata table is 18 entries, and slot 17 is a real dispatchable mode.
    // ORDER NOTE 2  FOURTEEN embedded modes, not the DWARF's fifteen. The DWARF's mOnlineFugitive AND
    //               mOnlineFreeBurn do not exist on X360: Construct points slots 12 (ONLINE_FUGITIVE),
    //               14 (ONLINE_FREE_BURN) and 17 ALL at the ONE OnlineStuntRunMode @+2256
    //               (`*(a1+48) = *(a1+56) = *(a1+68) = a1+2256`), so the slot loop invokes that one
    //               object's ctor virtual three times -- idempotent, keep it that way.
    // ORDER NOTE 3  Slots 6 (E_MODE_ELIMINATOR) and 9 (E_MODE_TRAFFIC_ATTACK) are AUTHORED NULLS --
    //               Construct never stores them. Dispatching into them is a null call and the console
    //               asserts "mpCurrentGameMode"; keep that assert, do not "fix" the nulls.
    // ORDER NOTE 4  The DWARF omits CarCheckpointData[35] @+32480 and ScoringSystemDebugComponent
    //               @+28136 entirely, and has no mbStuntChallengeActive / SetupStuntChallenge /
    //               EndStuntChallenge / SetNetworkStuntScore / TellGuiToShowOnlineFinalStandings at
    //               all. X360 build drift in this class is REAL: DWARF is a naming aid here, never a
    //               layout proof.
    // ===============================================================================================

    GameMode*                mapGameModes[KI_GAME_MODE_SLOTS];   // +0      (C) 18 slots; 6 and 9 authored NULL
    RaceMode                 mRace;                              // +72     slot 0
    FaceOffMode              mFaceOff;                           // +268    slot 1
    CrashMode                mCrashMode;                         // +464    slot 2  (E_MODE_OFFLINE_SHOWTIME)
    RoadRageMode             mRoadRage;                          // +652    slot 3
    PursuitMode              mPursuit;                           // +908    slot 4
    BurningRouteMode         mBurningRoute;                      // +1096   slot 5
    StuntAttackMode          mStuntAttackMode;                   // +1328   slot 7  == E_MODE_STUNT_ATTACK
    SurvivorMode             mSurvivor;                          // +1552   slot 8  (E_MODE_MARKED_MAN)
    OnlineRaceMode           mOnlineRace;                        // +1776   slot 10
    OnlineRoadRageMode       mOnlineRoadRage;                    // +2016   slot 11
    OnlineStuntRunMode       mOnlineStuntRun;                    // +2256   slots 12, 14 AND 17 (ALIAS -- ORDER NOTE 2)
    OnlineBurningHomeRunMode mOnlineBurningHomeRun;              // +2512   slot 13
    OnlineFreeBurnLobbyMode  mOnlineFreeBurnLobby;               // +2952   slot 15 == E_MODE_ONLINE_FREE_BURN_LOBBY.
                                                                 //         The console stores the StreetManager at +3252 and
                                                                 //         the MugshotManager at +3256 INSIDE this object
                                                                 //         (the embedded BurnoutSkillzManager region begins
                                                                 //         at +3136) -- see the parked leg in
                                                                 //         BrnModeManager_Lifecycle.cpp.
    OnlineShowtimeMode       mOnlineShowtime;                    // +3296   slot 16 == E_MODE_ONLINE_SHOWTIME

    GameStateModuleIO::EGameModeType  meCurrentGameModeType;       // +3476  (C) = -1 (E_MODE_NONE) -- NEVER 0, see hazards H3
    GameMode*                         mpCurrentGameMode;           // +3480  (C) = 0
    GameStateModuleIO::EGameModeType  mePreviousGameModeType;      // +3484  (C) = -1   DWARF :932
    GameStateModuleIO::EGameModeState mePreviousGameModeState;     // +3488  (C) = -1   DWARF :933
    GameStateModuleIO::EGameModeType  meLastAttemptedGameModeType; // +3492  (C) = -1   DWARF :936
    s32                               miNumUnsucessfulGameModeAttempts; // +3496 (C) = 0  DWARF :937 (the console's own spelling)

    ScoringSystem   mScoringSystem;      // +3504   (C) ScoringSystem::Construct(this+3504, lpAchievementManager).
                                         //         Offline StuntModeScoring == ss+0x350 (this+4352), online == ss+0x2620
                                         //         (this+13264) -- both proven by ProcessEvent @0x82340AB8. Ends +27392.
    HUDMessageLogic mHUDMessageLogic;    // +27392  (C) HUDMessageLogic::Construct(this+27392) -- PARKED (conductor
                                         //         decision #4); the MEMBER exists regardless. 600 B, ends +27992.

    GameStateModule*                    mpGameStateModule;       // +27992  (C) asserts "lpGameStateModule" (BrnModeManager.cpp:202)
    BrnProgression::ProgressionManager* mpProgressionManager;    // +27996  (C) asserts "lpProgressionManager" (:205)
    TriggerQueryManager*                mpTriggerQueryManager;   // +28000  (C) THE holder behind the old
                                                                 //         "+0x6D60 / +0x640 GetTrafficData mystery": its
                                                                 //         TriggerData resource sits at TQM+1568 (0x620).
                                                                 //         See accessor grow (5).
    NetworkRoundManager*                mpNetworkRoundManager;   // +28004  (C) asserts "lpNetworkRoundManager" (:210)
    GameStateModuleIO::GameActionQueue* mpGameActionQueue;       // +28008  (C) = 0     DWARF :948
    CgsNumeric::Random                  mRandom;                 // +28016  (C) == CgsNumeric::Random::Construct() inlined:
                                                                 //         muSeed = KU_RANDOM_DEFAULT_SEED, ring[0] = 1.0f,
                                                                 //         seven AddRandomFloatToBuffer refills, index += 1.
                                                                 //         48 B (alignas(16)), ends +28064.
    CgsSystem::TimerStatusInterface     mTimerStatusInterface;   // +28064  [!] SPEC CORRECTION: header_grow_spec said +28060.
                                                                 //         +28064 is the ONLY seat that fits and it is
                                                                 //         double-confirmed: mRandom is 48 B from a
                                                                 //         16-aligned +28016, AND UpdateCurrentMode's reads
                                                                 //         then land exactly on the SIM sub-status --
                                                                 //           +28092 = sim mfBaseTimeStep       (iface+28)
                                                                 //           +28096 = sim mfTimeStepMultiplier (iface+32)
                                                                 //           +28104 / +28108 = sim mTime        (iface+40/+44)
                                                                 //         48 B, ends +28112, flush against the next member.

    // [X][X] DIVERGENCE at console +28112: `ModeManagerDebugComponent mModeManagerDebugComponent` (24 B)
    // IS NOT DECLARED HERE, and this is NOT a scope decision -- it is an INCLUDE CYCLE:
    // Debug/BrnModeManagerDebugComponent.h:5 does `#include ".../BrnModeManager.h"`, so this header
    // cannot include it back (whichever of the two a TU reaches first, the other's class is incomplete
    // at the point of use, and BrnModeManagerDebugComponent.cpp dereferences mpModeManager).
    // Console: `*(comp+12) = this; *(comp+16) = 0; *(comp+17) = 0; *(comp+20) = 1;
    //           CgsDev::DebugComponent::Register(comp);`  -- an inlined ModeManagerDebugComponent::
    // Construct(this), whose three seeded fields are mpModeManager / mbShowModeInfo / mbInfiniteLives
    // and miFinishPosition = 1.
    // THE FIX IS TWO LINES AND IS FILED AS A HEADER_REQUEST (agent 1's report):
    //   BrnModeManagerDebugComponent.h  : replace that include with `namespace BrnGameState { class ModeManager; }`
    //   BrnModeManagerDebugComponent.cpp: add `#include ".../BrnModeManager.h"`
    // Re-declare the member here the moment that lands; Construct's parked leg is already written for it.

    ScoringSystemDebugComponent mScoringSystemDebugComponent;    // +28136  (C) scoring pointer at comp+12 (== +28148), the
                                                                 //         show-chainable flag at comp+16 (== +28152) = 0,
                                                                 //         then DebugComponent::Register(comp).
                                                                 //         [!] DWARF has NO such member -- pure X360 addition
                                                                 //         (its assert names BrnScoringSystemDebugComponent.cpp:99).
                                                                 //         Its Construct leg is PARKED: the component header
                                                                 //         declares no Construct and both fields are private.

    // [X][X] DIVERGENCE at console +28160: `ChallengeManager mChallengeManager` (4128 B, ends +32288)
    // IS NOT EMBEDDED ON HOST (29 TUs, ~35 unresolved externals; freeburn challenges are off the
    // offline-event path). The console spine calls into it FIVE times -- Construct, Prepare,
    // ProcessEvent (unconditionally, as the FIRST statement), PreWorldUpdate, PostWorldUpdate -- and
    // every one of those call sites carries its own DIVERGENCE banner naming the exact console call.
    // [!] THE ProcessEvent ARM IS THE ONE THAT CHANGES BEHAVIOUR: freeburn challenge events die.
    // Re-wire all five when the ChallengeManager mount lands.

    // ---- the landmark / checkpoint block -----------------------------------------------------------
    // Cleared by ClearLandmarkAndFinishLineData @0x82328590 using the sentinel half-word at X360
    // 0x82CDB7D4 == 0xFFFF (image-dumped this session: offset 0xCDB7D4 reads FF FF) -- i.e.
    // LandmarkIndex(-1), the canonical K_INVALID_LANDMARK. Its neighbour at 0x82CDB7D8 is 0xFFFE,
    // which is K_MULTIPLE_LANDMARKS.
    u16 maLandmarkIndices[GameStateModuleIO::KI_MAX_LANDMARKS_IN_MODE];         // +32288  RENAMED from maLandmarkRegionIndexes.
                                                                                //   These ARE TriggerData REGION indexes:
                                                                                //   PrepareForMode reads element
                                                                                //   [muNumLandmarks-1] as one, and
                                                                                //   HasRaceCarHitValidCheckpoint matches the
                                                                                //   triggered landmark id against them.
                                                                                //   Cleared to 0xFFFF, NOT to 0.
    CgsID maLandmarkCgsIDs[GameStateModuleIO::KI_MAX_LANDMARKS_IN_MODE];        // +32320  StartPlayingMode's action-34 payload;
                                                                                //   cleared to 0xFFFFFFFFFFFFFFFF (`std` of -1).
    u16 mauLandmarkSectionIndices[GameStateModuleIO::KI_MAX_LANDMARKS_IN_MODE]; // +32448  DWARF :961.
                                                                                //   [!] WRITER CORRECTED 2026-08-26
                                                                                //   (wave-B fix round). It is NOT
                                                                                //   SetUpCheckPointsForGameMode: an image
                                                                                //   sweep for the `this+0x7EC0` form
                                                                                //   returns exactly two ModeManager
                                                                                //   functions -- SetupGameMode @0x8234B158
                                                                                //   (`addi r28, r31, 0x7EC0` @0x8234B690,
                                                                                //   the landmark-publication loop) and
                                                                                //   ClearLandmarkAndFinishLineData
                                                                                //   @0x82328590 (`addi r11, r31, 0x7EC0`
                                                                                //   @0x823285CC, the clear-to-0 leg).
                                                                                //   SetUpCheckPointsForGameMode @0x82328BC8
                                                                                //   makes exactly two stores outside its own
                                                                                //   frame -- `stw r30, 0x144(params)` and
                                                                                //   the 8-slot ScoringSystem loop at
                                                                                //   this+0x677C -- and the AI-section index
                                                                                //   it fetches goes only into the
                                                                                //   CheckpointData it appends. Cleared to 0.
    GameStateModuleIO::CarCheckpointData maCarCheckpointData[E_GLOBAL_RACE_CAR_INDEX_COUNT]; // +32480  8 B each, 280 B.
                                                                                //   [!] ORDER NOTE 4: DWARF does not list it.
    u8  mauNextLandmark[E_GLOBAL_RACE_CAR_INDEX_COUNT];                         // +32760  RENAMED from maNextLandmarkIndex.
    // [!] FLAG (UNPLACED -- deliberately NOT declared): DWARF :964 puts `uint8_t mauLastLandmarkHit[35]`
    // immediately after mauNextLandmark, but +32760 + 35 == 32795 and muNumLandmarks sits at 32796, so
    // 35 bytes CANNOT fit there. Its only writer is RaceCarTriggersLandmark (out of this wave's scope).
    // Do not declare it blind; pin it from that writer's asm when that leg is worked.
    u32           muNumLandmarks;             // +32796  cleared to 0 by ClearLandmarkAndFinishLineData
    LandmarkIndex mPlayerCurrentLandmark;     // +32800  DWARF :967; cleared to K_INVALID_LANDMARK (-1)

    f32 mfModeTimeLimit;                      // +32804  StartGameMode writes it from the mode's GameModeParams;
                                              //         UpdateCurrentMode feeds it to ScoringSystem::SetTimeLimitSeconds
                                              //         for modes 3 / 7 / 12 / 14 / 17.
    f32 mfPlayerTotalledTime;                 // +32808  (C) = 0.0f; PrepareForMode zeroes it; UpdateCurrentMode
                                              //         accumulates for modes 3 / 8 and fires PlayerFinishedMode past 0.1 s.
    CgsID mRaceId;                            // +32816  [!] SUSPECT OFFSET, CERTAIN MEMBER: StartGameMode stores
                                              //         *(startParams+712) here, but IDA garbles the store
                                              //         (`*(a1+HIDWORD(v19)) = v19`, hazards H9). AGENT 2 PINS IT from the
                                              //         asm near 0x8234FCE8+0x1A0 -- do not trust this number.
    EActiveRaceCarIndex mePlayerActiveRaceCarIndex; // +32824  UpdateCurrentMode's action-143 payload read
    EGlobalRaceCarIndex mePlayerGlobalRaceCarIndex; // +32828  StartPlayingMode's range assert names it

    StartGameModeParams mStartGameModeParams;   // +32832  console 832 B. HandleLoadingScreenLoaded passes &this as the
                                                //         StartGameModeParams*. Fields seen: +712 raceId, +720 mode type,
                                                //         +796 / +800 copied into the PFM action.
                                                //         [!] HOST SIZE MEASURES 864 B -- see the WIRE-FORMAT note below.
    GameModeParams      mCurrentGameModeParams; // +33664  console 2160 B. HandleLoadingScreenLoaded passes &this as the
                                                //         GameModeParams*. Fields seen: +96 / +100 / +104 burning-route
                                                //         medal times, +2128 online time limit (assert names
                                                //         GetOnlineTimeLimit).
                                                //         [!] HOST SIZE MEASURES 1680 B -- see the WIRE-FORMAT note below.

    CgsContainers::BitArray<E_GLOBAL_RACE_CAR_INDEX_COUNT> mRaceCarReachedCheckpoint; // +35824  (C) `std r30(=0), 0(this+0x8BF0)`
    CgsContainers::BitArray<E_GLOBAL_RACE_CAR_INDEX_COUNT> mRaceCarReachedFinish;     // +35832  (C) `std r30(=0), 0(this+0x8BF8)`
    // (IDA renders those two stores as `*(a1+35824) = v29` with a bogus 64-bit v29; the asm is
    //  unambiguous -- r30 is the zero register for the whole tail of Construct.)

    // [!!] SUSPECT RESOLVED 2026-08-26 by the wave-B fix round; the DWARF name is restored.
    // The old note claimed "PrepareForMode stores the player-LOOP COUNT there as a 64-bit
    // (`*(a1+35840) = v5`)" -- that is an IDA artefact. The real instruction, re-read this pass, is
    //     0x82342EA0  ori  r9, r10, 0x8C00
    //     0x82342EA8  stdx r20, r21, r9          ; r21 == this
    // and r20 is the function's ZERO register from `li r20, 0` @0x823429D8 onward. So the store is
    // a plain 64-bit ZERO -- a CgsID cleared to kCGSID_NULL, which contradicts nothing about the
    // DWARF name and refutes the loop-count reading outright.
    CgsID mPlayersPreSpecialEventCarID;         // +35840  DWARF BrnModeManager.h:983

    u32  muNextDistanceRequestCheckpoint;       // +35848  (C) = 0     DWARF :986
    bool mbNeedToSendNextRequest;               // +35852  (C) = 0
    bool mbIsCalculatingCheckpointDistances;    // +35853  UpdateCurrentMode gates UpdateCheckpointDistanceRequests on it

    // [X][X] WIRE-FORMAT DIVERGENCE, MEASURED 2026-08-26. header_grow_spec section 3.4 asks for a HARD
    // `static_assert(sizeof(PrepareForModeAction) == 2272)`. IT CANNOT BE HONOURED ON THIS TREE AND IS
    // NOT LANDED, because it would fail the gate:
    //     console  PrepareForModeAction 2272   GameModeParams 2160   StartGameModeParams 832
    //     host     PrepareForModeAction 1792   GameModeParams 1680   StartGameModeParams  864
    // (host figures measured with a compile-time sizeof probe against the current headers). The
    // console pinning is solid -- PrepareForMode does `memcpy(this+35856, action, 2272)` and
    // mfPFMSecondPhaseTimer sits at +38128 == 35856 + 2272 -- so the 480-byte GameModeParams shortfall
    // is a genuine reconstruction hole in BrnGameModeParams.h, not a layout choice here. It is
    // reported to the conductor as a wave item: action 23 is posted VERBATIM into a shared 13312-byte
    // queue and re-posted from this cache, so producer and consumer only agree by accident of both
    // being host code. What _AssertLayout() pins instead is the invariant that actually protects the
    // cache: the gap from mPFMActionCache to mfPFMSecondPhaseTimer is EXACTLY one action.
    GameStateModuleIO::PrepareForModeAction mPFMActionCache;  // +35856  console 2272 B, ends +38128
    f32  mfPFMSecondPhaseTimer;                               // +38128  (C) = 0.0f; the 0.2 s second-phase accumulate
    bool mbIsWaitingForSecondPFM;                             // +38132  (C) = 0

    // ===============================================================================================
    // [!][!] THE BOOL BLOCK +38133..+38157 (0x94F5..0x950D) -- 25 CONTIGUOUS BYTES, 25 NAMES.
    //
    // DWARF ORDER IS PROVEN WRONG INSIDE THIS BLOCK (two independent violations: the named assert
    // "!mbIsInTimeUpOutro" pins 38156 while naive DWARF order lands it near 38154; the road-rage crash
    // arm pins player-crashed semantics at 38154 while DWARF order says 38152). RULE FOR EVERY AGENT:
    // a byte here may only be NAMED from a writer or reader whose semantics you can state -- otherwise
    // it stays muUnkByte_0xNNNN. The verifier runs a cross-agent collision pass at the end of the wave:
    // exactly one name per byte, and each name's comment must cite the function that pins it.
    //
    // Construct @0x82340008 zeroes 23 of the 25 -- all except 38138 and 38150, which PrepareForMode /
    // StartGameMode zero instead. That store set is what fixes the block's extent at exactly 25.
    // ===============================================================================================
    bool mbInModeStartRegion;               // +38133  0x94F5  PROVISIONAL (DWARF order anchor-fit only)     (C)=0
    bool mbLastInModeStartRegion;           // +38134  0x94F6  PROVISIONAL                                    (C)=0
    bool mbFinishCurrentModeNextUpdate;     // +38135  0x94F7  PINNED BYTE -- SendModeResults @0x82343438 does
                                            //                 `lbzx r11, r29, 0x94F7`. RENAMED this wave from the
                                            //                 committed mbResultsPositionValid to the DWARF name
                                            //                 (:1000): same byte, same use --
                                            //                 FinishCurrentModeNextUpdateWithFinishPosition sets it
                                            //                 together with miDebugFinishPosition, SendModeResults
                                            //                 consumes both.                                 (C)=0
    bool mbOnlineFinalStandingsShown;       // +38136  0x94F8  COMMITTED NAME KEPT (the verified
                                            //                 TellGuiToShowOnlineFinalStandings latch). The
                                            //                 DWARF-order candidate here is mbRivalShutDown --
                                            //                 CONTESTED: do not mass-rename until
                                            //                 SetRivalShutDown / HasRivalShutDown are read from asm.
                                            //                                                                (C)=0
    bool mbHasAborted;                      // +38137  0x94F9  PROVISIONAL                                    (C)=0
    bool mbAbortedDuringIntro;              // +38138  0x94FA  PROVISIONAL -- [!] NOT zeroed by Construct;
                                            //                 PrepareForMode zeroes it (semantics fit).
    bool mbHasTimedOut;                     // +38139  0x94FB  PROVISIONAL: UpdateCurrentMode passes it to
                                            //                 ExitCurrentMode as the bool argument.          (C)=0
    bool mbHasCrashedOut;                   // +38140  0x94FC  PROVISIONAL                                    (C)=0
    // [x] H4 ARBITRATION -- RULED 2026-08-26 (wave-B fix round), APPLIED 2026-08-26 (CLOSURE
    // round). The two bytes below WERE spelled mbResultsTeamWon (+38141) and
    // mbHasAbortedDueToDisconnect (+38142); both names were refuted by their own writer and both
    // are now renamed, here and at all ~19 call sites (BrnModeManager.cpp,
    // BrnModeManager_Finish.cpp, _Lifecycle.cpp, _Prepare.cpp, _UpdateMode.cpp).
    // THE EVIDENCE, KEPT SO NOBODY RE-LITIGATES IT -- and re-derived from the export this pass:
    // ModeManager::PlayerFinishedMode @0x823280D8 writes both straight out of the incoming
    // PlayerFinishedModeEvent, with nothing in between:
    //     0x82328118  lbz r11, 0(r30)   -> if set, `stbx r28(=1), r31, 0x94FD`  @0x82328130
    //     0x82328134  lbz r11, 1(r30)   -> if set, `stbx r28(=1), r31, 0x94FE`  @0x82328148
    // DWARF names event byte 0 mbTimedOut (setter SetTimedOut) and byte 1 mbCarDestroyed (setter
    // SetCrashedOut), so BY WRITER these bytes are "the player finished because the clock ran out"
    // and "...because the car was destroyed". What the old names got wrong:
    //   * mbResultsTeamWon had NO writer anywhere -- the only asm behind it was "SendModeResults
    //     reads 0x94FD and packs it into the 48-byte results record at +0x2D" (pseudocode
    //     `v31 = *(a1 + 38141)`), which says nothing about teams.
    //   * mbHasAbortedDueToDisconnect was refuted by its own reader: GetPlayersFinishPosition
    //     @0x823281E8's MARKED_MAN arm is `lbzx 0x94FE / cntlzw / extrwi / xori / addi` ==
    //     (byte != 0) ? 2 : 1, i.e. "car destroyed -> failed" -- a disconnect abort has no business
    //     deciding a marked-man finish position.
    // NOT A TWO-BYTE SHIFT: +38139 (mbHasTimedOut) is a DIFFERENT, equally real byte -- it is the
    // MODE's time-up flag that UpdateCurrentMode hands to ExitCurrentMode -- while +38141 is the
    // PLAYER's per-finish reason that travels in the results record. Both readers exist.
    bool mbPlayerFinishedTimedOut;          // +38141  0x94FD  writer = PlayerFinishedModeEvent byte 0
                                            //                 (DWARF mbTimedOut); reader = SendModeResults
                                            //                 @0x82343438 `lbzx r11, r29, 0x94FD`.  (C)=0
    bool mbPlayerFinishedCarDestroyed;      // +38142  0x94FE  writer = PlayerFinishedModeEvent byte 1
                                            //                 (DWARF mbCarDestroyed); reader = the
                                            //                 MARKED_MAN arm of GetPlayersFinishPosition.
                                            //                                                       (C)=0
    bool mbHasPlayerFinished;               // +38143  0x94FF  PROVISIONAL                                    (C)=0
    bool mbModeStartFromRegionEnabled;      // +38144  0x9500  PROVISIONAL                                    (C)=0
    bool mbModeDataIsLoading;               // +38145  0x9501  IsWaitingForModeDataToLoad() returns it        (C)=0
    bool mbReadyForModeIntro;               // +38146  0x9502  PROVISIONAL                                    (C)=0
    bool mbIsModePrepared;                  // +38147  0x9503  PROVISIONAL                                    (C)=0
    bool mbDistanceToFinishLineTransmitted; // +38148  0x9504  PINNED: PrepareForMode computes exactly this
                                            //                 semantics, and StartModeIntro's fire-once gate needs
                                            //                 it true. A stunt run with ZERO checkpoints MUST still
                                            //                 set it true in PrepareForMode or the intro never
                                            //                 fires (hazards H6).                            (C)=0
    bool mbModeIntroStarted;                // +38149  0x9505  PINNED SEMANTICS, name provisional. THE intro
                                            //                 fire-once latch: UpdateCurrentMode does
                                            //                 `if (!b38149 && AreAllRaceCarsSetup() && b38148)
                                            //                  { b38149 = 1; StartModeIntro(); }`. The DWARF-order
                                            //                 candidate (mbFinishedOnlineEvent) does NOT fit --
                                            //                 do not use it.                                 (C)=0
    // [!!] RENAMED 2026-08-26 by the wave-B fix round (H4; was the DWARF-order-only, writer-less
    // `mbFinishedOnlineLobbyMode`). PINNED SEMANTICS, name provisional. Re-derived from the
    // exports this pass, not taken from the report: a sweep of EVERY ModeManager export for the
    // `addis r,r,1 / addi r,r,-0x6AFA` form (== this+38150) returns exactly two functions --
    //   * TransmitCheckPointDistancesToFinishLine @0x82341FF8 -- the whole use:
    //         0x8234200C  addi r29, r29, -0x6AFA        ; r29 = this + 38150
    //         0x82342014  lbz  r11, 0(r29) / bne  -> return          (already sent: do nothing)
    //         0x82342080  bl   AddEvent(q, rec, 0x76 /*118*/, 0x44)  (the waypoint payload)
    //         0x82342084  li r11,1 / stb r11, 0(r29)                 (latch it)
    //     i.e. this byte IS the fire-once latch guarding the action-118 waypoint
    //     distance-to-finish post -- it is that function's only reader and its only SET;
    //   * StartGameMode @0x8234FCE8, which only CLEARS it at mode start (PrepareForMode does too).
    // Distinct from +38148 mbDistanceToFinishLineTransmitted, which UpdateCurrentMode reads via
    // `ori r11,r11,0x9504` -- different byte, different consumer (the intro latch).
    bool mbWayPointDistancesToFinishSent;   // +38150  0x9506  -- [!] NOT zeroed by Construct;
                                            //                 StartGameMode and PrepareForMode zero it.
    // [!!] RENAMED 2026-08-26 by the wave-B fix round (was the SUSPECT `u8 muUnkByte_0x9507`).
    // SUSPECT RESOLVED -- three independent pins, all re-read from the exports this pass, and all
    // three say the same thing:
    //   * WRITER, SendModeStopMessages @0x8234BEC0: the byte is set exactly when an ONLINE,
    //     non-lobby, non-showtime mode ended cleanly (not timed out, not a sub-two-player region
    //     start) -- i.e. "the online EVENT finished".
    //   * READER 1, PrepareForMode @0x82342930: `addis r27,r21,1 / addi r27,r27,-0x6AF9` (== this
    //     + 38151), `lbz r11,0(r27)` @0x82342AB0 -> `stb r11, var_AF` == PrepareForModeAction
    //     +0x8D1, which BrnGameActions.h already names mbFinishedOnlineEvent (its neighbour
    //     var_AE == +0x8D2 takes NRM+0x130, mbStartingFreeburnDueToPlayerJoin -- the pair fixes
    //     which slot is which). The same byte is re-read at 0x82342FB4 for the +0x9504 composite.
    //   * READER 2, StartModeIntro @0x82343018: copied into StartModeIntroAction
    //     ::mbFinishedOnlineEvent (DWARF BrnGameActions.h:1177).
    // The DWARF-order candidate mbPersuitModeStartNextFrame is REFUTED by all three. NOTE the
    // header's own note at +38149 -- "the DWARF-order candidate mbFinishedOnlineEvent does not fit
    // THERE" -- is still true; it fits HERE, two bytes along.
    bool mbFinishedOnlineEvent;             // +38151  0x9507                                     (C)=0
    bool mbInstantIntroSplash;              // +38152  0x9508  PINNED SEMANTICS: the (mode == 15 || 16) && this
                                            //                 composite behind IsOnlineModeWithInstantIntro,
                                            //                 StopModeIntro's payload byte and the
                                            //                 PrepareForModeAction argument. The DWARF-order
                                            //                 candidate mbPlayerCrashedLastFrame is WRONG here
                                            //                 (see +38154).                                  (C)=0
    bool mbEventJustFinished;               // +38153  0x9509  PROVISIONAL                                    (C)=0
    bool mbPlayerCrashedLastFrame;          // +38154  0x950A  PINNED SEMANTICS: UpdateCurrentMode's road-rage arm --
                                            //                 `if (!IsInTakedownCamera() && this)
                                            //                  ScoringSystem::OnRoadRagePlayerCrashed(...)`. (C)=0
    u8   muUnkByte_0x950B;                  // +38155  0x950B  UNKNOWN: spare / pad, or a 23rd flag. Construct zeroes
                                            //                 it; no reader identified anywhere.             (C)=0
    bool mbIsInTimeUpOutro;                 // +38156  0x950C  PINNED: the console assert string names it.
                                            //                 UpdateCurrentMode sets the 3.0 s timer on time-up;
                                            //                 StartPlayingMode clears it.                    (C)=0
    bool mbStuntChallengeActive;            // +38157  0x950D  PINNED (the committed Setup/EndStuntChallenge bodies).
                                            //                 X360-ONLY member, absent from DWARF.           (C)=0

    s32 miFramesUntilModeSwitchSend;        // +38160  PrepareForMode sets 30 for modes 2 / 16; UpdateCurrentMode
                                            //         decrements and posts action 143 (16 B) at EXACTLY 0.   (C)=0
    f32 mfTimeUpStateTimer;                 // +38164  UpdateCurrentMode sets 3.0 on time-up, decrements it, and
                                            //         calls PlayerFinishedMode once it goes below 0.        (C)=0.0f
    s32 miDebugFinishPosition;              // +38168  PINNED BYTE -- SendModeResults does `lwzx r11, r29, 0x9518`
                                            //         (a 32-bit load). RENAMED this wave from the committed
                                            //         miResultsOverridePosition to the DWARF name (:1023).
                                            //         Construct writes it BEFORE the ChallengeManager call. (C)=0
    // [!] RETIRED 2026-08-26: the bounded header carried `bool mbResultsEliminatorValid; // X360 +0x9519`.
    // THAT OFFSET IS REFUTED. 0x9519 is byte 1 of miDebugFinishPosition's four, and SendModeResults
    // @0x82343438 -- the only claimed reader -- makes exactly three loads anywhere in this region
    // (byte 0x94F7, byte 0x94FD, word 0x9518) and none at 0x9519. The eliminator SendModeResults
    // reports comes from ScoringSystem::GetRaceCarEliminatorIndex, not from a ModeManager latch. The
    // member is removed rather than left standing on a fabricated offset; re-add it only if a real
    // writer or reader turns up.

    f32 mfTimeInFreeBurn;                   // +38172  DWARF :1025   (C)=0.0f
    f32 mfTimeInMode;                       // +38176  DWARF :1026   (C)=0.0f
    f32 mfTimeInOnline;                     // +38180  DWARF :1027   (C)=0.0f
    // The console object ends at approximately +38184, and the whole thing is embedded at
    // GameStateModule+4128 (0x1020) -- mpCurrentGameMode == gsm+7608 and the three clocks ==
    // gsm+42300 / 42304 / 42308, all previously proven.
    // [!] NOT MEMBERS: miPreWorldUpdatePM / miPostWorldUpdatePM (dword_82CDB6F4 / F8) are TU-local
    // statics -- the DWARF's own `extern` lines say so -- registered by Construct through
    // CgsDev::PerfMonCpu::AddMonitor.

    // ===============================================================================================
    // [!] STAND-IN BLOCK -- these are NOT ModeManager members on the console. They are kept only so the
    // already-committed bodies keep compiling BY NAME, and they sit at the very END so they cannot
    // perturb the offsetof ordering chain _AssertLayout() pins over the real run above. Retire each
    // one as its real owner grows the accessor.
    // ===============================================================================================
    // FillInRaceDistanceInterface reads these two at X360 +0x5C98 and +0x6A94 -- BOTH INSIDE the
    // ScoringSystem span (3504..27392), i.e. they are ScoringSystem members reached through the embed
    // (the same class of mistake the mode-clock identity proof fixed). Re-point that body at
    // ScoringSystem accessors when they land.
    s32 miNumActiveRaceCars;                // claimed X360 +0x5C98 -- actually ScoringSystem-internal
    f32 mfTotalRaceDistance;                // claimed X360 +0x6A94 -- actually ScoringSystem-internal
    // SetNetworkStuntScore's cache. [!] SUSPECT: +0x6CD0 / D4 / D8 == 27856 / 27860 / 27864 lies INSIDE
    // the HUDMessageLogic span (27392..27992), so if that offset claim is right these are
    // HUDMessageLogic sub-members and must move there. Re-verify against 0x82363540's asm.
    s32 miNetworkStuntActiveCarIndex;       // claimed X360 +0x6CD0
    s32 miNetworkStuntScore;                // claimed X360 +0x6CD4
    s32 miNetworkStuntPreviousScore;        // claimed X360 +0x6CD8
};
}
