// GENERATED by tools/assets/memory_map/generate_header.py from progress/memory_map_artist.yaml -- do not edit by hand.
// The real Burnout X360 (ARTIST) resource-pool definition table (from the binary memory map
// unk_82F2A788). GameDataModule::CreatePools stands these up via PoolModule::CreatePool. Per-type
// muHeapSize is the pool's heap budget for memory type t (0 = type unused); the pool's total
// per-type region (descriptor) is heapSize + the pool overhead (entry arrays / hash / heap nodes),
// computed at create time via Pool::GetOverheadMemoryRequired.
#pragma once

#include "types.hpp"

namespace BrnResource
{
    struct MemoryMapPoolDef
    {
        s32         miId;
        const char* mpcName;
        s32         miMaxHeapNodes;
        s32         miMaxResources;
        s32         miMaxImports;
        bool        mbAllowDefrag;
        u32         mauHeapSize[3];   // per memory type (0 = unused)
        u32         mauHeapAlign[3];
        s32         miNumDeps;
        s32         maiDeps[8];        // dependent pool ids (import sources)
    };

    static const MemoryMapPoolDef KAC_MEMORY_MAP_POOLS[] =
    {
        { 0, "Fonts", 64, 32, 32, false, {0x192B0,0x200000,0x0}, {16,4096,0}, 0, {0} },
        { 1, "Physics", 300, 300, 0, false, {0xF0000,0x0,0x0}, {16,0,0}, 0, {0} },
        { 2, "OpenWorldPhy", 1000, 1000, 0, false, {0x1740000,0x0,0x0}, {16,0,0}, 0, {0} },
        { 5, "GameData", 500, 500, 0, false, {0x6872C0,0x0,0x0}, {16,0,0}, 0, {0} },
        { 6, "Sound", 1024, 1024, 0, false, {0x108E800,0x0,0x0}, {64,0,0}, 0, {0} },
        { 7, "AttribSysPool", 100, 100, 0, false, {0x39800,0x0,0x0}, {16,0,0}, 0, {0} },
        { 8, "Gui_Persistent_Apt_Pool", 180, 180, 64, false, {0x369AF0,0x820000,0x0}, {16,4096,0}, 0, {0} },
        { 9, "Apt_Streaming_Data", 128, 128, 48, false, {0x917C0,0x400000,0x0}, {16,4096,0}, 0, {0} },
        { 10, "Global Textures", 500, 500, 500, false, {0x1E3C00,0x380000,0x0}, {16,4096,0}, 0, {0} },
        { 3, "OpenWorldGr", 8500, 8500, 6000, false, {0x9BE000,0x5620000,0x0}, {16,4096,0}, 1, {10} },
        { 11, "Gui_Lang_Fsm_Data_Pool", 64, 64, 0, false, {0x7CEC0,0x0,0x0}, {16,0,0}, 0, {0} },
        { 12, "Gui_Sat_Nav_Textures", 256, 64, 128, false, {0x43C0,0x360000,0x0}, {16,4096,0}, 0, {0} },
        { 13, "VFX Pool", 120, 120, 75, false, {0x57800,0x380000,0x0}, {16,4096,0}, 1, {10} },
        { 14, "ICE Pool", 150, 150, 0, false, {0x29230,0x0,0x0}, {16,0,0}, 0, {0} },
        { 16, "Environment", 100, 100, 0, false, {0x7A800,0x0,0x0}, {16,0,0}, 1, {10} },
        { 17, "Car0 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 18, "Car1 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 19, "Car2 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 20, "Car3 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 21, "Car4 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 22, "Car5 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 23, "Car6 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 24, "Car7 Physics", 5, 5, 0, false, {0x17C00,0x0,0x0}, {16,0,0}, 0, {0} },
        { 25, "CarSharedPool", 100, 100, 100, false, {0x9C00,0x440000,0x0}, {16,4096,0}, 1, {10} },
        { 4, "CarPool", 3500, 3500, 3500, false, {0x200000,0x2980000,0x0}, {16,4096,0}, 2, {10, 25} },
        { 15, "Traffic", 5000, 5000, 5000, false, {0x217800,0x27C0000,0x0}, {16,4096,0}, 2, {10, 25} },
        { 26, "Freeburn Challenges", 20, 20, 0, false, {0x3F000,0x0,0x0}, {16,0,0}, 0, {0} },
    };

    static const s32 KI_NUM_MEMORY_MAP_POOLS = 27;

    // The memory map's five allocator record tables (unk_82F2A788 header counts @+16..+32,
    // table offsets @+44..+60): the definitions GameDataModule::CreateAllocators (0x8266DD00)
    // publishes as type-10 (raw resource) / 14 (linear + heap) / 11 (rw linear) / 12 (rw
    // general) create requests. miBankId keys the AllocatorList registry; miParentBankId is
    // the X360 CreateBanks-tree parent the leaf bank is carved from. Descriptor lanes are the
    // rw 5-entry {size, align} set (only lanes 0/2 are populated by the map).
    struct MemoryMapAllocatorDef
    {
        s32         miBankId;
        const char* mpcName;
        s32         miParentBankId;
        u32         mauSize[5];    // per rw memory-type lane (0 = unused)
        u32         mauAlign[5];
    };

    static const MemoryMapAllocatorDef KAC_MEMORY_MAP_RAW_ALLOCATORS[] =
    {
        { 34, "Ice", 29, {0x40000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
    };
    static const s32 KI_NUM_MEMORY_MAP_RAW_ALLOCATORS = 1;

    static const MemoryMapAllocatorDef KAC_MEMORY_MAP_LINEAR_ALLOCATORS[] =
    {
        { 22, "AttribSysLinAlloc", 10, {0x44000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 30, "Behaviours", 29, {0x10000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 44, "Gui_State_Allocator", 5, {0xF0000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 48, "Replays Allocator", 47, {0x200000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 61, "SP Allocator", 2, {0x419000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 65, "Mugshots", 5, {0x100000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 66, "FLAPT_Allocator", 5, {0xE1000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
    };
    static const s32 KI_NUM_MEMORY_MAP_LINEAR_ALLOCATORS = 7;

    static const MemoryMapAllocatorDef KAC_MEMORY_MAP_HEAP_ALLOCATORS[] =
    {
        { 19, "AttrSysHeap", 10, {0x94000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 20, "GameTalkAlloc", 10, {0x24000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 21, "EAStl", 10, {0x4000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 27, "Network Memory", 26, {0x6F0000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 32, "Apt_Heap_Allocator", 5, {0xD0000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 38, "Gui_FSM_Lang_Alloc", 5, {0x80000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 41, "VFX Heap", 33, {0x340000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 63, "Massive Heap", 62, {0x20000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
    };
    static const s32 KI_NUM_MEMORY_MAP_HEAP_ALLOCATORS = 8;

    static const MemoryMapAllocatorDef KAC_MEMORY_MAP_RWLINEAR_ALLOCATORS[] =
    {
        { 23, "PhysicsAlloc", 2, {0x3ED800,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 42, "Network Image Allocator", 26, {0x40000,0x0,0x200000,0x0,0x0}, {16,1,128,1,1} },
        { 49, "Scene Manager", 2, {0x17A800,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 60, "VFX Graphics Allocator", 33, {0x3C000,0x0,0x400000,0x0,0x0}, {16,1,128,1,1} },
    };
    static const s32 KI_NUM_MEMORY_MAP_RWLINEAR_ALLOCATORS = 4;

    static const MemoryMapAllocatorDef KAC_MEMORY_MAP_RWGENERAL_ALLOCATORS[] =
    {
        { 9, "Playback", 4, {0x13BC00,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 24, "Rwac", 4, {0x35C000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 25, "Logic", 4, {0x3BC00,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
        { 31, "2D Immediate Heap", 8, {0x3FC000,0x0,0x0,0x0,0x0}, {16,1,1,1,1} },
    };
    static const s32 KI_NUM_MEMORY_MAP_RWGENERAL_ALLOCATORS = 4;
}
