// ===========================================================================
// RealmcIface::XenonRunnableTask -- reconstructed from BURNOUT_X360_ARTIST.XEX.
//
// The Xenon (Xbox 360) intermediate base of the Realmc memory-card worker tasks.
// It derives from RealmcCore::IRunnableTask and holds a pointer to the shared
// XenonUtil::State the platform helpers operate on. No leak source / no DWARF:
// SHAPE and BODIES both come from the X360 pseudocode + asm. See
// RealmcXenonRunnableTask.h for the class layout and the two functions
// (SelectDevice, GetCa) left BLOCKED pending their un-homed collaborators.
// ===========================================================================

#include "SDKs/Realmc/RealmcXenonRunnableTask.h"

namespace RealmcIface
{

// ---------------------------------------------------------------------------
// XenonRunnableTask ctor @ 0x82B57698 -- IRunnableTask(pContext, pMemcardState);
// mpState = pState; then MSVC installs the final XenonRunnableTask vtable.
// ---------------------------------------------------------------------------
XenonRunnableTask::XenonRunnableTask(void* pContext, RealmcCore::MemcardState* pMemcardState,
                                     XenonUtil::State* pState)
    : RealmcCore::IRunnableTask(pContext, pMemcardState)
    , mpState(pState)   // stw r30, 0x10(r31)
{
}

// ---------------------------------------------------------------------------
// ~XenonRunnableTask @ 0x82B576E8 -- restore the vtable (compiler-emitted) and
// chain into ~IRunnableTask (the X360 tail-branches into the base dtor). The
// body is empty; the vtable-restore + base-dtor call are generated by MSVC.
// ---------------------------------------------------------------------------
XenonRunnableTask::~XenonRunnableTask()
{
}

// ---------------------------------------------------------------------------
// VerifyActiveCard @ 0x82B576F8 -- if the active card's storage device is still
// present, roll the active card data back to empty and report 7 (the device
// changed underneath us / a reselect is required); otherwise there is no active
// card and 0 is returned.
// ---------------------------------------------------------------------------
int XenonRunnableTask::VerifyActiveCard()
{
    // CardExists reads the active block's leading device-id word (mCardData at
    // State+0x08; its first word is maCurrent.muState -- the X360 passes
    // mpState+8 as the device-id pointer).
    if (!XenonUtil::CardExists(&mpState->mCardData.maCurrent.muState))
        return 0;

    mpState->mCardData = CardData::Empty();
    return 7;
}

} // namespace RealmcIface
