#pragma once

#include "types.hpp"

// BrnGame::BrnG @ 0x827E3090 (X360 ARTIST) -- a compiler-generated destructor thunk.
//
// The asm is: r31 = a1 + 0x228 (=552); BaseCollisionGenerator::Destruct(r31); return r31. It
// destructs a BaseCollisionGenerator embedded at +552 inside some BrnGame-namespace owner object
// and returns the pointer to that member (the standard "destruct-and-return-member" thunk shape
// the compiler emits for a sub-object's destructor).
//
// FLAG (opaque owner): the owning class/type and its full layout are UNKNOWN (empty xrefs_to ->
// the thunk is referenced indirectly, e.g. through a vtable, so the owner could not be recovered).
// We model this MINIMALLY and FAITHFULLY to the asm: a free function in namespace BrnGame that
// takes the owner object, destructs its embedded BaseCollisionGenerator, and returns a pointer to
// that member. Semantic parity only -- the exact +552 offset is NOT reproduced (the surrounding
// members between the object start and the collision generator are unknown). When the owner is
// recovered this function moves to (or is regenerated by) that class's real destructor.
namespace CgsSceneManager { namespace CgsCollision
{
    // ad-hoc BaseCollisionGenerator: mirrors b5-decomp/src/SharedClasses/DataLists/
    // VehicleListResourceType.cpp (lines 13-20) EXACTLY -- same 8-byte storage + a declare-only
    // Destruct(). Destruct is an external symbol with its own TU (X360 0x8284CB38); declare only.
    // FLAG (ad-hoc): minimal stand-in; the real BaseCollisionGenerator layout is owned elsewhere.
    struct BaseCollisionGenerator
    {
        void Destruct();
        u8   maStorage[8];
    };
}}

namespace BrnGame
{
    // FLAG (opaque-owner model): minimal stand-in for the unknown owner object. It carries the
    // embedded BaseCollisionGenerator the thunk operates on; the intervening members (which place
    // it at +552 in the real object) are not modelled. Named-member parity, not byte-exact.
    struct BrnGDtorThunkOwner
    {
        CgsSceneManager::CgsCollision::BaseCollisionGenerator mCollisionGenerator;
    };

    // BrnG @ 0x827E3090 -- destruct the owner's embedded BaseCollisionGenerator and return a
    // pointer to that member (faithful to the asm: Destruct(member); return &member).
    CgsSceneManager::CgsCollision::BaseCollisionGenerator* BrnG(BrnGDtorThunkOwner* lpOwner);
}
