#include "GameSource/Sound/Global/BrnCameraControl.h"

// =============================================================================
// BrnSound::Logic::CameraControl — out-of-line bodies.
// Reconstructed from BURNOUT_X360_ARTIST.XEX. See BrnCameraControl.h for the
// inheritance rationale and the X360-32-bit-vs-host-64-bit offset note.
//
// This TU's recon'd function set is exactly ONE entry:
//   `vector deleting destructor' adjustor{4}  @ 0x826BB438
// =============================================================================

namespace BrnSound
{
namespace Logic
{

// ---------------------------------------------------------------------------
// ~CameraControl  (the out-of-line destructor that anchors the vtable)
//
// The destructor itself runs the inherited BrnEffectControl teardown (the X360
// `scalar deleting destructor' the adjustor below forwards to). All observable
// member teardown lives in the committed BrnEffectControl base, so this leaf
// destructor body is empty.
// ---------------------------------------------------------------------------
CameraControl::~CameraControl()
{
}

// ---------------------------------------------------------------------------
// `vector deleting destructor' adjustor{4}  @ 0x826BB438
//
//   0x826BB438  addi r3, r3, -4
//   0x826BB43C  b    BrnSound::Logic::CameraControl::`scalar deleting destructor'
//
// The IResourceRequester sub-object (the second base of BrnEffectControl) lives
// at this+4; a delete through an IResourceRequester* enters here, recovers the
// primary CameraControl `this` (this - 4), and forwards to the real
// (scalar/vector deleting) destructor. In reconstructed C++ this thunk is
// generated by the compiler from BrnEffectControl's multiple-inheritance vtable
// layout (the virtual destructor declared above is reached through the
// IResourceRequester base), so no hand-written body is emitted.
// FLAG: thunk reproduced structurally by the inheritance declaration in the
// header (CameraControl : public BrnEffectControl); not a hand-bodied function.
// ---------------------------------------------------------------------------

} // namespace Logic
} // namespace BrnSound
