#include "GameSource/Sound/Global/BrnMixerControl.h"

// =============================================================================
// BrnSound::Logic::MixerControl — out-of-line bodies.
// Reconstructed from BURNOUT_X360_ARTIST.XEX. See BrnMixerControl.h for the
// inheritance rationale and the X360-32-bit-vs-host-64-bit offset note.
//
// This TU's recon'd function set is exactly two entries:
//   `vector deleting destructor'              @ 0x826BAED8
//   `vector deleting destructor' adjustor{4}  @ 0x826BAED0
// (the second is a compiler-generated thunk; see note).
//
// dep_flags: none un-homed for THIS TU. The destructor teardown touches only the
// committed BrnEffectControl base members (meDetachState / mbResourcesReady /
// meAttachState, all pinned BY NAME). The (a2 & 1) deallocation tail dispatches
// the global sound allocator (off_82FFB954); that allocator vtable is not homed
// here, so the `delete` half of the X360 vector deleting destructor is left to the
// host toolchain (same treatment as the CameraControl / BrnEffectControl siblings).
// =============================================================================

namespace BrnSound
{
namespace Logic
{

// ---------------------------------------------------------------------------
// ~MixerControl  @ 0x826BAED8  (the X360 `vector deleting destructor')
//
//   stw  off_820AEA6C, 0(this)   ; primary (MixerControl) vptr settle
//   stw  off_820AEA38, 4(this)   ; (transient) base IResourceRequester vptr
//   li   r7, 3 ; stw r7, 0x28(this) ; meDetachState = E_DETACH_STATE_FINISHED
//   stw  off_820AA820, 4(this)   ; final IResourceRequester sub-object vptr
//   stb  0, 0x31(this)           ; mbResourcesReady = false
//   stw  0, 0x24(this)           ; meAttachState = E_ATTACH_STATE_NONE
//   if (a2 & 1) { ... deallocate via off_82FFB954 }
//   return this
//
// The vptr stores are the compiler-emitted devirtualization of the destructor
// base sub-objects; the observable member teardown is the inherited
// BrnEffectControl teardown (meDetachState/mbResourcesReady/meAttachState). The
// MixerControl-owned members are non-owning, so this leaf destructor runs only the
// inherited base teardown (the base destructor body), leaving this body empty.
// ---------------------------------------------------------------------------
MixerControl::~MixerControl()
{
}

// ---------------------------------------------------------------------------
// `vector deleting destructor' adjustor{4}  @ 0x826BAED0
//
//   0x826BAED0  addi r3, r3, -4
//   0x826BAED4  b    BrnSound::Logic::MixerControl::`vector deleting destructor'
//
// The IResourceRequester sub-object (the second base of BrnEffectControl) lives
// at this+4; a delete through an IResourceRequester* enters here, recovers the
// primary MixerControl `this` (this - 4), and forwards to the real destructor. In
// reconstructed C++ this thunk is generated by the compiler from BrnEffectControl's
// multiple-inheritance vtable layout (the virtual destructor declared in the header
// is reached through the IResourceRequester base), so no hand-written body is
// emitted.
// FLAG: thunk reproduced structurally by the inheritance declaration in the header
// (MixerControl : public BrnEffectControl); not a hand-bodied function.
// ---------------------------------------------------------------------------

} // namespace Logic
} // namespace BrnSound
